update entityscore set admitted=56 ,vacancy=75 where entityid = (select id from entity where name like '%聖嘉祿學校%') and year=2013;
update entityscore set admitted=87 ,vacancy=100 where entityid = (select id from entity where name like '%佛教黃焯菴小學%') and year=2013;
update entityscore set admitted=75 ,vacancy=100 where entityid = (select id from entity where name like '%保良局金銀業貿易場張凝文學校%') and year=2013;
update entityscore set admitted=115 ,vacancy=125 where entityid = (select id from entity where name like '%啟基學校（港島）%') and year=2013;
update entityscore set admitted=104 ,vacancy=125 where entityid = (select id from entity where name like '%北角官立小學（雲景道）%') and year=2013;
update entityscore set admitted=78 ,vacancy=100 where entityid = (select id from entity where name like '%慈幼學校%') and year=2013;
update entityscore set admitted=81 ,vacancy=100 where entityid = (select id from entity where name like '%廣東道官立小學%') and year=2013;
update entityscore set admitted=87 ,vacancy=100 where entityid = (select id from entity where name like '%九龍婦女福利會李炳紀念學校%') and year=2013;
update entityscore set admitted=98 ,vacancy=100 where entityid = (select id from entity where name like '%聖匠小學%') and year=2013;
update entityscore set admitted=131 ,vacancy=150 where entityid = (select id from entity where name like '%天主教領島學校%') and year=2013;
update entityscore set admitted=127 ,vacancy=150 where entityid = (select id from entity where name like '%葛量洪校友會黃埔學校%') and year=2013;
update entityscore set admitted=65 ,vacancy=75 where entityid = (select id from entity where name like '%深水埔街坊福利會小學%') and year=2013;
update entityscore set admitted=120 ,vacancy=125 where entityid = (select id from entity where name like '%五邑工商總會學校%') and year=2013;
update entityscore set admitted=133 ,vacancy=150 where entityid = (select id from entity where name like '%白田天主教小學%') and year=2013;
update entityscore set admitted=130 ,vacancy=150 where entityid = (select id from entity where name like '%深水埗官立小學%') and year=2013;
update entityscore set admitted=122 ,vacancy=125 where entityid = (select id from entity where name like '%樂善堂小學%') and year=2013;
update entityscore set admitted=76 ,vacancy=100 where entityid = (select id from entity where name like '%樂善堂楊仲明學校%') and year=2013;
update entityscore set admitted=100 ,vacancy=125 where entityid = (select id from entity where name like '%香港道教聯合會圓玄學院石圍角小學%') and year=2013;
update entityscore set admitted=141 ,vacancy=150 where entityid = (select id from entity where name like '%荃灣潮州公學%') and year=2013;
update entityscore set admitted=138 ,vacancy=150 where entityid = (select id from entity where name like '%路德會聖十架學校%') and year=2013;
update entityscore set admitted=110 ,vacancy=125 where entityid = (select id from entity where name like '%仁愛堂劉皇發夫人小學%') and year=2013;
update entityscore set admitted=25 ,vacancy=50 where entityid = (select id from entity where name like '%通德學校%') and year=2013;
update entityscore set admitted=70 ,vacancy=75 where entityid = (select id from entity where name like '%打鼓嶺嶺英公立學校%') and year=2013;
update entityscore set admitted=116 ,vacancy=125 where entityid = (select id from entity where name like '%九龍城浸信會禧年（恩平）小學%') and year=2013;
update entityscore set admitted=119 ,vacancy=125 where entityid = (select id from entity where name like '%東莞工商總會張煌偉小學%') and year=2013;
update entityscore set admitted=144 ,vacancy=150 where entityid = (select id from entity where name like '%天主教聖華學校%') and year=2013;
update entityscore set admitted=134 ,vacancy=150 where entityid = (select id from entity where name like '%世界龍岡學校黃耀南小學%') and year=2013;
update entityscore set admitted=140 ,vacancy=150 where entityid = (select id from entity where name like '%慈航學校%') and year=2013;
update entityscore set admitted=28 ,vacancy=50 where entityid = (select id from entity where name like '%李陞小學%') and year=2013;
update entityscore set admitted=25 ,vacancy=50 where entityid = (select id from entity where name like '%英皇書院同學會小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=50 where entityid = (select id from entity where name like '%新會商會學校%') and year=2013;
update entityscore set admitted=25 ,vacancy=50 where entityid = (select id from entity where name like '%聖公會聖馬太小學%') and year=2013;
update entityscore set admitted=24 ,vacancy=60 where entityid = (select id from entity where name like '%般咸道官立小學%') and year=2013;
update entityscore set admitted=35 ,vacancy=75 where entityid = (select id from entity where name like '%英皇書院同學會小學第二校%') and year=2013;
update entityscore set admitted=45 ,vacancy=90 where entityid = (select id from entity where name like '%中西區聖安多尼學校%') and year=2013;
update entityscore set admitted=42 ,vacancy=90 where entityid = (select id from entity where name like '%聖公會基恩小學%') and year=2013;
update entityscore set admitted=43 ,vacancy=90 where entityid = (select id from entity where name like '%聖安多尼學校%') and year=2013;
update entityscore set admitted=75 ,vacancy=100 where entityid = (select id from entity where name like '%天主教總堂區學校%') and year=2013;
update entityscore set admitted=75 ,vacancy=100 where entityid = (select id from entity where name like '%香港潮商學校%') and year=2013;
update entityscore set admitted=47 ,vacancy=100 where entityid = (select id from entity where name like '%聖士提反女子中學附屬小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會呂明才紀念小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=150 where entityid = (select id from entity where name like '%嘉諾撒聖心學校%') and year=2013;
update entityscore set admitted=74 ,vacancy=180 where entityid = (select id from entity where name like '%聖公會聖彼得小學%') and year=2013;
update entityscore set admitted=24 ,vacancy=50 where entityid = (select id from entity where name like '%李陞大坑學校%') and year=2013;
update entityscore set admitted=23 ,vacancy=50 where entityid = (select id from entity where name like '%寶覺小學%') and year=2013;
update entityscore set admitted=21 ,vacancy=60 where entityid = (select id from entity where name like '%番禺會所華仁上午小學%') and year=2013;
update entityscore set admitted=28 ,vacancy=60 where entityid = (select id from entity where name like '%番禺會所華仁下午小學%') and year=2013;
update entityscore set admitted=40 ,vacancy=75 where entityid = (select id from entity where name like '%東華三院李賜豪小學%') and year=2013;
update entityscore set admitted=35 ,vacancy=75 where entityid = (select id from entity where name like '%寶血小學%') and year=2013;
update entityscore set admitted=85 ,vacancy=100 where entityid = (select id from entity where name like '%官立嘉道理爵士小學%') and year=2013;
update entityscore set admitted=56 ,vacancy=120 where entityid = (select id from entity where name like '%嘉諾撒聖方濟各學校%') and year=2013;
update entityscore set admitted=56 ,vacancy=120 where entityid = (select id from entity where name like '%瑪利曼小學%') and year=2013;
update entityscore set admitted=56 ,vacancy=120 where entityid = (select id from entity where name like '%聖保祿天主教小學%') and year=2013;
update entityscore set admitted=55 ,vacancy=125 where entityid = (select id from entity where name like '%軒尼詩道官立上午小學%') and year=2013;
update entityscore set admitted=54 ,vacancy=125 where entityid = (select id from entity where name like '%軒尼詩道官立下午小學%') and year=2013;
update entityscore set admitted=58 ,vacancy=125 where entityid = (select id from entity where name like '%聖公會聖雅各小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=150 where entityid = (select id from entity where name like '%聖若瑟小學%') and year=2013;
update entityscore set admitted=22 ,vacancy=60 where entityid = (select id from entity where name like '%北角衞理上午小學%') and year=2013;
update entityscore set admitted=23 ,vacancy=60 where entityid = (select id from entity where name like '%北角衞理下午小學%') and year=2013;
update entityscore set admitted=31 ,vacancy=75 where entityid = (select id from entity where name like '%丹拿山循道學校%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%北角循道學校%') and year=2013;
update entityscore set admitted=95 ,vacancy=100 where entityid = (select id from entity where name like '%佛教中華康山學校%') and year=2013;
update entityscore set admitted=60 ,vacancy=120 where entityid = (select id from entity where name like '%聖公會聖米迦勒小學%') and year=2013;
update entityscore set admitted=54 ,vacancy=120 where entityid = (select id from entity where name like '%滬江小學%') and year=2013;
update entityscore set admitted=84 ,vacancy=125 where entityid = (select id from entity where name like '%太古小學%') and year=2013;
update entityscore set admitted=75 ,vacancy=150 where entityid = (select id from entity where name like '%北角官立小學%') and year=2013;
update entityscore set admitted=82 ,vacancy=180 where entityid = (select id from entity where name like '%香港嘉諾撒學校%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%天主教明德學校%') and year=2013;
update entityscore set admitted=80 ,vacancy=100 where entityid = (select id from entity where name like '%基督教香港信義會信愛學校%') and year=2013;
update entityscore set admitted=73 ,vacancy=100 where entityid = (select id from entity where name like '%救世軍中原慈善基金學校%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%救世軍韋理夫人紀念學校%') and year=2013;
update entityscore set admitted=81 ,vacancy=100 where entityid = (select id from entity where name like '%筲箕灣官立小學%') and year=2013;
update entityscore set admitted=47 ,vacancy=100 where entityid = (select id from entity where name like '%筲箕灣崇真學校%') and year=2013;
update entityscore set admitted=86 ,vacancy=100 where entityid = (select id from entity where name like '%聖馬可小學%') and year=2013;
update entityscore set admitted=45 ,vacancy=120 where entityid = (select id from entity where name like '%中華基督教會基灣小學%') and year=2013;
update entityscore set admitted=47 ,vacancy=120 where entityid = (select id from entity where name like '%中華基督教會基灣小學（愛蝶灣）%') and year=2013;
update entityscore set admitted=54 ,vacancy=120 where entityid = (select id from entity where name like '%聖公會柴灣聖米迦勒小學%') and year=2013;
update entityscore set admitted=57 ,vacancy=125 where entityid = (select id from entity where name like '%培僑小學%') and year=2013;
update entityscore set admitted=86 ,vacancy=125 where entityid = (select id from entity where name like '%愛秩序灣官立小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%勵志會梁李秀娛紀念小學%') and year=2013;
update entityscore set admitted=71 ,vacancy=150 where entityid = (select id from entity where name like '%香港中國婦女會丘佐榮學校%') and year=2013;
update entityscore set admitted=36 ,vacancy=50 where entityid = (select id from entity where name like '%香島道官立小學%') and year=2013;
update entityscore set admitted=27 ,vacancy=50 where entityid = (select id from entity where name like '%嘉諾撒培德學校%') and year=2013;
update entityscore set admitted=81 ,vacancy=100 where entityid = (select id from entity where name like '%東華三院鶴山學校%') and year=2013;
update entityscore set admitted=44 ,vacancy=100 where entityid = (select id from entity where name like '%香港南區官立小學%') and year=2013;
update entityscore set admitted=46 ,vacancy=100 where entityid = (select id from entity where name like '%海怡寶血小學%') and year=2013;
update entityscore set admitted=73 ,vacancy=100 where entityid = (select id from entity where name like '%華富邨寶血小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%聖伯多祿天主教小學%') and year=2013;
update entityscore set admitted=78 ,vacancy=100 where entityid = (select id from entity where name like '%鴨脷洲街坊學校%') and year=2013;
update entityscore set admitted=60 ,vacancy=120 where entityid = (select id from entity where name like '%聖公會置富始南小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%香港仔聖伯多祿天主教小學%') and year=2013;
update entityscore set admitted=75 ,vacancy=150 where entityid = (select id from entity where name like '%聖公會田灣始南小學%') and year=2013;
update entityscore set admitted=27 ,vacancy=60 where entityid = (select id from entity where name like '%油蔴地街坊會學校%') and year=2013;
update entityscore set admitted=34 ,vacancy=75 where entityid = (select id from entity where name like '%中華基督教會灣仔堂基道小學%') and year=2013;
update entityscore set admitted=78 ,vacancy=100 where entityid = (select id from entity where name like '%佐敦道官立小學%') and year=2013;
update entityscore set admitted=47 ,vacancy=100 where entityid = (select id from entity where name like '%嘉諾撒聖瑪利學校%') and year=2013;
update entityscore set admitted=56 ,vacancy=120 where entityid = (select id from entity where name like '%循道學校%') and year=2013;
update entityscore set admitted=56 ,vacancy=120 where entityid = (select id from entity where name like '%德信學校%') and year=2013;
update entityscore set admitted=114 ,vacancy=125 where entityid = (select id from entity where name like '%東莞同鄉會方樹泉學校%') and year=2013;
update entityscore set admitted=117 ,vacancy=125 where entityid = (select id from entity where name like '%東華三院羅裕積小學%') and year=2013;
update entityscore set admitted=57 ,vacancy=150 where entityid = (select id from entity where name like '%油蔴地天主教小學%') and year=2013;
update entityscore set admitted=55 ,vacancy=150 where entityid = (select id from entity where name like '%油蔴地天主教小學（海泓道）%') and year=2013;
update entityscore set admitted=24 ,vacancy=50 where entityid = (select id from entity where name like '%鮮魚行學校%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%塘尾道官立小學%') and year=2013;
update entityscore set admitted=60 ,vacancy=120 where entityid = (select id from entity where name like '%聖公會基榮小學%') and year=2013;
update entityscore set admitted=58 ,vacancy=125 where entityid = (select id from entity where name like '%大角嘴天主教小學%') and year=2013;
update entityscore set admitted=104 ,vacancy=125 where entityid = (select id from entity where name like '%中華基督教會基全小學%') and year=2013;
update entityscore set admitted=80 ,vacancy=125 where entityid = (select id from entity where name like '%路德會沙崙學校%') and year=2013;
update entityscore set admitted=75 ,vacancy=150 where entityid = (select id from entity where name like '%大角嘴天主教小學（海帆道）%') and year=2013;
update entityscore set admitted=67 ,vacancy=180 where entityid = (select id from entity where name like '%中華基督教會協和小學%') and year=2013;
update entityscore set admitted=25 ,vacancy=50 where entityid = (select id from entity where name like '%九龍靈光小學%') and year=2013;
update entityscore set admitted=35 ,vacancy=50 where entityid = (select id from entity where name like '%基督教香港信義會紅磡信義學校%') and year=2013;
update entityscore set admitted=23 ,vacancy=50 where entityid = (select id from entity where name like '%聖公會牧愛小學%') and year=2013;
update entityscore set admitted=37 ,vacancy=75 where entityid = (select id from entity where name like '%中華基督教會灣仔堂基道小學（九龍城）%') and year=2013;
update entityscore set admitted=36 ,vacancy=75 where entityid = (select id from entity where name like '%獻主會聖馬善樂小學%') and year=2013;
update entityscore set admitted=42 ,vacancy=90 where entityid = (select id from entity where name like '%協恩中學附屬小學%') and year=2013;
update entityscore set admitted=47 ,vacancy=100 where entityid = (select id from entity where name like '%合一堂學校%') and year=2013;
update entityscore set admitted=44 ,vacancy=100 where entityid = (select id from entity where name like '%農圃道官立小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%獻主會小學%') and year=2013;
update entityscore set admitted=56 ,vacancy=120 where entityid = (select id from entity where name like '%聖羅撒學校%') and year=2013;
update entityscore set admitted=49 ,vacancy=125 where entityid = (select id from entity where name like '%馬頭涌官立小學%') and year=2013;
update entityscore set admitted=61 ,vacancy=150 where entityid = (select id from entity where name like '%陳瑞祺（喇沙）小學%') and year=2013;
update entityscore set admitted=35 ,vacancy=75 where entityid = (select id from entity where name like '%天神嘉諾撒學校%') and year=2013;
update entityscore set admitted=46 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會奉基千禧小學%') and year=2013;
update entityscore set admitted=47 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會奉基小學%') and year=2013;
update entityscore set admitted=80 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會聖提摩太小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=125 where entityid = (select id from entity where name like '%馬頭涌官立小學（紅磡灣）%') and year=2013;
update entityscore set admitted=70 ,vacancy=150 where entityid = (select id from entity where name like '%黃埔宣道小學%') and year=2013;
update entityscore set admitted=25 ,vacancy=50 where entityid = (select id from entity where name like '%基督教香港信義會深信學校%') and year=2013;
update entityscore set admitted=58 ,vacancy=75 where entityid = (select id from entity where name like '%香港四邑商工總會新會商會學校%') and year=2013;
update entityscore set admitted=42 ,vacancy=90 where entityid = (select id from entity where name like '%聖公會聖多馬小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%天主教善導小學%') and year=2013;
update entityscore set admitted=41 ,vacancy=100 where entityid = (select id from entity where name like '%李鄭屋官立小學%') and year=2013;
update entityscore set admitted=45 ,vacancy=100 where entityid = (select id from entity where name like '%旅港開平商會學校%') and year=2013;
update entityscore set admitted=92 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會基愛小學%') and year=2013;
update entityscore set admitted=44 ,vacancy=100 where entityid = (select id from entity where name like '%瑪利諾神父教會學校（小學部）%') and year=2013;
update entityscore set admitted=54 ,vacancy=100 where entityid = (select id from entity where name like '%福榮街官立小學%') and year=2013;
update entityscore set admitted=59 ,vacancy=120 where entityid = (select id from entity where name like '%聖方濟愛德小學%') and year=2013;
update entityscore set admitted=60 ,vacancy=120 where entityid = (select id from entity where name like '%大坑東宣道小學%') and year=2013;
update entityscore set admitted=86 ,vacancy=120 where entityid = (select id from entity where name like '%聖公會聖紀文小學%') and year=2013;
update entityscore set admitted=68 ,vacancy=150 where entityid = (select id from entity where name like '%中華基督教會協和小學（長沙灣）%') and year=2013;
update entityscore set admitted=67 ,vacancy=150 where entityid = (select id from entity where name like '%荔枝角天主教小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=150 where entityid = (select id from entity where name like '%寶血會嘉靈學校%') and year=2013;
update entityscore set admitted=85 ,vacancy=180 where entityid = (select id from entity where name like '%聖公會基福小學%') and year=2013;
update entityscore set admitted=90 ,vacancy=180 where entityid = (select id from entity where name like '%聖公會聖安德烈小學%') and year=2013;
update entityscore set admitted=15 ,vacancy=25 where entityid = (select id from entity where name like '%耀山學校%') and year=2013;
update entityscore set admitted=24 ,vacancy=60 where entityid = (select id from entity where name like '%拔萃小學%') and year=2013;
update entityscore set admitted=42 ,vacancy=90 where entityid = (select id from entity where name like '%嘉諾撒聖家學校%') and year=2013;
update entityscore set admitted=41 ,vacancy=100 where entityid = (select id from entity where name like '%九龍塘天主教華德學校 （S)%') and year=2013;
update entityscore set admitted=36 ,vacancy=100 where entityid = (select id from entity where name like '%九龍塘官立小學%') and year=2013;
update entityscore set admitted=41 ,vacancy=100 where entityid = (select id from entity where name like '%華德學校%') and year=2013;
update entityscore set admitted=56 ,vacancy=120 where entityid = (select id from entity where name like '%嘉諾撒聖家學校（九龍塘）%') and year=2013;
update entityscore set admitted=47 ,vacancy=120 where entityid = (select id from entity where name like '%中華基督教會基華小學（九龍塘）%') and year=2013;
update entityscore set admitted=73 ,vacancy=150 where entityid = (select id from entity where name like '%瑪利諾修院學校（小學部）%') and year=2013;
update entityscore set admitted=84 ,vacancy=180 where entityid = (select id from entity where name like '%喇沙小學%') and year=2013;
update entityscore set admitted=51 ,vacancy=100 where entityid = (select id from entity where name like '%天主教博智小學%') and year=2013;
update entityscore set admitted=65 ,vacancy=100 where entityid = (select id from entity where name like '%孔教學院大成小學%') and year=2013;
update entityscore set admitted=46 ,vacancy=100 where entityid = (select id from entity where name like '%浸信會天虹小學%') and year=2013;
update entityscore set admitted=34 ,vacancy=100 where entityid = (select id from entity where name like '%黃大仙天主教小學%') and year=2013;
update entityscore set admitted=37 ,vacancy=100 where entityid = (select id from entity where name like '%黃大仙官立小學%') and year=2013;
update entityscore set admitted=34 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會基德小學%') and year=2013;
update entityscore set admitted=46 ,vacancy=100 where entityid = (select id from entity where name like '%聖博德學校%') and year=2013;
update entityscore set admitted=47 ,vacancy=100 where entityid = (select id from entity where name like '%嘉諾撒小學%') and year=2013;
update entityscore set admitted=58 ,vacancy=100 where entityid = (select id from entity where name like '%福德學校%') and year=2013;
update entityscore set admitted=52 ,vacancy=100 where entityid = (select id from entity where name like '%獻主會溥仁小學%') and year=2013;
update entityscore set admitted=41 ,vacancy=120 where entityid = (select id from entity where name like '%天主教伍華小學%') and year=2013;
update entityscore set admitted=56 ,vacancy=120 where entityid = (select id from entity where name like '%保良局何壽南小學%') and year=2013;
update entityscore set admitted=36 ,vacancy=50 where entityid = (select id from entity where name like '%保良局陳南昌夫人小學%') and year=2013;
update entityscore set admitted=37 ,vacancy=75 where entityid = (select id from entity where name like '%真鐸學校%') and year=2013;
update entityscore set admitted=45 ,vacancy=100 where entityid = (select id from entity where name like '%中華基督教會基華小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=100 where entityid = (select id from entity where name like '%中華基督教會基慈小學%') and year=2013;
update entityscore set admitted=76 ,vacancy=100 where entityid = (select id from entity where name like '%伊斯蘭鮑伯濤紀念小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%彩雲聖若瑟小學%') and year=2013;
update entityscore set admitted=44 ,vacancy=100 where entityid = (select id from entity where name like '%嗇色園主辦可立小學%') and year=2013;
update entityscore set admitted=47 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會日修小學%') and year=2013;
update entityscore set admitted=34 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會靜山小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%慈雲山天主教小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=125 where entityid = (select id from entity where name like '%慈雲山聖文德天主教小學%') and year=2013;
update entityscore set admitted=60 ,vacancy=125 where entityid = (select id from entity where name like '%聖文德天主教小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%聖博德天主教小學（蒲崗村道）%') and year=2013;
update entityscore set admitted=62 ,vacancy=150 where entityid = (select id from entity where name like '%保良局錦泰小學%') and year=2013;
update entityscore set admitted=65 ,vacancy=150 where entityid = (select id from entity where name like '%嘉諾撒小學（新蒲崗）%') and year=2013;
update entityscore set admitted=53 ,vacancy=100 where entityid = (select id from entity where name like '%佐敦谷聖若瑟天主教小學%') and year=2013;
update entityscore set admitted=63 ,vacancy=100 where entityid = (select id from entity where name like '%佛教慈敬學校%') and year=2013;
update entityscore set admitted=66 ,vacancy=100 where entityid = (select id from entity where name like '%坪石天主教小學%') and year=2013;
update entityscore set admitted=53 ,vacancy=100 where entityid = (select id from entity where name like '%迦密梁省德學校%') and year=2013;
update entityscore set admitted=80 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會聖約翰小學%') and year=2013;
update entityscore set admitted=66 ,vacancy=125 where entityid = (select id from entity where name like '%九龍灣聖若翰天主教小學%') and year=2013;
update entityscore set admitted=69 ,vacancy=125 where entityid = (select id from entity where name like '%天主教柏德學校%') and year=2013;
update entityscore set admitted=68 ,vacancy=125 where entityid = (select id from entity where name like '%浸信宣道會呂明才小學%') and year=2013;
update entityscore set admitted=68 ,vacancy=125 where entityid = (select id from entity where name like '%聖公會九龍灣基樂小學%') and year=2013;
update entityscore set admitted=35 ,vacancy=50 where entityid = (select id from entity where name like '%中華基督教會基法小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=100 where entityid = (select id from entity where name like '%天主教佑華小學%') and year=2013;
update entityscore set admitted=57 ,vacancy=100 where entityid = (select id from entity where name like '%香港道教聯合會雲泉學校%') and year=2013;
update entityscore set admitted=67 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會基顯小學%') and year=2013;
update entityscore set admitted=65 ,vacancy=100 where entityid = (select id from entity where name like '%聖若翰天主教小學%') and year=2013;
update entityscore set admitted=99 ,vacancy=100 where entityid = (select id from entity where name like '%閩僑小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=100 where entityid = (select id from entity where name like '%樂華天主教小學%') and year=2013;
update entityscore set admitted=67 ,vacancy=100 where entityid = (select id from entity where name like '%觀塘官立小學%') and year=2013;
update entityscore set admitted=60 ,vacancy=120 where entityid = (select id from entity where name like '%聖公會基樂小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=120 where entityid = (select id from entity where name like '%路德會聖馬太學校（秀茂坪）%') and year=2013;
update entityscore set admitted=83 ,vacancy=125 where entityid = (select id from entity where name like '%秀明小學%') and year=2013;
update entityscore set admitted=103 ,vacancy=125 where entityid = (select id from entity where name like '%秀茂坪天主教小學%') and year=2013;
update entityscore set admitted=84 ,vacancy=125 where entityid = (select id from entity where name like '%基督教聖約教會堅樂小學%') and year=2013;
update entityscore set admitted=87 ,vacancy=125 where entityid = (select id from entity where name like '%聖安當小學%') and year=2013;
update entityscore set admitted=83 ,vacancy=125 where entityid = (select id from entity where name like '%聖愛德華天主教小學%') and year=2013;
update entityscore set admitted=83 ,vacancy=125 where entityid = (select id from entity where name like '%藍田循道衛理小學%') and year=2013;
update entityscore set admitted=83 ,vacancy=125 where entityid = (select id from entity where name like '%觀塘官立小學（秀明道）%') and year=2013;
update entityscore set admitted=88 ,vacancy=125 where entityid = (select id from entity where name like '%香港道教聯合會圓玄學院陳呂重德紀念學校%') and year=2013;
update entityscore set admitted=100 ,vacancy=150 where entityid = (select id from entity where name like '%中華基督教會基法小學（油塘）%') and year=2013;
update entityscore set admitted=60 ,vacancy=150 where entityid = (select id from entity where name like '%聖公會李兆強小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=150 where entityid = (select id from entity where name like '%聖公會德田李兆強小學%') and year=2013;
update entityscore set admitted=77 ,vacancy=180 where entityid = (select id from entity where name like '%聖公會油塘基顯小學%') and year=2013;
update entityscore set admitted=11 ,vacancy=25 where entityid = (select id from entity where name like '%中華基督教會全完第一小學%') and year=2013;
update entityscore set admitted=12 ,vacancy=25 where entityid = (select id from entity where name like '%靈光小學%') and year=2013;
update entityscore set admitted=23 ,vacancy=60 where entityid = (select id from entity where name like '%天佑小學%') and year=2013;
update entityscore set admitted=42 ,vacancy=90 where entityid = (select id from entity where name like '%荃灣天主教小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%中華基督教會基慧小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%柴灣角天主教小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%荃灣公立何傳耀紀念小學%') and year=2013;
update entityscore set admitted=33 ,vacancy=100 where entityid = (select id from entity where name like '%深井天主教小學%') and year=2013;
update entityscore set admitted=54 ,vacancy=120 where entityid = (select id from entity where name like '%寶血會伍季明紀念學校%') and year=2013;
update entityscore set admitted=50 ,vacancy=120 where entityid = (select id from entity where name like '%寶血會思源學校%') and year=2013;
update entityscore set admitted=47 ,vacancy=125 where entityid = (select id from entity where name like '%海壩街官立小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=150 where entityid = (select id from entity where name like '%中華基督教會基慧小學（馬灣）%') and year=2013;
update entityscore set admitted=70 ,vacancy=150 where entityid = (select id from entity where name like '%天主教石鐘山紀念小學%') and year=2013;
update entityscore set admitted=54 ,vacancy=150 where entityid = (select id from entity where name like '%香港浸信會聯會小學%') and year=2013;
update entityscore set admitted=56 ,vacancy=150 where entityid = (select id from entity where name like '%荃灣官立小學%') and year=2013;
update entityscore set admitted=37 ,vacancy=75 where entityid = (select id from entity where name like '%石籬聖若望天主教小學%') and year=2013;
update entityscore set admitted=41 ,vacancy=90 where entityid = (select id from entity where name like '%聖公會主愛小學（梨木樹）%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%石籬天主教小學%') and year=2013;
update entityscore set admitted=46 ,vacancy=100 where entityid = (select id from entity where name like '%梨木樹天主教小學%') and year=2013;
update entityscore set admitted=80 ,vacancy=100 where entityid = (select id from entity where name like '%嗇色園主辦可信學校%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%慈幼葉漢小學%') and year=2013;
update entityscore set admitted=71 ,vacancy=150 where entityid = (select id from entity where name like '%慈幼葉漢千禧小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=150 where entityid = (select id from entity where name like '%聖公會主愛小學%') and year=2013;
update entityscore set admitted=42 ,vacancy=90 where entityid = (select id from entity where name like '%中華基督教會全完第二小學%') and year=2013;
update entityscore set admitted=69 ,vacancy=100 where entityid = (select id from entity where name like '%中華傳道會許大同學校%') and year=2013;
update entityscore set admitted=69 ,vacancy=100 where entityid = (select id from entity where name like '%佛教林炳炎紀念學校%') and year=2013;
update entityscore set admitted=83 ,vacancy=100 where entityid = (select id from entity where name like '%亞斯理衞理小學%') and year=2013;
update entityscore set admitted=68 ,vacancy=100 where entityid = (select id from entity where name like '%東華三院高可寧紀念小學%') and year=2013;
update entityscore set admitted=55 ,vacancy=100 where entityid = (select id from entity where name like '%祖堯天主教小學%') and year=2013;
update entityscore set admitted=44 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會主恩小學%') and year=2013;
update entityscore set admitted=72 ,vacancy=100 where entityid = (select id from entity where name like '%柏立基教育學院校友會李一諤紀念學校%') and year=2013;
update entityscore set admitted=56 ,vacancy=100 where entityid = (select id from entity where name like '%基督教香港信義會葵盛信義學校%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%中華基督教會基真小學%') and year=2013;
update entityscore set admitted=71 ,vacancy=150 where entityid = (select id from entity where name like '%佛教林金殿紀念小學%') and year=2013;
update entityscore set admitted=58 ,vacancy=150 where entityid = (select id from entity where name like '%聖公會仁立小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=150 where entityid = (select id from entity where name like '%聖公會仁立紀念小學%') and year=2013;
update entityscore set admitted=37 ,vacancy=75 where entityid = (select id from entity where name like '%東華三院周演森小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%中華傳道會呂明才小學%') and year=2013;
update entityscore set admitted=63 ,vacancy=100 where entityid = (select id from entity where name like '%仁濟醫院趙曾學韞小學%') and year=2013;
update entityscore set admitted=56 ,vacancy=100 where entityid = (select id from entity where name like '%東華三院黃士心小學%') and year=2013;
update entityscore set admitted=73 ,vacancy=100 where entityid = (select id from entity where name like '%青衣商會小學%') and year=2013;
update entityscore set admitted=68 ,vacancy=100 where entityid = (select id from entity where name like '%荃灣商會學校%') and year=2013;
update entityscore set admitted=69 ,vacancy=100 where entityid = (select id from entity where name like '%郭怡雅神父紀念學校%') and year=2013;
update entityscore set admitted=53 ,vacancy=120 where entityid = (select id from entity where name like '%保良局世德小學%') and year=2013;
update entityscore set admitted=60 ,vacancy=120 where entityid = (select id from entity where name like '%保良局陳溢小學%') and year=2013;
update entityscore set admitted=58 ,vacancy=125 where entityid = (select id from entity where name like '%聖公會何澤芸小學%') and year=2013;
update entityscore set admitted=72 ,vacancy=150 where entityid = (select id from entity where name like '%聖公會青衣主恩小學%') and year=2013;
update entityscore set admitted=75 ,vacancy=150 where entityid = (select id from entity where name like '%聖公會青衣邨何澤芸小學%') and year=2013;
update entityscore set admitted=39 ,vacancy=100 where entityid = (select id from entity where name like '%五邑鄒振猷學校%') and year=2013;
update entityscore set admitted=79 ,vacancy=100 where entityid = (select id from entity where name like '%仁德天主教小學%') and year=2013;
update entityscore set admitted=42 ,vacancy=100 where entityid = (select id from entity where name like '%屯門官立小學%') and year=2013;
update entityscore set admitted=79 ,vacancy=100 where entityid = (select id from entity where name like '%世界龍岡學校劉德容紀念小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=100 where entityid = (select id from entity where name like '%柏立基教育學院校友會何壽基學校%') and year=2013;
update entityscore set admitted=60 ,vacancy=100 where entityid = (select id from entity where name like '%香港紅卍字會屯門卍慈小學%') and year=2013;
update entityscore set admitted=39 ,vacancy=100 where entityid = (select id from entity where name like '%香港路德會增城兆霖學校%') and year=2013;
update entityscore set admitted=42 ,vacancy=100 where entityid = (select id from entity where name like '%道教青松小學（湖景邨）%') and year=2013;
update entityscore set admitted=42 ,vacancy=100 where entityid = (select id from entity where name like '%僑港伍氏宗親會伍時暢紀念學校%') and year=2013;
update entityscore set admitted=39 ,vacancy=100 where entityid = (select id from entity where name like '%樂善堂梁黃蕙芳紀念學校%') and year=2013;
update entityscore set admitted=48 ,vacancy=120 where entityid = (select id from entity where name like '%保良局方王錦全小學%') and year=2013;
update entityscore set admitted=52 ,vacancy=125 where entityid = (select id from entity where name like '%中華基督教會何福堂小學%') and year=2013;
update entityscore set admitted=52 ,vacancy=125 where entityid = (select id from entity where name like '%中華基督教會蒙黃花沃紀念小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=125 where entityid = (select id from entity where name like '%仁濟醫院羅陳楚思小學%') and year=2013;
update entityscore set admitted=82 ,vacancy=125 where entityid = (select id from entity where name like '%台山商會學校%') and year=2013;
update entityscore set admitted=49 ,vacancy=125 where entityid = (select id from entity where name like '%保良局莊啟程第二小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=125 where entityid = (select id from entity where name like '%道教青松小學%') and year=2013;
update entityscore set admitted=60 ,vacancy=150 where entityid = (select id from entity where name like '%保良局志豪小學%') and year=2013;
update entityscore set admitted=60 ,vacancy=150 where entityid = (select id from entity where name like '%保良局梁周順琴小學%') and year=2013;
update entityscore set admitted=21 ,vacancy=50 where entityid = (select id from entity where name like '%中華基督教會拔臣小學%') and year=2013;
update entityscore set admitted=92 ,vacancy=100 where entityid = (select id from entity where name like '%仁濟醫院何式南小學%') and year=2013;
update entityscore set admitted=87 ,vacancy=100 where entityid = (select id from entity where name like '%伊斯蘭學校%') and year=2013;
update entityscore set admitted=92 ,vacancy=100 where entityid = (select id from entity where name like '%青山天主教小學%') and year=2013;
update entityscore set admitted=42 ,vacancy=100 where entityid = (select id from entity where name like '%保良局西區婦女福利會馮李佩瑤小學%') and year=2013;
update entityscore set admitted=30 ,vacancy=100 where entityid = (select id from entity where name like '%順德聯誼總會胡少渠紀念小學%') and year=2013;
update entityscore set admitted=64 ,vacancy=100 where entityid = (select id from entity where name like '%興德學校%') and year=2013;
update entityscore set admitted=32 ,vacancy=100 where entityid = (select id from entity where name like '%博愛醫院歷屆總理聯誼會鄭任安夫人學校%') and year=2013;
update entityscore set admitted=73 ,vacancy=125 where entityid = (select id from entity where name like '%東華三院鄧肇堅小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=125 where entityid = (select id from entity where name like '%順德聯誼總會李金小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=125 where entityid = (select id from entity where name like '%路德會呂祥光小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=125 where entityid = (select id from entity where name like '%博愛醫院歷屆總理聯誼會鄭任安夫人千禧小學%') and year=2013;
update entityscore set admitted=54 ,vacancy=150 where entityid = (select id from entity where name like '%順德聯誼總會何日東小學%') and year=2013;
update entityscore set admitted=42 ,vacancy=150 where entityid = (select id from entity where name like '%聖公會蒙恩小學%') and year=2013;
update entityscore set admitted=18 ,vacancy=50 where entityid = (select id from entity where name like '%寶覺分校%') and year=2013;
update entityscore set admitted=32 ,vacancy=100 where entityid = (select id from entity where name like '%嗇色園主辦可銘學校%') and year=2013;
update entityscore set admitted=48 ,vacancy=125 where entityid = (select id from entity where name like '%十八鄉鄉事委員會公益社小學%') and year=2013;
update entityscore set admitted=38 ,vacancy=125 where entityid = (select id from entity where name like '%中華基督教青年會小學%') and year=2013;
update entityscore set admitted=36 ,vacancy=125 where entityid = (select id from entity where name like '%元朗公立中學校友會英業小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=125 where entityid = (select id from entity where name like '%天水圍天主教小學%') and year=2013;
update entityscore set admitted=52 ,vacancy=125 where entityid = (select id from entity where name like '%天水圍官立小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=125 where entityid = (select id from entity where name like '%天水圍循道衞理小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=125 where entityid = (select id from entity where name like '%伊利沙伯中學舊生會小學%') and year=2013;
update entityscore set admitted=52 ,vacancy=125 where entityid = (select id from entity where name like '%伊利沙伯中學舊生會小學分校%') and year=2013;
update entityscore set admitted=37 ,vacancy=125 where entityid = (select id from entity where name like '%東華三院李東海小學%') and year=2013;
update entityscore set admitted=41 ,vacancy=125 where entityid = (select id from entity where name like '%東華三院姚達之紀念小學（元朗）%') and year=2013;
update entityscore set admitted=37 ,vacancy=125 where entityid = (select id from entity where name like '%金巴崙長老會耀道小學%') and year=2013;
update entityscore set admitted=52 ,vacancy=125 where entityid = (select id from entity where name like '%宣道會葉紹蔭紀念小學%') and year=2013;
update entityscore set admitted=52 ,vacancy=125 where entityid = (select id from entity where name like '%香港青年協會李兆基小學%') and year=2013;
update entityscore set admitted=39 ,vacancy=125 where entityid = (select id from entity where name like '%香港普通話研習社科技創意小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=125 where entityid = (select id from entity where name like '%香港潮陽小學%') and year=2013;
update entityscore set admitted=39 ,vacancy=125 where entityid = (select id from entity where name like '%香港學生輔助會小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=125 where entityid = (select id from entity where name like '%順德聯誼總會伍冕端小學%') and year=2013;
update entityscore set admitted=39 ,vacancy=125 where entityid = (select id from entity where name like '%獅子會何德心小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%聖公會天水圍靈愛小學%') and year=2013;
update entityscore set admitted=36 ,vacancy=125 where entityid = (select id from entity where name like '%樂善堂梁銶琚學校%') and year=2013;
update entityscore set admitted=39 ,vacancy=125 where entityid = (select id from entity where name like '%樂善堂梁銶琚學校（分校）%') and year=2013;
update entityscore set admitted=37 ,vacancy=125 where entityid = (select id from entity where name like '%潮陽百欣小學%') and year=2013;
update entityscore set admitted=22 ,vacancy=60 where entityid = (select id from entity where name like '%聖公會靈愛小學%') and year=2013;
update entityscore set admitted=46 ,vacancy=75 where entityid = (select id from entity where name like '%元朗朗屏邨東莞學校%') and year=2013;
update entityscore set admitted=64 ,vacancy=100 where entityid = (select id from entity where name like '%元朗公立中學校友會小學%') and year=2013;
update entityscore set admitted=68 ,vacancy=100 where entityid = (select id from entity where name like '%元朗朗屏邨惠州學校%') and year=2013;
update entityscore set admitted=63 ,vacancy=100 where entityid = (select id from entity where name like '%元朗商會小學%') and year=2013;
update entityscore set admitted=59 ,vacancy=100 where entityid = (select id from entity where name like '%光明學校%') and year=2013;
update entityscore set admitted=67 ,vacancy=100 where entityid = (select id from entity where name like '%佛教陳榮根紀念學校%') and year=2013;
update entityscore set admitted=66 ,vacancy=100 where entityid = (select id from entity where name like '%博愛醫院歷屆總理聯誼會梁省德學校%') and year=2013;
update entityscore set admitted=72 ,vacancy=125 where entityid = (select id from entity where name like '%南元朗官立小學%') and year=2013;
update entityscore set admitted=14 ,vacancy=25 where entityid = (select id from entity where name like '%八鄉中心小學%') and year=2013;
update entityscore set admitted=19 ,vacancy=25 where entityid = (select id from entity where name like '%錦田公立蒙養學校%') and year=2013;
update entityscore set admitted=29 ,vacancy=50 where entityid = (select id from entity where name like '%惇裕學校%') and year=2013;
update entityscore set admitted=29 ,vacancy=50 where entityid = (select id from entity where name like '%港澳信義會黃陳淑英紀念學校%') and year=2013;
update entityscore set admitted=23 ,vacancy=60 where entityid = (select id from entity where name like '%聖公會錦田聖約瑟小學%') and year=2013;
update entityscore set admitted=21 ,vacancy=60 where entityid = (select id from entity where name like '%中華基督教會元朗真光小學%') and year=2013;
update entityscore set admitted=53 ,vacancy=100 where entityid = (select id from entity where name like '%佛教榮茵學校%') and year=2013;
update entityscore set admitted=68 ,vacancy=125 where entityid = (select id from entity where name like '%元朗官立小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=125 where entityid = (select id from entity where name like '%光明英來學校%') and year=2013;
update entityscore set admitted=49 ,vacancy=150 where entityid = (select id from entity where name like '%基督教宣道會徐澤林紀念小學%') and year=2013;
update entityscore set admitted=53 ,vacancy=150 where entityid = (select id from entity where name like '%鐘聲學校%') and year=2013;
update entityscore set admitted=10 ,vacancy=25 where entityid = (select id from entity where name like '%育賢學校%') and year=2013;
update entityscore set admitted=44 ,vacancy=50 where entityid = (select id from entity where name like '%東莞學校%') and year=2013;
update entityscore set admitted=46 ,vacancy=50 where entityid = (select id from entity where name like '%金錢村何東學校%') and year=2013;
update entityscore set admitted=37 ,vacancy=100 where entityid = (select id from entity where name like '%東華三院馬錦燦紀念小學%') and year=2013;
update entityscore set admitted=40 ,vacancy=100 where entityid = (select id from entity where name like '%東華三院港九電器商聯會小學%') and year=2013;
update entityscore set admitted=40 ,vacancy=100 where entityid = (select id from entity where name like '%香海正覺蓮社佛教陳式宏學校%') and year=2013;
update entityscore set admitted=48 ,vacancy=120 where entityid = (select id from entity where name like '%鳳溪第一小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=120 where entityid = (select id from entity where name like '%鳳溪創新小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=120 where entityid = (select id from entity where name like '%聖公會榮真小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=125 where entityid = (select id from entity where name like '%石湖墟公立學校%') and year=2013;
update entityscore set admitted=55 ,vacancy=150 where entityid = (select id from entity where name like '%上水惠州公立學校%') and year=2013;
update entityscore set admitted=60 ,vacancy=150 where entityid = (select id from entity where name like '%李志達紀念學校%') and year=2013;
update entityscore set admitted=60 ,vacancy=150 where entityid = (select id from entity where name like '%香海正覺蓮社佛教正慧小學%') and year=2013;
update entityscore set admitted=60 ,vacancy=150 where entityid = (select id from entity where name like '%曾梅千禧學校%') and year=2013;
update entityscore set admitted=40 ,vacancy=50 where entityid = (select id from entity where name like '%方樹福堂基金方樹泉小學%') and year=2013;
update entityscore set admitted=31 ,vacancy=75 where entityid = (select id from entity where name like '%粉嶺官立小學%') and year=2013;
update entityscore set admitted=27 ,vacancy=75 where entityid = (select id from entity where name like '%鳳溪廖潤琛紀念學校%') and year=2013;
update entityscore set admitted=29 ,vacancy=75 where entityid = (select id from entity where name like '%寶血會培靈學校%') and year=2013;
update entityscore set admitted=28 ,vacancy=90 where entityid = (select id from entity where name like '%上水宣道小學%') and year=2013;
update entityscore set admitted=37 ,vacancy=90 where entityid = (select id from entity where name like '%粉嶺公立學校%') and year=2013;
update entityscore set admitted=46 ,vacancy=100 where entityid = (select id from entity where name like '%五旬節于良發小學%') and year=2013;
update entityscore set admitted=33 ,vacancy=100 where entityid = (select id from entity where name like '%五旬節靳茂生小學%') and year=2013;
update entityscore set admitted=34 ,vacancy=100 where entityid = (select id from entity where name like '%基督教粉嶺神召會小學%') and year=2013;
update entityscore set admitted=43 ,vacancy=120 where entityid = (select id from entity where name like '%聖公會嘉福榮真小學%') and year=2013;
update entityscore set admitted=52 ,vacancy=125 where entityid = (select id from entity where name like '%香海正覺蓮社佛教正覺蓮社學校%') and year=2013;
update entityscore set admitted=8 ,vacancy=50 where entityid = (select id from entity where name like '%山咀公立學校%') and year=2013;
update entityscore set admitted=8 ,vacancy=50 where entityid = (select id from entity where name like '%沙頭角中心學校%') and year=2013;
update entityscore set admitted=28 ,vacancy=75 where entityid = (select id from entity where name like '%香港教育學院賽馬會小學%') and year=2013;
update entityscore set admitted=59 ,vacancy=100 where entityid = (select id from entity where name like '%三水同鄉會禤景榮學校%') and year=2013;
update entityscore set admitted=59 ,vacancy=100 where entityid = (select id from entity where name like '%大埔崇德黃建常紀念學校%') and year=2013;
update entityscore set admitted=64 ,vacancy=100 where entityid = (select id from entity where name like '%仁濟醫院蔡衍濤小學%') and year=2013;
update entityscore set admitted=61 ,vacancy=100 where entityid = (select id from entity where name like '%天主教聖母聖心小學%') and year=2013;
update entityscore set admitted=69 ,vacancy=100 where entityid = (select id from entity where name like '%林村公立黃福鑾紀念學校%') and year=2013;
update entityscore set admitted=59 ,vacancy=100 where entityid = (select id from entity where name like '%保良局田家炳小學%') and year=2013;
update entityscore set admitted=83 ,vacancy=100 where entityid = (select id from entity where name like '%香港道教聯合會雲泉吳禮和紀念學校%') and year=2013;
update entityscore set admitted=59 ,vacancy=100 where entityid = (select id from entity where name like '%港九街坊婦女會孫方中小學%') and year=2013;
update entityscore set admitted=59 ,vacancy=100 where entityid = (select id from entity where name like '%新界婦孺福利會梁省德學校%') and year=2013;
update entityscore set admitted=55 ,vacancy=100 where entityid = (select id from entity where name like '%聖公會阮鄭夢芹銀禧小學%') and year=2013;
update entityscore set admitted=44 ,vacancy=120 where entityid = (select id from entity where name like '%大埔舊墟公立學校%') and year=2013;
update entityscore set admitted=73 ,vacancy=125 where entityid = (select id from entity where name like '%大埔官立小學%') and year=2013;
update entityscore set admitted=85 ,vacancy=125 where entityid = (select id from entity where name like '%大埔浸信會公立學校%') and year=2013;
update entityscore set admitted=77 ,vacancy=125 where entityid = (select id from entity where name like '%大埔循道衞理小學%') and year=2013;
update entityscore set admitted=77 ,vacancy=125 where entityid = (select id from entity where name like '%保良局田家炳千禧小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=125 where entityid = (select id from entity where name like '%聖公會阮鄭夢芹小學%') and year=2013;
update entityscore set admitted=52 ,vacancy=150 where entityid = (select id from entity where name like '%大埔舊墟公立學校（寶湖道）%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%東華三院冼次雲小學%') and year=2013;
update entityscore set admitted=47 ,vacancy=100 where entityid = (select id from entity where name like '%迦密愛禮信小學%') and year=2013;
update entityscore set admitted=88 ,vacancy=100 where entityid = (select id from entity where name like '%香港中文大學校友會聯會張煊昌學校%') and year=2013;
update entityscore set admitted=46 ,vacancy=100 where entityid = (select id from entity where name like '%循理會白普理基金循理小學%') and year=2013;
update entityscore set admitted=82 ,vacancy=100 where entityid = (select id from entity where name like '%循理會美林小學%') and year=2013;
update entityscore set admitted=43 ,vacancy=120 where entityid = (select id from entity where name like '%聖母無玷聖心學校%') and year=2013;
update entityscore set admitted=51 ,vacancy=120 where entityid = (select id from entity where name like '%香港九龍塘基督教中華宣道會陳元喜小學%') and year=2013;
update entityscore set admitted=60 ,vacancy=125 where entityid = (select id from entity where name like '%沙田官立小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%保良局王賜豪（田心谷）小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%九龍城浸信會禧年小學%') and year=2013;
update entityscore set admitted=79 ,vacancy=100 where entityid = (select id from entity where name like '%吳氏宗親總會泰伯紀念學校%') and year=2013;
update entityscore set admitted=48 ,vacancy=100 where entityid = (select id from entity where name like '%保良局莊啓程小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=100 where entityid = (select id from entity where name like '%基督教香港信義會馬鞍山信義學校%') and year=2013;
update entityscore set admitted=58 ,vacancy=125 where entityid = (select id from entity where name like '%保良局雨川小學%') and year=2013;
update entityscore set admitted=86 ,vacancy=125 where entityid = (select id from entity where name like '%香港道教聯合會純陽小學%') and year=2013;
update entityscore set admitted=112 ,vacancy=125 where entityid = (select id from entity where name like '%馬鞍山聖若瑟小學%') and year=2013;
update entityscore set admitted=51 ,vacancy=125 where entityid = (select id from entity where name like '%聖公會馬鞍山主風小學%') and year=2013;
update entityscore set admitted=118 ,vacancy=125 where entityid = (select id from entity where name like '%香港九龍塘基督教中華宣道會台山陳元喜小學%') and year=2013;
update entityscore set admitted=71 ,vacancy=150 where entityid = (select id from entity where name like '%馬鞍山循道衛理小學%') and year=2013;
update entityscore set admitted=70 ,vacancy=150 where entityid = (select id from entity where name like '%馬鞍山靈糧小學%') and year=2013;
update entityscore set admitted=75 ,vacancy=100 where entityid = (select id from entity where name like '%沙田崇真學校%') and year=2013;
update entityscore set admitted=40 ,vacancy=100 where entityid = (select id from entity where name like '%沙田圍胡素貞博士紀念學校%') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name like '%沙田循道衞理小學%') and year=2013;
update entityscore set admitted=48 ,vacancy=100 where entityid = (select id from entity where name like '%保良局蕭漢森小學%') and year=2013;
update entityscore set admitted=98 ,vacancy=100 where entityid = (select id from entity where name like '%基督教香港信義會禾輋信義學校%') and year=2013;
update entityscore set admitted=48 ,vacancy=100 where entityid = (select id from entity where name like '%救世軍田家炳學校%') and year=2013;
update entityscore set admitted=56 ,vacancy=120 where entityid = (select id from entity where name like '%保良局朱正賢小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=120 where entityid = (select id from entity where name like '%胡素貞博士紀念學校%') and year=2013;
update entityscore set admitted=32 ,vacancy=120 where entityid = (select id from entity where name like '%浸信會呂明才小學%') and year=2013;
update entityscore set admitted=42 ,vacancy=120 where entityid = (select id from entity where name like '%培基小學%') and year=2013;
update entityscore set admitted=54 ,vacancy=120 where entityid = (select id from entity where name like '%聖公會主風小學%') and year=2013;
update entityscore set admitted=49 ,vacancy=125 where entityid = (select id from entity where name like '%路德會梁鉅鏐小學%') and year=2013;
update entityscore set admitted=50 ,vacancy=150 where entityid = (select id from entity where name like '%浸信會沙田圍呂明才小學%') and year=2013;
update entityscore set admitted=42 ,vacancy=75 where entityid = (select id from entity where name like '%西貢崇真天主教學校（小學部）%') and year=2013;
update entityscore set admitted=81 ,vacancy=100 where entityid = (select id from entity where name like '%景林天主教小學%') and year=2013;
update entityscore set admitted=80 ,vacancy=100 where entityid = (select id from entity where name like '%樂善堂劉德學校%') and year=2013;
update entityscore set admitted=78 ,vacancy=125 where entityid = (select id from entity where name like '%仁愛堂田家炳小學%') and year=2013;
update entityscore set admitted=100 ,vacancy=125 where entityid = (select id from entity where name like '%仁濟醫院陳耀星小學%') and year=2013;
update entityscore set admitted=58 ,vacancy=125 where entityid = (select id from entity where name like '%天主教聖安德肋小學%') and year=2013;
update entityscore set admitted=67 ,vacancy=125 where entityid = (select id from entity where name like '%西貢中心李少欽紀念學校%') and year=2013;
update entityscore set admitted=105 ,vacancy=125 where entityid = (select id from entity where name like '%佛教志蓮小學%') and year=2013;
update entityscore set admitted=58 ,vacancy=125 where entityid = (select id from entity where name like '%東華三院王余家潔紀念小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%保良局馮晴紀念小學%') and year=2013;
update entityscore set admitted=59 ,vacancy=125 where entityid = (select id from entity where name like '%保良局黃永樹小學%') and year=2013;
update entityscore set admitted=83 ,vacancy=125 where entityid = (select id from entity where name like '%香海正覺蓮社佛教黃藻森學校%') and year=2013;
update entityscore set admitted=58 ,vacancy=125 where entityid = (select id from entity where name like '%基督教宣道會宣基小學%') and year=2013;
update entityscore set admitted=104 ,vacancy=125 where entityid = (select id from entity where name like '%基督教神召會梁省德小學%') and year=2013;
update entityscore set admitted=58 ,vacancy=125 where entityid = (select id from entity where name like '%將軍澳天主教小學%') and year=2013;
update entityscore set admitted=81 ,vacancy=125 where entityid = (select id from entity where name like '%將軍澳官立小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%將軍澳循道衛理小學%') and year=2013;
update entityscore set admitted=102 ,vacancy=125 where entityid = (select id from entity where name like '%博愛醫院陳國威小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%港澳信義會小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%港澳信義會明道小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%順德聯誼總會梁潔華小學%') and year=2013;
update entityscore set admitted=98 ,vacancy=125 where entityid = (select id from entity where name like '%聖公會將軍澳基德小學%') and year=2013;
update entityscore set admitted=12 ,vacancy=25 where entityid = (select id from entity where name like '%南丫北段公立小學%') and year=2013;
update entityscore set admitted=14 ,vacancy=30 where entityid = (select id from entity where name like '%中華基督教會長洲堂錦江小學%') and year=2013;
update entityscore set admitted=22 ,vacancy=50 where entityid = (select id from entity where name like '%長洲聖心學校%') and year=2013;
update entityscore set admitted=47 ,vacancy=75 where entityid = (select id from entity where name like '%國民學校%') and year=2013;
update entityscore set admitted=22 ,vacancy=25 where entityid = (select id from entity where name like '%中華基督教會大澳小學%') and year=2013;
update entityscore set admitted=5 ,vacancy=25 where entityid = (select id from entity where name like '%杯澳公立學校%') and year=2013;
update entityscore set admitted=11 ,vacancy=25 where entityid = (select id from entity where name like '%梅窩學校%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%東涌天主教學校%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%青松侯寶垣小學%') and year=2013;
update entityscore set admitted=93 ,vacancy=125 where entityid = (select id from entity where name like '%香港教育工作者聯會黃楚標學校%') and year=2013;
update entityscore set admitted=59 ,vacancy=125 where entityid = (select id from entity where name like '%救世軍林拔中紀念學校%') and year=2013;
update entityscore set admitted=99 ,vacancy=125 where entityid = (select id from entity where name like '%嗇色園主辦可譽中學暨可譽小學%') and year=2013;
update entityscore set admitted=107 ,vacancy=125 where entityid = (select id from entity where name like '%寶安商會溫浩根小學%') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name like '%靈糧堂秀德小學%') and year=2013;
update entityscore set admitted=11 ,vacancy=25 where entityid = (select id from entity where name like '%聖家學校%') and year=2013;
update entityscore set admitted=31 ,vacancy=75 where entityid = (select id from entity where name like '%聖公會偉倫小學%') and year=2013;




update entity set admitted=56 ,vacancy=75 where name like '%聖嘉祿學校%';
update entity set admitted=87 ,vacancy=100 where name like '%佛教黃焯菴小學%';
update entity set admitted=75 ,vacancy=100 where name like '%保良局金銀業貿易場張凝文學校%';
update entity set admitted=115 ,vacancy=125 where name like '%啟基學校（港島）%';
update entity set admitted=104 ,vacancy=125 where name like '%北角官立小學（雲景道）%';
update entity set admitted=78 ,vacancy=100 where name like '%慈幼學校%';
update entity set admitted=81 ,vacancy=100 where name like '%廣東道官立小學%';
update entity set admitted=87 ,vacancy=100 where name like '%九龍婦女福利會李炳紀念學校%';
update entity set admitted=98 ,vacancy=100 where name like '%聖匠小學%';
update entity set admitted=131 ,vacancy=150 where name like '%天主教領島學校%';
update entity set admitted=127 ,vacancy=150 where name like '%葛量洪校友會黃埔學校%';
update entity set admitted=65 ,vacancy=75 where name like '%深水埔街坊福利會小學%';
update entity set admitted=120 ,vacancy=125 where name like '%五邑工商總會學校%';
update entity set admitted=133 ,vacancy=150 where name like '%白田天主教小學%';
update entity set admitted=130 ,vacancy=150 where name like '%深水埗官立小學%';
update entity set admitted=122 ,vacancy=125 where name like '%樂善堂小學%';
update entity set admitted=76 ,vacancy=100 where name like '%樂善堂楊仲明學校%';
update entity set admitted=100 ,vacancy=125 where name like '%香港道教聯合會圓玄學院石圍角小學%';
update entity set admitted=141 ,vacancy=150 where name like '%荃灣潮州公學%';
update entity set admitted=138 ,vacancy=150 where name like '%路德會聖十架學校%';
update entity set admitted=110 ,vacancy=125 where name like '%仁愛堂劉皇發夫人小學%';
update entity set admitted=25 ,vacancy=50 where name like '%通德學校%';
update entity set admitted=70 ,vacancy=75 where name like '%打鼓嶺嶺英公立學校%';
update entity set admitted=116 ,vacancy=125 where name like '%九龍城浸信會禧年（恩平）小學%';
update entity set admitted=119 ,vacancy=125 where name like '%東莞工商總會張煌偉小學%';
update entity set admitted=144 ,vacancy=150 where name like '%天主教聖華學校%';
update entity set admitted=134 ,vacancy=150 where name like '%世界龍岡學校黃耀南小學%';
update entity set admitted=140 ,vacancy=150 where name like '%慈航學校%';
update entity set admitted=28 ,vacancy=50 where name like '%李陞小學%';
update entity set admitted=25 ,vacancy=50 where name like '%英皇書院同學會小學%';
update entity set admitted=49 ,vacancy=50 where name like '%新會商會學校%';
update entity set admitted=25 ,vacancy=50 where name like '%聖公會聖馬太小學%';
update entity set admitted=24 ,vacancy=60 where name like '%般咸道官立小學%';
update entity set admitted=35 ,vacancy=75 where name like '%英皇書院同學會小學第二校%';
update entity set admitted=45 ,vacancy=90 where name like '%中西區聖安多尼學校%';
update entity set admitted=42 ,vacancy=90 where name like '%聖公會基恩小學%';
update entity set admitted=43 ,vacancy=90 where name like '%聖安多尼學校%';
update entity set admitted=75 ,vacancy=100 where name like '%天主教總堂區學校%';
update entity set admitted=75 ,vacancy=100 where name like '%香港潮商學校%';
update entity set admitted=47 ,vacancy=100 where name like '%聖士提反女子中學附屬小學%';
update entity set admitted=48 ,vacancy=100 where name like '%聖公會呂明才紀念小學%';
update entity set admitted=70 ,vacancy=150 where name like '%嘉諾撒聖心學校%';
update entity set admitted=74 ,vacancy=180 where name like '%聖公會聖彼得小學%';
update entity set admitted=24 ,vacancy=50 where name like '%李陞大坑學校%';
update entity set admitted=23 ,vacancy=50 where name like '%寶覺小學%';
update entity set admitted=21 ,vacancy=60 where name like '%番禺會所華仁上午小學%';
update entity set admitted=28 ,vacancy=60 where name like '%番禺會所華仁下午小學%';
update entity set admitted=40 ,vacancy=75 where name like '%東華三院李賜豪小學%';
update entity set admitted=35 ,vacancy=75 where name like '%寶血小學%';
update entity set admitted=85 ,vacancy=100 where name like '%官立嘉道理爵士小學%';
update entity set admitted=56 ,vacancy=120 where name like '%嘉諾撒聖方濟各學校%';
update entity set admitted=56 ,vacancy=120 where name like '%瑪利曼小學%';
update entity set admitted=56 ,vacancy=120 where name like '%聖保祿天主教小學%';
update entity set admitted=55 ,vacancy=125 where name like '%軒尼詩道官立上午小學%';
update entity set admitted=54 ,vacancy=125 where name like '%軒尼詩道官立下午小學%';
update entity set admitted=58 ,vacancy=125 where name like '%聖公會聖雅各小學%';
update entity set admitted=70 ,vacancy=150 where name like '%聖若瑟小學%';
update entity set admitted=22 ,vacancy=60 where name like '%北角衞理上午小學%';
update entity set admitted=23 ,vacancy=60 where name like '%北角衞理下午小學%';
update entity set admitted=31 ,vacancy=75 where name like '%丹拿山循道學校%';
update entity set admitted=50 ,vacancy=100 where name like '%北角循道學校%';
update entity set admitted=95 ,vacancy=100 where name like '%佛教中華康山學校%';
update entity set admitted=60 ,vacancy=120 where name like '%聖公會聖米迦勒小學%';
update entity set admitted=54 ,vacancy=120 where name like '%滬江小學%';
update entity set admitted=84 ,vacancy=125 where name like '%太古小學%';
update entity set admitted=75 ,vacancy=150 where name like '%北角官立小學%';
update entity set admitted=82 ,vacancy=180 where name like '%香港嘉諾撒學校%';
update entity set admitted=50 ,vacancy=100 where name like '%天主教明德學校%';
update entity set admitted=80 ,vacancy=100 where name like '%基督教香港信義會信愛學校%';
update entity set admitted=73 ,vacancy=100 where name like '%救世軍中原慈善基金學校%';
update entity set admitted=50 ,vacancy=100 where name like '%救世軍韋理夫人紀念學校%';
update entity set admitted=81 ,vacancy=100 where name like '%筲箕灣官立小學%';
update entity set admitted=47 ,vacancy=100 where name like '%筲箕灣崇真學校%';
update entity set admitted=86 ,vacancy=100 where name like '%聖馬可小學%';
update entity set admitted=45 ,vacancy=120 where name like '%中華基督教會基灣小學%';
update entity set admitted=47 ,vacancy=120 where name like '%中華基督教會基灣小學（愛蝶灣）%';
update entity set admitted=54 ,vacancy=120 where name like '%聖公會柴灣聖米迦勒小學%';
update entity set admitted=57 ,vacancy=125 where name like '%培僑小學%';
update entity set admitted=86 ,vacancy=125 where name like '%愛秩序灣官立小學%';
update entity set admitted=62 ,vacancy=125 where name like '%勵志會梁李秀娛紀念小學%';
update entity set admitted=71 ,vacancy=150 where name like '%香港中國婦女會丘佐榮學校%';
update entity set admitted=36 ,vacancy=50 where name like '%香島道官立小學%';
update entity set admitted=27 ,vacancy=50 where name like '%嘉諾撒培德學校%';
update entity set admitted=81 ,vacancy=100 where name like '%東華三院鶴山學校%';
update entity set admitted=44 ,vacancy=100 where name like '%香港南區官立小學%';
update entity set admitted=46 ,vacancy=100 where name like '%海怡寶血小學%';
update entity set admitted=73 ,vacancy=100 where name like '%華富邨寶血小學%';
update entity set admitted=50 ,vacancy=100 where name like '%聖伯多祿天主教小學%';
update entity set admitted=78 ,vacancy=100 where name like '%鴨脷洲街坊學校%';
update entity set admitted=60 ,vacancy=120 where name like '%聖公會置富始南小學%';
update entity set admitted=62 ,vacancy=125 where name like '%香港仔聖伯多祿天主教小學%';
update entity set admitted=75 ,vacancy=150 where name like '%聖公會田灣始南小學%';
update entity set admitted=27 ,vacancy=60 where name like '%油蔴地街坊會學校%';
update entity set admitted=34 ,vacancy=75 where name like '%中華基督教會灣仔堂基道小學%';
update entity set admitted=78 ,vacancy=100 where name like '%佐敦道官立小學%';
update entity set admitted=47 ,vacancy=100 where name like '%嘉諾撒聖瑪利學校%';
update entity set admitted=56 ,vacancy=120 where name like '%循道學校%';
update entity set admitted=56 ,vacancy=120 where name like '%德信學校%';
update entity set admitted=114 ,vacancy=125 where name like '%東莞同鄉會方樹泉學校%';
update entity set admitted=117 ,vacancy=125 where name like '%東華三院羅裕積小學%';
update entity set admitted=57 ,vacancy=150 where name like '%油蔴地天主教小學%';
update entity set admitted=55 ,vacancy=150 where name like '%油蔴地天主教小學（海泓道）%';
update entity set admitted=24 ,vacancy=50 where name like '%鮮魚行學校%';
update entity set admitted=50 ,vacancy=100 where name like '%塘尾道官立小學%';
update entity set admitted=60 ,vacancy=120 where name like '%聖公會基榮小學%';
update entity set admitted=58 ,vacancy=125 where name like '%大角嘴天主教小學%';
update entity set admitted=104 ,vacancy=125 where name like '%中華基督教會基全小學%';
update entity set admitted=80 ,vacancy=125 where name like '%路德會沙崙學校%';
update entity set admitted=75 ,vacancy=150 where name like '%大角嘴天主教小學（海帆道）%';
update entity set admitted=67 ,vacancy=180 where name like '%中華基督教會協和小學%';
update entity set admitted=25 ,vacancy=50 where name like '%九龍靈光小學%';
update entity set admitted=35 ,vacancy=50 where name like '%基督教香港信義會紅磡信義學校%';
update entity set admitted=23 ,vacancy=50 where name like '%聖公會牧愛小學%';
update entity set admitted=37 ,vacancy=75 where name like '%中華基督教會灣仔堂基道小學（九龍城）%';
update entity set admitted=36 ,vacancy=75 where name like '%獻主會聖馬善樂小學%';
update entity set admitted=42 ,vacancy=90 where name like '%協恩中學附屬小學%';
update entity set admitted=47 ,vacancy=100 where name like '%合一堂學校%';
update entity set admitted=44 ,vacancy=100 where name like '%農圃道官立小學%';
update entity set admitted=50 ,vacancy=100 where name like '%獻主會小學%';
update entity set admitted=56 ,vacancy=120 where name like '%聖羅撒學校%';
update entity set admitted=49 ,vacancy=125 where name like '%馬頭涌官立小學%';
update entity set admitted=61 ,vacancy=150 where name like '%陳瑞祺（喇沙）小學%';
update entity set admitted=35 ,vacancy=75 where name like '%天神嘉諾撒學校%';
update entity set admitted=46 ,vacancy=100 where name like '%聖公會奉基千禧小學%';
update entity set admitted=47 ,vacancy=100 where name like '%聖公會奉基小學%';
update entity set admitted=80 ,vacancy=100 where name like '%聖公會聖提摩太小學%';
update entity set admitted=49 ,vacancy=125 where name like '%馬頭涌官立小學（紅磡灣）%';
update entity set admitted=70 ,vacancy=150 where name like '%黃埔宣道小學%';
update entity set admitted=25 ,vacancy=50 where name like '%基督教香港信義會深信學校%';
update entity set admitted=58 ,vacancy=75 where name like '%香港四邑商工總會新會商會學校%';
update entity set admitted=42 ,vacancy=90 where name like '%聖公會聖多馬小學%';
update entity set admitted=50 ,vacancy=100 where name like '%天主教善導小學%';
update entity set admitted=41 ,vacancy=100 where name like '%李鄭屋官立小學%';
update entity set admitted=45 ,vacancy=100 where name like '%旅港開平商會學校%';
update entity set admitted=92 ,vacancy=100 where name like '%聖公會基愛小學%';
update entity set admitted=44 ,vacancy=100 where name like '%瑪利諾神父教會學校（小學部）%';
update entity set admitted=54 ,vacancy=100 where name like '%福榮街官立小學%';
update entity set admitted=59 ,vacancy=120 where name like '%聖方濟愛德小學%';
update entity set admitted=60 ,vacancy=120 where name like '%大坑東宣道小學%';
update entity set admitted=86 ,vacancy=120 where name like '%聖公會聖紀文小學%';
update entity set admitted=68 ,vacancy=150 where name like '%中華基督教會協和小學（長沙灣）%';
update entity set admitted=67 ,vacancy=150 where name like '%荔枝角天主教小學%';
update entity set admitted=70 ,vacancy=150 where name like '%寶血會嘉靈學校%';
update entity set admitted=85 ,vacancy=180 where name like '%聖公會基福小學%';
update entity set admitted=90 ,vacancy=180 where name like '%聖公會聖安德烈小學%';
update entity set admitted=15 ,vacancy=25 where name like '%耀山學校%';
update entity set admitted=24 ,vacancy=60 where name like '%拔萃小學%';
update entity set admitted=42 ,vacancy=90 where name like '%嘉諾撒聖家學校%';
update entity set admitted=41 ,vacancy=100 where name like '%九龍塘天主教華德學校 （S)%';
update entity set admitted=36 ,vacancy=100 where name like '%九龍塘官立小學%';
update entity set admitted=41 ,vacancy=100 where name like '%華德學校%';
update entity set admitted=56 ,vacancy=120 where name like '%嘉諾撒聖家學校（九龍塘）%';
update entity set admitted=47 ,vacancy=120 where name like '%中華基督教會基華小學（九龍塘）%';
update entity set admitted=73 ,vacancy=150 where name like '%瑪利諾修院學校（小學部）%';
update entity set admitted=84 ,vacancy=180 where name like '%喇沙小學%';
update entity set admitted=51 ,vacancy=100 where name like '%天主教博智小學%';
update entity set admitted=65 ,vacancy=100 where name like '%孔教學院大成小學%';
update entity set admitted=46 ,vacancy=100 where name like '%浸信會天虹小學%';
update entity set admitted=34 ,vacancy=100 where name like '%黃大仙天主教小學%';
update entity set admitted=37 ,vacancy=100 where name like '%黃大仙官立小學%';
update entity set admitted=34 ,vacancy=100 where name like '%聖公會基德小學%';
update entity set admitted=46 ,vacancy=100 where name like '%聖博德學校%';
update entity set admitted=47 ,vacancy=100 where name like '%嘉諾撒小學%';
update entity set admitted=58 ,vacancy=100 where name like '%福德學校%';
update entity set admitted=52 ,vacancy=100 where name like '%獻主會溥仁小學%';
update entity set admitted=41 ,vacancy=120 where name like '%天主教伍華小學%';
update entity set admitted=56 ,vacancy=120 where name like '%保良局何壽南小學%';
update entity set admitted=36 ,vacancy=50 where name like '%保良局陳南昌夫人小學%';
update entity set admitted=37 ,vacancy=75 where name like '%真鐸學校%';
update entity set admitted=45 ,vacancy=100 where name like '%中華基督教會基華小學%';
update entity set admitted=49 ,vacancy=100 where name like '%中華基督教會基慈小學%';
update entity set admitted=76 ,vacancy=100 where name like '%伊斯蘭鮑伯濤紀念小學%';
update entity set admitted=50 ,vacancy=100 where name like '%彩雲聖若瑟小學%';
update entity set admitted=44 ,vacancy=100 where name like '%嗇色園主辦可立小學%';
update entity set admitted=47 ,vacancy=100 where name like '%聖公會日修小學%';
update entity set admitted=34 ,vacancy=100 where name like '%聖公會靜山小學%';
update entity set admitted=62 ,vacancy=125 where name like '%慈雲山天主教小學%';
update entity set admitted=70 ,vacancy=125 where name like '%慈雲山聖文德天主教小學%';
update entity set admitted=60 ,vacancy=125 where name like '%聖文德天主教小學%';
update entity set admitted=62 ,vacancy=125 where name like '%聖博德天主教小學（蒲崗村道）%';
update entity set admitted=62 ,vacancy=150 where name like '%保良局錦泰小學%';
update entity set admitted=65 ,vacancy=150 where name like '%嘉諾撒小學（新蒲崗）%';
update entity set admitted=53 ,vacancy=100 where name like '%佐敦谷聖若瑟天主教小學%';
update entity set admitted=63 ,vacancy=100 where name like '%佛教慈敬學校%';
update entity set admitted=66 ,vacancy=100 where name like '%坪石天主教小學%';
update entity set admitted=53 ,vacancy=100 where name like '%迦密梁省德學校%';
update entity set admitted=80 ,vacancy=100 where name like '%聖公會聖約翰小學%';
update entity set admitted=66 ,vacancy=125 where name like '%九龍灣聖若翰天主教小學%';
update entity set admitted=69 ,vacancy=125 where name like '%天主教柏德學校%';
update entity set admitted=68 ,vacancy=125 where name like '%浸信宣道會呂明才小學%';
update entity set admitted=68 ,vacancy=125 where name like '%聖公會九龍灣基樂小學%';
update entity set admitted=35 ,vacancy=50 where name like '%中華基督教會基法小學%';
update entity set admitted=70 ,vacancy=100 where name like '%天主教佑華小學%';
update entity set admitted=57 ,vacancy=100 where name like '%香港道教聯合會雲泉學校%';
update entity set admitted=67 ,vacancy=100 where name like '%聖公會基顯小學%';
update entity set admitted=65 ,vacancy=100 where name like '%聖若翰天主教小學%';
update entity set admitted=99 ,vacancy=100 where name like '%閩僑小學%';
update entity set admitted=70 ,vacancy=100 where name like '%樂華天主教小學%';
update entity set admitted=67 ,vacancy=100 where name like '%觀塘官立小學%';
update entity set admitted=60 ,vacancy=120 where name like '%聖公會基樂小學%';
update entity set admitted=48 ,vacancy=120 where name like '%路德會聖馬太學校（秀茂坪）%';
update entity set admitted=83 ,vacancy=125 where name like '%秀明小學%';
update entity set admitted=103 ,vacancy=125 where name like '%秀茂坪天主教小學%';
update entity set admitted=84 ,vacancy=125 where name like '%基督教聖約教會堅樂小學%';
update entity set admitted=87 ,vacancy=125 where name like '%聖安當小學%';
update entity set admitted=83 ,vacancy=125 where name like '%聖愛德華天主教小學%';
update entity set admitted=83 ,vacancy=125 where name like '%藍田循道衛理小學%';
update entity set admitted=83 ,vacancy=125 where name like '%觀塘官立小學（秀明道）%';
update entity set admitted=88 ,vacancy=125 where name like '%香港道教聯合會圓玄學院陳呂重德紀念學校%';
update entity set admitted=100 ,vacancy=150 where name like '%中華基督教會基法小學（油塘）%';
update entity set admitted=60 ,vacancy=150 where name like '%聖公會李兆強小學%';
update entity set admitted=70 ,vacancy=150 where name like '%聖公會德田李兆強小學%';
update entity set admitted=77 ,vacancy=180 where name like '%聖公會油塘基顯小學%';
update entity set admitted=11 ,vacancy=25 where name like '%中華基督教會全完第一小學%';
update entity set admitted=12 ,vacancy=25 where name like '%靈光小學%';
update entity set admitted=23 ,vacancy=60 where name like '%天佑小學%';
update entity set admitted=42 ,vacancy=90 where name like '%荃灣天主教小學%';
update entity set admitted=50 ,vacancy=100 where name like '%中華基督教會基慧小學%';
update entity set admitted=50 ,vacancy=100 where name like '%柴灣角天主教小學%';
update entity set admitted=50 ,vacancy=100 where name like '%荃灣公立何傳耀紀念小學%';
update entity set admitted=33 ,vacancy=100 where name like '%深井天主教小學%';
update entity set admitted=54 ,vacancy=120 where name like '%寶血會伍季明紀念學校%';
update entity set admitted=50 ,vacancy=120 where name like '%寶血會思源學校%';
update entity set admitted=47 ,vacancy=125 where name like '%海壩街官立小學%';
update entity set admitted=50 ,vacancy=150 where name like '%中華基督教會基慧小學（馬灣）%';
update entity set admitted=70 ,vacancy=150 where name like '%天主教石鐘山紀念小學%';
update entity set admitted=54 ,vacancy=150 where name like '%香港浸信會聯會小學%';
update entity set admitted=56 ,vacancy=150 where name like '%荃灣官立小學%';
update entity set admitted=37 ,vacancy=75 where name like '%石籬聖若望天主教小學%';
update entity set admitted=41 ,vacancy=90 where name like '%聖公會主愛小學（梨木樹）%';
update entity set admitted=50 ,vacancy=100 where name like '%石籬天主教小學%';
update entity set admitted=46 ,vacancy=100 where name like '%梨木樹天主教小學%';
update entity set admitted=80 ,vacancy=100 where name like '%嗇色園主辦可信學校%';
update entity set admitted=50 ,vacancy=100 where name like '%慈幼葉漢小學%';
update entity set admitted=71 ,vacancy=150 where name like '%慈幼葉漢千禧小學%';
update entity set admitted=70 ,vacancy=150 where name like '%聖公會主愛小學%';
update entity set admitted=42 ,vacancy=90 where name like '%中華基督教會全完第二小學%';
update entity set admitted=69 ,vacancy=100 where name like '%中華傳道會許大同學校%';
update entity set admitted=69 ,vacancy=100 where name like '%佛教林炳炎紀念學校%';
update entity set admitted=83 ,vacancy=100 where name like '%亞斯理衞理小學%';
update entity set admitted=68 ,vacancy=100 where name like '%東華三院高可寧紀念小學%';
update entity set admitted=55 ,vacancy=100 where name like '%祖堯天主教小學%';
update entity set admitted=44 ,vacancy=100 where name like '%聖公會主恩小學%';
update entity set admitted=72 ,vacancy=100 where name like '%柏立基教育學院校友會李一諤紀念學校%';
update entity set admitted=56 ,vacancy=100 where name like '%基督教香港信義會葵盛信義學校%';
update entity set admitted=62 ,vacancy=125 where name like '%中華基督教會基真小學%';
update entity set admitted=71 ,vacancy=150 where name like '%佛教林金殿紀念小學%';
update entity set admitted=58 ,vacancy=150 where name like '%聖公會仁立小學%';
update entity set admitted=70 ,vacancy=150 where name like '%聖公會仁立紀念小學%';
update entity set admitted=37 ,vacancy=75 where name like '%東華三院周演森小學%';
update entity set admitted=50 ,vacancy=100 where name like '%中華傳道會呂明才小學%';
update entity set admitted=63 ,vacancy=100 where name like '%仁濟醫院趙曾學韞小學%';
update entity set admitted=56 ,vacancy=100 where name like '%東華三院黃士心小學%';
update entity set admitted=73 ,vacancy=100 where name like '%青衣商會小學%';
update entity set admitted=68 ,vacancy=100 where name like '%荃灣商會學校%';
update entity set admitted=69 ,vacancy=100 where name like '%郭怡雅神父紀念學校%';
update entity set admitted=53 ,vacancy=120 where name like '%保良局世德小學%';
update entity set admitted=60 ,vacancy=120 where name like '%保良局陳溢小學%';
update entity set admitted=58 ,vacancy=125 where name like '%聖公會何澤芸小學%';
update entity set admitted=72 ,vacancy=150 where name like '%聖公會青衣主恩小學%';
update entity set admitted=75 ,vacancy=150 where name like '%聖公會青衣邨何澤芸小學%';
update entity set admitted=39 ,vacancy=100 where name like '%五邑鄒振猷學校%';
update entity set admitted=79 ,vacancy=100 where name like '%仁德天主教小學%';
update entity set admitted=42 ,vacancy=100 where name like '%屯門官立小學%';
update entity set admitted=79 ,vacancy=100 where name like '%世界龍岡學校劉德容紀念小學%';
update entity set admitted=62 ,vacancy=100 where name like '%柏立基教育學院校友會何壽基學校%';
update entity set admitted=60 ,vacancy=100 where name like '%香港紅卍字會屯門卍慈小學%';
update entity set admitted=39 ,vacancy=100 where name like '%香港路德會增城兆霖學校%';
update entity set admitted=42 ,vacancy=100 where name like '%道教青松小學（湖景邨）%';
update entity set admitted=42 ,vacancy=100 where name like '%僑港伍氏宗親會伍時暢紀念學校%';
update entity set admitted=39 ,vacancy=100 where name like '%樂善堂梁黃蕙芳紀念學校%';
update entity set admitted=48 ,vacancy=120 where name like '%保良局方王錦全小學%';
update entity set admitted=52 ,vacancy=125 where name like '%中華基督教會何福堂小學%';
update entity set admitted=52 ,vacancy=125 where name like '%中華基督教會蒙黃花沃紀念小學%';
update entity set admitted=48 ,vacancy=125 where name like '%仁濟醫院羅陳楚思小學%';
update entity set admitted=82 ,vacancy=125 where name like '%台山商會學校%';
update entity set admitted=49 ,vacancy=125 where name like '%保良局莊啟程第二小學%';
update entity set admitted=48 ,vacancy=125 where name like '%道教青松小學%';
update entity set admitted=60 ,vacancy=150 where name like '%保良局志豪小學%';
update entity set admitted=60 ,vacancy=150 where name like '%保良局梁周順琴小學%';
update entity set admitted=21 ,vacancy=50 where name like '%中華基督教會拔臣小學%';
update entity set admitted=92 ,vacancy=100 where name like '%仁濟醫院何式南小學%';
update entity set admitted=87 ,vacancy=100 where name like '%伊斯蘭學校%';
update entity set admitted=92 ,vacancy=100 where name like '%青山天主教小學%';
update entity set admitted=42 ,vacancy=100 where name like '%保良局西區婦女福利會馮李佩瑤小學%';
update entity set admitted=30 ,vacancy=100 where name like '%順德聯誼總會胡少渠紀念小學%';
update entity set admitted=64 ,vacancy=100 where name like '%興德學校%';
update entity set admitted=32 ,vacancy=100 where name like '%博愛醫院歷屆總理聯誼會鄭任安夫人學校%';
update entity set admitted=73 ,vacancy=125 where name like '%東華三院鄧肇堅小學%';
update entity set admitted=49 ,vacancy=125 where name like '%順德聯誼總會李金小學%';
update entity set admitted=49 ,vacancy=125 where name like '%路德會呂祥光小學%';
update entity set admitted=49 ,vacancy=125 where name like '%博愛醫院歷屆總理聯誼會鄭任安夫人千禧小學%';
update entity set admitted=54 ,vacancy=150 where name like '%順德聯誼總會何日東小學%';
update entity set admitted=42 ,vacancy=150 where name like '%聖公會蒙恩小學%';
update entity set admitted=18 ,vacancy=50 where name like '%寶覺分校%';
update entity set admitted=32 ,vacancy=100 where name like '%嗇色園主辦可銘學校%';
update entity set admitted=48 ,vacancy=125 where name like '%十八鄉鄉事委員會公益社小學%';
update entity set admitted=38 ,vacancy=125 where name like '%中華基督教青年會小學%';
update entity set admitted=36 ,vacancy=125 where name like '%元朗公立中學校友會英業小學%';
update entity set admitted=48 ,vacancy=125 where name like '%天水圍天主教小學%';
update entity set admitted=52 ,vacancy=125 where name like '%天水圍官立小學%';
update entity set admitted=48 ,vacancy=125 where name like '%天水圍循道衞理小學%';
update entity set admitted=50 ,vacancy=125 where name like '%伊利沙伯中學舊生會小學%';
update entity set admitted=52 ,vacancy=125 where name like '%伊利沙伯中學舊生會小學分校%';
update entity set admitted=37 ,vacancy=125 where name like '%東華三院李東海小學%';
update entity set admitted=41 ,vacancy=125 where name like '%東華三院姚達之紀念小學（元朗）%';
update entity set admitted=37 ,vacancy=125 where name like '%金巴崙長老會耀道小學%';
update entity set admitted=52 ,vacancy=125 where name like '%宣道會葉紹蔭紀念小學%';
update entity set admitted=52 ,vacancy=125 where name like '%香港青年協會李兆基小學%';
update entity set admitted=39 ,vacancy=125 where name like '%香港普通話研習社科技創意小學%';
update entity set admitted=48 ,vacancy=125 where name like '%香港潮陽小學%';
update entity set admitted=39 ,vacancy=125 where name like '%香港學生輔助會小學%';
update entity set admitted=48 ,vacancy=125 where name like '%順德聯誼總會伍冕端小學%';
update entity set admitted=39 ,vacancy=125 where name like '%獅子會何德心小學%';
update entity set admitted=62 ,vacancy=125 where name like '%聖公會天水圍靈愛小學%';
update entity set admitted=36 ,vacancy=125 where name like '%樂善堂梁銶琚學校%';
update entity set admitted=39 ,vacancy=125 where name like '%樂善堂梁銶琚學校（分校）%';
update entity set admitted=37 ,vacancy=125 where name like '%潮陽百欣小學%';
update entity set admitted=22 ,vacancy=60 where name like '%聖公會靈愛小學%';
update entity set admitted=46 ,vacancy=75 where name like '%元朗朗屏邨東莞學校%';
update entity set admitted=64 ,vacancy=100 where name like '%元朗公立中學校友會小學%';
update entity set admitted=68 ,vacancy=100 where name like '%元朗朗屏邨惠州學校%';
update entity set admitted=63 ,vacancy=100 where name like '%元朗商會小學%';
update entity set admitted=59 ,vacancy=100 where name like '%光明學校%';
update entity set admitted=67 ,vacancy=100 where name like '%佛教陳榮根紀念學校%';
update entity set admitted=66 ,vacancy=100 where name like '%博愛醫院歷屆總理聯誼會梁省德學校%';
update entity set admitted=72 ,vacancy=125 where name like '%南元朗官立小學%';
update entity set admitted=14 ,vacancy=25 where name like '%八鄉中心小學%';
update entity set admitted=19 ,vacancy=25 where name like '%錦田公立蒙養學校%';
update entity set admitted=29 ,vacancy=50 where name like '%惇裕學校%';
update entity set admitted=29 ,vacancy=50 where name like '%港澳信義會黃陳淑英紀念學校%';
update entity set admitted=23 ,vacancy=60 where name like '%聖公會錦田聖約瑟小學%';
update entity set admitted=21 ,vacancy=60 where name like '%中華基督教會元朗真光小學%';
update entity set admitted=53 ,vacancy=100 where name like '%佛教榮茵學校%';
update entity set admitted=68 ,vacancy=125 where name like '%元朗官立小學%';
update entity set admitted=49 ,vacancy=125 where name like '%光明英來學校%';
update entity set admitted=49 ,vacancy=150 where name like '%基督教宣道會徐澤林紀念小學%';
update entity set admitted=53 ,vacancy=150 where name like '%鐘聲學校%';
update entity set admitted=10 ,vacancy=25 where name like '%育賢學校%';
update entity set admitted=44 ,vacancy=50 where name like '%東莞學校%';
update entity set admitted=46 ,vacancy=50 where name like '%金錢村何東學校%';
update entity set admitted=37 ,vacancy=100 where name like '%東華三院馬錦燦紀念小學%';
update entity set admitted=40 ,vacancy=100 where name like '%東華三院港九電器商聯會小學%';
update entity set admitted=40 ,vacancy=100 where name like '%香海正覺蓮社佛教陳式宏學校%';
update entity set admitted=48 ,vacancy=120 where name like '%鳳溪第一小學%';
update entity set admitted=48 ,vacancy=120 where name like '%鳳溪創新小學%';
update entity set admitted=48 ,vacancy=120 where name like '%聖公會榮真小學%';
update entity set admitted=49 ,vacancy=125 where name like '%石湖墟公立學校%';
update entity set admitted=55 ,vacancy=150 where name like '%上水惠州公立學校%';
update entity set admitted=60 ,vacancy=150 where name like '%李志達紀念學校%';
update entity set admitted=60 ,vacancy=150 where name like '%香海正覺蓮社佛教正慧小學%';
update entity set admitted=60 ,vacancy=150 where name like '%曾梅千禧學校%';
update entity set admitted=40 ,vacancy=50 where name like '%方樹福堂基金方樹泉小學%';
update entity set admitted=31 ,vacancy=75 where name like '%粉嶺官立小學%';
update entity set admitted=27 ,vacancy=75 where name like '%鳳溪廖潤琛紀念學校%';
update entity set admitted=29 ,vacancy=75 where name like '%寶血會培靈學校%';
update entity set admitted=28 ,vacancy=90 where name like '%上水宣道小學%';
update entity set admitted=37 ,vacancy=90 where name like '%粉嶺公立學校%';
update entity set admitted=46 ,vacancy=100 where name like '%五旬節于良發小學%';
update entity set admitted=33 ,vacancy=100 where name like '%五旬節靳茂生小學%';
update entity set admitted=34 ,vacancy=100 where name like '%基督教粉嶺神召會小學%';
update entity set admitted=43 ,vacancy=120 where name like '%聖公會嘉福榮真小學%';
update entity set admitted=52 ,vacancy=125 where name like '%香海正覺蓮社佛教正覺蓮社學校%';
update entity set admitted=8 ,vacancy=50 where name like '%山咀公立學校%';
update entity set admitted=8 ,vacancy=50 where name like '%沙頭角中心學校%';
update entity set admitted=28 ,vacancy=75 where name like '%香港教育學院賽馬會小學%';
update entity set admitted=59 ,vacancy=100 where name like '%三水同鄉會禤景榮學校%';
update entity set admitted=59 ,vacancy=100 where name like '%大埔崇德黃建常紀念學校%';
update entity set admitted=64 ,vacancy=100 where name like '%仁濟醫院蔡衍濤小學%';
update entity set admitted=61 ,vacancy=100 where name like '%天主教聖母聖心小學%';
update entity set admitted=69 ,vacancy=100 where name like '%林村公立黃福鑾紀念學校%';
update entity set admitted=59 ,vacancy=100 where name like '%保良局田家炳小學%';
update entity set admitted=83 ,vacancy=100 where name like '%香港道教聯合會雲泉吳禮和紀念學校%';
update entity set admitted=59 ,vacancy=100 where name like '%港九街坊婦女會孫方中小學%';
update entity set admitted=59 ,vacancy=100 where name like '%新界婦孺福利會梁省德學校%';
update entity set admitted=55 ,vacancy=100 where name like '%聖公會阮鄭夢芹銀禧小學%';
update entity set admitted=44 ,vacancy=120 where name like '%大埔舊墟公立學校%';
update entity set admitted=73 ,vacancy=125 where name like '%大埔官立小學%';
update entity set admitted=85 ,vacancy=125 where name like '%大埔浸信會公立學校%';
update entity set admitted=77 ,vacancy=125 where name like '%大埔循道衞理小學%';
update entity set admitted=77 ,vacancy=125 where name like '%保良局田家炳千禧小學%';
update entity set admitted=70 ,vacancy=125 where name like '%聖公會阮鄭夢芹小學%';
update entity set admitted=52 ,vacancy=150 where name like '%大埔舊墟公立學校（寶湖道）%';
update entity set admitted=50 ,vacancy=100 where name like '%東華三院冼次雲小學%';
update entity set admitted=47 ,vacancy=100 where name like '%迦密愛禮信小學%';
update entity set admitted=88 ,vacancy=100 where name like '%香港中文大學校友會聯會張煊昌學校%';
update entity set admitted=46 ,vacancy=100 where name like '%循理會白普理基金循理小學%';
update entity set admitted=82 ,vacancy=100 where name like '%循理會美林小學%';
update entity set admitted=43 ,vacancy=120 where name like '%聖母無玷聖心學校%';
update entity set admitted=51 ,vacancy=120 where name like '%香港九龍塘基督教中華宣道會陳元喜小學%';
update entity set admitted=60 ,vacancy=125 where name like '%沙田官立小學%';
update entity set admitted=62 ,vacancy=125 where name like '%保良局王賜豪（田心谷）小學%';
update entity set admitted=50 ,vacancy=100 where name like '%九龍城浸信會禧年小學%';
update entity set admitted=79 ,vacancy=100 where name like '%吳氏宗親總會泰伯紀念學校%';
update entity set admitted=48 ,vacancy=100 where name like '%保良局莊啓程小學%';
update entity set admitted=48 ,vacancy=100 where name like '%基督教香港信義會馬鞍山信義學校%';
update entity set admitted=58 ,vacancy=125 where name like '%保良局雨川小學%';
update entity set admitted=86 ,vacancy=125 where name like '%香港道教聯合會純陽小學%';
update entity set admitted=112 ,vacancy=125 where name like '%馬鞍山聖若瑟小學%';
update entity set admitted=51 ,vacancy=125 where name like '%聖公會馬鞍山主風小學%';
update entity set admitted=118 ,vacancy=125 where name like '%香港九龍塘基督教中華宣道會台山陳元喜小學%';
update entity set admitted=71 ,vacancy=150 where name like '%馬鞍山循道衛理小學%';
update entity set admitted=70 ,vacancy=150 where name like '%馬鞍山靈糧小學%';
update entity set admitted=75 ,vacancy=100 where name like '%沙田崇真學校%';
update entity set admitted=40 ,vacancy=100 where name like '%沙田圍胡素貞博士紀念學校%';
update entity set admitted=50 ,vacancy=100 where name like '%沙田循道衞理小學%';
update entity set admitted=48 ,vacancy=100 where name like '%保良局蕭漢森小學%';
update entity set admitted=98 ,vacancy=100 where name like '%基督教香港信義會禾輋信義學校%';
update entity set admitted=48 ,vacancy=100 where name like '%救世軍田家炳學校%';
update entity set admitted=56 ,vacancy=120 where name like '%保良局朱正賢小學%';
update entity set admitted=49 ,vacancy=120 where name like '%胡素貞博士紀念學校%';
update entity set admitted=32 ,vacancy=120 where name like '%浸信會呂明才小學%';
update entity set admitted=42 ,vacancy=120 where name like '%培基小學%';
update entity set admitted=54 ,vacancy=120 where name like '%聖公會主風小學%';
update entity set admitted=49 ,vacancy=125 where name like '%路德會梁鉅鏐小學%';
update entity set admitted=50 ,vacancy=150 where name like '%浸信會沙田圍呂明才小學%';
update entity set admitted=42 ,vacancy=75 where name like '%西貢崇真天主教學校（小學部）%';
update entity set admitted=81 ,vacancy=100 where name like '%景林天主教小學%';
update entity set admitted=80 ,vacancy=100 where name like '%樂善堂劉德學校%';
update entity set admitted=78 ,vacancy=125 where name like '%仁愛堂田家炳小學%';
update entity set admitted=100 ,vacancy=125 where name like '%仁濟醫院陳耀星小學%';
update entity set admitted=58 ,vacancy=125 where name like '%天主教聖安德肋小學%';
update entity set admitted=67 ,vacancy=125 where name like '%西貢中心李少欽紀念學校%';
update entity set admitted=105 ,vacancy=125 where name like '%佛教志蓮小學%';
update entity set admitted=58 ,vacancy=125 where name like '%東華三院王余家潔紀念小學%';
update entity set admitted=62 ,vacancy=125 where name like '%保良局馮晴紀念小學%';
update entity set admitted=59 ,vacancy=125 where name like '%保良局黃永樹小學%';
update entity set admitted=83 ,vacancy=125 where name like '%香海正覺蓮社佛教黃藻森學校%';
update entity set admitted=58 ,vacancy=125 where name like '%基督教宣道會宣基小學%';
update entity set admitted=104 ,vacancy=125 where name like '%基督教神召會梁省德小學%';
update entity set admitted=58 ,vacancy=125 where name like '%將軍澳天主教小學%';
update entity set admitted=81 ,vacancy=125 where name like '%將軍澳官立小學%';
update entity set admitted=62 ,vacancy=125 where name like '%將軍澳循道衛理小學%';
update entity set admitted=102 ,vacancy=125 where name like '%博愛醫院陳國威小學%';
update entity set admitted=62 ,vacancy=125 where name like '%港澳信義會小學%';
update entity set admitted=62 ,vacancy=125 where name like '%港澳信義會明道小學%';
update entity set admitted=62 ,vacancy=125 where name like '%順德聯誼總會梁潔華小學%';
update entity set admitted=98 ,vacancy=125 where name like '%聖公會將軍澳基德小學%';
update entity set admitted=12 ,vacancy=25 where name like '%南丫北段公立小學%';
update entity set admitted=14 ,vacancy=30 where name like '%中華基督教會長洲堂錦江小學%';
update entity set admitted=22 ,vacancy=50 where name like '%長洲聖心學校%';
update entity set admitted=47 ,vacancy=75 where name like '%國民學校%';
update entity set admitted=22 ,vacancy=25 where name like '%中華基督教會大澳小學%';
update entity set admitted=5 ,vacancy=25 where name like '%杯澳公立學校%';
update entity set admitted=11 ,vacancy=25 where name like '%梅窩學校%';
update entity set admitted=62 ,vacancy=125 where name like '%東涌天主教學校%';
update entity set admitted=62 ,vacancy=125 where name like '%青松侯寶垣小學%';
update entity set admitted=93 ,vacancy=125 where name like '%香港教育工作者聯會黃楚標學校%';
update entity set admitted=59 ,vacancy=125 where name like '%救世軍林拔中紀念學校%';
update entity set admitted=99 ,vacancy=125 where name like '%嗇色園主辦可譽中學暨可譽小學%';
update entity set admitted=107 ,vacancy=125 where name like '%寶安商會溫浩根小學%';
update entity set admitted=62 ,vacancy=125 where name like '%靈糧堂秀德小學%';
update entity set admitted=11 ,vacancy=25 where name like '%聖家學校%';
update entity set admitted=31 ,vacancy=75 where name like '%聖公會偉倫小學%';

update entityscore set admitted=41 ,vacancy=100 where entityid = (select id from entity where name = '九龍塘天主教華德學校') and year=2013;
update entityscore set admitted=8 ,vacancy=50 where entityid = (select id from entity where name = '沙頭角中心小學') and year=2013;
update entityscore set admitted=48 ,vacancy=100 where entityid = (select id from entity where name = '保良局莊啟程小學') and year=2013;
update entityscore set admitted=77 ,vacancy=125 where entityid = (select id from entity where name = '大埔循道衞理小學') and year=2013;
update entityscore set admitted=48 ,vacancy=125 where entityid = (select id from entity where name = '天水圍循道衞理小學') and year=2013;
update entityscore set admitted=22 ,vacancy=60 where entityid = (select id from entity where name = '北角衞理小學（上午）') and year=2013;
update entityscore set admitted=23 ,vacancy=60 where entityid = (select id from entity where name = '北角衞理小學（下午）') and year=2013;
update entityscore set admitted=50 ,vacancy=100 where entityid = (select id from entity where name = '沙田循道衞理小學') and year=2013;
update entityscore set admitted=68 ,vacancy=150 where entityid = (select id from entity where name = '中華基督教會協和小學（長沙灣）') and year=2013;
update entityscore set admitted=41 ,vacancy=125 where entityid = (select id from entity where name = '東華三院姚達之紀念小學（元朗）') and year=2013;
update entityscore set admitted=42 ,vacancy=100 where entityid = (select id from entity where name = '道教青松小學（湖景邨）') and year=2013;
update entityscore set admitted=98 ,vacancy=100 where entityid = (select id from entity where name = '基督教香港信義會禾輋信義學校') and year=2013;
update entityscore set admitted=59 ,vacancy=100 where entityid = (select id from entity where name = '港九街坊婦女會孫方中小學') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name = '香港仔聖伯多祿天主教小學') and year=2013;
update entityscore set admitted=62 ,vacancy=125 where entityid = (select id from entity where name = '東涌天主教學校' and categoryid=1) and year=2013;
update entityscore set admitted=99 ,vacancy=125 where entityid = (select id from entity where name = '嗇色園主辦可譽中學暨可譽小學' and categoryid=1) and year=2013;
update entityscore set admitted=49 ,vacancy=120 where entityid = (select id from entity where name = '番禺會所華仁小學') and year=2013;
update entityscore set admitted=74 ,vacancy=180 where entityid = (select id from entity where name = '聖公會聖彼得小學（上午）') and year=2013;
update entityscore set admitted=74 ,vacancy=180 where entityid = (select id from entity where name = '聖公會聖彼得小學（下午）') and year=2013;

update entity set admitted=41 ,vacancy=100 where name = '九龍塘天主教華德學校';
update entity set admitted=8 ,vacancy=50 where name = '沙頭角中心小學';
update entity set admitted=48 ,vacancy=100 where name = '保良局莊啟程小學';
update entity set admitted=77 ,vacancy=125 where name = '大埔循道衞理小學';
update entity set admitted=48 ,vacancy=125 where name = '天水圍循道衞理小學';
update entity set admitted=22 ,vacancy=60 where name = '北角衞理小學（上午）';
update entity set admitted=23 ,vacancy=60 where name = '北角衞理小學（下午）';
update entity set admitted=50 ,vacancy=100 where name = '沙田循道衞理小學';
update entity set admitted=68 ,vacancy=150 where name = '中華基督教會協和小學（長沙灣）';
update entity set admitted=41 ,vacancy=125 where name = '東華三院姚達之紀念小學（元朗）';
update entity set admitted=42 ,vacancy=100 where name = '道教青松小學（湖景邨）';
update entity set admitted=98 ,vacancy=100 where name = '基督教香港信義會禾輋信義學校';
update entity set admitted=59 ,vacancy=100 where name = '港九街坊婦女會孫方中小學';
update entity set admitted=62 ,vacancy=125 where name = '香港仔聖伯多祿天主教小學';
update entity set admitted=62 ,vacancy=125 where name = '東涌天主教學校';
update entity set admitted=99 ,vacancy=125 where name = '嗇色園主辦可譽中學暨可譽小學';
update entity set admitted=49 ,vacancy=120 where name = '番禺會所華仁小學';
update entity set admitted=74 ,vacancy=180 where name = '聖公會聖彼得小學（上午）';
update entity set admitted=74 ,vacancy=180 where name = '聖公會聖彼得小學（下午）';