update entity set debatechi=0 where categoryid=2;
update  entity set debatechi=1 where name = '拔萃女書院' and categoryid=2;
update  entity set debatechi=2 where name = '拔萃男書院' and categoryid=2;
update  entity set debatechi=3 where name = '協恩中學' and categoryid=2;
update  entity set debatechi=4 where name = '九龍塘學校（中學部）' and categoryid=2;
update entityscore es, entity e set es.debatechi=e.debatechi where es.entityid=e.id and es.year=2014 and e.categoryid=2;
update entity set debatechi=0 where categoryid=2;
update  entity set debatechi=1 where name = '喇沙書院' and categoryid=2;
update  entity set debatechi=2 where name = '華英中學' and categoryid=2;
update  entity set debatechi=3 where name = '拔萃女書院' and categoryid=2;
update  entity set debatechi=4 where name = '香港華仁書院' and categoryid=2;
update entityscore es, entity e set es.debatechi=e.debatechi where es.entityid=e.id and es.year=2015 and e.categoryid=2;
update entity set debatechi=0 where categoryid=2;
update  entity set debatechi=1 where name = '德蘭中學' and categoryid=2;
update  entity set debatechi=2 where name = '華英中學' and categoryid=2;
update  entity set debatechi=3 where name = '藍田聖保祿中學' and categoryid=2;
update  entity set debatechi=4 where name = '拔萃男書院' and categoryid=2;
update entityscore es, entity e set es.debatechi=e.debatechi where es.entityid=e.id and es.year=2016 and e.categoryid=2;
update entity set debatechi=0 where categoryid=2;
update  entity set debatechi=1 where name = '聖馬可中學' and categoryid=2;
update  entity set debatechi=2 where name = '基督教聖約教會堅樂中學' and categoryid=2;
update  entity set debatechi=3 where name = '九龍塘學校（中學部）' and categoryid=2;
update  entity set debatechi=4 where name = '德蘭中學' and categoryid=2;
update entityscore es, entity e set es.debatechi=e.debatechi where es.entityid=e.id and es.year=2017 and e.categoryid=2;
update entity set debatechi=0 where categoryid=2;
update  entity set debatechi=1 where name = '聖公會呂明才中學' and categoryid=2;
update  entity set debatechi=2 where name = '華英中學' and categoryid=2;
update  entity set debatechi=3 where name = '協恩中學' and categoryid=2;
update  entity set debatechi=4 where name = '寶血會上智英文書院' and categoryid=2;
update entityscore es, entity e set es.debatechi=e.debatechi where es.entityid=e.id and es.year=2018 and e.categoryid=2;
