update entity set  hkdsepassrate=0, chipassrate=0,engpassrate=0, urate=0 where categoryid in (2,5);
update entityscore set  hkdsepassrate=0, chipassrate=0,engpassrate=0, urate=0 where categoryid in (2,5) and year=2015;

update entity set hkdsepassrate=96.1, chipassrate=96.1, engpassrate=100, urate=90 where name='聖保羅男女中學' and categoryid=2;
update entity set hkdsepassrate=89.5 where name='拔萃女書院' and categoryid=2;
update entity set hkdsepassrate=87.9, chipassrate=87.9, engpassrate=100, urate=81.4 where name='皇仁書院' and categoryid=2;
update entity set hkdsepassrate=99.3, chipassrate=100, engpassrate=99.3, urate=95.8 where name='香港道教聯合會鄧顯紀念中學' and categoryid=2;
update entity set hkdsepassrate=92.4, chipassrate=92.4, engpassrate=100, urate=79.2 where name='嘉諾撒聖瑪利書院' and categoryid=2;
update entity set hkdsepassrate=94, chipassrate=94, engpassrate=100, urate=88 where name='聖保祿學校' and categoryid=2;
update entity set hkdsepassrate=85 where name='喇沙書院' and categoryid=2;
update entity set hkdsepassrate=88, chipassrate=88, engpassrate=100, urate=71.7 where name='英華女學校' and categoryid=2;
update entity set hkdsepassrate=85.2, chipassrate=85.2, engpassrate=100, urate=0 where name='協恩中學' and categoryid=2;
update entity set hkdsepassrate=96.4, chipassrate=96.4, engpassrate=100, urate=63.3 where name='庇理羅士女子中學' and categoryid=2;
update entity set hkdsepassrate=94.8, chipassrate=94.8, engpassrate=99.4, urate=81.8 where name='聖公會林護紀念中學' and categoryid=2;
update entity set hkdsepassrate=93, chipassrate=93, engpassrate=99.4, urate=66.9 where name='張祝珊英文中學' and categoryid=2;
update entity set hkdsepassrate=92.4, chipassrate=93.6, engpassrate=98.3, urate=72.1 where name='聖公會曾肇添中學' and categoryid=2;
update entity set hkdsepassrate=85.3, urate=60.2 where name='瑪利諾修院學校（中學部）' and categoryid=2;
update entity set hkdsepassrate=91.6, chipassrate=91.6, engpassrate=99.4, urate=0 where name='保良局百周年李兆忠紀念中學' and categoryid=2;
update entity set hkdsepassrate=87.9, chipassrate=89, engpassrate=100, urate=70.5 where name='保良局第一張永慶中學' and categoryid=2;

update entity set hkdsepassrate=95.2, chipassrate=95.2, engpassrate=100, urate=63.6 where name='迦密中學' and categoryid=2;
update entity set hkdsepassrate=83.2, chipassrate=83.2, engpassrate=100, urate=0 where name='聖若瑟書院' and categoryid=2;
update entity set hkdsepassrate=77.8, urate=59.4 where name='聖士提反女子中學' and categoryid=2;
update entity set hkdsepassrate=85.4, chipassrate=85.4, engpassrate=100, urate=77.2 where name='聖馬可中學' and categoryid=2;
update entity set hkdsepassrate=77, urate=64 where name='瑪利曼中學' and categoryid=2;
update entity set hkdsepassrate=87, chipassrate=87, engpassrate=100, urate=70 where name='香港真光中學' and categoryid=2;
update entity set hkdsepassrate=84.1, urate=61 where name='德望學校' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=0, engpassrate=0, urate=61 where name='浸信會呂明才中學' and categoryid=2;
update entity set hkdsepassrate=81.7, chipassrate=84, engpassrate=97, urate=71 where name='聖言中學' and categoryid=2;
update entity set hkdsepassrate=94, urate=57.69 where name='荃灣官立中學' and categoryid=2;
update entity set hkdsepassrate=82 where name='英皇書院' and categoryid=2;

update entity set hkdsepassrate=88.9 where name='新界鄉議局元朗區中學' and categoryid=2;
update entity set urate=44.74 where name='香港華仁書院' and categoryid=2;
update entity set hkdsepassrate=82, chipassrate=83, engpassrate=99, urate=0 where name='伊利沙伯中學' and categoryid=2;
update entity set hkdsepassrate=83.4, urate=51.2 where name='聖保祿中學' and categoryid=2;
update entity set hkdsepassrate=86.4, chipassrate=86.9, engpassrate=99.4, urate=68 where name='順德聯誼總會梁銶琚中學' and categoryid=2;
update entity set hkdsepassrate=91.1, chipassrate=91.7, engpassrate=97.8, urate=60.3 where name='中華傳道會安柱中學' and categoryid=2;
update entity set hkdsepassrate=84.6 where name='香港九龍塘基督教中華宣道會陳瑞芝紀念中學' and categoryid=2;
update entity set hkdsepassrate=91, chipassrate=91, engpassrate=100, urate=69 where name='聖羅撒書院' and categoryid=2;
update entity set hkdsepassrate=83, chipassrate=84, engpassrate=99.4, urate=78 where name='保良局董玉娣中學' and categoryid=2;
update entity set hkdsepassrate=83.8, chipassrate=83.8, engpassrate=99.4, urate=55.9 where name='香港中國婦女會中學' and categoryid=2;
update entity set hkdsepassrate=80.8, chipassrate=80.8, engpassrate=99.4, urate=55.3 where name='民生書院' and categoryid=2;
update entity set hkdsepassrate=83.5, chipassrate=84.7, engpassrate=99.4, urate=67 where name='華英中學' and categoryid=2;
update entity set hkdsepassrate=85.9, chipassrate=88.6, engpassrate=95.7, urate=66.3 where name='沙田培英中學' and categoryid=2;
update entity set hkdsepassrate=90.3, chipassrate=91.9, engpassrate=97.8, urate=0 where name='迦密主恩中學' and categoryid=2;
update entity set hkdsepassrate=81.2, urate=54.1 where name='真光女書院' and categoryid=2;
update entity set urate=70.9 where name='沙田崇真中學' and categoryid=2;
update entity set hkdsepassrate=87.9, chipassrate=87.9, engpassrate=99.3, urate=60.4 where name='嘉諾撒書院' and categoryid=2;
update entity set hkdsepassrate=84.9, chipassrate=86, engpassrate=97.1, urate=0 where name='荃灣公立何傳耀紀念中學' and categoryid=2;
update entity set hkdsepassrate=80.3, urate=42.77 where name='沙田官立中學' and categoryid=2;
update entity set hkdsepassrate=87 where name='優才（楊殷有娣）書院' and categoryid=2;
update entity set hkdsepassrate=90.3, chipassrate=90.3, engpassrate=100, urate=62.8 where name='藍田聖保祿中學' and categoryid=2;
update entity set hkdsepassrate=86.4, chipassrate=86.9, engpassrate=100, urate=65.3 where name='旅港開平商會中學' and categoryid=2;
update entity set hkdsepassrate=82.9, chipassrate=84.6, engpassrate=97.7, urate=70 where name='佛教善德英文中學' and categoryid=2;
update entity set hkdsepassrate=72.3, urate=63 where name='英華書院' and categoryid=2;
update entity set hkdsepassrate=82.1, urate=52 where name='可風中學（嗇色園主辦）' and categoryid=2;
update entity set hkdsepassrate=80, chipassrate=82, engpassrate=98, urate=0 where name='何明華會督銀禧中學' and categoryid=2;
update entity set hkdsepassrate=78.7, urate=48.31 where name='趙聿修紀念中學' and categoryid=2;
update entity set hkdsepassrate=84.2, chipassrate=85.2, engpassrate=97.4, urate=57.9 where name='天主教崇德英文書院' and categoryid=2;
update entity set hkdsepassrate=73.8, urate=54.2 where name='華仁書院（九龍）' and categoryid=2;
update entity set hkdsepassrate=72.7, chipassrate=72.7, engpassrate=99.2, urate=59.5 where name='保良局顏寶鈴書院' and categoryid=2;
update entity set hkdsepassrate=79.5, urate=62.3 where name='順德聯誼總會譚伯羽中學' and categoryid=2;
update entity set hkdsepassrate=81.1, chipassrate=81.1, engpassrate=98.2, urate=73.8 where name='沙田蘇浙公學' and categoryid=2;
update entity set hkdsepassrate=87, chipassrate=88.3, engpassrate=98.1, urate=0 where name='保祿六世書院' and categoryid=2;
update entity set hkdsepassrate=64.3, urate=47.2 where name='港大同學會書院' and categoryid=2;
update entity set hkdsepassrate=85.1, chipassrate=85.1, engpassrate=99.4, urate=0 where name='聖公會林裘謀中學' and categoryid=2;
update entity set hkdsepassrate=85 where name='基督教香港信義會元朗信義中學' and categoryid=2;
update entity set hkdsepassrate=84.7, urate=52.6 where name='中華基督教會銘賢書院' and categoryid=2;
update entity set hkdsepassrate=79.7, urate=61 where name='中華基督教會協和書院' and categoryid=2;
update entity set hkdsepassrate=91, chipassrate=92.8, engpassrate=98.8, urate=76 where name='天主教母佑會蕭明中學' and categoryid=2;
update entity set hkdsepassrate=75, chipassrate=76.1, engpassrate=94.5, urate=57.7 where name='聖公會鄧肇堅中學' and categoryid=2;
update entity set hkdsepassrate=83.3, chipassrate=83.9, engpassrate=98.3, urate=59.4 where name='迦密柏雨中學' and categoryid=2;
update entity set hkdsepassrate=82, chipassrate=84.5, engpassrate=95, urate=0 where name='沙田循道衛理中學' and categoryid=2;
update entity set hkdsepassrate=82 where name='保良局羅傑承（一九八三）中學' and categoryid=2;
update entity set hkdsepassrate=82.7, urate=70 where name='聖母玫瑰書院' and categoryid=2;
update entity set hkdsepassrate=80.4, chipassrate=87.5, engpassrate=92.9, urate=45.8 where name='王肇枝中學' and categoryid=2;
update entity set hkdsepassrate=81.6, urate=49.7 where name='順利天主教中學' and categoryid=2;
update entity set hkdsepassrate=81.3, chipassrate=85.2, engpassrate=93.4, urate=70 where name='東華三院甲寅年總理中學' and categoryid=2;
update entity set hkdsepassrate=79, urate=55 where name='嘉諾撒聖家書院' and categoryid=2;
update entity set hkdsepassrate=77.6, urate=57.5 where name='嘉諾撒聖心書院' and categoryid=2;
update entity set hkdsepassrate=77, chipassrate=88, engpassrate=82, urate=0 where name='基督教宣道會宣基中學' and categoryid=2;
update entity set hkdsepassrate=69.9, chipassrate=82.4, engpassrate=81.3, urate=48.3 where name='田家炳中學' and categoryid=2;
update entity set hkdsepassrate=74.4, chipassrate=74.4, engpassrate=98.4, urate=0 where name='基督教女青年會丘佐榮中學' and categoryid=2;
update entity set hkdsepassrate=73.7, urate=47.7 where name='滙基書院（東九龍）' and categoryid=2;
update entity set urate=44 where name='培僑書院' and categoryid=2;
update entity set hkdsepassrate=67, chipassrate=69, engpassrate=97, urate=0 where name='筲箕灣官立中學' and categoryid=2;
update entity set hkdsepassrate=79.3, urate=46.2 where name='觀塘瑪利諾書院' and categoryid=2;
update entity set hkdsepassrate=79, urate=41.13 where name='循道中學' and categoryid=2;


update entity set hkdsepassrate=75.5 where name='觀塘官立中學' and categoryid=2;
update entity set hkdsepassrate=75.4, urate=62 where name='德愛中學' and categoryid=2;
update entity set urate=50 where name='高主教書院' and categoryid=2;
update entity set hkdsepassrate=73.8 where name='寶安商會王少清中學' and categoryid=2;

update entity set hkdsepassrate=71.6, chipassrate=85.1, engpassrate=81.3, urate=70 where name='九龍真光中學' and categoryid=2;
update entity set hkdsepassrate=75, chipassrate=77, engpassrate=96, urate=44 where name='聖芳濟書院' and categoryid=2;
update entity set hkdsepassrate=72, chipassrate=77, engpassrate=89, urate=50 where name='仁愛堂田家炳中學' and categoryid=2;
update entity set hkdsepassrate=70.5, urate=52 where name='福建中學' and categoryid=2;
update entity set hkdsepassrate=70.2, urate=36.9 where name='梁式芝書院' and categoryid=2;
update entity set hkdsepassrate=69.9, urate=39 where name='東華三院黃笏南中學' and categoryid=2;

update entity set hkdsepassrate=65.3, chipassrate=67.3, engpassrate=98, urate=42.2 where name='香港青年協會李兆基書院' and categoryid=2;

update entity set hkdsepassrate=63, chipassrate=63, engpassrate=97, urate=36.2 where name='中華基金中學' and categoryid=2;
update entity set hkdsepassrate=68.6, chipassrate=70.5, engpassrate=91.9, urate=43.9 where name='港島民生書院' and categoryid=2;
update entity set hkdsepassrate=68.5 where name='保良局羅氏基金中學' and categoryid=2;
update entity set hkdsepassrate=79.5, chipassrate=87.7, engpassrate=87.7, urate=45 where name='景嶺書院' and categoryid=2;
update entity set hkdsepassrate=71, chipassrate=78, engpassrate=90, urate=0 where name='天主教郭得勝中學' and categoryid=2;
update entity set hkdsepassrate=57.4, urate=63.9 where name='風采中學（教育評議會主辦）' and categoryid=2;
update entity set urate=83.6 where name='聖瑪加利男女英文中小學' and categoryid=2;

update entity set hkdsepassrate=61.3 where name='香港神託會培基書院' and categoryid=2;
update entity set hkdsepassrate=55.6, chipassrate=75, engpassrate=65.3, urate=43.8 where name='香島中學' and categoryid=2;
update entity set hkdsepassrate=46.3, chipassrate=57.6, engpassrate=58.8, urate=0 where name='仁濟醫院王華湘中學' and categoryid=2;
update entity set hkdsepassrate=64.6 where name='恩主教書院' and categoryid=2;
update entity set urate=58 where name='啟思中學' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=0, engpassrate=0, urate=43 where name='香港管理專業協會李國寶中學' and categoryid=2;
update entity set hkdsepassrate=64.7, chipassrate=73.4, engpassrate=76.6, urate=46.7 where name='中華基督教會蒙民偉書院' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=77.7, engpassrate=77.1, urate=33.8 where name='香港培道中學' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=66.2, engpassrate=85.2, urate=42 where name='南屯門官立中學' and categoryid=2;
update entity set urate=65.5 where name='寶血會上智英文書院' and categoryid=2;
update entity set hkdsepassrate=70, chipassrate=0, engpassrate=0, urate=65 where name='東華三院李嘉誠中學' and categoryid=2;
update entity set urate=50 where name='聖保羅書院' and categoryid=2;
update entity set hkdsepassrate=65, chipassrate=66.9, engpassrate=93.2, urate=42.1 where name='南亞路德會沐恩中學' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=0, engpassrate=0, urate=40.9 where name='屯門官立中學' and categoryid=2;
update entity set hkdsepassrate=61.6, chipassrate=68.8, engpassrate=82.6, urate=33 where name='東華三院陳兆民中學' and categoryid=2;
update entity set hkdsepassrate=58.1, urate=28 where name='中華基督教會基元中學' and categoryid=2;
update entity set hkdsepassrate=56.9, chipassrate=69.7, engpassrate=71.3, urate=46.3 where name='東華三院盧幹庭紀念中學' and categoryid=2;
update entity set hkdsepassrate=56.9 where name='保良局馬錦明夫人章馥仙中學' and categoryid=2;
update entity set hkdsepassrate=55, urate=44 where name='播道書院' and categoryid=2;
update entity set hkdsepassrate=54.64, urate=48.6 where name='香港華人基督教聯會真道書院' and categoryid=2;
update entity set hkdsepassrate=53.5 where name='香港管理專業協會羅桂祥中學' and categoryid=2;
update entity set hkdsepassrate=50, urate=72 where name='金文泰中學' and categoryid=2;
update entity set hkdsepassrate=96.9 where name='聖士提反書院' and categoryid=2;

update entity set hkdsepassrate=94.7 where name='聖公會白約翰會督中學' and categoryid=2;
update entity set hkdsepassrate=71.6, chipassrate=75.7, engpassrate=90.5, urate=46.2 where name='聖公會陳融中學' and categoryid=2;
update entity set hkdsepassrate=63.5, urate=40.5 where name='香港九龍塘基督教中華宣道會鄭榮之中學' and categoryid=2;

update entity set hkdsepassrate=0, chipassrate=0, engpassrate=0, urate=18 where name='東華三院辛亥年總理中學' and categoryid=2;

update entity set urate=21.5 where name='何文田官立中學' and categoryid=2;
update entity set hkdsepassrate=64.3, chipassrate=69.9, engpassrate=89.9, urate=45.7 where name='德雅中學' and categoryid=2;
update entity set urate=40.6 where name='荃灣聖芳濟中學' and categoryid=2;
update entity set hkdsepassrate=78.4, urate=27 where name='新生命教育協會呂郭碧鳳中學' and categoryid=2;
update entity set hkdsepassrate=53.9, urate=15.5 where name='博愛醫院歷屆總理聯誼會梁省德中學' and categoryid=2;
update entity set hkdsepassrate=54, chipassrate=60, engpassrate=75, urate=36 where name='聖公會呂明才中學' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=0, engpassrate=0, urate=20 where name='順德聯誼總會胡兆熾中學' and categoryid=2;
update entity set hkdsepassrate=51, chipassrate=64.8, engpassrate=67.9, urate=24 where name='中華基督教會全完中學' and categoryid=2;
update entity set hkdsepassrate=51.9, urate=25.3 where name='聖母書院' and categoryid=2;
update entity set hkdsepassrate=50, chipassrate=62, engpassrate=52, urate=40 where name='中華基督教青年會中學' and categoryid=2;
update entity set hkdsepassrate=51, urate=3.8 where name='粉嶺官立中學' and categoryid=2;
update entity set hkdsepassrate=48.8, urate=27 where name='妙法寺劉金龍中學' and categoryid=2;
update entity set hkdsepassrate=47.4, chipassrate=92.4, engpassrate=97.1, urate=0 where name='保良局李城璧中學' and categoryid=2;
update entity set hkdsepassrate=47.7 where name='中華基督教會譚李麗芬紀念中學' and categoryid=2;
update entity set hkdsepassrate=46.55, urate=24.7 where name='聖類斯中學' and categoryid=2;
update entity set hkdsepassrate=43 where name='基督教中國佈道會聖道迦南書院' and categoryid=2;
update entity set hkdsepassrate=42.1, urate=28.3 where name='陳瑞祺（喇沙）書院' and categoryid=2;
update entity set hkdsepassrate=41 where name='香港鄧鏡波書院' and categoryid=2;
update entity set hkdsepassrate=40 where name='保良局馬錦明中學' and categoryid=2;
update entity set hkdsepassrate=40 where name='羅定邦中學' and categoryid=2;
update entity set hkdsepassrate=38.1, chipassrate=49.4, engpassrate=50.3, urate=0 where name='中華基督教會基朗中學' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=58.6, engpassrate=54.1, urate=23 where name='慈幼英文學校' and categoryid=2;
update entity set urate=18.2 where name='香港道教聯合會圓玄學院第二中學' and categoryid=2;


update entity set urate=36 where name='基督教香港信義會心誠中學' and categoryid=2;
update entity set hkdsepassrate=36.9, chipassrate=45.5, engpassrate=59, urate=23.4 where name='鄧鏡波學校' and categoryid=2;
update entity set urate=21 where name='明愛粉嶺陳震夏中學' and categoryid=2;
update entity set urate=7.25 where name='香海正覺蓮社佛教梁植偉中學' and categoryid=2;
update entity set hkdsepassrate=36.8, urate=6.32 where name='德信中學' and categoryid=2;
update entity set hkdsepassrate=34.34 where name='浸信會永隆中學' and categoryid=2;
update entity set hkdsepassrate=32, urate=18 where name='顯理中學' and categoryid=2;
update entity set hkdsepassrate=32 where name='何東中學' and categoryid=2;
update entity set hkdsepassrate=32 where name='五旬節中學' and categoryid=2;
update entity set hkdsepassrate=29.6, urate=10 where name='香港仔浸信會呂明才書院' and categoryid=2;
update entity set hkdsepassrate=29.28 where name='東華三院馮黃鳳亭中學' and categoryid=2;
update entity set hkdsepassrate=27.9 where name='東華三院呂潤財紀念中學' and categoryid=2;
update entity set urate=20 where name='孔教學院大成何郭佩珍中學' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=0, engpassrate=0, urate=23 where name='鳳溪廖萬石堂中學' and categoryid=2;
update entity set hkdsepassrate=16.5 where name='博愛醫院八十週年鄧英喜中學' and categoryid=2;



update entity set urate=18.6 where name='佛教孔仙洲紀念中學' and categoryid=2;
update entity set urate=15 where name='鄧肇堅維多利亞官立中學' and categoryid=2;
update entity set urate=15.4 where name='上水官立中學' and categoryid=2;
update entity set urate=15.15 where name='寶覺中學' and categoryid=2;
update entity set hkdsepassrate=24.58, urate=11.05 where name='樂善堂顧超文中學' and categoryid=2;
update entity set hkdsepassrate=32.1, urate=2 where name='梁文燕紀念中學（沙田）' and categoryid=2;
update entity set hkdsepassrate=25.3 where name='宣道中學' and categoryid=2;

update entity set hkdsepassrate=22.8 where name='嶺南中學' and categoryid=2;
update entity set hkdsepassrate=22, urate=11 where name='青年會書院' and categoryid=2;
update entity set hkdsepassrate=20.3, urate=6.7 where name='石籬天主教中學' and categoryid=2;
update entity set hkdsepassrate=20.2, urate=10.9 where name='東涌天主教學校' and categoryid=2;
update entity set hkdsepassrate=19, urate=9.52 where name='迦密聖道中學' and categoryid=2;
update entity set hkdsepassrate=18, urate=7.8 where name='東華三院邱子田紀念中學' and categoryid=2;
update entity set hkdsepassrate=17.7, urate=1.89 where name='新會商會中學' and categoryid=2;
update entity set hkdsepassrate=15.9, urate=15 where name='東華三院李潤田紀念中學' and categoryid=2;
update entity set hkdsepassrate=15.5, urate=6.8 where name='新生命教育協會平安福音中學' and categoryid=2;
update entity set hkdsepassrate=15, chipassrate=28.9, engpassrate=18.6, urate=6.2 where name='天主教伍華中學' and categoryid=2;
update entity set hkdsepassrate=14.8, urate=11 where name='中華基督教會燕京書院' and categoryid=2;
update entity set hkdsepassrate=14.7 where name='德貞女子中學' and categoryid=2;
update entity set hkdsepassrate=14 where name='嶺南衡怡紀念中學' and categoryid=2;
update entity set urate=14.6 where name='香海正覺蓮社佛教馬錦燦紀念英文中學' and categoryid=2;
update entity set hkdsepassrate=9.2 where name='西貢崇真天主教學校（中學部）' and categoryid=2;
update entity set hkdsepassrate=8.6, urate=5.1 where name='明愛屯門馬登基金中學' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=0, engpassrate=0, urate=6.1 where name='閩僑中學' and categoryid=2;
update entity set hkdsepassrate=7.8, urate=2.1 where name='香港聖公會何明華會督中學' and categoryid=2;
update entity set hkdsepassrate=4, chipassrate=19, engpassrate=5, urate=12 where name='棉紡會中學' and categoryid=2;
update entity set hkdsepassrate=3.08 where name='中華基督教會基協中學' and categoryid=2;
update entity set hkdsepassrate=2.4 where name='東華三院郭一葦中學' and categoryid=2;
update entity set hkdsepassrate=2.4 where name='東華三院邱金元中學' and categoryid=2;
update entity set hkdsepassrate=0, chipassrate=0, engpassrate=0, urate=8 where name='中華聖潔會靈風中學' and categoryid=2;
update entity set hkdsepassrate=1.6 where name='東華三院黃鳳翎中學' and categoryid=2;
update entity set urate=6.19 where name='加拿大神召會嘉智中學' and categoryid=2;
update entity set urate=4.92 where name='神召會康樂中學' and categoryid=2;
update entity set urate=4.1 where name='聖芳濟各書院' and categoryid=2;
update entity set urate=4 where name='葵涌蘇浙公學' and categoryid=2;
update entity set urate=3.9 where name='聖公會聖西門呂明才中學' and categoryid=2;
update entity set urate=3.2 where name='紡織學會美國商會胡漢輝中學' and categoryid=2;
update entity set urate=2 where name='廠商會蔡章閣中學' and categoryid=2;
update entity set urate=1.45 where name='培英中學' and categoryid=2;
update entity set urate=0.96 where name='中華基督教會基新中學' and categoryid=2;
update entity set urate=0.54 where name='博愛醫院鄧佩瓊紀念中學' and categoryid=2;


update entityscore es, entity e set es.hkdsepassrate=e.hkdsepassrate,es.chipassrate=e.chipassrate,es.engpassrate=e.engpassrate,es.urate=e.urate where es.entityid=e.id and es.year=2015 and e.categoryid in (2,5) ;
