update entity set  hkdsepassrate=0, chipassrate=0,engpassrate=0, urate=0 where categoryid in (2,5);
update entityscore set  hkdsepassrate=0, chipassrate=0,engpassrate=0, urate=0 where categoryid in (2,5) and year=2017;

update entity set hkdsepassrate=88 where name='聖保祿學校' and categoryid=2;
update entity set hkdsepassrate=87, urate=80.6 where name='拔萃女書院' and categoryid=2;
update entity set hkdsepassrate=86 where name='馬錦明慈善基金馬可賓紀念中學' and categoryid=2;
update entity set hkdsepassrate=82, urate=51.8 where name='港島民生書院' and categoryid=2;
update entity set hkdsepassrate=82.2 where name='聖公會陳融中學' and categoryid=2;
update entity set hkdsepassrate=81.3 where name='保良局羅氏基金中學' and categoryid=2;
update entity set hkdsepassrate=81.3 where name='景嶺書院' and categoryid=2;
update entity set hkdsepassrate=76.8 where name='香港培道中學' and categoryid=2;
update entity set hkdsepassrate=75 where name='華仁書院（九龍）' and categoryid=2;
update entity set hkdsepassrate=73.8, urate=41.27 where name='沙田官立中學' and categoryid=2;
update entity set hkdsepassrate=72 where name='聖瑪加利男女英文中小學' and categoryid=2;
update entity set hkdsepassrate=65 where name='衛理中學' and categoryid=2;
update entity set hkdsepassrate=63 where name='香港管理專業協會李國寶中學' and categoryid=2;
update entity set hkdsepassrate=21.9 where name='梁文燕紀念中學（沙田）' and categoryid=2;
update entity set hkdsepassrate=80 where name='香港培正中學' and categoryid=2;
update entity set hkdsepassrate=97.58, urate=68 where name='嘉諾撒聖瑪利書院' and categoryid=2;
update entity set hkdsepassrate=96.6 where name='沙田崇真中學' and categoryid=2;
update entity set hkdsepassrate=96.4, urate=95.7 where name='迦密柏雨中學' and categoryid=2;
update entity set hkdsepassrate=96.4 where name='聖保羅男女中學' and categoryid=2;
update entity set hkdsepassrate=95.1, urate=71.3 where name='庇理羅士女子中學' and categoryid=2;
update entity set hkdsepassrate=94.9, urate=87.18 where name='聖公會林護紀念中學' and categoryid=2;
update entity set hkdsepassrate=94.5, urate=91.3 where name='香港道教聯合會鄧顯紀念中學' and categoryid=2;
update entity set hkdsepassrate=94.5, urate=80.47 where name='可風中學（嗇色園主辦）' and categoryid=2;
update entity set hkdsepassrate=94.3, urate=82.9 where name='天主教崇德英文書院' and categoryid=2;
update entity set hkdsepassrate=94 where name='保良局百周年李兆忠紀念中學' and categoryid=2;
update entity set hkdsepassrate=94 where name='浸信會呂明才中學' and categoryid=2;
update entity set hkdsepassrate=93.5, urate=83.33 where name='荃灣官立中學' and categoryid=2;
update entity set hkdsepassrate=93.2, urate=83.3 where name='迦密主恩中學' and categoryid=2;
update entity set hkdsepassrate=93, urate=85.99 where name='聖公會曾肇添中學' and categoryid=2;
update entity set hkdsepassrate=93 where name='天主教母佑會蕭明中學' and categoryid=2;
update entity set hkdsepassrate=90.8, urate=85.6 where name='保良局第一張永慶中學' and categoryid=2;
update entity set hkdsepassrate=90.15, urate=72.18 where name='皇仁書院' and categoryid=2;
update entity set hkdsepassrate=90 where name='嘉諾撒聖家書院' and categoryid=2;
update entity set hkdsepassrate=89.66 where name='瑪利曼中學' and categoryid=2;
update entity set hkdsepassrate=89.4, urate=70.92 where name='華英中學' and categoryid=2;
update entity set hkdsepassrate=89, urate=62.14 where name='英華女學校' and categoryid=2;
update entity set hkdsepassrate=88.3 where name='東華三院甲寅年總理中學' and categoryid=2;
update entity set hkdsepassrate=88.1 where name='香港中國婦女會中學' and categoryid=2;
update entity set hkdsepassrate=87.5, urate=88.2 where name='保良局董玉娣中學' and categoryid=2;
update entity set hkdsepassrate=87.5 where name='聖士提反女子中學' and categoryid=2;
update entity set hkdsepassrate=87.4 where name='新界鄉議局元朗區中學' and categoryid=2;
update entity set hkdsepassrate=87.4 where name='寶血會上智英文書院' and categoryid=2;
update entity set hkdsepassrate=87.3, urate=81.74 where name='伊利沙伯中學' and categoryid=2;
update entity set hkdsepassrate=87, urate=77.7 where name='張祝珊英文中學' and categoryid=2;
update entity set hkdsepassrate=87, urate=80.24 where name='基督教香港信義會元朗信義中學' and categoryid=2;
update entity set hkdsepassrate=86.9, urate=80 where name='沙田培英中學' and categoryid=2;
update entity set hkdsepassrate=86.9 where name='瑪利諾中學' and categoryid=2;
update entity set hkdsepassrate=86.8 where name='中華基督教會協和書院' and categoryid=2;
update entity set hkdsepassrate=86.5 where name='佛教善德英文中學' and categoryid=2;
update entity set hkdsepassrate=86.4 where name='嘉諾撒聖心書院' and categoryid=2;
update entity set hkdsepassrate=85.9, urate=75.56 where name='中華基督教會銘賢書院' and categoryid=2;
update entity set hkdsepassrate=85.5 where name='拔萃男書院' and categoryid=2;
update entity set hkdsepassrate=85.3 where name='聖公會林裘謀中學' and categoryid=2;
update entity set hkdsepassrate=85, urate=77 where name='九龍真光中學' and categoryid=2;
update entity set hkdsepassrate=85 where name='聖馬可中學' and categoryid=2;
update entity set hkdsepassrate=85 where name='真光女書院' and categoryid=2;
update entity set hkdsepassrate=84.96 where name='保祿六世書院' and categoryid=2;
update entity set hkdsepassrate=84.5, urate=63.43 where name='瑪利諾修院學校（中學部）' and categoryid=2;
update entity set hkdsepassrate=83.9, urate=83.3 where name='德望學校' and categoryid=2;
update entity set hkdsepassrate=83.9, urate=65.4 where name='順利天主教中學' and categoryid=2;
update entity set hkdsepassrate=83.7, urate=48.1 where name='嘉諾撒書院' and categoryid=2;
update entity set hkdsepassrate=83.3 where name='香港真光中學' and categoryid=2;
update entity set hkdsepassrate=83.09, urate=71.53 where name='聖若瑟書院' and categoryid=2;
update entity set hkdsepassrate=82.9, urate=72 where name='沙田蘇浙公學' and categoryid=2;
update entity set hkdsepassrate=82.7 where name='英華書院' and categoryid=2;
update entity set hkdsepassrate=82.4, urate=80 where name='英皇書院' and categoryid=2;
update entity set hkdsepassrate=82.4 where name='香港九龍塘基督教中華宣道會陳瑞芝紀念中學' and categoryid=2;
update entity set hkdsepassrate=82.1 where name='順德聯誼總會梁銶琚中學' and categoryid=2;
update entity set hkdsepassrate=81.7 where name='王肇枝中學' and categoryid=2;
update entity set hkdsepassrate=81.3 where name='東華三院陳兆民中學' and categoryid=2;
update entity set hkdsepassrate=81.15, urate=59.02 where name='保良局羅傑承（一九八三）中學' and categoryid=2;
update entity set hkdsepassrate=80.9, urate=82 where name='聖保羅書院' and categoryid=2;
update entity set hkdsepassrate=80.6 where name='聖言中學' and categoryid=2;
update entity set hkdsepassrate=80.6 where name='荃灣公立何傳耀紀念中學' and categoryid=2;
update entity set hkdsepassrate=80.4, urate=75 where name='旅港開平商會中學' and categoryid=2;
update entity set hkdsepassrate=80, urate=82 where name='沙田循道衛理中學' and categoryid=2;
update entity set hkdsepassrate=80, urate=67.5 where name='德愛中學' and categoryid=2;
update entity set hkdsepassrate=80 where name='喇沙書院' and categoryid=2;
update entity set hkdsepassrate=78.6 where name='筲箕灣官立中學' and categoryid=2;
update entity set hkdsepassrate=78, urate=50.35 where name='趙聿修紀念中學' and categoryid=2;
update entity set hkdsepassrate=77.3, urate=58.33 where name='香港管理專業協會羅桂祥中學' and categoryid=2;
update entity set hkdsepassrate=76.7 where name='優才（楊殷有娣）書院' and categoryid=2;
update entity set hkdsepassrate=75 where name='南亞路德會沐恩中學' and categoryid=2;
update entity set hkdsepassrate=74.8, urate=71.4 where name='東華三院黃笏南中學' and categoryid=2;
update entity set hkdsepassrate=74.6 where name='順德聯誼總會譚伯羽中學' and categoryid=2;
update entity set hkdsepassrate=73.6, urate=42.4 where name='東華三院伍若瑜夫人紀念中學' and categoryid=2;
update entity set hkdsepassrate=73 where name='寶安商會王少清中學' and categoryid=2;
update entity set hkdsepassrate=72.95, urate=52.46 where name='循道中學' and categoryid=2;
update entity set hkdsepassrate=72.7 where name='滙基書院（東九龍）' and categoryid=2;
update entity set hkdsepassrate=72, urate=62 where name='基督教女青年會丘佐榮中學' and categoryid=2;
update entity set hkdsepassrate=72 where name='梁式芝書院' and categoryid=2;
update entity set hkdsepassrate=70.6, urate=67.59 where name='港大同學會書院' and categoryid=2;
update entity set hkdsepassrate=70 where name='仁愛堂田家炳中學' and categoryid=2;
update entity set hkdsepassrate=70 where name='保良局馬錦明夫人章馥仙中學' and categoryid=2;
update entity set hkdsepassrate=69.9 where name='福建中學' and categoryid=2;
update entity set hkdsepassrate=69.3 where name='風采中學（教育評議會主辦）' and categoryid=2;
update entity set hkdsepassrate=69.23 where name='中華基督教會蒙民偉書院' and categoryid=2;
update entity set hkdsepassrate=67.4 where name='基督教宣道會宣基中學' and categoryid=2;
update entity set hkdsepassrate=63.57 where name='中華基督教會基元中學' and categoryid=2;
update entity set hkdsepassrate=63 where name='仁濟醫院王華湘中學' and categoryid=2;
update entity set hkdsepassrate=62.5 where name='賽馬會體藝中學' and categoryid=2;
update entity set hkdsepassrate=62.16 where name='聖母書院' and categoryid=2;
update entity set hkdsepassrate=62 where name='香港青年協會李兆基書院' and categoryid=2;
update entity set hkdsepassrate=61.2 where name='香島中學' and categoryid=2;
update entity set hkdsepassrate=57.1 where name='香港神託會培基書院' and categoryid=2;
update entity set hkdsepassrate=57 where name='瑪利諾神父教會學校' and categoryid=2;
update entity set hkdsepassrate=56.9, urate=48.6 where name='中華基金中學' and categoryid=2;
update entity set hkdsepassrate=56.31 where name='香港華人基督教聯會真道書院' and categoryid=2;
update entity set hkdsepassrate=56 where name='金文泰中學' and categoryid=2;
update entity set hkdsepassrate=54.5 where name='播道書院' and categoryid=2;
update entity set hkdsepassrate=53.2 where name='中華基督教會基朗中學' and categoryid=2;
update entity set hkdsepassrate=52.6 where name='保良局馬錦明中學' and categoryid=2;
update entity set hkdsepassrate=52.5 where name='基督教崇真中學' and categoryid=2;
update entity set hkdsepassrate=49 where name='陳瑞祺（喇沙）書院' and categoryid=2;
update entity set hkdsepassrate=48.9, urate=56.8 where name='恩主教書院' and categoryid=2;
update entity set hkdsepassrate=45 where name='顯理中學' and categoryid=2;
update entity set hkdsepassrate=43.7 where name='伊利沙伯中學舊生會中學' and categoryid=2;
update entity set hkdsepassrate=39.8 where name='保良局李城璧中學' and categoryid=2;
update entity set hkdsepassrate=35.5 where name='荃灣聖芳濟中學' and categoryid=2;
update entity set hkdsepassrate=35 where name='香港鄧鏡波書院' and categoryid=2;
update entity set hkdsepassrate=31.1 where name='東華三院辛亥年總理中學' and categoryid=2;
update entity set hkdsepassrate=30.6 where name='東涌天主教學校' and categoryid=2;
update entity set hkdsepassrate=29.4 where name='五旬節中學' and categoryid=2;
update entity set hkdsepassrate=27.7 where name='東華三院馮黃鳳亭中學' and categoryid=2;
update entity set hkdsepassrate=26.9 where name='青年會書院' and categoryid=2;
update entity set hkdsepassrate=25 where name='石籬天主教中學' and categoryid=2;
update entity set hkdsepassrate=21.05 where name='神召會康樂中學' and categoryid=2;
update entity set hkdsepassrate=20.6 where name='天主教伍華中學' and categoryid=2;
update entity set hkdsepassrate=20.23 where name='創知中學' and categoryid=2;
update entity set hkdsepassrate=20.2 where name='中華基督教會燕京書院' and categoryid=2;
update entity set hkdsepassrate=12.62 where name='迦密聖道中學' and categoryid=2;
update entity set hkdsepassrate=4.8 where name='東華三院邱金元中學' and categoryid=2;
update entity set urate=62.67 where name='民生書院' and categoryid=2;
update entity set urate=62 where name='中華傳道會安柱中學' and categoryid=2;
update entity set urate=57 where name='培僑書院' and categoryid=2;
update entity set urate=46.49 where name='聖芳濟書院' and categoryid=2;
update entity set urate=22.31 where name='港青基信書院' and categoryid=2;
update entity set urate=5.1 where name='培英中學' and categoryid=2;
update entity set urate=80.9 where name='何明華會督銀禧中學' and categoryid=2;
update entity set urate=76.7 where name='協恩中學' and categoryid=2;
update entity set urate=30 where name='聖伯多祿中學' and categoryid=2;
update entity set urate=27.12 where name='順德聯誼總會胡兆熾中學' and categoryid=2;
update entity set urate=12.07 where name='博愛醫院歷屆總理聯誼會梁省德中學' and categoryid=2;


update entityscore es, entity e set es.hkdsepassrate=e.hkdsepassrate,es.chipassrate=e.chipassrate,es.engpassrate=e.engpassrate,es.urate=e.urate where es.entityid=e.id and es.year=2017 and e.categoryid in (2,5) ;
