update entity set  hkdsepassrate=0, chipassrate=0,engpassrate=0, urate=0 where categoryid in (2,5);
update entityscore set  hkdsepassrate=0, chipassrate=0,engpassrate=0, urate=0 where categoryid in (2,5) and year=2017;

update entity set hkdsepassrate=88 where name='聖保祿學校' and categoryid=2;
update entity set hkdsepassrate=87, urate=80.6 where name='拔萃女書院' and categoryid=2;
update entity set hkdsepassrate=86 where name='馬錦明慈善基金馬可賓紀念中學' and categoryid=2;
update entity set hkdsepassrate=82, urate=51.8 where name='港島民生書院' and categoryid=2;
update entity set hkdsepassrate=82.2 where name='聖公會陳融中學' and categoryid=2;
update entity set hkdsepassrate=81.3 where name='保良局羅氏基金中學' and categoryid=2;
update entity set hkdsepassrate=81.3 where name='景嶺書院' and categoryid=2;
update entity set hkdsepassrate=76.8 where name='香港培道中學' and categoryid=2;
update entity set hkdsepassrate=75 where name='華仁書院（九龍）' and categoryid=2;
update entity set hkdsepassrate=73.8, urate=41.27 where name='沙田官立中學' and categoryid=2;
update entity set hkdsepassrate=72 where name='聖瑪加利男女英文中小學' and categoryid=2;
update entity set hkdsepassrate=65 where name='衛理中學' and categoryid=2;
update entity set hkdsepassrate=63 where name='香港管理專業協會李國寶中學' and categoryid=2;
update entity set hkdsepassrate=21.9 where name='梁文燕紀念中學（沙田）' and categoryid=2;
update entity set hkdsepassrate=80 where name='香港培正中學' and categoryid=2;
update entity set hkdsepassrate=97.58, urate=68 where name='嘉諾撒聖瑪利書院' and categoryid=2;
update entity set hkdsepassrate=96.6 where name='沙田崇真中學' and categoryid=2;
update entity set hkdsepassrate=96.4, urate=95.7 where name='迦密柏雨中學' and categoryid=2;
update entity set hkdsepassrate=96.4 where name='聖保羅男女中學' and categoryid=2;
update entity set hkdsepassrate=95.1, urate=71.3 where name='庇理羅士女子中學' and categoryid=2;
update entity set hkdsepassrate=94.9, urate=87.18 where name='聖公會林護紀念中學' and categoryid=2;
update entity set hkdsepassrate=94.5, urate=91.3 where name='香港道教聯合會鄧顯紀念中學' and categoryid=2;
update entity set hkdsepassrate=94.5, urate=80.47 where name='可風中學（嗇色園主辦）' and categoryid=2;
update entity set hkdsepassrate=94.3, urate=82.9 where name='天主教崇德英文書院' and categoryid=2;
update entity set hkdsepassrate=94 where name='保良局百周年李兆忠紀念中學' and categoryid=2;
update entity set hkdsepassrate=94 where name='浸信會呂明才中學' and categoryid=2;
update entity set hkdsepassrate=93.5, urate=83.33 where name='荃灣官立中學' and categoryid=2;
update entity set hkdsepassrate=93.2, urate=83.3 where name='迦密主恩中學' and categoryid=2;
update entity set hkdsepassrate=93, urate=85.99 where name='聖公會曾肇添中學' and categoryid=2;
update entity set hkdsepassrate=93 where name='天主教母佑會蕭明中學' and categoryid=2;
update entity set hkdsepassrate=90.8, urate=85.6 where name='保良局第一張永慶中學' and categoryid=2;
update entity set hkdsepassrate=90.15, urate=72.18 where name='皇仁書院' and categoryid=2;
update entity set hkdsepassrate=90 where name='嘉諾撒聖家書院' and categoryid=2;
update entity set hkdsepassrate=89.66 where name='瑪利曼中學' and categoryid=2;
update entity set hkdsepassrate=89.4, urate=70.92 where name='華英中學' and categoryid=2;
update entity set hkdsepassrate=89, urate=62.14 where name='英華女學校' and categoryid=2;
update entity set hkdsepassrate=88.3 where name='東華三院甲寅年總理中學' and categoryid=2;
update entity set hkdsepassrate=88.1 where name='香港中國婦女會中學' and categoryid=2;
update entity set hkdsepassrate=87.5, urate=88.2 where name='保良局董玉娣中學' and categoryid=2;
update entity set hkdsepassrate=87.5 where name='聖士提反女子中學' and categoryid=2;
update entity set hkdsepassrate=87.4 where name='新界鄉議局元朗區中學' and categoryid=2;
update entity set hkdsepassrate=87.4 where name='寶血會上智英文書院' and categoryid=2;
update entity set hkdsepassrate=87.3, urate=81.74 where name='伊利沙伯中學' and categoryid=2;
update entity set hkdsepassrate=87, urate=77.7 where name='張祝珊英文中學' and categoryid=2;
update entity set hkdsepassrate=87, urate=80.24 where name='基督教香港信義會元朗信義中學' and categoryid=2;
update entity set hkdsepassrate=86.9, urate=80 where name='沙田培英中學' and categoryid=2;
update entity set hkdsepassrate=86.9 where name='瑪利諾中學' and categoryid=2;
update entity set hkdsepassrate=86.8 where name='中華基督教會協和書院' and categoryid=2;
update entity set hkdsepassrate=86.5 where name='佛教善德英文中學' and categoryid=2;
update entity set hkdsepassrate=86.4 where name='嘉諾撒聖心書院' and categoryid=2;
update entity set hkdsepassrate=85.9, urate=75.56 where name='中華基督教會銘賢書院' and categoryid=2;
update entity set hkdsepassrate=85.5 where name='拔萃男書院' and categoryid=2;
update entity set hkdsepassrate=85.3 where name='聖公會林裘謀中學' and categoryid=2;
update entity set hkdsepassrate=85, urate=77 where name='九龍真光中學' and categoryid=2;
update entity set hkdsepassrate=85 where name='聖馬可中學' and categoryid=2;
update entity set hkdsepassrate=85 where name='真光女書院' and categoryid=2;
update entity set hkdsepassrate=84.96 where name='保祿六世書院' and categoryid=2;
update entity set hkdsepassrate=84.5, urate=63.43 where name='瑪利諾修院學校（中學部）' and categoryid=2;
update entity set hkdsepassrate=83.9, urate=83.3 where name='德望學校' and categoryid=2;
update entity set hkdsepassrate=83.9, urate=65.4 where name='順利天主教中學' and categoryid=2;
update entity set hkdsepassrate=83.7, urate=48.1 where name='嘉諾撒書院' and categoryid=2;
update entity set hkdsepassrate=83.3 where name='香港真光中學' and categoryid=2;
update entity set hkdsepassrate=83.09, urate=71.53 where name='聖若瑟書院' and categoryid=2;
update entity set hkdsepassrate=82.9, urate=72 where name='沙田蘇浙公學' and categoryid=2;
update entity set hkdsepassrate=82.7 where name='英華書院' and categoryid=2;
update entity set hkdsepassrate=82.4, urate=80 where name='英皇書院' and categoryid=2;
update entity set hkdsepassrate=82.4 where name='香港九龍塘基督教中華宣道會陳瑞芝紀念中學' and categoryid=2;
update entity set hkdsepassrate=82.1 where name='順德聯誼總會梁銶琚中學' and categoryid=2;
update entity set hkdsepassrate=81.7 where name='王肇枝中學' and categoryid=2;
update entity set hkdsepassrate=81.3 where name='東華三院陳兆民中學' and categoryid=2;
update entity set hkdsepassrate=81.15, urate=59.02 where name='保良局羅傑承（一九八三）中學' and categoryid=2;
update entity set hkdsepassrate=80.9, urate=82 where name='聖保羅書院' and categoryid=2;
update entity set hkdsepassrate=80.6 where name='聖言中學' and categoryid=2;
update entity set hkdsepassrate=80.6 where name='荃灣公立何傳耀紀念中學' and categoryid=2;
update entity set hkdsepassrate=80.4, urate=75 where name='旅港開平商會中學' and categoryid=2;
update entity set hkdsepassrate=80, urate=82 where name='沙田循道衛理中學' and categoryid=2;
update entity set hkdsepassrate=80, urate=67.5 where name='德愛中學' and categoryid=2;
update entity set hkdsepassrate=80 where name='喇沙書院' and categoryid=2;
update entity set hkdsepassrate=78.6 where name='筲箕灣官立中學' and categoryid=2;
update entity set hkdsepassrate=78, urate=50.35 where name='趙聿修紀念中學' and categoryid=2;
update entity set hkdsepassrate=77.3, urate=58.33 where name='香港管理專業協會羅桂祥中學' and categoryid=2;
update entity set hkdsepassrate=76.7 where name='優才（楊殷有娣）書院' and categoryid=2;
update entity set hkdsepassrate=75 where name='南亞路德會沐恩中學' and categoryid=2;
update entity set hkdsepassrate=74.8, urate=71.4 where name='東華三院黃笏南中學' and categoryid=2;
update entity set hkdsepassrate=74.6 where name='順德聯誼總會譚伯羽中學' and categoryid=2;
update entity set hkdsepassrate=73.6, urate=42.4 where name='東華三院伍若瑜夫人紀念中學' and categoryid=2;
update entity set hkdsepassrate=73 where name='寶安商會王少清中學' and categoryid=2;
update entity set hkdsepassrate=72.95, urate=52.46 where name='循道中學' and categoryid=2;
update entity set hkdsepassrate=72.7 where name='滙基書院（東九龍）' and categoryid=2;
update entity set hkdsepassrate=72, urate=62 where name='基督教女青年會丘佐榮中學' and categoryid=2;
update entity set hkdsepassrate=72 where name='梁式芝書院' and categoryid=2;
update entity set hkdsepassrate=70.6, urate=67.59 where name='港大同學會書院' and categoryid=2;
update entity set hkdsepassrate=70 where name='仁愛堂田家炳中學' and categoryid=2;
update entity set hkdsepassrate=70 where name='保良局馬錦明夫人章馥仙中學' and categoryid=2;
update entity set hkdsepassrate=69.9 where name='福建中學' and categoryid=2;
update entity set hkdsepassrate=69.3 where name='風采中學（教育評議會主辦）' and categoryid=2;
update entity set hkdsepassrate=69.23 where name='中華基督教會蒙民偉書院' and categoryid=2;
update entity set hkdsepassrate=67.4 where name='基督教宣道會宣基中學' and categoryid=2;
update entity set hkdsepassrate=63.57 where name='中華基督教會基元中學' and categoryid=2;
update entity set hkdsepassrate=63 where name='仁濟醫院王華湘中學' and categoryid=2;
update entity set hkdsepassrate=62.5 where name='賽馬會體藝中學' and categoryid=2;
update entity set hkdsepassrate=62.16 where name='聖母書院' and categoryid=2;
update entity set hkdsepassrate=62 where name='香港青年協會李兆基書院' and categoryid=2;
update entity set hkdsepassrate=61.2 where name='香島中學' and categoryid=2;
update entity set hkdsepassrate=57.1 where name='香港神託會培基書院' and categoryid=2;
update entity set hkdsepassrate=57 where name='瑪利諾神父教會學校' and categoryid=2;
update entity set hkdsepassrate=56.9, urate=48.6 where name='中華基金中學' and categoryid=2;
update entity set hkdsepassrate=56.31 where name='香港華人基督教聯會真道書院' and categoryid=2;
update entity set hkdsepassrate=56 where name='金文泰中學' and categoryid=2;
update entity set hkdsepassrate=54.5 where name='播道書院' and categoryid=2;
update entity set hkdsepassrate=53.2 where name='中華基督教會基朗中學' and categoryid=2;
update entity set hkdsepassrate=52.6 where name='保良局馬錦明中學' and categoryid=2;
update entity set hkdsepassrate=52.5 where name='基督教崇真中學' and categoryid=2;
update entity set hkdsepassrate=49 where name='陳瑞祺（喇沙）書院' and categoryid=2;
update entity set hkdsepassrate=48.9, urate=56.8 where name='恩主教書院' and categoryid=2;
update entity set hkdsepassrate=45 where name='顯理中學' and categoryid=2;
update entity set hkdsepassrate=43.7 where name='伊利沙伯中學舊生會中學' and categoryid=2;
update entity set hkdsepassrate=39.8 where name='保良局李城璧中學' and categoryid=2;
update entity set hkdsepassrate=35.5 where name='荃灣聖芳濟中學' and categoryid=2;
update entity set hkdsepassrate=35 where name='香港鄧鏡波書院' and categoryid=2;
update entity set hkdsepassrate=31.1 where name='東華三院辛亥年總理中學' and categoryid=2;
update entity set hkdsepassrate=30.6 where name='東涌天主教學校' and categoryid=2;
update entity set hkdsepassrate=29.4 where name='五旬節中學' and categoryid=2;
update entity set hkdsepassrate=27.7 where name='東華三院馮黃鳳亭中學' and categoryid=2;
update entity set hkdsepassrate=26.9 where name='青年會書院' and categoryid=2;
update entity set hkdsepassrate=25 where name='石籬天主教中學' and categoryid=2;
update entity set hkdsepassrate=21.05 where name='神召會康樂中學' and categoryid=2;
update entity set hkdsepassrate=20.6 where name='天主教伍華中學' and categoryid=2;
update entity set hkdsepassrate=20.23 where name='創知中學' and categoryid=2;
update entity set hkdsepassrate=20.2 where name='中華基督教會燕京書院' and categoryid=2;
update entity set hkdsepassrate=12.62 where name='迦密聖道中學' and categoryid=2;
update entity set hkdsepassrate=4.8 where name='東華三院邱金元中學' and categoryid=2;
update entity set urate=62.67 where name='民生書院' and categoryid=2;
update entity set urate=62 where name='中華傳道會安柱中學' and categoryid=2;
update entity set urate=57 where name='培僑書院' and categoryid=2;
update entity set urate=46.49 where name='聖芳濟書院' and categoryid=2;
update entity set urate=22.31 where name='港青基信書院' and categoryid=2;
update entity set urate=5.1 where name='培英中學' and categoryid=2;
update entity set urate=80.9 where name='何明華會督銀禧中學' and categoryid=2;
update entity set urate=76.7 where name='協恩中學' and categoryid=2;
update entity set urate=30 where name='聖伯多祿中學' and categoryid=2;
update entity set urate=27.12 where name='順德聯誼總會胡兆熾中學' and categoryid=2;
update entity set urate=12.07 where name='博愛醫院歷屆總理聯誼會梁省德中學' and categoryid=2;

update entity set hkdsepassrate=98.4,chipassrate=89,engpassrate=97.7 where name='聖士提反女子中學' and categoryid=2;
update entity set hkdsepassrate=97.6,chipassrate=97.6,engpassrate=100,urate=78 where name='嘉諾撒聖瑪利書院' and categoryid=2;
update entity set hkdsepassrate=96.6,chipassrate=97.3,engpassrate=98.6,urate=91.9 where name='沙田崇真中學' and categoryid=2;
update entity set hkdsepassrate=96.4,chipassrate=96.4,engpassrate=100,urate=69.6 where name='迦密柏雨中學' and categoryid=2;
update entity set hkdsepassrate=96.4,chipassrate=96.4,engpassrate=100 where name='聖保羅男女中學' and categoryid=2;
update entity set hkdsepassrate=94.9,chipassrate=94.9,engpassrate=100,urate=84 where name='聖公會林護紀念中學' and categoryid=2;
update entity set hkdsepassrate=94.5,chipassrate=95.3,engpassrate=98.4,urate=92.9 where name='香港道教聯合會鄧顯紀念中學' and categoryid=2;
update entity set hkdsepassrate=94.5,chipassrate=94.5,engpassrate=100,urate=71.1 where name='可風中學（嗇色園主辦）' and categoryid=2;
update entity set hkdsepassrate=94.3,chipassrate=95.1,engpassrate=100,urate=70.7 where name='天主教崇德英文書院' and categoryid=2;
update entity set hkdsepassrate=94.3,chipassrate=94.3,engpassrate=100,urate=72.6 where name='聖公會曾肇添中學' and categoryid=2;
update entity set hkdsepassrate=94,chipassrate=94,engpassrate=99.3 where name='保良局百周年李兆忠紀念中學' and categoryid=2;
update entity set hkdsepassrate=93.98,chipassrate=94.74,engpassrate=100,urate=75.19 where name='迦密中學' and categoryid=2;
update entity set hkdsepassrate=93.5,urate=73.55 where name='浸信會呂明才中學' and categoryid=2;
update entity set hkdsepassrate=93.2,chipassrate=93.9,engpassrate=99.2,urate=83.3 where name='迦密主恩中學' and categoryid=2;
update entity set hkdsepassrate=93,chipassrate=94.7,engpassrate=97.7,urate=80.3 where name='天主教母佑會蕭明中學' and categoryid=2;
update entity set hkdsepassrate=90.8,chipassrate=90.8,engpassrate=100,urate=78.4 where name='保良局第一張永慶中學' and categoryid=2;
update entity set hkdsepassrate=90.7,chipassrate=91.2,engpassrate=98.8,urate=66 where name='藍田聖保祿中學' and categoryid=2;
update entity set hkdsepassrate=89.5,chipassrate=83.3,engpassrate=100,urate=75.4 where name='香港真光中學' and categoryid=2;
update entity set hkdsepassrate=89.4,chipassrate=90.2,engpassrate=100,urate=74 where name='皇仁書院' and categoryid=2;
update entity set hkdsepassrate=89.1,chipassrate=89.1,engpassrate=94.6,urate=67 where name='中華傳道會安柱中學' and categoryid=2;
update entity set hkdsepassrate=89,chipassrate=90.9,engpassrate=97.6,urate=81.7 where name='基督教香港信義會元朗信義中學' and categoryid=2;
update entity set hkdsepassrate=89,chipassrate=89,engpassrate=100,urate=75 where name='聖保祿學校' and categoryid=2;
update entity set hkdsepassrate=88.8,chipassrate=89.6,engpassrate=99.3,urate=70.2 where name='香港中國婦女會中學' and categoryid=2;
update entity set hkdsepassrate=88.6,chipassrate=88.6,engpassrate=100,urate=73.6 where name='英華女學校' and categoryid=2;
update entity set hkdsepassrate=88.3,chipassrate=90.6,engpassrate=96.1,urate=81.3 where name='東華三院甲寅年總理中學' and categoryid=2;
update entity set hkdsepassrate=88.2,chipassrate=87.7,engpassrate=100,urate=72.1 where name='張祝珊英文中學' and categoryid=2;
update entity set hkdsepassrate=88,chipassrate=91,engpassrate=93 where name='保祿六世書院' and categoryid=2;
update entity set hkdsepassrate=87.5,chipassrate=88.2,engpassrate=97.8,urate=70 where name='聖羅撒書院' and categoryid=2;
update entity set hkdsepassrate=87.5,chipassrate=88.2,engpassrate=97.1,urate=83.8 where name='保良局董玉娣中學' and categoryid=2;
update entity set hkdsepassrate=87.3,chipassrate=88.1,engpassrate=97.6 where name='伊利沙伯中學' and categoryid=2;
update entity set hkdsepassrate=87,chipassrate=87,engpassrate=100,urate=63 where name='拔萃女書院' and categoryid=2;
update entity set hkdsepassrate=86.5,chipassrate=90.8,engpassrate=95.7,urate=73.1 where name='佛教善德英文中學' and categoryid=2;
update entity set hkdsepassrate=86.15,chipassrate=90.7,engpassrate=96.1,urate=67 where name='沙田培英中學' and categoryid=2;
update entity set hkdsepassrate=85.96,chipassrate=87.6,engpassrate=98.3,urate=76.7 where name='協恩中學' and categoryid=2;
update entity set hkdsepassrate=85.4,chipassrate=91.7,engpassrate=92.7,urate=69 where name='九龍真光中學' and categoryid=2;
update entity set hkdsepassrate=85.3,chipassrate=86.8,engpassrate=98.4,urate=75 where name='聖公會林裘謀中學' and categoryid=2;
update entity set hkdsepassrate=85,chipassrate=85,engpassrate=100,urate=77 where name='聖馬可中學' and categoryid=2;
update entity set hkdsepassrate=84.3,chipassrate=85.8,engpassrate=98.4,urate=63 where name='真光女書院' and categoryid=2;
update entity set hkdsepassrate=83.97,chipassrate=8473,engpassrate=97.71,urate=59.5 where name='聖公會莫壽增會督中學' and categoryid=2;
update entity set hkdsepassrate=83.7,chipassrate=86.8,engpassrate=95.3,urate=56.6 where name='嘉諾撒書院' and categoryid=2;
update entity set hkdsepassrate=83.3,chipassrate=83.3,engpassrate=100,urate=74 where name='民生書院' and categoryid=2;
update entity set hkdsepassrate=83,chipassrate=90,engpassrate=92,urate=74 where name='沙田蘇浙公學' and categoryid=2;
update entity set hkdsepassrate=83,chipassrate=88,engpassrate=95 where name='聖傑靈女子中學' and categoryid=2;
update entity set hkdsepassrate=82.1,chipassrate=85.7,engpassrate=94.3,urate=72 where name='順德聯誼總會梁銶琚中學' and categoryid=2;
update entity set hkdsepassrate=81.7,chipassrate=86.3,engpassrate=94.7,urate=58.8 where name='王肇枝中學' and categoryid=2;
update entity set hkdsepassrate=81.6,chipassrate=85.6,engpassrate=84.8 where name='東華三院伍若瑜夫人紀念中學' and categoryid=2;
update entity set hkdsepassrate=81.3,chipassrate=81,engpassrate=87.8,urate=35 where name='東華三院陳兆民中學' and categoryid=2;
update entity set hkdsepassrate=81.1,chipassrate=86.9,engpassrate=94.3,urate=68 where name='保良局羅傑承（一九八三）中學' and categoryid=2;
update entity set hkdsepassrate=80.8,chipassrate=82.2,engpassrate=98.6 where name='優才（楊殷有娣）書院' and categoryid=2;
update entity set hkdsepassrate=80.6,chipassrate=82.2,engpassrate=97.7,urate=63.6 where name='荃灣公立何傳耀紀念中學' and categoryid=2;
update entity set hkdsepassrate=80.6,chipassrate=80.6,engpassrate=98.2,urate=60 where name='聖言中學' and categoryid=2;
update entity set hkdsepassrate=80,chipassrate=86,engpassrate=87,urate=72 where name='馬錦明慈善基金馬可賓紀念中學' and categoryid=2;
update entity set hkdsepassrate=79.86,chipassrate=82,engpassrate=96.4,urate=67.6 where name='港島民生書院' and categoryid=2;
update entity set hkdsepassrate=79.8,chipassrate=86.8,engpassrate=91.4,urate=58.1 where name='沙田循道衛理中學' and categoryid=2;
update entity set hkdsepassrate=78.6,chipassrate=84.1,engpassrate=91.3,urate=51.6 where name='筲箕灣官立中學' and categoryid=2;
update entity set hkdsepassrate=78.5,chipassrate=80,engpassrate=94.7,urate=56.1 where name='聖公會鄧肇堅中學' and categoryid=2;
update entity set hkdsepassrate=75.4,chipassrate=82.3,engpassrate=89.2,urate=68.2 where name='田家炳中學' and categoryid=2;
update entity set hkdsepassrate=75,chipassrate=75.8,engpassrate=98.1,urate=67.6 where name='保良局顏寶鈴書院' and categoryid=2;
update entity set hkdsepassrate=73.7,chipassrate=75.4,engpassrate=93,urate=54.4 where name='聖芳濟書院' and categoryid=2;
update entity set hkdsepassrate=72.7,chipassrate=76.6,engpassrate=96.4,urate=60 where name='滙基書院（東九龍）' and categoryid=2;
update entity set hkdsepassrate=72,chipassrate=77,engpassrate=87,urate=50 where name='仁愛堂田家炳中學' and categoryid=2;
update entity set hkdsepassrate=72,chipassrate=76.6,engpassrate=93.5,urate=40 where name='基督教女青年會丘佐榮中學' and categoryid=2;
update entity set hkdsepassrate=71.3,chipassrate=82.9,engpassrate=82.2,urate=52.7 where name='聖公會陳融中學' and categoryid=2;
update entity set hkdsepassrate=70.42,chipassrate=81.7,engpassrate=84.5,urate=54.9 where name='順德聯誼總會李兆基中學' and categoryid=2;
update entity set hkdsepassrate=70,urate=60 where name='東華三院李嘉誠中學' and categoryid=2;
update entity set hkdsepassrate=69.9,chipassrate=76.5,engpassrate=85.2,urate=51 where name='福建中學' and categoryid=2;
update entity set hkdsepassrate=69.3,chipassrate=83.9,engpassrate=75.2,urate=67.2 where name='風采中學（教育評議會主辦）' and categoryid=2;
update entity set hkdsepassrate=64,chipassrate=71,engpassrate=81 where name='聖公會呂明才中學' and categoryid=2;
update entity set hkdsepassrate=62.8,chipassrate=79.84,engpassrate=72.87,urate=55.9 where name='仁濟醫院王華湘中學' and categoryid=2;
update entity set hkdsepassrate=62.5,chipassrate=66,engpassrate=90.3 where name='賽馬會體藝中學' and categoryid=2;
update entity set hkdsepassrate=62,chipassrate=71,engpassrate=80,urate=48 where name='聖母無玷聖心書院' and categoryid=2;
update entity set hkdsepassrate=62,chipassrate=62.9,engpassrate=93.8,urate=45 where name='香港青年協會李兆基書院' and categoryid=2;
update entity set hkdsepassrate=61.9,chipassrate=82.3,engpassrate=69.4,urate=47.6 where name='香島中學' and categoryid=2;
update entity set hkdsepassrate=60.55,chipassrate=70.64,engpassrate=99,urate=73.39 where name='港大同學會書院' and categoryid=2;
update entity set hkdsepassrate=60.2,chipassrate=71.3,engpassrate=80.6,urate=53.7 where name='德雅中學' and categoryid=2;
update entity set hkdsepassrate=59.2,chipassrate=70,engpassrate=80.8,urate=44.62 where name='東華三院盧幹庭紀念中學' and categoryid=2;
update entity set hkdsepassrate=58.6,chipassrate=70.7,engpassrate=75.7,urate=35.7 where name='中華基督教會全完中學' and categoryid=2;
update entity set hkdsepassrate=56,chipassrate=59.6,engpassrate=93.6,urate=49.5 where name='中華基金中學' and categoryid=2;
update entity set hkdsepassrate=53.38,chipassrate=73.68,engpassrate=65.41,urate=36.09 where name='保良局馬錦明中學' and categoryid=2;
update entity set hkdsepassrate=53.2,chipassrate=65.1,engpassrate=64.3,urate=23 where name='中華基督教會基朗中學' and categoryid=2;
update entity set hkdsepassrate=50.7,chipassrate=68.6,engpassrate=64.2,urate=37.7 where name='新生命教育協會呂郭碧鳳中學' and categoryid=2;
update entity set hkdsepassrate=48.4,chipassrate=65.6,engpassrate=62.3,urate=39.3 where name='保良局胡忠中學' and categoryid=2;
update entity set hkdsepassrate=47.4,engpassrate=90.2,urate=38.2 where name='地利亞修女紀念學校（百老匯）' and categoryid=2;
update entity set hkdsepassrate=44.2,chipassrate=70,engpassrate=55,urate=28.1 where name='顯理中學' and categoryid=2;
update entity set hkdsepassrate=43.7,chipassrate=68.3,engpassrate=51.4,urate=35.9 where name='伊利沙伯中學舊生會中學' and categoryid=2;
update entity set hkdsepassrate=43.2,chipassrate=58.7,engpassrate=63.5,urate=30 where name='馬鞍山聖若瑟中學' and categoryid=2;
update entity set hkdsepassrate=42,chipassrate=58,engpassrate=58,urate=33 where name='馬鞍山崇真中學' and categoryid=2;
update entity set hkdsepassrate=40,chipassrate=60,engpassrate=40,urate=50 where name='青年會書院' and categoryid=2;
update entity set hkdsepassrate=40 where name='鐘聲慈善社胡陳金枝中學' and categoryid=2;
update entity set hkdsepassrate=32.8,chipassrate=52,engpassrate=54.4,urate=24.8 where name='慈幼英文學校' and categoryid=2;
update entity set hkdsepassrate=31.1,chipassrate=63.9,engpassrate=36.1,urate=26.9 where name='東華三院辛亥年總理中學' and categoryid=2;
update entity set hkdsepassrate=8.6,chipassrate=28.57,engpassrate=10.47,urate=3.8 where name='佛教沈香林紀念中學' and categoryid=2;
update entity set hkdsepassrate=5,chipassrate=20,engpassrate=5,urate=5 where name='棉紡會中學' and categoryid=2;
update entity set chipassrate=87.3,engpassrate=79.1,urate=72 where name='順德聯誼總會譚伯羽中學' and categoryid=2;
update entity set chipassrate=86,engpassrate=95.6 where name='香港九龍塘基督教中華宣道會陳瑞芝紀念中學' and categoryid=2;
update entity set chipassrate=81.3,engpassrate=98.2,urate=62.5 where name='景嶺書院' and categoryid=2;
update entity set chipassrate=76.8,engpassrate=87.5,urate=48.2 where name='香港培道中學' and categoryid=2;
update entity set chipassrate=71.8,engpassrate=72.5,urate=37.4 where name='南屯門官立中學' and categoryid=2;
update entity set urate=20 where name='元朗公立中學校友會鄧兆棠中學' and categoryid=2;
update entity set urate=70 where name='旅港開平商會中學' and categoryid=2;
update entity set urate=64.2 where name='嘉諾撒聖心書院' and categoryid=2;
update entity set urate=64 where name='香港浸會大學附屬學校王錦輝中小學' and categoryid=2;
update entity set urate=47 where name='屯門官立中學' and categoryid=2;
update entity set urate=39 where name='孔教學院大成何郭佩珍中學' and categoryid=2;
update entity set urate=25 where name='新會商會陳白沙紀念中學' and categoryid=2;
update entity set urate=21.6 where name='荃灣聖芳濟中學' and categoryid=2;
update entity set urate=21 where name='伊斯蘭脫維善紀念中學' and categoryid=2;
update entity set urate=20 where name='順德聯誼總會胡兆熾中學' and categoryid=2;
update entity set urate=18 where name='神召會康樂中學' and categoryid=2;
update entity set urate=17.6 where name='葵涌蘇浙公學' and categoryid=2;
update entity set urate=17.5 where name='聖公會基孝中學' and categoryid=2;
update entity set urate=15.3 where name='東涌天主教學校' and categoryid=2;
update entity set urate=15 where name='加拿大神召會嘉智中學' and categoryid=2;
update entity set urate=6 where name='閩僑中學' and categoryid=2;
update entity set urate=5 where name='明愛粉嶺陳震夏中學' and categoryid=2;
update entity set urate=4 where name='中華聖潔會靈風中學' and categoryid=2;

update entityscore es, entity e set es.hkdsepassrate=e.hkdsepassrate,es.chipassrate=e.chipassrate,es.engpassrate=e.engpassrate,es.urate=e.urate where es.entityid=e.id and es.year=2017 and e.categoryid in (2,5) ;
