update entity set  hkdsepassrate=0, chipassrate=0,engpassrate=0, urate=0 where categoryid in (2,5);
update entityscore set  hkdsepassrate=0, chipassrate=0,engpassrate=0, urate=0 where categoryid in (2,5) and year=2018;

update entity set hkdsepassrate=78.4, urate=67.2 where name='基督教女青年會丘佐榮中學' and categoryid=2;
update entity set hkdsepassrate=92 where name='香港中國婦女會中學' and categoryid=2;
update entity set hkdsepassrate=82.1, urate=74 where name='中華基金中學' and categoryid=2;
update entity set hkdsepassrate=80, urate=78 where name='九龍真光中學' and categoryid=2;
update entity set hkdsepassrate=78 where name='華仁書院（九龍）' and categoryid=2;
update entity set hkdsepassrate=35.3 where name='五旬節中學' and categoryid=2;
update entity set hkdsepassrate=51.3 where name='伊利沙伯中學舊生會中學' and categoryid=2;
update entity set hkdsepassrate=85.2, urate=75.56 where name='伊利沙伯中學' and categoryid=2;
update entity set hkdsepassrate=80.3 where name='荃灣公立何傳耀紀念中學' and categoryid=2;
update entity set hkdsepassrate=88 where name='何明華會督銀禧中學' and categoryid=2;
update entity set hkdsepassrate=20.5 where name='何東中學' and categoryid=2;
update entity set urate=30.5 where name='孔教學院大成何郭佩珍中學' and categoryid=2;
update entity set hkdsepassrate=91.4 where name='佛教善德英文中學' and categoryid=2;
update entity set urate=36.8 where name='佛教孔仙洲紀念中學' and categoryid=2;
update entity set hkdsepassrate=86.51 where name='保祿六世書院' and categoryid=2;
update entity set hkdsepassrate=81.3 where name='保良局羅氏基金中學' and categoryid=2;
update entity set hkdsepassrate=47.4 where name='保良局胡忠中學' and categoryid=2;
update entity set hkdsepassrate=20 where name='基督教香港信義會宏信書院' and categoryid=2;
update entity set hkdsepassrate=87.9 where name='優才（楊殷有娣）書院' and categoryid=2;
update entity set hkdsepassrate=91.3, urate=82 where name='基督教香港信義會元朗信義中學' and categoryid=2;
update entity set hkdsepassrate=87.2 where name='中華基督教會協和書院' and categoryid=2;
update entity set urate=60.5 where name='協恩中學' and categoryid=2;
update entity set hkdsepassrate=90, urate=77.34 where name='可風中學（嗇色園主辦）' and categoryid=2;
update entity set hkdsepassrate=90 where name='浸信會呂明才中學' and categoryid=2;
update entity set hkdsepassrate=76.7 where name='嘉諾撒書院' and categoryid=2;
update entity set hkdsepassrate=82 where name='嘉諾撒聖家書院' and categoryid=2;
update entity set hkdsepassrate=84.85 where name='嘉諾撒聖心書院' and categoryid=2;
update entity set hkdsepassrate=97.1 where name='嘉諾撒聖瑪利書院' and categoryid=2;
update entity set urate=1.6 where name='香港道教聯合會圓玄學院第二中學' and categoryid=2;
update entity set hkdsepassrate=43.4 where name='地利亞修女紀念學校（百老匯）' and categoryid=2;
update entity set urate=63 where name='培僑書院' and categoryid=2;
update entity set hkdsepassrate=41.2 where name='中華基督教會基朗中學' and categoryid=2;
update entity set hkdsepassrate=59.34 where name='基督教崇真中學' and categoryid=2;
update entity set urate=13.2 where name='基督書院' and categoryid=2;
update entity set urate=88.5 where name='天主教崇德英文書院' and categoryid=2;
update entity set urate=67 where name='天主教郭得勝中學' and categoryid=2;
update entity set hkdsepassrate=47.75 where name='妙法寺劉金龍中學' and categoryid=2;
update entity set hkdsepassrate=90.1 where name='中華傳道會安柱中學' and categoryid=2;
update entity set hkdsepassrate=82.7 where name='基督教宣道會宣基中學' and categoryid=2;
update entity set hkdsepassrate=91.3 where name='寶血會上智英文書院' and categoryid=2;
update entity set hkdsepassrate=12.6 where name='嶺南中學' and categoryid=2;
update entity set urate=12 where name='新生命教育協會平安福音中學' and categoryid=2;
update entity set hkdsepassrate=95.2, urate=80.95 where name='庇理羅士女子中學' and categoryid=2;
update entity set hkdsepassrate=93.4 where name='保良局第一張永慶中學' and categoryid=2;
update entity set urate=33 where name='香港中文大學校友會聯會張煊昌中學' and categoryid=2;
update entity set hkdsepassrate=97.6, urate=91.27 where name='張祝珊英文中學' and categoryid=2;
update entity set hkdsepassrate=69.67, urate=60.48 where name='循道中學' and categoryid=2;
update entity set urate=18 where name='德信中學' and categoryid=2;
update entity set hkdsepassrate=86, urate=77 where name='德愛中學' and categoryid=2;
update entity set hkdsepassrate=94.3 where name='德望學校' and categoryid=2;
update entity set hkdsepassrate=90 where name='恩主教書院' and categoryid=2;
update entity set hkdsepassrate=35.7 where name='慈幼英文學校' and categoryid=2;
update entity set hkdsepassrate=69 where name='播道書院' and categoryid=2;
update entity set hkdsepassrate=28 where name='啟思中學' and categoryid=2;
update entity set hkdsepassrate=85.2 where name='旅港開平商會中學' and categoryid=2;
update entity set hkdsepassrate=92.5 where name='景嶺書院' and categoryid=2;
update entity set hkdsepassrate=94.4, urate=79.38 where name='聖公會曾肇添中學' and categoryid=2;
update entity set hkdsepassrate=76 where name='香港青年協會李兆基書院' and categoryid=2;
update entity set urate=70 where name='東華三院李嘉誠中學' and categoryid=2;
update entity set hkdsepassrate=53.8 where name='保良局李城璧中學' and categoryid=2;
update entity set hkdsepassrate=19.6 where name='東涌天主教學校' and categoryid=2;
update entity set hkdsepassrate=14 where name='林大輝中學' and categoryid=2;
update entity set hkdsepassrate=92.5, urate=85.6 where name='聖公會林護紀念中學' and categoryid=2;
update entity set hkdsepassrate=29.8 where name='梁文燕紀念中學（沙田）' and categoryid=2;
update entity set urate=11.76 where name='香海正覺蓮社佛教梁植偉中學' and categoryid=2;
update entity set hkdsepassrate=88.5 where name='順德聯誼總會梁銶琚中學' and categoryid=2;
update entity set hkdsepassrate=25 where name='樂善堂顧超文中學' and categoryid=2;
update entity set hkdsepassrate=90.2, urate=89 where name='沙田培英中學' and categoryid=2;
update entity set urate=46.32 where name='沙田官立中學' and categoryid=2;
update entity set hkdsepassrate=85.9, urate=80.47 where name='沙田循道衛理中學' and categoryid=2;
update entity set hkdsepassrate=97.9 where name='沙田崇真中學' and categoryid=2;
update entity set hkdsepassrate=80, urate=70 where name='沙田蘇浙公學' and categoryid=2;
update entity set hkdsepassrate=81.5, urate=79.83 where name='港大同學會書院' and categoryid=2;
update entity set urate=56.83 where name='港島民生書院' and categoryid=2;
update entity set urate=17.29 where name='港青基信書院' and categoryid=2;
update entity set hkdsepassrate=76.5, urate=78.47 where name='滙基書院（東九龍）' and categoryid=2;
update entity set hkdsepassrate=14 where name='中華基督教會燕京書院' and categoryid=2;
update entity set hkdsepassrate=91.6 where name='寶安商會王少清中學' and categoryid=2;
update entity set hkdsepassrate=78.8 where name='王肇枝中學' and categoryid=2;
update entity set hkdsepassrate=75 where name='香港浸會大學附屬學校王錦輝中小學' and categoryid=2;
update entity set hkdsepassrate=25.6 where name='玫瑰崗學校' and categoryid=2;
update entity set hkdsepassrate=86.1, urate=61.36 where name='瑪利諾修院學校（中學部）' and categoryid=2;
update entity set hkdsepassrate=79.1, urate=56.21 where name='仁愛堂田家炳中學' and categoryid=2;
update entity set hkdsepassrate=82.5 where name='仁愛堂田家炳中學' and categoryid=2;
update entity set hkdsepassrate=89.4 where name='東華三院甲寅年總理中學' and categoryid=2;
update entity set hkdsepassrate=81.5 where name='拔萃男書院' and categoryid=2;
update entity set urate=68.22 where name='皇仁書院' and categoryid=2;
update entity set hkdsepassrate=57.6 where name='東華三院盧幹庭紀念中學' and categoryid=2;
update entity set hkdsepassrate=83.6 where name='真光女書院' and categoryid=2;
update entity set hkdsepassrate=37.25 where name='香港華人基督教聯會真道書院' and categoryid=2;
update entity set hkdsepassrate=28 where name='石籬天主教中學' and categoryid=2;
update entity set hkdsepassrate=12.7 where name='神召會康樂中學' and categoryid=2;
update entity set hkdsepassrate=69.1 where name='香港神託會培基書院' and categoryid=2;
update entity set hkdsepassrate=70.3, urate=62 where name='福建中學' and categoryid=2;
update entity set hkdsepassrate=36.67 where name='福建中學（小西灣）' and categoryid=2;
update entity set hkdsepassrate=69.9 where name='筲箕灣官立中學' and categoryid=2;
update entity set urate=23 where name='粉嶺救恩書院' and categoryid=2;
update entity set hkdsepassrate=79.67, urate=48.78 where name='保良局羅傑承（一九八三）中學' and categoryid=2;
update entity set hkdsepassrate=70.9 where name='香港管理專業協會羅桂祥中學' and categoryid=2;
update entity set urate=30 where name='聖伯多祿中學' and categoryid=2;
update entity set urate=60.31 where name='聖保祿中學' and categoryid=2;
update entity set hkdsepassrate=80 where name='聖保羅書院' and categoryid=2;
update entity set hkdsepassrate=94.5 where name='聖保羅男女中學' and categoryid=2;
update entity set hkdsepassrate=91.8 where name='聖公會呂明才中學' and categoryid=2;
update entity set hkdsepassrate=84.7 where name='聖公會林裘謀中學' and categoryid=2;
update entity set hkdsepassrate=84.7 where name='聖公會陳融中學' and categoryid=2;
update entity set hkdsepassrate=87.3, urate=61.11 where name='聖士提反女子中學' and categoryid=2;
update entity set hkdsepassrate=46.09 where name='聖母書院' and categoryid=2;
update entity set hkdsepassrate=89.5 where name='聖羅撒書院' and categoryid=2;
update entity set hkdsepassrate=84.78, urate=78 where name='聖若瑟書院' and categoryid=2;
update entity set hkdsepassrate=80.4 where name='聖言中學' and categoryid=2;
update entity set hkdsepassrate=37.2 where name='基督教中國佈道會聖道迦南書院' and categoryid=2;
update entity set hkdsepassrate=80.3 where name='聖馬可中學' and categoryid=2;
update entity set urate=38.5 where name='順德聯誼總會胡兆熾中學' and categoryid=2;
update entity set hkdsepassrate=82.8 where name='英皇書院' and categoryid=2;
update entity set hkdsepassrate=93, urate=66.67 where name='英華女學校' and categoryid=2;
update entity set hkdsepassrate=76.2 where name='英華書院' and categoryid=2;
update entity set hkdsepassrate=94.3, urate=89.36 where name='荃灣官立中學' and categoryid=2;
update entity set hkdsepassrate=35 where name='荃灣聖芳濟中學' and categoryid=2;
update entity set urate=25 where name='聖公會聖馬利亞堂莫慶堯中學' and categoryid=2;
update entity set urate=70.5 where name='華英中學' and categoryid=2;
update entity set hkdsepassrate=92.4 where name='藍田聖保祿中學' and categoryid=2;
update entity set hkdsepassrate=4.3 where name='西貢崇真天主教學校（中學部）' and categoryid=2;
update entity set hkdsepassrate=63.6 where name='觀塘官立中學' and categoryid=2;
update entity set hkdsepassrate=73.1 where name='觀塘瑪利諾書院' and categoryid=2;
update entity set hkdsepassrate=82.3 where name='順德聯誼總會譚伯羽中學' and categoryid=2;
update entity set hkdsepassrate=60.1 where name='賽馬會體藝中學' and categoryid=2;
update entity set hkdsepassrate=80 where name='趙聿修紀念中學' and categoryid=2;
update entity set hkdsepassrate=38 where name='路德會呂祥光中學' and categoryid=2;
update entity set hkdsepassrate=70 where name='南亞路德會沐恩中學' and categoryid=2;
update entity set urate=39.17 where name='東華三院辛亥年總理中學' and categoryid=2;
update entity set hkdsepassrate=96.3 where name='迦密主恩中學' and categoryid=2;
update entity set hkdsepassrate=93.1 where name='迦密柏雨中學' and categoryid=2;
update entity set hkdsepassrate=14.9 where name='迦密聖道中學' and categoryid=2;
update entity set hkdsepassrate=6.1 where name='東華三院邱金元中學' and categoryid=2;
update entity set hkdsepassrate=91.3, urate=86.96 where name='新界鄉議局元朗區中學' and categoryid=2;
update entity set urate=25 where name='元朗公立中學校友會鄧兆棠中學' and categoryid=2;
update entity set hkdsepassrate=97.3, urate=96.6 where name='香港道教聯合會鄧顯紀念中學' and categoryid=2;
update entity set hkdsepassrate=20 where name='順德聯誼總會鄭裕彤中學' and categoryid=2;
update entity set hkdsepassrate=52 where name='金文泰中學' and categoryid=2;
update entity set hkdsepassrate=90.2, urate=63.41 where name='中華基督教會銘賢書院' and categoryid=2;
update entity set hkdsepassrate=15 where name='長洲官立中學' and categoryid=2;
update entity set urate=73.2 where name='東華三院陳兆民中學' and categoryid=2;
update entity set hkdsepassrate=56.1 where name='陳瑞祺（喇沙）書院' and categoryid=2;
update entity set urate=68.8 where name='香港九龍塘基督教中華宣道會陳瑞芝紀念中學' and categoryid=2;
update entity set hkdsepassrate=30 where name='中華基督教青年會中學' and categoryid=2;
update entity set hkdsepassrate=30.9 where name='青年會書院' and categoryid=2;
update entity set hkdsepassrate=61.4 where name='保良局馬錦明夫人章馥仙中學' and categoryid=2;
update entity set hkdsepassrate=81.5, urate=72.3 where name='順利天主教中學' and categoryid=2;
update entity set hkdsepassrate=75.6 where name='風采中學（教育評議會主辦）' and categoryid=2;
update entity set hkdsepassrate=45.8 where name='香島中學' and categoryid=2;
update entity set hkdsepassrate=28.4, urate=12.8 where name='香港仔浸信會呂明才書院' and categoryid=2;
update entity set hkdsepassrate=73.2 where name='香港培道中學' and categoryid=2;
update entity set hkdsepassrate=97.2 where name='香港真光中學' and categoryid=2;
update entity set hkdsepassrate=51 where name='香港鄧鏡波書院' and categoryid=2;
update entity set hkdsepassrate=84 where name='馬錦明慈善基金馬可賓紀念中學' and categoryid=2;
update entity set hkdsepassrate=53.1, urate=47.79 where name='保良局馬錦明中學' and categoryid=2;
update entity set hkdsepassrate=45.1 where name='馬鞍山崇真中學' and categoryid=2;
update entity set hkdsepassrate=24 where name='東華三院馮黃鳳亭中學' and categoryid=2;
update entity set hkdsepassrate=45.7 where name='鳳溪廖萬石堂中學' and categoryid=2;
update entity set hkdsepassrate=71.9 where name='東華三院黃笏南中學' and categoryid=2;

update entityscore es, entity e set es.hkdsepassrate=e.hkdsepassrate,es.chipassrate=e.chipassrate,es.engpassrate=e.engpassrate,es.urate=e.urate where es.entityid=e.id and es.year=2018 and e.categoryid in (2,5) ;
