update entity set speechfirst=0, speechsecond=0, speechthird=0;

update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('A.D.&F.D. of Pok Oi Hospital Mrs. Cheng Yam On Millennium Sch.') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('A.D. & F.D. of Pok Oi Hospital Mrs Cheng Yam On School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Alliance Primary School, Whampoa') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Baptist (STW) Lui Ming Choi Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Baptist Lui Ming Choi Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+2 where lower(nameeng) = lower('Belilios Public School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Bishop Paschang Catholic School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Bishop Walsh Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Buddhist Chan Wing Kan Memorial School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Buddhist Sum Heung Lam Memorial College') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Buddhist Wing Yan School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Buddhist Wong Cheuk Um Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Buddhist Wong Fung Ling College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Christian & Missionary Alliance Sun Kei Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('C.C.C. Hoh Fuk Tong Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Canossa Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Canossa School (Hong Kong)') and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Carmel Divine Grace Foundation Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1 where lower(nameeng) = lower('Carmel Holy Word Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Carmel Pak U Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Castle Peak Catholic Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Catholic Mission School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('CCC Fong Yun Wah Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('C.C.C. Heep Woh Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('CCC Kei San Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('C.C.C. Kei Wai Primary School (Ma Wan)') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('CCC Kwei Wah Shan College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Chai Wan Kok Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Cheung Chau Government Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+4,speechthird=speechthird+1 where lower(nameeng) = lower('Cheung Sha Wan Catholic Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Chinese YMCA Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('Ching Chung Hau Po Woon Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Ching Chung Hau Po Woon Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Chiu Lut Sau Memorial Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Cho Yiu Catholic Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Christ College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('C.&M.A. Chui Chak Lam Memorial School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Christian Alliance Cheng Wing Gee College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Christian Alliance H.C. Chan Primary School') and categoryid=1;
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('CNEC Christian College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('CUHKFAA Chan Chun Ha Secondary School') and categoryid=2;
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('Delia Memorial School (Hip Wo)') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Diocesan Boys'' School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Diocesan Boys'' School Primary Division') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Diocesan Girls'' Junior School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Diocesan Girls'' School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Daughters of Mary Help of Christians Siu Ming Catholic Secondary School') and categoryid=2;
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('Dr. Catherine F. Woo Memorial School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('ELCHK Lutheran Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Fanling Government Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Fanling Kau Yan College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Fanling Lutheran Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Fanling Rhenish Church Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('F.M.B. Chun Lei Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('French International School') and categoryid=5;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('F.S.F.T.F. Fong Shu Chuen Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+1,speechthird=speechthird+2 where lower(nameeng) = lower('Fukien Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Fukien Secondary School (Siu Sai Wan)') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Fung Kai Innovative School') and categoryid=1;
update entity set speechfirst=speechfirst+5,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Good Hope School') and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+3 where lower(nameeng) = lower('Heep Yunn School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Heung To Middle School (Tin Shui Wai)') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('HHCKLA Buddhist Wong Cho Sum School') and categoryid=1;
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('HKBUAS Wong Kam Fai Secondary and Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('HKFEW Wong Cho Bau Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('HKFYG Lee Shau Kee College') and categoryid=2;
update entity set speechfirst=speechfirst+3,speechthird=speechthird+4 where lower(nameeng) = lower('HKMA David Li Kwok Po College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Hong Kong Taoist Association The Yuen Yuen Institute No. 2 Secondary Sch.') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('HKWMA Chu Shek Lun Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Hoi Pa Street Government Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('Hoi Ping Chamber of Commerce Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Holy Family Canossian College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Holy Family Canossian School') and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1 where lower(nameeng) = lower('Holy Trinity College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Holy Trinity Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Hong Kong Baptist Convention Primary School') and categoryid=1;
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('Hong Kong Tang King Po College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Hong Kong True Light College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Immaculate Heart of Mary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Island School') and categoryid=5;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Ka Ling School of The Precious Blood') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Kam Tsin Village Ho Tung School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Kiangsu & Chekiang Primary School (W.D.)') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('King Lam Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('King Ling College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('King''s College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Kowloon City Baptist Church Hay Nien Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Kowloon Tong Government Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Kwong Ming Ying Loi School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Kwun Tong Maryknoll College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('La Salle College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Laichikok Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Lam Tin Methodist Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Law Ting Pong Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Lee Kau Yan Memorial School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Li Po Chun United World College of Hong Kong') and categoryid=5;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+2 where lower(nameeng) = lower('Lingnan Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Lok Sin Tong Lau Tak Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Lok Sin Tong Leung Chik Wai Memorial School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Lok Sin Tong Leung Kau Kui Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('L.S.T. Yeung Chung Ming Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Lui Cheung Kwong Lutheran College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Ma On Shan St. Joseph''s Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Ma On Shan Tsung Tsin Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('Madam Lau Kam Lung Sec School of Miu Fat Buddhist Monastery') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Maryknoll Convent School (Secondary Section)') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('NT Heung Yee Kuk Yuen Long District Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+2 where lower(nameeng) = lower('Ng Wah Catholic Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Ning Po No. 2 College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('North Point Government Primary School (Cloud View Road)') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('North Point Methodist Primary School (A.M.)') and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Our Lady of The Rosary College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Pentecostal Lam Hon Kwong School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Pentecostal Yu Leung Fat Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Ping Shek Estate Catholic Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Po Leung Kuk Centenary Li Shiu Chung Memorial College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Po Leung Kuk Hong Kong Taoist Association Yuen Yuen Pri. Sch.') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('Po Leung Kuk Lee Shing Pik College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('PLK Mrs. Ma Kam Ming-Cheung Fook Sien College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Po Kok Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('P.L.K. Camões Tan Siu Lin Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Po Leung Kuk Castar Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('P.L.K. Chong Kee Ting Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('P.L.K. Leung Chow Shun Kam Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('PLK Ngan Po Ling College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('P.O.C.A. Wan Ho Kan Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('Po On Commercial Association Wong Siu Ching Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('POH 80th Anniversary Tang Ying Hei College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Pope Paul VI College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+2 where lower(nameeng) = lower('Pui Ching Middle School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Pui Kiu Middle School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+2 where lower(nameeng) = lower('Raimondi College') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+2 where lower(nameeng) = lower('SKH Bishop Baker Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1 where lower(nameeng) = lower('Sacred Heart Canossian College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Sacred Heart Canossian School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Sacred Heart Canossian School Private Section') and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1 where lower(nameeng) = lower('Salesians of Don Bosco Ng Siu Mui Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Sha Tin Government Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Shak Chung Shan Memorial Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Sham Tseng Catholic Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Shek Lei Catholic Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('STFA Cheng Yu Tung Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+4,speechsecond=speechsecond+6,speechthird=speechthird+7 where lower(nameeng) = lower('Shung Tak Catholic English College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Si Yuan School of The Precious Blood') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Sing Yin Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('S.K.H. Chai Wan St. Michael''s Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Chi Fu Chi Nam Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Chu Yan Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('S.K.H. Good Shepherd Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. Ka Fuk Wing Chun Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('S.K.H. Kei Hin Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Kei Wing Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+2 where lower(nameeng) = lower('SKH Lam Woo Memorial Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. Ling Oi Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Lui Ming Choi Memorial Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. Mung Yan Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Tak Tin Lee Shiu Keung Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Tin Wan Chi Nam Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Tsing Yi Chu Yan Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. Yan Laap Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Yuen Chen Maun Chen Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Clare''s Girls'' School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Francis'' Canossian College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Francis of Assisi''s Caritas School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('St. Francis of Assisi''s College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Joan of Arc Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('St. Louis School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Margaret''s Co-edu English Secondary & Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Margaret''s Co-Educational English Secondary and Primary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('St. Mark''s School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('St. Mary''s Canossian College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Paul''s Co-educational College Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Paul''s College Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+8,speechsecond=speechsecond+9,speechthird=speechthird+6 where lower(nameeng) = lower('St. Paul''s Convent School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('St. Paul''s Convent School (Primary Section)') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('St. Paul''s Primary Catholic School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+3 where lower(nameeng) = lower('St. Paul''s School (Lam Tin)') and categoryid=2;
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('St. Paul''s Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Peter''s Catholic Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Rose of Lima''s College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('St. Rose of Lima''s School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Stephen''s Church College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Stephen''s Girls'' College') and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('St. Teresa Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('Stewards Pooi Tun Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('S.T.F.A. Ho Yat Tung Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('STFA Lee Kam Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Shun Tak Fraternal Association Lee Shau Kee College') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+2 where lower(nameeng) = lower('Shun Tak Fraternal Association Leung Kau Kui College') and categoryid=2;
update entity set speechfirst=speechfirst+5,speechsecond=speechsecond+1,speechthird=speechthird+3 where lower(nameeng) = lower('Shun Tak Fraternal Association Yung Yau College') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('HKKKWA Sun Fong Chung Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Tai Kok Tsui Catholic Primary School') and categoryid=1;
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('Tai Po Sam Yuk Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Tak Nga Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Tak Oi Secondary School') and categoryid=2;
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('Tak Sun School') and categoryid=1;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Tang Shiu Kin Victoria Government Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Taoist Ching Chung Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Taoist Ching Chung Primary School (Wu King Estate)') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('The Chinese Foundation Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('CCC Fung Leung Kit Memorial Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('The Endeavourers Leung Lee Sau Yu Memorial Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('The ELCHK Yuen Long Lutheran Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('The Hong Kong Taoist Association Ching Chung Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('The Methodist Church HK Wesley College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('The Salvation Army Lam Butt Chung Memorial School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Tin Ka Ping Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Tin Shui Wai Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Toi Shan Association College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('True Light Girls'' College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Tsuen Wan Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Tsuen Wan Trade Association Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('TWGHs Chen Zao Men College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('T.W.G.Hs. Chow Yin Sum Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('T.W.G.Hs. H.K. & KLN. E.A.M.A. Ltd. School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('TWGHs Hok Shan School') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('TWGHs Lee Ching Dea Memorial College') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+1 where lower(nameeng) = lower('TWGHs Lui Yun Choy Memorial College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('T.W.G.Hs Ma Kam Chan Memorial Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('T.W.G.Hs Sin Chu Wan Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('TWGHs Sun Hoi Directors'' College') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('TWGHs Wong Fut Nam College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Tsz Wan Shan St Bonaventure Catholic Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+2 where lower(nameeng) = lower('Wah Yan College Kowloon') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Wah Yan College Hong Kong') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Workers'' Children Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Yan Chai Hospital No. 2 Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Yan Chai Hospital Wong Wha San Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Yan Tak Catholic Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Yaumati Catholic Primary School (Hoi Wang Road)') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Ying Wa College') and categoryid=2;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Ying Wa Girls'' School') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Ying Wa Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Y.L. Long Ping Estate Tung Koon Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Y.L. Long Ping Estate Wai Chow School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('YLPMSAA Tang Siu Tong Secondary School') and categoryid=2;
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('Yu Chun Keung Memorial College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Yuen Long Merchants Association Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Y.L. Public Middle School Alumni Association Primary School') and categoryid=1;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Buddhist Lam Bing Yim Memorial School(SPSD by HKBA)') and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1 where lower(nameeng) = lower('The ELCHK Yuen Long Lutheran Secondary School') and categoryid=2;
update entity set speechthird=speechthird+1 where name = '九龍婦女福利會李炳紀念學校' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '九龍塘官立小學' and categoryid=1;
update entity set speechfirst=speechfirst+2 where name = '九龍塘宣道小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '十八鄉鄉事委員會公益社小學' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '上水宣道小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '大角嘴天主教小學' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '大角嘴天主教小學（海帆道）' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '中西區聖安多尼學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '中華基督教會何福堂書院' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '中華基督教會基協中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '中華基督教會基法小學（油塘）' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '中華基督教會基華小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '中華傳道會安柱中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '五旬節靳茂生小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '五育中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '五邑工商總會學校' and categoryid=1;
update entity set speechfirst=speechfirst+2 where name = '五邑鄒振猷學校' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '仁愛堂田家炳小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '仁濟醫院靚次伯紀念中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '元朗公立中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '元朗公立中學校友會鄧兆棠中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '元朗官立小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '元朗朗屏邨惠州學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '天水圍香島中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '天主教母佑會蕭明中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '天主教石鐘山紀念小學' and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1 where name = '天主教伍華中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '天主教明德學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '天主教崇德英文書院' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '天主教善導小學' and categoryid=1;
update entity set speechthird=speechthird+2 where name = '屯門官立小學' and categoryid=1;
update entity set speechthird=speechthird+4 where name = '方樹福堂基金方樹泉小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '王肇枝中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '北角循道學校' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '弘立書院' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '民生書院小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '石湖墟公立學校' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '石籬天主教小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '伊利沙伯中學舊生會小學分校' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '伊利沙伯中學舊生會中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '伊斯蘭學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '光明英來學校' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '光明學校' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '佛教中華康山學校' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '佛教何南金中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '佛教沈香林紀念中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '佛教林炳炎紀念學校（香港佛教聯合會主辦）' and categoryid=1;
update entity set speechthird=speechthird+2 where name = '佛教茂峰法師紀念中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '佛教善德英文中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '佛教榮茵學校' and categoryid=1;
update entity set speechfirst=speechfirst+5,speechsecond=speechsecond+6,speechthird=speechthird+1 where name = '妙法寺劉金龍中學' and categoryid=2;
update entity set speechfirst=speechfirst+2 where name = '庇理羅士女子中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '李志達紀念學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '沙田崇真學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '沙田圍胡素貞博士紀念學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '沙田循道衛理小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '秀茂坪天主教小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '和富慈善基金李宗德小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '拔萃男書院附屬小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '東涌天主教學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '東莞工商總會劉百樂中學' and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '東華三院呂潤財紀念中學' and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '東華三院李嘉誠中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '東華三院李賜豪小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '東華三院冼次雲小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '東華三院邱金元中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '東華三院馬錦燦紀念小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '東華三院高可寧紀念小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '東華三院張明添中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '東華三院郭一葦中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '東華三院陳兆民中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '東華三院黃笏南中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '東華三院羅裕積小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '油蔴地天主教小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '油蔴地天主教小學（海泓道）' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '玫瑰崗學校' and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '青松侯寶垣小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '青松侯寶垣中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '保良局王賜豪（田心谷）小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '保良局世德小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '保良局何壽南小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '保良局志豪小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '保良局李城璧中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '保良局雨川小學' and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '保良局香港道教聯合會圓玄小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '保良局馬錦明夫人章馥仙中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '保良局梁周順琴小學' and categoryid=1;
update entity set speechthird=speechthird+2 where name = '保良局莊啟程小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '保良局陳守仁小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '保良局馮晴紀念小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '保良局蔡繼有學校' and categoryid=1;
update entity set speechfirst=speechfirst+2 where name = '保良局顏寶鈴書院' and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '保良局羅傑承（一九八三）中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '香港九龍塘基督教中華宣道會台山陳元喜小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '香港九龍塘基督教中華宣道會陳元喜小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '香港九龍塘基督教中華宣道會陳瑞芝紀念中學' and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '宣道會葉紹蔭紀念小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '皇仁書院' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '皇仁舊生會中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '胡素貞博士紀念學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '英皇書院' and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '英華女學校' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '英華小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '英華書院' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '迦密主恩中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '迦密柏雨中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '迦密唐賓南紀念中學' and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where name = '香島中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '香海正覺蓮社佛教正慧小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '香海正覺蓮社佛教梁植偉中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '香港中文大學校友會聯會張煊昌學校' and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1,speechthird=speechthird+2 where name = '香港中文大學校友會聯會陳震夏中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '香港仔聖伯多祿天主教小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '香港青年協會李兆基小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '香港浸信會聯會小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '香港浸會大學附屬學校王錦輝中小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '香港浸會大學附屬學校王錦輝中小學' and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '香港培正小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '香港教育工作者聯會黃楚標學校' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '香港教育學院賽馬會小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '香港普通話研習社科技創意小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '香港華人基督教聯會真道書院' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '香港華仁書院' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '香港道教聯合會圓玄學院第二中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '香港道教聯合會圓玄學院陳呂重德紀念學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '香港嘉諾撒學校' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '香港潮陽小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '香港鄧鏡波書院' and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '港九街坊婦女會孫方中小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '旅港開平商會學校' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '柴灣角天主教小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '海壩街官立小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '浸信宣道會呂明才小學' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '浸信會呂明才小學' and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1 where name = '浸信會沙田圍呂明才小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '祖堯天主教小學' and categoryid=1;
update entity set speechthird=speechthird+2 where name = '神召會康樂中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '粉嶺救恩書院' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '粉嶺禮賢會中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '荃灣官立小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '荃灣官立中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '荔枝角天主教小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '荔景天主教中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '軒尼詩道官立小學（下午）' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '馬鞍山循道衛理小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '馬鞍山聖若瑟小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '高主教書院小學部' and categoryid=1;
update entity set speechthird=speechthird+2 where name = '培僑小學' and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+7 where name = '培僑中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '培僑書院' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '培僑書院' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '基督教女青年會丘佐榮中學' and categoryid=2;
update entity set speechfirst=speechfirst+2 where name = '基督教宣道會宣基中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '基督教宣道會徐澤林紀念小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '基督教香港信義會心誠中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '基督教香港信義會深信學校' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '基督教香港信義會葵盛信義學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '將軍澳天主教小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '將軍澳官立小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '將軍澳官立中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '將軍澳香島中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '將軍澳循道衛理小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '崇真小學暨幼稚園' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '梨木樹天主教小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '陳瑞祺（喇沙）小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '勞工子弟中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '博愛醫院歷屆總理聯誼會鄭任安夫人千禧小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '循理會白普理基金循理小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '景嶺書院' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '曾梅千禧學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '棉紡會中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '港九潮州公會中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '港大同學會小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '順利天主教中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '順德聯誼總會何日東小學' and categoryid=1;
update entity set speechthird=speechthird+2 where name = '順德聯誼總會李金小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '順德聯誼總會胡少渠紀念小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '順德聯誼總會胡兆熾中學' and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+3 where name = '順德聯誼總會翁祐中學' and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '黃埔宣道小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '慈幼葉漢千禧小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '新加坡國際學校' and categoryid=5;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '新生命教育協會平安福音中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '新界婦孺福利會梁省德學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+4 where name = '新界鄉議局元朗區中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '筲箕灣官立中學' and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '筲箕灣崇真學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '聖士提反女子中學附屬小學' and categoryid=1;
update entity set speechfirst=speechfirst+2 where name = '聖公會仁立小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖公會仁立紀念小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖公會主風小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖公會主恩小學' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '聖公會主愛小學（梨木樹）' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖公會李福慶中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '聖公會阮鄭夢芹小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖公會奉基千禧小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖公會林裘謀中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '聖公會林護紀念中學' and categoryid=2;
update entity set speechthird=speechthird+2 where name = '聖公會青衣主恩小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '聖公會青衣邨何澤芸小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖公會馬鞍山主風小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖公會基愛小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖公會基福小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖公會基顯小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖公會梁季彜中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '聖公會陳融中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '聖公會置富始南小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖公會聖米迦勒小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖公會聖彼得小學(下午)' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖公會聖馬太小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '聖公會聖馬利亞堂莫慶堯中學' and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '聖公會嘉福榮真小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖公會榮真小學' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '聖公會蒙恩小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖公會德田李兆強小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖公會聖約瑟小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖方濟各英文小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖方濟愛德小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖母玫瑰書院' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '聖母無玷聖心學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖伯多祿天主教小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖言中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '聖保祿中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '聖保祿天主教小學' and categoryid=1;
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+1,speechthird=speechthird+4 where name = '聖保祿學校' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '聖保羅男女中學附屬小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖保羅書院小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖若瑟英文書院' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '聖馬可中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '聖愛德華天主教小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '聖嘉勒小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '聖瑪加利男女英文中小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖羅撒書院' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '裘錦秋中學（葵涌）' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '路德會呂明才中學' and categoryid=2;
update entity set speechfirst=speechfirst+2 where name = '路德會呂祥光中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '路德會協同中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '路德會梁鉅鏐小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '路德會聖馬太學校（秀茂坪）' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '道教青松小學（湖景邨）' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '僑港伍氏宗親會伍時暢紀念學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '嘉諾撒小學（新蒲崗）' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '嘉諾撒書院' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '嘉諾撒聖家學校' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '嘉諾撒聖瑪利學校' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '漢華中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '瑪利諾修院學校（中學部）' and categoryid=2;
update entity set speechthird=speechthird+2 where name = '趙聿修紀念中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '閩僑小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '鳳溪創新小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '鳳溪廖潤琛紀念學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '德信學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '德望學校' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '播道書院' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '樂善堂梁植偉紀念中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '樂善堂楊葛小琳中學' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '潮陽百欣小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '衛理中學' and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '優才（楊殷有娣）書院' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '優才（楊殷有娣）書院' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '勵志會梁李秀娛紀念小學' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '嶺南鍾榮光博士紀念中學' and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '藍田循道衛理小學' and categoryid=1;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+2 where name = '藍田聖保祿中學' and categoryid=2;
update entity set speechfirst=speechfirst+2 where name = '寶血女子中學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '寶血會伍季明紀念學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '蘇浙小學（全日）' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '蘇浙公學' and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1 where name = '靈糧堂怡文中學' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '觀塘官立中學' and categoryid=2;


update entityscore es, entity e set es.speechfirst=e.speechfirst,es.speechsecond=e.speechsecond,es.speechthird=e.speechthird where es.entityid=e.id and es.year=2014;







