update entity set musicfirst=0, musicsecond=0, musicthird=0;

update entity set musicfirst=1,musicsecond=1 where lower(nameeng) = lower('Aberdeen St. Peter''s Catholic Primary School') and categoryid=1;
update entity set musicsecond=4 where lower(nameeng) = lower('Alliance Primary School, Kowloon Tong') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('Baptist Lui Ming Choi Primary School') and categoryid=1;
update entity set musicsecond=1,musicthird=1 where lower(nameeng) = lower('Baptist Lui Ming Choi Secondary School') and categoryid=2;
update entity set musicsecond=1,musicthird=2 where lower(nameeng) = lower('Belilios Public School') and categoryid=2;
update entity set musicfirst=2,musicsecond=1 where lower(nameeng) = lower('Bishop Hall Jubilee School') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('Bonham Road Government Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('Christian & Missionary Alliance Sun Kei Secondary School') and categoryid=2;
update entity set musicsecond=1,musicthird=1 where lower(nameeng) = lower('Canossa Primary School') and categoryid=1;
update entity set musicfirst=1,musicsecond=3 where lower(nameeng) = lower('Carmel Pak U Secondary School') and categoryid=2;
update entity set musicfirst=1 where lower(nameeng) = lower('C.C.C. Heep Woh Primary School') and categoryid=1;
update entity set musicsecond=1,musicthird=2 where lower(nameeng) = lower('CCC Kei Chun Primary School') and categoryid=1;
update entity set musicfirst=5 where lower(nameeng) = lower('C.C.C. Kei Wai Primary School (Ma Wan)') and categoryid=1;
update entity set musicfirst=2,musicsecond=2 where lower(nameeng) = lower('C.C.C. Kei Wan Primary School (Aldrich Bay)') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('C.C.C. Mong Wong Far Yok Memorial Primary School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Chinese Methodist School (North Point)') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Chiu Lut Sau Memorial Secondary School') and categoryid=2;
update entity set musicsecond=1 where lower(nameeng) = lower('Chiu Yang Por Yen Primary School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Chiu Yang Primary School of Hong Kong') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('Cho Yiu Catholic Primary School') and categoryid=1;
update entity set musicsecond=2 where lower(nameeng) = lower('Christian Alliance S. C. Chan Memorial College') and categoryid=2;
update entity set musicfirst=7,musicsecond=6,musicthird=2 where lower(nameeng) = lower('Diocesan Boys'' School') and categoryid=2;
update entity set musicfirst=4,musicthird=3 where lower(nameeng) = lower('Diocesan Boys'' School Primary Division') and categoryid=1;
update entity set musicfirst=1,musicsecond=2,musicthird=1 where lower(nameeng) = lower('Diocesan Girls'' Junior School') and categoryid=1;
update entity set musicfirst=2,musicsecond=4,musicthird=5 where lower(nameeng) = lower('Diocesan Girls'' School') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('Daughters of Mary Help of Christians Siu Ming Catholic Secondary School') and categoryid=2;
update entity set musicfirst=1 where lower(nameeng) = lower('Dr. Catherine F. Woo Memorial School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Elegantia College (Sponsored by Education Convergence)') and categoryid=2;
update entity set musicthird=2 where lower(nameeng) = lower('Fanling Lutheran Secondary School') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('G.T. (Ellen Yeung) College') and categoryid=1;
update entity set musicthird=2 where lower(nameeng) = lower('Good Hope Primary School cum Kindergarten') and categoryid=1;
update entity set musicfirst=1,musicsecond=1,musicthird=2 where lower(nameeng) = lower('Good Hope School') and categoryid=2;
update entity set musicfirst=1 where lower(nameeng) = lower('Heep Yunn Primary School') and categoryid=1;
update entity set musicfirst=5,musicsecond=1,musicthird=1 where lower(nameeng) = lower('Heep Yunn School') and categoryid=2;
update entity set musicfirst=1 where lower(nameeng) = lower('HKBUAS Wong Kam Fai Secondary and Primary School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('HKBU Affiliated School Wong Kam Fai Secondary & Primary School') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('Hong Kong Taoist Association Tang Hin Memorial Secondary School') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('Hoi Pa Street Government Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Holy Family Canossian College') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('Hong Kong Student Aid Society Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('International Christian Quality Music Sec. and Pri. School') and categoryid=1;
update entity set musicsecond=1,musicthird=1 where lower(nameeng) = lower('Kowloon Tong School (Primary Section)') and categoryid=1;
update entity set musicfirst=1,musicthird=1 where lower(nameeng) = lower('Kwok Tak Seng Catholic Secondary School') and categoryid=2;
update entity set musicfirst=1,musicsecond=1 where lower(nameeng) = lower('La Salle College') and categoryid=2;
update entity set musicfirst=1,musicsecond=2 where lower(nameeng) = lower('La Salle Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('Lee Chi Tat Memorial School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Ma On Shan Ling Liang Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Ma On Shan Methodist Primary School') and categoryid=1;
update entity set musicsecond=1,musicthird=1 where lower(nameeng) = lower('Marymount Primary School') and categoryid=1;
update entity set musicsecond=2 where lower(nameeng) = lower('Marymount Secondary School') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('Methodist School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('North Point Methodist Primary School (A.M.)') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Po Leung Kuk Centenary Li Shiu Chung Memorial College') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('PLK Dr. Jimmy Wong Chi-Ho ( Tin Sum Valley ) Primary School') and categoryid=1;
update entity set musicfirst=1,musicthird=1 where lower(nameeng) = lower('Po Leung Kuk Hong Kong Taoist Association Yuen Yuen Pri. Sch.') and categoryid=1;
update entity set musicfirst=1,musicthird=1 where lower(nameeng) = lower('P.L.K. Camões Tan Siu Lin Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Po Leung Kuk Chee Jing Yin Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Po Leung Kuk Choi Kai Yau School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('P.L.K. Chong Kee Ting Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('P.L.K. Fong Wong Kam Chuen Primary School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Po Leung Kuk Grandmont Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Po Leung Kuk Luk Hing Too Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('Po Leung Kuk Tin Ka Ping Millennium Primary School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Po Leung Kuk Tin Ka Ping Primary School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Po On Commercial Association Wong Siu Ching Secondary School') and categoryid=2;
update entity set musicfirst=1,musicsecond=1 where lower(nameeng) = lower('Pui Kiu College') and categoryid=1;
update entity set musicfirst=1,musicsecond=1 where lower(nameeng) = lower('Queen''s College') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('Raimondi College') and categoryid=2;
update entity set musicfirst=2,musicsecond=1,musicthird=2 where lower(nameeng) = lower('Sacred Heart Canossian College') and categoryid=2;
update entity set musicsecond=1 where lower(nameeng) = lower('Salesian English School') and categoryid=2;
update entity set musicsecond=1 where lower(nameeng) = lower('Shak Chung Shan Memorial Catholic Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Shatin Government Primary School') and categoryid=1;
update entity set musicfirst=2,musicsecond=1,musicthird=2 where lower(nameeng) = lower('Sha Tin Methodist College') and categoryid=2;
update entity set musicsecond=1 where lower(nameeng) = lower('Si Yuan School of The Precious Blood') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('SKH Bishop Mok Sau Tseng Secondary School') and categoryid=2;
update entity set musicfirst=1 where lower(nameeng) = lower('S.K.H. Chu Oi Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('S.K.H. Chu Yan Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('S.K.H. Holy Spirit Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('S.K.H. Ka Fuk Wing Chun Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('S.K.H. Kei Yan Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('SKH Lam Kau Mow Secondary School') and categoryid=2;
update entity set musicfirst=2,musicsecond=3,musicthird=2 where lower(nameeng) = lower('SKH Lam Woo Memorial Secondary School') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('S.K.H. Lui Ming Choi Memorial Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('S.K.H. Ma On Shan Holy Spirit Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('S.K.H. Mung Yan Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('S.K.H. Tin Wan Chi Nam Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('S.K.H. Tsing Yi Chu Yan Primary School') and categoryid=1;
update entity set musicfirst=1,musicthird=1 where lower(nameeng) = lower('S.K.H. Yan Laap Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('St. Bonaventure College & High School') and categoryid=2;
update entity set musicfirst=1,musicsecond=1 where lower(nameeng) = lower('St. Francis'' Canossian College') and categoryid=2;
update entity set musicfirst=1,musicthird=1 where lower(nameeng) = lower('St. Francis Xavier''s College') and categoryid=2;
update entity set musicfirst=2,musicsecond=2 where lower(nameeng) = lower('St. Joseph''s College') and categoryid=2;
update entity set musicfirst=1 where lower(nameeng) = lower('St. Louis School') and categoryid=2;
update entity set musicsecond=1 where lower(nameeng) = lower('St. Patrick''s Catholic Primary School (Po Kong Village Road)') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('St. Paul''s Co-educational College') and categoryid=2;
update entity set musicfirst=4,musicsecond=1,musicthird=1 where lower(nameeng) = lower('St. Paul''s Co-educational College Primary School') and categoryid=1;
update entity set musicsecond=2,musicthird=4 where lower(nameeng) = lower('St. Paul''s College') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('St. Paul''s College Primary School') and categoryid=1;
update entity set musicfirst=2 where lower(nameeng) = lower('St. Paul''s Convent School (Primary Section)') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('St. Paul''s Primary Catholic School') and categoryid=1;
update entity set musicsecond=1,musicthird=3 where lower(nameeng) = lower('St. Stephen''s College Preparatory School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Stewards MKMCF Ma Ko Pan Memorial College') and categoryid=2;
update entity set musicsecond=1 where lower(nameeng) = lower('Stewards Pooi Kei Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('Shun Tak Fraternal Association Tam Pak Yu College') and categoryid=2;
update entity set musicfirst=2 where lower(nameeng) = lower('HKKKWA Sun Fong Chung Primary School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Tai Po Methodist School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Taoist Ching Chung Primary School') and categoryid=1;
update entity set musicfirst=1,musicthird=1 where lower(nameeng) = lower('The ELCHK Yuen Long Lutheran Secondary School') and categoryid=2;
update entity set musicfirst=1 where lower(nameeng) = lower('The Hong Kong Institute of Education Jockey Club Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('S.A. Ann Wyllie Memorial School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('The Salvation Army Lam Butt Chung Memorial School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('The True Light Middle School of Hong Kong (Primary Section)') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('Tin Shui Wai Catholic Primary School') and categoryid=1;
update entity set musicsecond=2 where lower(nameeng) = lower('Tin Shui Wai Government Primary School') and categoryid=1;
update entity set musicsecond=2,musicthird=1 where lower(nameeng) = lower('True Light Girls'' College') and categoryid=2;
update entity set musicsecond=1 where lower(nameeng) = lower('Tseung Kwan O Catholic Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('Tsuen Wan Government Primary School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Tsuen Wan Government Secondary School') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('Tuen Mun Government Primary School') and categoryid=1;
update entity set musicsecond=2,musicthird=1 where lower(nameeng) = lower('T.W.G.Hs. H.K. & KLN. E.A.M.A. Ltd. School') and categoryid=1;
update entity set musicsecond=1 where lower(nameeng) = lower('TWGHs Li Ka Shing College') and categoryid=2;
update entity set musicthird=2 where lower(nameeng) = lower('T.W.G.Hs Ma Kam Chan Memorial Primary School') and categoryid=1;
update entity set musicthird=1 where lower(nameeng) = lower('TWGHs Wong Fut Nam College') and categoryid=2;
update entity set musicthird=1 where lower(nameeng) = lower('United Christian College (Kowloon East)') and categoryid=2;
update entity set musicfirst=1,musicsecond=1 where lower(nameeng) = lower('Wa Ying College') and categoryid=2;
update entity set musicfirst=2,musicsecond=2,musicthird=1 where lower(nameeng) = lower('Wah Yan College Hong Kong') and categoryid=2;
update entity set musicfirst=1,musicsecond=2,musicthird=1 where lower(nameeng) = lower('Wah Yan College Kowloon') and categoryid=2;
update entity set musicfirst=1 where lower(nameeng) = lower('Yaumati Kaifong Association School') and categoryid=1;
update entity set musicfirst=1,musicsecond=1,musicthird=1 where lower(nameeng) = lower('Ying Wa College') and categoryid=2;
update entity set musicfirst=1,musicsecond=1,musicthird=1 where lower(nameeng) = lower('Ying Wa Primary School') and categoryid=1;
update entity set musicfirst=1 where lower(nameeng) = lower('Yuen Long Government Primary School') and categoryid=1;
update entity set musicfirst=1,musicsecond=1 where name = '九龍城浸信會禧年小學' and categoryid=1;
update entity set musicfirst=1,musicsecond=2,musicthird=1 where name = '華仁書院（九龍）' and categoryid=2;
update entity set musicthird=1 where name = '九龍塘天主教華德學校' and categoryid=1;
update entity set musicfirst=1 where name = '九龍塘宣道小學' and categoryid=1;
update entity set musicsecond=2 where name = '九龍塘學校（小學部）' and categoryid=1;
update entity set musicthird=1 where name = '九龍禮賢學校' and categoryid=1;
update entity set musicthird=1 where name = '大坑東宣道小學' and categoryid=1;
update entity set musicthird=1 where name = '大角嘴天主教小學' and categoryid=1;
update entity set musicthird=1 where name = '大埔舊墟公立學校' and categoryid=1;
update entity set musicsecond=1 where name = '中華基督教會全完中學' and categoryid=2;
update entity set musicfirst=1 where name = '中華基督教會協和小學（長沙灣）' and categoryid=1;
update entity set musicsecond=1 where name = '中華基督教會基真小學' and categoryid=1;
update entity set musicfirst=1 where name = '中華基督教會基慧小學（馬灣）' and categoryid=1;
update entity set musicsecond=1,musicthird=1 where name = '中華基督教會基灣小學' and categoryid=1;
update entity set musicthird=3 where name = '中華基督教會基灣小學（愛蝶灣）' and categoryid=1;
update entity set musicthird=1 where name = '五旬節于良發小學' and categoryid=1;
update entity set musicthird=1 where name = '五旬節林漢光中學' and categoryid=2;
update entity set musicthird=1 where name = '元朗公立中學校友會小學' and categoryid=1;
update entity set musicfirst=1 where name = '元朗商會小學' and categoryid=1;
update entity set musicfirst=2 where name = '天水圍天主教小學' and categoryid=1;
update entity set musicfirst=1 where name = '天主教伍華中學' and categoryid=2;
update entity set musicfirst=1 where name = '天神嘉諾撒學校' and categoryid=1;
update entity set musicsecond=1 where name = '屯門官立小學' and categoryid=1;
update entity set musicsecond=1 where name = '北角衛理小學（上午）' and categoryid=1;
update entity set musicthird=1 where name = '民生書院小學' and categoryid=1;
update entity set musicsecond=1 where name = '光明學校' and categoryid=1;
update entity set musicfirst=1,musicsecond=1,musicthird=1 where name = '何明華會督銀禧中學' and categoryid=2;
update entity set musicthird=3 where name = '庇理羅士女子中學' and categoryid=2;
update entity set musicfirst=2,musicthird=2 where name = '李志達紀念學校' and categoryid=1;
update entity set musicsecond=1,musicthird=1 where name = '沙田崇真中學' and categoryid=2;
update entity set musicthird=1 where name = '沙田循道衛理小學' and categoryid=1;
update entity set musicfirst=2,musicsecond=1 where name = '沙田循道衛理中學' and categoryid=2;
update entity set musicfirst=1 where name = '沙田蘇浙公學' and categoryid=2;
update entity set musicsecond=4,musicthird=1 where name = '協恩中學' and categoryid=2;
update entity set musicfirst=1 where name = '協恩中學附屬小學' and categoryid=1;
update entity set musicfirst=2,musicsecond=1 where name = '拔萃女小學 ' and categoryid=1;
update entity set musicfirst=4,musicsecond=4,musicthird=1 where name = '拔萃女書院' and categoryid=2;
update entity set musicfirst=5,musicsecond=1,musicthird=2 where name = '拔萃男書院' and categoryid=2;
update entity set musicfirst=1 where name = '拔萃男書院附屬小學' and categoryid=1;
update entity set musicthird=1 where name = '東華三院李嘉誠中學' and categoryid=2;
update entity set musicsecond=1 where name = '東華三院馬錦燦紀念小學' and categoryid=1;
update entity set musicsecond=1 where name = '保良局方王錦全小學' and categoryid=1;
update entity set musicthird=1 where name = '保良局田家炳小學' and categoryid=1;
update entity set musicfirst=2 where name = '保良局百周年李兆忠紀念中學' and categoryid=2;
update entity set musicthird=1 where name = '保良局馬錦明夫人章馥仙中學' and categoryid=2;
update entity set musicthird=1 where name = '保良局莊啟程第二小學' and categoryid=1;
update entity set musicthird=3 where name = '保良局陳守仁小學' and categoryid=1;
update entity set musicthird=1 where name = '保良局黃永樹小學' and categoryid=1;
update entity set musicfirst=2 where name = '保良局蔡繼有學校' and categoryid=1;
update entity set musicfirst=1 where name = '南元朗官立小學' and categoryid=1;
update entity set musicfirst=1 where name = '南亞路德會沐恩中學' and categoryid=2;
update entity set musicthird=1 where name = '宣道會葉紹蔭紀念小學' and categoryid=1;
update entity set musicfirst=1,musicsecond=1 where name = '皇仁書院' and categoryid=2;
update entity set musicsecond=1 where name = '英華小學' and categoryid=1;
update entity set musicthird=1 where name = '迦密中學' and categoryid=2;
update entity set musicfirst=1,musicsecond=1,musicthird=2 where name = '迦密柏雨中學' and categoryid=2;
update entity set musicthird=1 where name = '迦密唐賓南紀念中學' and categoryid=2;
update entity set musicthird=1 where name = '風采中學（教育評議會主辦）' and categoryid=2;
update entity set musicsecond=1 where name = '香海正覺蓮社佛教正慧小學' and categoryid=1;
update entity set musicfirst=1,musicthird=1 where name = '香港中國婦女會丘佐榮學校' and categoryid=1;
update entity set musicfirst=1 where name = '香港真光中學（小學部）' and categoryid=1;
update entity set musicfirst=1 where name = '香港神託會培基書院' and categoryid=2;
update entity set musicthird=1 where name = '香港培正小學' and categoryid=1;
update entity set musicthird=1 where name = '香港培道小學' and categoryid=1;
update entity set musicthird=1 where name = '香港普通話研習社科技創意小學' and categoryid=1;
update entity set musicsecond=1 where name = '香港道教聯合會鄧顯紀念中學' and categoryid=2;
update entity set musicsecond=1 where name = '香港嘉諾撒學校' and categoryid=1;
update entity set musicfirst=1 where name = '香港潮陽小學' and categoryid=1;
update entity set musicfirst=2 where name = '港九街坊婦女會孫方中小學' and categoryid=1;
update entity set musicfirst=1 where name = '真光女書院' and categoryid=2;
update entity set musicfirst=1 where name = '馬鞍山循道衛理小學' and categoryid=1;
update entity set musicsecond=1,musicthird=1 where name = '馬頭涌官立小學' and categoryid=1;
update entity set musicsecond=1 where name = '培基小學' and categoryid=1;
update entity set musicfirst=1,musicsecond=1 where name = '培僑書院' and categoryid=1;
update entity set musicthird=1 where name = '基督教宣道會宣基小學' and categoryid=1;
update entity set musicfirst=1 where name = '基督教宣道會徐澤林紀念小學' and categoryid=1;
update entity set musicthird=1 where name = '基督教香港信義會葵盛信義學校' and categoryid=1;
update entity set musicfirst=1 where name = '救世軍田家炳學校' and categoryid=1;
update entity set musicthird=1 where name = '救世軍韋理夫人紀念學校' and categoryid=1;
update entity set musicthird=1 where name = '深井天主教小學' and categoryid=1;
update entity set musicthird=1 where name = '陳瑞祺（喇沙）小學' and categoryid=1;
update entity set musicfirst=1 where name = '博愛醫院歷屆總理聯誼會鄭任安夫人學校' and categoryid=1;
update entity set musicfirst=1,musicsecond=2 where name = '喇沙小學' and categoryid=1;
update entity set musicsecond=3 where name = '喇沙書院' and categoryid=2;
update entity set musicfirst=2 where name = '循道學校' and categoryid=1;
update entity set musicthird=1 where name = '港澳信義會明道小學' and categoryid=1;
update entity set musicthird=1 where name = '順德聯誼總會李金小學' and categoryid=1;
update entity set musicsecond=1,musicthird=1 where name = '順德聯誼總會胡少渠紀念小學' and categoryid=1;
update entity set musicthird=1 where name = '順德聯誼總會梁銶琚中學' and categoryid=2;
update entity set musicthird=1 where name = '黃埔宣道小學' and categoryid=1;
update entity set musicsecond=1 where name = '慈幼葉漢小學' and categoryid=1;
update entity set musicsecond=1 where name = '新界婦孺福利會梁省德學校' and categoryid=1;
update entity set musicthird=1 where name = '新界鄉議局元朗區中學' and categoryid=2;
update entity set musicsecond=1 where name = '筲箕灣崇真學校' and categoryid=1;
update entity set musicthird=1 where name = '聖三一堂小學' and categoryid=1;
update entity set musicfirst=1 where name = '聖士提反女子中學' and categoryid=2;
update entity set musicfirst=1 where name = '聖士提反書院' and categoryid=2;
update entity set musicsecond=2 where name = '聖士提反書院附屬小學' and categoryid=1;
update entity set musicthird=1 where name = '聖公會九龍灣基樂小學' and categoryid=1;
update entity set musicsecond=1 where name = '聖公會仁立小學' and categoryid=1;
update entity set musicsecond=1,musicthird=1 where name = '聖公會主風小學' and categoryid=1;
update entity set musicsecond=1 where name = '聖公會田灣始南小學' and categoryid=1;
update entity set musicthird=1 where name = '聖公會阮鄭夢芹小學' and categoryid=1;
update entity set musicsecond=2,musicthird=1 where name = '聖公會林裘謀中學' and categoryid=2;
update entity set musicsecond=1,musicthird=5 where name = '聖公會林護紀念中學' and categoryid=2;
update entity set musicsecond=1 where name = '聖公會青衣邨何澤芸小學' and categoryid=1;
update entity set musicthird=1 where name = '聖公會基福小學' and categoryid=1;
update entity set musicsecond=1 where name = '聖公會莫壽增會督中學' and categoryid=2;
update entity set musicsecond=1,musicthird=1 where name = '聖公會曾肇添中學' and categoryid=2;
update entity set musicsecond=1,musicthird=1 where name = '聖公會置富始南小學' and categoryid=1;
update entity set musicsecond=1 where name = '聖公會聖米迦勒小學' and categoryid=1;
update entity set musicsecond=1 where name = '聖公會聖雅各小學' and categoryid=1;
update entity set musicsecond=1 where name = '聖公會嘉福榮真小學' and categoryid=1;
update entity set musicsecond=1,musicthird=1 where name = '聖公會蒙恩小學' and categoryid=1;
update entity set musicsecond=1 where name = '聖公會聖約瑟小學' and categoryid=1;
update entity set musicthird=1 where name = '聖方濟各英文小學' and categoryid=1;
update entity set musicthird=1 where name = '聖保祿學校（小學部）' and categoryid=1;
update entity set musicsecond=1 where name = '聖保羅男女中學' and categoryid=2;
update entity set musicfirst=3 where name = '聖保羅男女中學附屬小學' and categoryid=1;
update entity set musicfirst=1,musicsecond=1 where name = '聖保羅書院' and categoryid=2;
update entity set musicsecond=2 where name = '聖保羅書院小學' and categoryid=1;
update entity set musicsecond=1 where name = '聖若瑟英文書院' and categoryid=2;
update entity set musicthird=1 where name = '聖嘉勒女書院' and categoryid=2;
update entity set musicsecond=1 where name = '聖羅撒書院' and categoryid=2;
update entity set musicthird=1 where name = '路德會聖十架學校' and categoryid=1;
update entity set musicfirst=1 where name = '農圃道官立小學' and categoryid=1;
update entity set musicthird=1 where name = '嘉諾撒書院' and categoryid=2;
update entity set musicfirst=3,musicsecond=1 where name = '嘉諾撒聖心書院' and categoryid=2;
update entity set musicsecond=1 where name = '嘉諾撒聖心學校' and categoryid=1;
update entity set musicthird=1 where name = '嘉諾撒聖家書院' and categoryid=2;
update entity set musicsecond=1 where name = '嘉諾撒聖瑪利書院' and categoryid=2;
update entity set musicsecond=1 where name = '瑪利曼小學' and categoryid=1;
update entity set musicfirst=1,musicsecond=1 where name = '瑪利曼中學' and categoryid=2;
update entity set musicsecond=1 where name = '鳳溪第一小學' and categoryid=1;
update entity set musicthird=1 where name = '德信學校' and categoryid=1;
update entity set musicfirst=1 where name = '德望學校' and categoryid=2;
update entity set musicfirst=1 where name = '德望小學暨幼稚園' and categoryid=1;
update entity set musicsecond=1 where name = '德雅小學' and categoryid=1;
update entity set musicthird=1 where name = '樂善堂梁銶琚學校' and categoryid=1;
update entity set musicsecond=1 where name = '寶血女子中學' and categoryid=2;
update entity set musicsecond=1 where name = '鄧鏡波學校' and categoryid=2;
update entity set musicthird=1 where name = '寶血會培靈學校' and categoryid=1;
update entity set musicfirst=1 where name = '觀塘官立中學' and categoryid=2;


update entityscore es, entity e set es.musicfirst=e.musicfirst,es.musicsecond=e.musicsecond,es.musicthird=e.musicthird where es.entityid=e.id and es.year=2014;
