update entity set musicfirst=0, musicsecond=0, musicthird=0;



update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+3 where lower(nameeng) = lower('Alliance Primary School, Kowloon Tong') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Alliance Primary School, Sheung Shui') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Baptist (STW) Lui Ming Choi Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Baptist Lui Ming Choi Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Bishop Ford Memorial School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Carmel Alison Lam Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Catholic Mission School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('C.C.C. Heep Woh Primary School (Cheung Sha Wan)') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('C.C.C. Kei Wai Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+2 where lower(nameeng) = lower('C.C.C. Kei Wai Primary School (Ma Wan)') and categoryid=1;
update entity set musicsecond=musicsecond+2,musicthird=musicthird+2 where lower(nameeng) = lower('C.C.C. Kei Wan Primary School (Aldrich Bay)') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Chinese Methodist School (North Point)') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('Chiu Yang Primary School of Hong Kong') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Cho Yiu Catholic Primary School') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('Christian Alliance H.C. Chan Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Delia (Man Kiu) English Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+2,musicthird=musicthird+3 where lower(nameeng) = lower('Diocesan Boys'' School Primary Division') and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+2,musicthird=musicthird+2 where lower(nameeng) = lower('Diocesan Girls'' Junior School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Dr. Catherine F. Woo Memorial School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Fuk Wing Street Government Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('G.T. (Ellen Yeung) College') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('G.C.C.I.T.K.D. Cheong Wong Wai Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Good Hope Primary School cum Kindergarten') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where lower(nameeng) = lower('Heep Yunn Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+5,musicthird=musicthird+1 where lower(nameeng) = lower('HKKKWA Sun Fong Chung Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('HKBUAS Wong Kam Fai Secondary and Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('HKTA Wun Tsuen Ng Lai Wo Memorial School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Holy Family Canossian School (Kowloon Tong)') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Hong Kong Student Aid Society Primary School') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('International Christian Quality Music Sec. and Pri. School') and categoryid=1;
update entity set musicsecond=musicsecond+2 where lower(nameeng) = lower('Kowloon Tong School (Primary Section)') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Kwong Ming School') and categoryid=1;
update entity set musicthird=musicthird+3 where lower(nameeng) = lower('La Salle Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Ma On Shan Ling Liang Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Ma On Shan Methodist Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Marymount Primary School') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('Methodist School') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('North Point Methodist Primary School (A.M.)') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('PLK Dr. Jimmy Wong Chi-Ho ( Tin Sum Valley ) Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+3 where lower(nameeng) = lower('Po Leung Kuk Hong Kong Taoist Association Yuen Yuen Pri. Sch.') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Po Leung Kuk Horizon East Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('P.L.K. Camões Tan Siu Lin Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Po Leung Kuk Chan Yat Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Po Leung Kuk Chee Jing Yin Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Po Leung Kuk Choi Kai Yau School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('P.L.K. Chong Kee Ting Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('P.L.K. Fong Wong Kam Chuen Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Po Leung Kuk Luk Hing Too Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Po Leung Kuk Tin Ka Ping Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Pooi To Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Pui Kiu College') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Salesian School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where lower(nameeng) = lower('Shak Chung Shan Memorial Catholic Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Shatin Methodist Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Si Yuan School of The Precious Blood') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('S.K.H. Chu Oi Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('S.K.H. Chu Yan Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('S.K.H. Holy Spirit Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('S.K.H. Ka Fuk Wing Chun Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('S.K.H. Kei Tak Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('S.K.H. Ma On Shan Holy Spirit Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('S.K.H. Mung Yan Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('S.K.H. Tak Tin Lee Shiu Keung Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('S.K.H. Yan Laap Memorial Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('S.K.H. Yan Laap Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('South Yuen Long Government Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('St. Joseph''s Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('St. Patrick''s School') and categoryid=1;
update entity set musicfirst=musicfirst+5,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('St. Paul''s Co-educational College Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('St. Paul''s College Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+3 where lower(nameeng) = lower('St. Stephen''s College Preparatory School') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('St. Stephen''s Girls'' Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Stewards Pooi Kei Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Taoist Ching Chung Primary School (Wu King Estate)') and categoryid=1;
update entity set musicfirst=musicfirst+2 where lower(nameeng) = lower('The Hong Kong Institute of Education Jockey Club Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+2 where lower(nameeng) = lower('Tin Shui Wai Catholic Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where lower(nameeng) = lower('Tin Shui Wai Government Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where lower(nameeng) = lower('Tseung Kwan O Catholic Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Tsuen Wan Government Primary School') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('Tuen Mun Government Primary School') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('T.W.G.Hs. H.K. & KLN. E.A.M.A. Ltd. School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('T.W.G.Hs Ma Kam Chan Memorial Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+4,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Ying Wa Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Y.L. Long Ping Estate Tung Koon Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Yuen Long Government Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '九龍城浸信會禧年小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '九龍塘官立小學' and categoryid=1;
update entity set musicsecond=musicsecond+2 where name = '九龍塘宣道小學' and categoryid=1;
update entity set musicthird=musicthird+2 where name = '九龍塘學校（小學部）' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '九龍禮賢學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '大埔官立小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '大埔舊墟公立學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '大埔舊墟公立學校（寶湖道）' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '中華基督教會基真小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '中華基督教會基慧小學（馬灣）' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '中華基督教會基灣小學' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where name = '中華基督教會基灣小學（愛蝶灣）' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '中華傳道會許大同學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '五旬節于良發小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '仁愛堂田家炳小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '元朗公立中學校友會小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '元朗朗屏邨惠州學校' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '元朗商會小學' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '天水圍天主教小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '天水圍官立小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '天神嘉諾撒學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '屯門官立小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '北角循道學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '民生書院小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '合一堂學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '佛教榮茵學校' and categoryid=1;
update entity set musicfirst=musicfirst+2,musicthird=musicthird+2 where name = '李志達紀念學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '沙田循道衛理小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '協恩中學附屬小學' and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1 where name = '拔萃女小學 ' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '拔萃男書院附屬小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '東涌天主教學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '東華三院王余家潔紀念小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '東華三院李賜豪小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '東華三院馬錦燦紀念小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '油蔴地天主教小學（海泓道）' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '青山天主教小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '保良局方王錦全小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '保良局朱正賢小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '保良局梁周順琴小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '保良局莊啟程第二小學' and categoryid=1;
update entity set musicsecond=musicsecond+2 where name = '保良局陳守仁小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '保良局馮晴紀念小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '保良局黃永樹小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '保良局蔡繼有學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '南元朗官立小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '宣道會葉紹蔭紀念小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '胡素貞博士紀念學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '香海正覺蓮社佛教正慧小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '香港真光中學（小學部）' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '香港培正小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '香港培道小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '香港潮陽小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '荃灣天主教小學' and categoryid=1;
update entity set musicsecond=musicsecond+2 where name = '馬鞍山循道衛理小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '馬鞍山靈糧小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '馬頭涌官立小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '國際基督教優質音樂中學暨小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '培基小學' and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where name = '培僑書院' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '基督教宣道會徐澤林紀念小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '將軍澳循道衛理小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '救世軍韋理夫人紀念學校' and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1 where name = '喇沙小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '循理會白普理基金循理小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '循道學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '曾梅千禧學校' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '港九街坊婦女會孫方中小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '港大同學會小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '港澳信義會明道小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '番禺會所華仁小學' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '順德聯誼總會胡少渠紀念小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '黃大仙天主教小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '黃埔宣道小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '慈幼葉漢小學' and categoryid=1;
update entity set musicthird=musicthird+2 where name = '筲箕灣崇真學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖士提反女子中學附屬小學' and categoryid=1;
update entity set musicsecond=musicsecond+2 where name = '聖士提反書院附屬小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖公會九龍灣基樂小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖公會何澤芸小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '聖公會青衣主恩小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '聖公會青衣邨何澤芸小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '聖公會置富始南小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖公會聖彼得小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖安多尼學校' and categoryid=1;
update entity set musicfirst=musicfirst+3,musicsecond=musicsecond+1 where name = '聖保羅男女中學附屬小學' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where name = '聖保羅書院小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '聖博德學校' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '路德會梁鉅鏐小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '道教青松小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '僑港伍氏宗親會伍時暢紀念學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '嘉諾撒小學（新蒲崗）' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '嘉諾撒聖心學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '嘉諾撒聖家學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '鳳溪第一小學' and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1 where name = '德望小學暨幼稚園' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '優才（楊殷有娣）書院' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '寶血小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '寶血會伍季明紀念學校' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where lower(nameeng) = lower('Baptist Lui Ming Choi Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Belilios Public School') and categoryid=2;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('Bishop Hall Jubilee School') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Christian & Missionary Alliance Sun Kei Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Carmel Pak U Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Chinese Y.M.C.A. Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Chiu Lut Sau Memorial Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Clementi Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+2 where lower(nameeng) = lower('Cognitio College (Kowloon)') and categoryid=2;
update entity set musicfirst=musicfirst+8,musicsecond=musicsecond+6,musicthird=musicthird+6 where lower(nameeng) = lower('Diocesan Boys'' School') and categoryid=2;
update entity set musicfirst=musicfirst+3,musicsecond=musicsecond+9,musicthird=musicthird+3 where lower(nameeng) = lower('Diocesan Girls'' School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+3 where lower(nameeng) = lower('Good Hope School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+3,musicthird=musicthird+1 where lower(nameeng) = lower('Heep Yunn School') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Ho Fung College (Sponsored by Sik Sik Yuen)') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Holy Family Canossian College') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Hong Kong Tang King Po College') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Hotung Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('International Christian Quality Music Sec. and Pri. School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where lower(nameeng) = lower('King''s College') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Kwok Tak Seng Catholic Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+4,musicthird=musicthird+2 where lower(nameeng) = lower('La Salle College') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Law Ting Pong Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Ma On Shan St. Joseph''s Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where lower(nameeng) = lower('Marymount Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+2 where lower(nameeng) = lower('Munsang College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Notre Dame College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Po Leung Kuk Centenary Li Shiu Chung Memorial College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Precious Blood Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Pui Ching Middle School') and categoryid=2;
update entity set musicfirst=musicfirst+3,musicsecond=musicsecond+1,musicthird=musicthird+3 where lower(nameeng) = lower('Queen''s College') and categoryid=2;
update entity set musicfirst=musicfirst+2,musicthird=musicthird+2 where lower(nameeng) = lower('Sacred Heart Canossian College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Salesian English School') and categoryid=2;
update entity set musicfirst=musicfirst+4,musicsecond=musicsecond+1 where lower(nameeng) = lower('Sha Tin Methodist College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Sing Yin Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+2 where lower(nameeng) = lower('S.K.H. Bishop Mok Sau Tseng Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('S.K.H. Lam Kau Mow Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+2,musicthird=musicthird+4 where lower(nameeng) = lower('S.K.H. Lam Woo Memorial Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('S.K.H. Tsang Shiu Tim Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('St. Paul''s College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('St. Bonaventure College & High School') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('St. Catharine''s School For Girls') and categoryid=2;
update entity set musicfirst=musicfirst+2,musicthird=musicthird+1 where lower(nameeng) = lower('St. Francis'' Canossian College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('St. Francis Xavier''s College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('St. Joseph''s Anglo-Chinese School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+2 where lower(nameeng) = lower('St. Joseph''s College') and categoryid=2;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('St. Mark''s School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('St. Mary''s Canossian College') and categoryid=2;
update entity set musicfirst=musicfirst+5,musicsecond=musicsecond+3,musicthird=musicthird+2 where lower(nameeng) = lower('St. Paul''s Co-educational College') and categoryid=2;
update entity set musicfirst=musicfirst+2,musicthird=musicthird+2 where lower(nameeng) = lower('St. Paul''s College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('St. Paul''s Convent School') and categoryid=2;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('St. Stephen''s College') and categoryid=2;
update entity set musicsecond=musicsecond+2,musicthird=musicthird+1 where lower(nameeng) = lower('St. Stephen''s Girls'' College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Stewards Pooi Kei College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('STFA Seaward Woo College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Tak Oi Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('The ELCHK Yuen Long Lutheran Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('The Hong Kong Management Association K. S. Lo College') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('True Light Girls'' College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('True Light Middle School of Hong Kong') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Tsuen Wan Government Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('TWGHs Kap Yan Directors'' College') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where lower(nameeng) = lower('TWGHs Li Ka Shing College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Tung Wah Group of Hospitals Lo Kon Ting Memorial College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('United Christian College (Kowloon East)') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Wa Ying College') and categoryid=2;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('Wah Yan College Hong Kong') and categoryid=2;
update entity set musicfirst=musicfirst+5,musicsecond=musicsecond+3,musicthird=musicthird+2 where lower(nameeng) = lower('Wah Yan College, Kowloon') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Yan Chai Hospital Law Chan Chor Si College') and categoryid=2;
update entity set musicsecond=musicsecond+2,musicthird=musicthird+1 where lower(nameeng) = lower('Ying Wa College') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Yuen Long Merchants Association Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+3 where name = '華仁書院（九龍）' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '中華基督教會全完中學' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where name = '何明華會督銀禧中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '佛教善德英文中學' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '妙法寺劉金龍中學' and categoryid=2;
update entity set musicsecond=musicsecond+2,musicthird=musicthird+1 where name = '庇理羅士女子中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '沙田崇真中學' and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+2 where name = '沙田循道衛理中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '沙田蘇浙公學' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+3 where name = '協恩中學' and categoryid=2;
update entity set musicfirst=musicfirst+4,musicsecond=musicsecond+2,musicthird=musicthird+2 where name = '拔萃女書院' and categoryid=2;
update entity set musicfirst=musicfirst+6,musicthird=musicthird+3 where name = '拔萃男書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '東華三院甲寅年總理中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '保良局百周年李兆忠紀念中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '南亞路德會沐恩中學' and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where name = '皇仁書院' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '英華女學校' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '英華書院' and categoryid=2;
update entity set musicfirst=musicfirst+3,musicsecond=musicsecond+3 where name = '迦密柏雨中學' and categoryid=2;
update entity set musicfirst=musicfirst+2 where name = '風采中學（教育評議會主辦）' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '香港華仁書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '香港道教聯合會鄧顯紀念中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '旅港開平商會中學' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1,musicthird=musicthird+1 where name = '喇沙書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '新界鄉議局元朗區中學' and categoryid=2;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+2 where name = '聖公會林裘謀中學' and categoryid=2;
update entity set musicsecond=musicsecond+2,musicthird=musicthird+1 where name = '聖公會林護紀念中學' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where name = '聖公會曾肇添中學' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '聖保羅男女中學' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+2 where name = '聖保羅書院' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '聖若瑟英文書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '聖嘉勒女書院' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '聖羅撒書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '路德會呂明才中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '路德會協同中學' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '嘉諾撒聖心書院' and categoryid=2;
update entity set musicfirst=musicfirst+2 where name = '嘉諾撒聖家書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '嘉諾撒聖瑪利書院' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '廖寶珊紀念書院' and categoryid=2;
update entity set musicfirst=musicfirst+3 where name = '瑪利曼中學' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '德望學校' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '德蘭中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '觀塘官立中學' and categoryid=2;



update entityscore es, entity e set es.musicfirst=e.musicfirst,es.musicsecond=e.musicsecond,es.musicthird=e.musicthird where es.entityid=e.id and es.year=2015;
