update entity set musicfirst=0, musicsecond=0, musicthird=0;
update entityscore set musicfirst=0, musicsecond=0, musicthird=0 where year=2017;


update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Aberdeen St. Peter''s Catholic Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Alliance Primary School, Kowloon Tong') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Alliance Primary School, Whampoa') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Baptist Lui Ming Choi Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+3 where lower(nameeng) = lower('Belilios Public School') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Bishop Hall Jubilee School') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Bonham Road Government Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+4 where lower(nameeng) = lower('Carmel Pak U Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('C.C.C. Heep Woh Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('C.C.C. Kei Wai Primary School (Ma Wan)') and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('C.C.C. Kei Wan Primary School (Aldrich Bay)') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('Cheung Chuk Shan College') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Chiu Lut Sau Memorial Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Chiu Yang Por Yen Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Christian Alliance Cheng Wing Gee College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Christian Alliance H.C. Chan Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Christian Alliance S. C. Chan Memorial College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Christian Alliance Toi Shan H C Chan Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Chung Sing School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('CNEC Christian College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Cognitio College (Kowloon)') and categoryid=2;
update entity set musicfirst=musicfirst+11,musicsecond=musicsecond+2 where lower(nameeng) = lower('Diocesan Boys'' School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where lower(nameeng) = lower('Diocesan Boys'' School Primary Division') and categoryid=1;
update entity set musicfirst=musicfirst+3,musicsecond=musicsecond+3 where lower(nameeng) = lower('Diocesan Girls'' Junior School') and categoryid=1;
update entity set musicfirst=musicfirst+7,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Diocesan Girls'' School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where lower(nameeng) = lower('Dr. Catherine F. Woo Memorial School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('The ELCHK Faith Lutheran School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Elegantia College (Sponsored by Education Convergence)') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Evangel College') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('G.T. (Ellen Yeung) College') and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Good Hope Primary School cum Kindergarten') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Good Hope School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Heep Yunn Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where lower(nameeng) = lower('Heep Yunn School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Hennessy Road Government Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+3,musicsecond=musicsecond+1 where lower(nameeng) = lower('HKKKWA Sun Fong Chung Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('HKUGA College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Ho Fung College (Sponsored by Sik Sik Yuen)') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Holy Family Canossian College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Hong Kong And Macau Lutheran Church Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Hong Kong Student Aid Society Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Hotung Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('International Christian Quality Music Sec. and Pri. School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Jockey Club Ti-I College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Kowloon Bay St. John The Baptist Catholic Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Kowloon City Baptist Church Hay Nien (Yan Ping) Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Kowloon Tong School (Primary Section)') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+2 where lower(nameeng) = lower('Kwok Tak Seng Catholic Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Kwong Ming School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+2 where lower(nameeng) = lower('La Salle College') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where lower(nameeng) = lower('La Salle Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Law Ting Pong Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Lui Cheung Kwong Lutheran Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Ma On Shan Ling Liang Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Ma On Shan Methodist Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Maryknoll Convent School (Primary Section)') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Marymount Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+2 where lower(nameeng) = lower('Marymount Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Methodist College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Notre Dame College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Pentecostal Gin Mao Sheng Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+4 where lower(nameeng) = lower('Po Leung Kuk Hong Kong Taoist Association Yuen Yuen Pri. Sch.') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('PLK Women''s Welfare Club (WD) Fung Lee Pui Yiu Pri. Sch.') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('P.L.K. Camões Tan Siu Lin Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Po Leung Kuk Castar Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('P.L.K. Chong Kee Ting Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('P.L.K. Fong Wong Kam Chuen Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Po Leung Kuk Grandmont Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Po Leung Kuk Horizon East Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+2 where lower(nameeng) = lower('Po Leung Kuk Lo Kit Sing (1983) College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Po Leung Kuk Luk Hing Too Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Po Leung Kuk Tin Ka Ping Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Po On Commercial Association Wong Siu Ching Secondary School') and categoryid=2;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('Pui Ching Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+2,musicthird=musicthird+1 where lower(nameeng) = lower('Pui Kiu College') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Pun U Association Wah Yan Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+3,musicthird=musicthird+4 where lower(nameeng) = lower('Queen''s College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Raimondi College Primary Section') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('S.K.H. Kei Wing Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+2 where lower(nameeng) = lower('S.K.H. Lam Kau Mow Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+3,musicthird=musicthird+2 where lower(nameeng) = lower('S.K.H. Lam Woo Memorial Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('S.K.H. Tsing Yi Chu Yan Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('S.K.H. Wing Chun Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('S.K.H. Yan Laap Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+2 where lower(nameeng) = lower('Sacred Heart Canossian College') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Sacred Heart Canossian School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Sacred Heart Canossian School, Private Section') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Salesian English School') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Shak Chung Shan Memorial Catholic Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Shak Chung Shan Memorial Catholic Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Shatin Government Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Sha Tin Methodist College') and categoryid=2;
update entity set musicsecond=musicsecond+2 where lower(nameeng) = lower('Shatin Tsung Tsin Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Si Yuan School of The Precious Blood') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where lower(nameeng) = lower('Sing Yin Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+3 where lower(nameeng) = lower('S.K.H. Bishop Mok Sau Tseng Secondary School') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('S.K.H. Chu Oi Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('S.K.H. Chu Yan Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('S.K.H. Holy Spirit Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('S.K.H. Lui Ming Choi Memorial Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('S.K.H. Ma On Shan Holy Spirit Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('South Yuen Long Government Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('S.R.B.C.E.P.S.A. Lee Yat Ngok Memorial School') and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1 where lower(nameeng) = lower('St. Francis'' Canossian College') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('St. Francis Xavier''s College') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('St. Joseph''s College') and categoryid=2;
update entity set musicsecond=musicsecond+2 where lower(nameeng) = lower('St. Joseph''s Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('St. Mark''s School') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('St. Patrick''s Catholic Primary School (Po Kong Village Road)') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('St. Patrick''s School') and categoryid=1;
update entity set musicsecond=musicsecond+2,musicthird=musicthird+1 where lower(nameeng) = lower('St. Paul''s Co-educational College') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+2,musicthird=musicthird+1 where lower(nameeng) = lower('St. Paul''s Co-educational College Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('St. Paul''s College') and categoryid=2;
update entity set musicfirst=musicfirst+2 where lower(nameeng) = lower('St. Paul''s College Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('St. Paul''s Convent School') and categoryid=2;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('St. Paul''s Convent School (Primary Section)') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('St. Paul''s Primary Catholic School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('St. Stephen''s College') and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+3 where lower(nameeng) = lower('St. Stephen''s Girls'' College') and categoryid=2;
update entity set musicsecond=musicsecond+2,musicthird=musicthird+1 where lower(nameeng) = lower('St. Stephen''s Girls'' Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Stewards Pooi Kei College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Ta Ku Ling Ling Ying Public School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where lower(nameeng) = lower('Tai Po Methodist School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Tai Po Old Market Public School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Tak Sun Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Taoist Ching Chung Primary School (Wu King Estate)') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('The Education University of Hong Kong Jockey Club Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('The ELCHK Yuen Long Lutheran Secondary School') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('The True Light Middle School of Hong Kong (Primary Section)') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Tin Shui Wai Catholic Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Tin Shui Wai Government Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('Toi Shan Association Primary School') and categoryid=1;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('True Light Girls'' College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Tseung Kwan O Catholic Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Tsuen Wan Government Secondary School') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Tuen Mun Government Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where lower(nameeng) = lower('T.W.G.Hs. H.K. & KLN. E.A.M.A. Ltd. School') and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+2 where lower(nameeng) = lower('TWGHs Li Ka Shing College') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('T.W.G.Hs Ma Kam Chan Memorial Primary School') and categoryid=1;
update entity set musicsecond=musicsecond+1 where lower(nameeng) = lower('T.W.G.Hs. Yiu Dak Chi Memorial Primary School (Yuen Long)') and categoryid=1;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('United Christian College (Kowloon East)') and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where lower(nameeng) = lower('Wa Ying College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Wah Yan College Hong Kong') and categoryid=2;
update entity set musicsecond=musicsecond+2,musicthird=musicthird+2 where lower(nameeng) = lower('Wah Yan College, Kowloon') and categoryid=2;
update entity set musicfirst=musicfirst+1 where lower(nameeng) = lower('Yaumati Kaifong Association School') and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1,musicthird=musicthird+2 where lower(nameeng) = lower('Ying Wa College') and categoryid=2;
update entity set musicthird=musicthird+1 where lower(nameeng) = lower('Ying Wa Girls'' School') and categoryid=2;
update entity set musicfirst=musicfirst+4,musicsecond=musicsecond+1,musicthird=musicthird+1 where lower(nameeng) = lower('Ying Wa Primary School') and categoryid=1;
update entity set musicthird=musicthird+2 where lower(nameeng) = lower('Yuen Long Government Primary School') and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '九龍城浸信會禧年小學' and categoryid=1;
update entity set musicfirst=musicfirst+2,musicthird=musicthird+3 where name = '華仁書院（九龍）' and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where name = '九龍塘宣道小學' and categoryid=1;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where name = '九龍塘學校（小學部）' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '三水同鄉會禤景榮學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '大埔三育中學' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '大埔官立小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '大埔崇德黃建常紀念學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '中華基督教會全完中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '中華基督教會協和小學（長沙灣）' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '中華基督教會基真小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '中華基督教會基華小學（九龍塘）' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '中華基督教會基慧小學（馬灣）' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '中華基督教會基灣小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '中華基督教會基灣小學（愛蝶灣）' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '五旬節于良發小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '元朗商會小學' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '天水圍天主教小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '天水圍官立小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '天主教崇德英文書院' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '天主教聖母聖心小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '天神嘉諾撒學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '太古小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '北角循道學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '民生書院' and categoryid=2;
update entity set musicfirst=musicfirst+3 where name = '何明華會督銀禧中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '妙法寺劉金龍中學' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+2 where name = '庇理羅士女子中學' and categoryid=2;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1 where name = '李志達紀念學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '沙田官立中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '沙田循道衛理小學' and categoryid=1;
update entity set musicsecond=musicsecond+2,musicthird=musicthird+1 where name = '沙田循道衛理中學' and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+2 where name = '協恩中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '協恩中學附屬小學' and categoryid=1;
update entity set musicfirst=musicfirst+4 where name = '拔萃女小學 ' and categoryid=1;
update entity set musicfirst=musicfirst+4,musicsecond=musicsecond+2,musicthird=musicthird+2 where name = '拔萃女書院' and categoryid=2;
update entity set musicfirst=musicfirst+4,musicsecond=musicsecond+4 where name = '拔萃男書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '拔萃男書院附屬小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '東涌天主教學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '東華三院吳祥川紀念中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '東華三院李東海小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '東華三院李嘉誠中學' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '林村公立黃福鑾紀念學校' and categoryid=1;
update entity set musicthird=musicthird+2 where name = '保良局方王錦全小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '保良局朱正賢小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '保良局百周年李兆忠紀念中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '保良局西區婦女福利會馮李佩瑤小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '保良局雨川小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '保良局馬錦明中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '保良局陳守仁小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '保良局蕭漢森小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '南元朗官立小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '南亞路德會沐恩中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '香港九龍塘基督教中華宣道會陳元喜小學' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '宣道會葉紹蔭紀念小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '柏立基教育學院校友會何壽基學校' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '英皇書院同學會小學第二校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '英華書院' and categoryid=2;
update entity set musicfirst=musicfirst+4,musicthird=musicthird+2 where name = '迦密柏雨中學' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '迦密唐賓南紀念中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '迦密愛禮信小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '風采中學（教育評議會主辦）' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '香港中文大學校友會聯會張煊昌學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '香港浸會大學附屬學校王錦輝中小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '香港真光中學（小學部）' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '香港普通話研習社科技創意小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '香港道教聯合會圓玄學院第二中學' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '香港潮陽小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '旅港開平商會中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '海壩街官立小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '浸信宣道會呂明才小學' and categoryid=1;
update entity set musicthird=musicthird+2 where name = '浸信會呂明才中學' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '真光女書院' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '祖堯天主教小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '粉嶺救恩書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '荔枝角天主教小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '軒尼詩道官立小學（銅鑼灣）' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '馬鞍山循道衛理小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '馬鞍山靈糧小學' and categoryid=1;
update entity set musicthird=musicthird+2 where name = '馬頭涌官立小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '高主教書院小學部' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '高雷中學' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '培僑書院' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '基督教宣道會徐澤林紀念小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '將軍澳天主教小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '將軍澳官立小學' and categoryid=1;
update entity set musicsecond=musicsecond+2 where name = '崇真小學暨幼稚園' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '救世軍韋理夫人紀念學校' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '博愛醫院歷屆總理聯誼會鄭任安夫人千禧小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '博愛醫院歷屆總理聯誼會鄭任安夫人學校' and categoryid=1;
update entity set musicfirst=musicfirst+2 where name = '喇沙小學' and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1 where name = '喇沙書院' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '循理會白普理基金循理小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '曾梅千禧學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '港九街坊婦女會孫方中小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '番禺會所華仁小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '順德聯誼總會翁祐中學' and categoryid=2;
update entity set musicthird=musicthird+2 where name = '順德聯誼總會梁銶琚中學' and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where name = '新界婦孺福利會梁省德學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '新界鄉議局元朗區中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '聖士提反女子中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '聖士提反書院附屬小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '聖公會仁立小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖公會天水圍靈愛小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖公會主風小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '聖公會田灣始南小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖公會何澤芸小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '聖公會林裘謀中學' and categoryid=2;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1,musicthird=musicthird+2 where name = '聖公會林護紀念中學' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '聖公會基榮小學' and categoryid=1;
update entity set musicfirst=musicfirst+1 where name = '聖公會莫壽增會督中學' and categoryid=2;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '聖公會曾肇添中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '聖公會置富始南小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖公會聖米迦勒小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖公會聖彼得小學' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicthird=musicthird+1 where name = '聖保祿學校（小學部）' and categoryid=1;
update entity set musicsecond=musicsecond+3 where name = '聖保羅男女中學' and categoryid=2;
update entity set musicfirst=musicfirst+3 where name = '聖保羅男女中學附屬小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖保羅書院' and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where name = '聖保羅書院小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '聖嘉勒女書院' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '聖羅撒書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '路德會梁鉅鏐小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '農圃道官立小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '道教青松小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '嘉諾撒書院' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '嘉諾撒聖心學校' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '嘉諾撒聖心學校私立部' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '嘉諾撒聖方濟各學校' and categoryid=1;
update entity set musicfirst=musicfirst+1,musicsecond=musicsecond+1 where name = '嘉諾撒聖家書院' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '嘉諾撒聖瑪利書院' and categoryid=2;
update entity set musicthird=musicthird+1 where name = '廖寶珊紀念書院' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '滬江小學' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '瑪利曼小學' and categoryid=1;
update entity set musicthird=musicthird+2 where name = '瑪利曼中學' and categoryid=2;
update entity set musicsecond=musicsecond+1 where name = '瑪利諾修院學校（中學部）' and categoryid=2;
update entity set musicsecond=musicsecond+1,musicthird=musicthird+1 where name = '瑪利諾神父教會學校（小學部）' and categoryid=1;
update entity set musicfirst=musicfirst+2,musicsecond=musicsecond+1,musicthird=musicthird+1 where name = '德望小學暨幼稚園' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '德望學校' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '樂善堂梁銶琚學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '勵志會梁李秀娛紀念小學' and categoryid=1;
update entity set musicthird=musicthird+1 where name = '寶血女子中學' and categoryid=2;
update entity set musicfirst=musicfirst+1 where name = '寶血會思源學校' and categoryid=1;
update entity set musicsecond=musicsecond+1 where name = '觀塘官立中學' and categoryid=2;


update entityscore es, entity e set es.musicfirst=e.musicfirst,es.musicsecond=e.musicsecond,es.musicthird=e.musicthird where es.entityid=e.id and es.year=2017;
