update entity set speechfirst=0, speechsecond=0, speechthird=0;
update entityscore set speechfirst=0, speechsecond=0, speechthird=0 where year=2018;


update entity set speechsecond=speechsecond+2 where name = '中華基督教會何福堂小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '中華基督教會全完第二小學' and categoryid=1;
update entity set speechthird=speechthird+6 where name = '中華基督教會基法小學(油塘)' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '中華基督教會基華小學(九龍塘)' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '中華基督教會蒙黃花沃紀念小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '中華基督教青年會小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '九龍城浸信會禧年(恩平)小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '九龍塘天主教華德學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '九龍塘學校（小學部）' and categoryid=1;
update entity set speechfirst=speechfirst+2 where name = '九龍塘宣道小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '九龍灣聖若翰天主教小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '五旬節于良發小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '五邑鄒振猷學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '仁愛堂田家炳小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '仁濟醫院何式南小學' and categoryid=1;
update entity set speechsecond=speechsecond+4 where name = '仁濟醫院羅陳楚思小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '仁濟醫院蔡衍濤小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '仁濟醫院陳耀星小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '伊利沙伯中學舊生會小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '伊利沙伯中學舊生會小學分校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '佐敦谷聖若瑟天主教小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '佛教林炳炎紀念學校(香港佛教聯合會)' and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '佛教陳榮根紀念學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '保良局世德小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '保良局何壽南小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '保良局志豪小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '保良局林文燦英文小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '保良局梁周順琴小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '保良局王賜豪（田心谷）小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '保良局莊啟程小學' and categoryid=1;
update entity set speechsecond=speechsecond+6 where name = '保良局蔡繼有學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '保良局西區婦女福利會馮李佩瑤小學' and categoryid=1;
update entity set speechsecond=speechsecond+4 where name = '保良局錦泰小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '保良局陳守仁小學' and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+2 where name = '保良局香港道教聯合會圓玄小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where name = '保良局馮晴紀念小學' and categoryid=1;
update entity set speechsecond=speechsecond+4 where name = '僑港伍氏宗親會伍時暢紀念學校' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '光明學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '光明英來學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '勵志會梁李秀娛紀念小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '十八鄉鄉事委員會公益社小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '嘉諾撒培德學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '嘉諾撒小學（新蒲崗）' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '嘉諾撒聖家學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '嘉諾撒聖心學校' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '嘉諾撒聖方濟各學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '嘉諾撒聖瑪利學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '培僑小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '培僑書院(小學部)' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '基督教宣道會徐澤林紀念小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '基督教香港信義會啟信學校' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '基督教香港信義會禾輋信義學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '基督教香港信義會葵盛信義學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '塘尾道官立小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '大埔循道衛理小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '天主教善導小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '天主教石鐘山紀念小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '天水圍天主教小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '天水圍官立小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '香港九龍塘基督教中華宣道會台山陳元喜小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where name = '宣道會葉紹蔭紀念小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '寶安商會溫浩根小學' and categoryid=1;
update entity set speechfirst=speechfirst+2 where name = '寶血會伍季明紀念學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '寶血會嘉靈學校' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '將軍澳官立小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '屯門官立小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '崇真小學暨幼稚園' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '弘立書院' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '德信學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '德望小學暨幼稚園' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '慈幼學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where name = '慈幼葉漢千禧小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '慈幼葉漢小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '慈航學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where name = '拔萃男書院附屬小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '啟思小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '方樹福堂基金方樹泉小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '旅港開平商會學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '曾梅千禧學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '東涌天主教學校(小學)' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '東華三院冼次雲小學' and categoryid=1;
update entity set speechfirst=speechfirst+2 where name = '東華三院李東海小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '東華三院李賜豪小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '東華三院港九電器商聯會小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '東華三院鄧肇堅小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '柏立基教育學院校友會何壽基學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '柴灣角天主教小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '樂善堂梁銶琚學校(分校)' and categoryid=1;
update entity set speechthird=speechthird+6 where name = '民生書院小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '沙田圍胡素貞博士紀念學校' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '沙田崇真學校' and categoryid=1;
update entity set speechfirst=speechfirst+2 where name = '油蔴地天主教小學(海泓道)' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '海壩街官立小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '海怡寶血小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '浸信會呂明才小學' and categoryid=1;
update entity set speechsecond=speechsecond+4 where name = '浸信會沙田圍呂明才小學' and categoryid=1;
update entity set speechthird=speechthird+6 where name = '港九街坊婦女會孫方中小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '港大同學會小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '港澳信義會明道小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '漢華中學(小學部)' and categoryid=1;
update entity set speechthird=speechthird+6 where name = '潮陽百欣小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '瑪利諾修院學校(小學部)' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '白田天主教小學' and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '石湖墟公立學校' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '石籬天主教小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '祖堯天主教小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '筲箕灣崇真學校' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '耀中國際學校(小學部)' and categoryid=1;
update entity set speechthird=speechthird+6 where name = '聖伯多祿天主教小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖保祿學校（小學部）' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖保羅書院小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖保羅男女中學附屬小學' and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '聖公會主恩小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '聖公會主愛小學（梨木樹）' and categoryid=1;
update entity set speechthird=speechthird+6 where name = '聖公會主風小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where name = '聖公會仁立小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '聖公會仁立紀念小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '聖公會呂明才紀念小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where name = '聖公會嘉福榮真小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖公會將軍澳基德小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖公會德田李兆強小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖公會油塘基顯小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '聖公會置富始南小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖公會聖彼得小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖公會聖紀文小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖公會蒙恩小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖公會阮鄭夢芹小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖公會阮鄭夢芹銀禧小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖公會靈愛小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖公會青衣主恩小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖公會青衣邨何澤芸小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where name = '聖公會馬鞍山主風小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖嘉勒小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '聖士提反女子中學附屬小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖士提反書院附屬小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '聖安多尼學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '聖安當小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '聖瑪加利男女英文中小學(小學部)' and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '聖羅撒學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '聖若翰天主教小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '英皇書院同學會小學(第二校)' and categoryid=1;
update entity set speechfirst=speechfirst+2 where name = '英華小學' and categoryid=1;
update entity set speechthird=speechthird+6 where name = '荃灣天主教小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '荃灣官立小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '荔枝角天主教小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '華富邨寶血小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '華德學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '葛量洪校友會黃埔學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '蘇浙小學（全日）' and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '路德會梁鉅鏐小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '路德會聖十架學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '路德會聖馬太學校（秀茂坪）' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '軒尼詩道官立小學' and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '軒尼詩道官立小學(銅鑼灣)' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '道教青松小學' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '道教青松小學（湖景邨）' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '鐘聲學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '閩僑小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '陳瑞祺（喇沙）小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '青松侯寶垣小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '順德聯誼總會何日東小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '順德聯誼總會李金小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '順德聯誼總會胡少渠紀念小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '香海正覺蓮社佛教正覺蓮社學校' and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '香港中國婦女會丘佐榮學校' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '香港中文大學校友會聯會張煊昌學校' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '香港嘉諾撒學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '香港培正小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '香港教育工作者聯會黃楚標學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '香港普通話研習社科技創意小學' and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '香港浸信會聯會小學' and categoryid=1;
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+2 where name = '香港浸會大學附屬學校王錦輝中小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '香港真光中學（小學部）' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '香港道教聯合會純陽小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '香港道教聯合會雲泉學校' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '馬鞍山循道衛理小學' and categoryid=1;
update entity set speechthird=speechthird+3 where name = '馬鞍山聖若瑟小學' and categoryid=1;
update entity set speechsecond=speechsecond+2 where name = '高主教書院小學部' and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Aberdeen St. Peter''s Catholic Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Alliance Primary School Sheung Shui') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Alliance Primary School, Whampoa') and categoryid=1;
update entity set speechfirst=speechfirst+3 where lower(nameeng) = lower('Baptist (Sha Tin Wai) Lui Ming Choi Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('Baptist Lui Ming Choi Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Bishop Ford Memorial School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Buddhist Wing Yan School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('C & M A Sun Kei Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Carmel Leung Sing Tak School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('CCC Heep Woh Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('CCC Kei Wa Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('CCC Kei Wai Primary School (Ma Wan)') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Central & Western District St. Anthony''s School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Chai Wan Kok Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Chan''s Creative School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('Ching Chung Hau Po Woon Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Cho Yiu Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Christian Alliance H.C. Chan Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Christian Alliance Toi Shan H C Chan Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Creative Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('CUHK FAA Thomas Cheung School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Diocesan Boys'' School Primary Division') and categoryid=1;
update entity set speechfirst=speechfirst+4,speechsecond=speechsecond+2,speechthird=speechthird+12 where lower(nameeng) = lower('Diocesan Girls'' Junior School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Dr. Catherine F. Woo Memorial School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Evangel College (Primary Section)') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('FSFTF Fong Shu Chuen Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Fung Kai Innovative School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Good Hope Primary School cum Kindergarten') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('HHCKLA Buddhist Ching Kok Lin Association School') and categoryid=1;
update entity set speechfirst=speechfirst+2,speechthird=speechthird+3 where lower(nameeng) = lower('HK & Kln Kaifong Women''s Asso Sun Fong Chung Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('HK & Macau Lutheran Church Ming Tao Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('HKFEW Wong Cho Bau School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('HKUGA Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Holy Family Canossian School') and categoryid=1;
update entity set speechsecond=speechsecond+4 where lower(nameeng) = lower('Hong Kong Baptist Convention Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Hop Yat Church School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('International Christian Quality Music Secondary & Primary School (Primary)') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Islamic Dharwood Pau Memorial Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Jordan Valley St. Joseph''s Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Ka Ling School of The Precious Blood') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Kiangsu & Chekiang Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('King''s College Old Boys'' Association Primary School (No.2)') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Kowloon Bay St. John The Baptist Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Kowloon Tong School (Primary Section)') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('La Salle Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Laichikok Catholic Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Leung Kui Kau Lutheran Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Lok Sin Tong Lau Tak Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Lok Wah Catholic Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Lui Cheung Kwong Lutheran Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Munsang College Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('North Point Government Primary School (Cloud View Road)') and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+2 where lower(nameeng) = lower('Oblate Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('PLK HK Taoist Association Yuen Yuen Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('PLK Women''s Welfare Club Western District Fung Lee Pui Yiu Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+4 where lower(nameeng) = lower('Po Kok Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('Po Leung Kuk Camoes Tan Siu Lin Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Po Leung Kuk Castar Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Po Leung Kuk Chong Kee Ting Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Po Leung Kuk Lam Man Chan English Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Po Leung Kuk Leung Chow Shun Kam Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Po Leung Kuk Tin Ka Ping Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('Pui Kiu College (Primary Section)') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Pui Kiu Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Pun U Association Wah Yan Primary School PM') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('S.K.H. Kei Fook Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('S.K.H. Kei Wing Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. St. Peter''s Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('S.K.H. Tin Wan Chi Nam Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('S.K.H. Wei Lun Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('S.K.H. Wing Chun Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('S.K.H. Yan Laap Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Sacred Heart Canossian School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Sam Shui Natives Association Huen King Wing School') and categoryid=1;
update entity set speechthird=speechthird+6 where lower(nameeng) = lower('Shak Chung Shan Memorial Catholic Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Shap Pat Heung Rural Committee Kung Yik She Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Shatin Tsung Tsin School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Shek Wu Hui Public School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Si Yuan School of The Precious Blood') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('SKH Chai Wan St. Michael''s Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('SKH Chi Fu Chi Nam Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('SKH Ka Fuk Wing Chun Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('SKH Ma On Shan Holy Spirit Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('SKH Mung Yan Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('SKH St. Michael''s Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('SKH Tsing Yi Estate Ho Chak Wan Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('SKH Yuen Chen Maun Chen Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('St. Francis'' Canossian School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('St. Margaret''s Co-educational English Secondary & Primary School (Primary Section)') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('St. Paul''s Co-educational College Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('St. Paul''s College Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Paul''s Convent School, Primary Section') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('St. Paul''s Primary Catholic School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Rose of Lima''s School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('St. Stephen''s College Preparatory School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('STFA Ho Yat Tung Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('STFA Lee Kam Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Tai Kok Tsui Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Tai Po Government Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Taoist Ching Chung Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Taoist Ching Chung Primary School (Wu King Estate)') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('The Church of Christ in China Hoh Fuk Tong Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('The Hong Kong Eng Clansman Association Wu Si Chong Memorial School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('Tin Shui Wai Catholic Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Toi Shan Association Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Tseung Kwan O Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Tsuen Wan Catholic Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Tsuen Wan Government Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Tung Chung Catholic School (Primary)') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('TWGHs HK & KLN Electrical Appliances Merchants Association Ltd School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('TWGHs Hok Shan School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('TWGHs Sin Chu Wan Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('TWGHs Tang Shiu Kin Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('TWGHs Wong Yee Jar Jat Memorial Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('W F Joseph Lee Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Xianggang Putonghua Yanxishe Primary School of Science and Creativity') and categoryid=1;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Yan Chai Hospital Law Chan Chor Si Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Yan Oi Tong Tin Ka Ping Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Yaumati Catholic Primary School (Hoi Wang Road)') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('YCH Ho Sik Nam Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+2 where lower(nameeng) = lower('Ying Wa Primary School') and categoryid=1;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('Yuen Long Long Ping Estate Wai Chow School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Yuen Long Merchants Association Primary School') and categoryid=1;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('世界龍岡學校劉皇發中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('中華基督教會何福堂書院') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('五育中學') and categoryid=2;
update entity set speechthird=speechthird+6 where lower(nameeng) = lower('伊利沙伯中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '佛教何南金中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '佛教沈香林紀念中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '佛教茂峰法師紀念中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '保良局唐乃勤初中書院') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '保良局李城璧中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '保良局羅傑承（一九八三）中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '元朗公立中學校友會鄧兆棠中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '元朗商會中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '十八鄉鄉事委員會公益社中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '嗇色園主辦可譽中學暨可譽小學(中學)') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '嘉諾撒書院') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '嘉諾撒聖心書院') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '培僑中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '基督教中國佈道會聖道迦南書院') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '基督教宣道會宣基中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '基督教香港信義會元朗信義中學') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechthird=speechthird+6 where name = '天主教伍華中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '天主教崇德英文書院') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '天水圍官立中學') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+6 where name = '妙法寺劉金龍中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '香港九龍塘基督教中華宣道會陳瑞芝紀念中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '寶血女子中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '寶覺中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '將軍澳官立中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '庇理羅士女子中學') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '張沛松紀念中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '德望學校') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '德貞女子中學') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+6 where name = '惠僑英文中學') and categoryid=2;
update entity set speechfirst=speechfirst+3 where name = '新界鄉議局元朗區中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '旅港開平商會中學') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+4 where name = '東華三院呂潤財紀念中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '東華三院李嘉誠中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '東華三院李潤田紀念中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '東華三院郭一葦中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '樂善堂梁植偉紀念中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '樂善堂楊葛小琳中學') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '沙田官立中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '沙田蘇浙公學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '漢華中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '王肇枝中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '神召會康樂中學') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where name = '粉嶺救恩書院') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where name = '粉嶺禮賢會中學') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '聖保祿中學') and categoryid=2;
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+2,speechthird=speechthird+9 where name = '聖保祿學校(中學部)') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '聖公會呂明才中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '聖公會梁季彜中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '聖公會陳融中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '聖若瑟英文書院') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '英華女學校') and categoryid=2;
update entity set speechsecond=speechsecond+6,speechthird=speechthird+9 where name = '藍田聖保祿中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '蘇浙公學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '裘錦秋中學(葵涌)') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '趙聿修紀念中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '路德會協同中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '路德會呂明才中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '路德會呂祥光中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '迦密唐賓南紀念中學') and categoryid=2;
update entity set speechthird=speechthird+3 where name = '迦密柏雨中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '迦密聖道中學') and categoryid=2;
update entity set speechsecond=speechsecond+4,speechthird=speechthird+6 where name = '陳樹渠紀念中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '靈糧堂怡文中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '順利天主教中學') and categoryid=2;
update entity set speechfirst=speechfirst+3,speechthird=speechthird+3 where name = '香島中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '香港中文大學校友會聯會陳震夏中學') and categoryid=2;
update entity set speechsecond=speechsecond+4 where name = '香港布廠商會朱石麟中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '香港浸會大學附屬學校王錦輝中小學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '香港管理專業協會李國寶中學') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '香港道教聯合會圓玄學院第一中學') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '香港青年協會李兆基書院') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '馬錦明慈善基金馬可賓紀念中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where name = '馬鞍山聖若瑟中學') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Belilios Public School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Bishop Hall Jubilee School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Buddhist Sum Heung Lam Memorial College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('C.C.C. Fung Leung Kit Memorial Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+6,speechthird=speechthird+3 where lower(nameeng) = lower('Carmel Divine Grace Foundation Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('Carmel Holy Word Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('CCC Kei Chi Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('Chang Pui Chung Memorial School') and categoryid=2;
update entity set speechfirst=speechfirst+4,speechsecond=speechsecond+6,speechthird=speechthird+9 where lower(nameeng) = lower('Cheung Sha Wan Catholic Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Choi Hung Estate Catholic Secondary School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Christ College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Christian & Missionary Alliance Sun Kei Secondary School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Christian Alliance S W Chan Memorial College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('CUHK FAA Chan Chun Ha Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('De La Salle Secondary School N.T.') and categoryid=2;
update entity set speechthird=speechthird+9 where lower(nameeng) = lower('Delia Memorial School (Hip Wo)') and categoryid=2;
update entity set speechthird=speechthird+6 where lower(nameeng) = lower('Diocesan Girls'' School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('DMHC Siu Ming Catholic Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Evangel College (Secondary Section)') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Fanling Kau Yan College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Fanling Lutheran Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+6,speechthird=speechthird+15 where lower(nameeng) = lower('Fukien Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Fung Kai Liu Man Shek Tong Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+4,speechthird=speechthird+6 where lower(nameeng) = lower('Good Hope School') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Heep Yunn School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Henrietta Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+4 where lower(nameeng) = lower('HKBUAS Wong Kam Fai Secondary & Primary School (Secondary Section)') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+10,speechthird=speechthird+12 where lower(nameeng) = lower('HKMA David Li Kwok Po College') and categoryid=2;
update entity set speechthird=speechthird+6 where lower(nameeng) = lower('HKTA The Yuen Yuen Institute No.1 Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('HKTA The Yuen Yuen Institute No.2 Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('HKUGA College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Ho Fung College (Sponsored by Sik Sik Yuen)') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+2 where lower(nameeng) = lower('Hoi Ping Chamber of Commerce Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Holy Family Canossian College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('Holy Trinity College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Hong Kong Tang King Po College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Hong Kong True Light College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Hotung Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('International Christian Quality Music Secondary & Primary School ( Secondary)') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('King''s College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Kwun Tong Maryknoll College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Law Ting Pong Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+6 where lower(nameeng) = lower('Lee Kau Yan Memorial School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Lingnan Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('LKWFSL Lau Wong Fat Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Lok Sin Tong Leung Chik Wai Memorial School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Lui Cheung Kwong Lutheran College') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Ma On Shan Tsung Tsin Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('Madam Lau Kam Lung Secondary School of MFBM') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('Marymount Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('Ng Wah Catholic Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+6 where lower(nameeng) = lower('Ng Yuk Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Ning Po No.2 College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Notre Dame College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Our Lady of The Rosary College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('Pentecostal Lam Hon Kwong School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Po Leung Kuk Ho Yuk Ching (1984) College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Po Leung Kuk Laws Foundation College') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Po Leung Kuk Lee Shing Pik College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Po Leung Kuk Lo Kit Sing (1983) College') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Po Leung Kuk Ngan Po Ling College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Pooi To Middle School') and categoryid=2;
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Pope Paul VI College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+6 where lower(nameeng) = lower('Pui Kiu Middle School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Pui Tak Canossian College') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('QualiEd College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Queen Elizabeth Sch Old Students'' Association Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('Raimondi College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Rhenish Church Pang Hok Ko Memorial College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. Lam Kau Mow Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+8,speechthird=speechthird+3 where lower(nameeng) = lower('S.K.H. Lam Woo Memorial Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. Leung Kwai Yee Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+4,speechthird=speechthird+3 where lower(nameeng) = lower('Sacred Heart Canossian College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Sai Kung Sung Tsun Catholic School (Secondary Section)') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Sha Tin Government Secondary School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Shun Tak Fraternal Association Cheng Yu Tung Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+5,speechsecond=speechsecond+2 where lower(nameeng) = lower('Shun Tak Fraternal Association Yung Yau College') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+6,speechthird=speechthird+6 where lower(nameeng) = lower('Shung Tak Catholic English College') and categoryid=2;
update entity set speechfirst=speechfirst+3 where lower(nameeng) = lower('Sing Yin Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('SKH Chan Young Secondary School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('SKH St. Mary''s Church Mok Hing Yiu College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('St. Joseph''s Anglo-Chinese School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Joseph''s College') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('St. Louis School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('St. Margaret''s Co-educational English Secondary & Primary School (Secondary Section)') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('St. Mark''s School') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('St. Mary''s Canossian College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Paul''s Co-educational College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('St. Paul''s College') and categoryid=2;
update entity set speechfirst=speechfirst+4,speechsecond=speechsecond+10,speechthird=speechthird+12 where lower(nameeng) = lower('St. Paul''s Convent School (Secondary Section)') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('St. Paul''s School (Lam Tin)') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('St. Paul''s Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('St. Stephen''s Church College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Teresa Secondary School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Stewards Pooi Kei College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('STFA Lee Shau Kee College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('STFA Leung Kau Kui College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('STFA Tam Pak Yu College') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('Tai Po Sam Yuk Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('Tak Nga Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Tak Sun Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('The Chinese Foundation Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+2,speechthird=speechthird+6 where lower(nameeng) = lower('The Evangelical Lutheran Church of Hong Kong Yuen Long Lutheran Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('The Hong Kong Taoist Association Ching Chung Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('The Methodist Church Hong Kong Wesley College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('Tin Shui Wai Government Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Toi Shan Association College') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('True Light Girls'' College') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('True Light Middle School of Hong Kong') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Tuen Mun Catholic Secondary School') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('Tuen Mun Government Secondary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('TWGHs Lee Ching Dea Memorial College') and categoryid=2;
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('TWGHs Li Ka Shing College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('TWGHs Lui Yun Choy Memorial College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('TWGHs Sun Hoi Directors'' College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('TWGHs Wong Fut Nam College') and categoryid=2;
update entity set speechsecond=speechsecond+2,speechthird=speechthird+3 where lower(nameeng) = lower('Wa Ying College') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Wah Yan College Hong Kong') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Wah Yan College Kowloon') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Yan Chai Hospital No.2 Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Yan Oi Tong Tin Ka Ping Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where lower(nameeng) = lower('Yuen Long Merchants Association Secondary School') and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '新生命教育協會平安福音中學') and categoryid=2;



update entityscore es, entity e set es.speechfirst=e.speechfirst,es.speechsecond=e.speechsecond,es.speechthird=e.speechthird where es.entityid=e.id and es.year=2018;
