update entity set speechfirst=0, speechsecond=0, speechthird=0;

update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('A.D. & F.D. of Pok Oi Hospital Mrs. Cheng Yam On Millennium Sch.');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Alliance Primary School, Whampoa');
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Baptist (STW) Lui Ming Choi Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Baptist Lui Ming Choi Secondary School');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2,speechthird=speechthird+2 where lower(nameeng) = lower('Belilios Public School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Buddhist Lam Bing Yim Memorial School(SPSD by HKBA)');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Buddhist Sin Tak College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Buddhist Sum Heung Lam Memorial College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Buddhist Tai Hung College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Buddhist Wong Cheuk Um Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Buddhist Yip Kei Nam Memorial College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Canossa School (Hong Kong)');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Carmel Bunnan Tong Memorial Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Carmel Divine Grace Foundation Secondary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Carmel Pak U Secondary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Castle Peak Catholic Primary School');
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('C.C.C. Kei Wa Primary School (Kowloon Tong)');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('C.C.C. Kei Wai Primary School (Ma Wan)');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('CCC Kei Yuen College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('WEO Chang Pui Chung Memorial School');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('Cheung Sha Wan Catholic Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Chinese YMCA Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Ching Chung Hau Po Woon Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Ching Chung Hau Po Woon Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Chiu Lut Sau Memorial Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Chiu Yang Por Yen Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Chiu Yang Primary School of Hong Kong');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Cho Yiu Catholic Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('C.&M.A. Chui Chak Lam Memorial School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Christian & Missionary Alliance Sun Kei Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Christian Alliance Cheng Wing Gee College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Christian Alliance H.C. Chan Primary School');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Christian Alliance S W Chan Memorial College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Christian Alliance Toi Shan H C Chan Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Clementi Secondary School');
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('CNEC Christian College');
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('Conservative Baptist Lui Ming Choi Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Delia Memorial School (Hip Wo)');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Diocesan Boys'' School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Diocesan Boys'' School Primary Division');
update entity set speechfirst=speechfirst+2,speechthird=speechthird+2 where lower(nameeng) = lower('Diocesan Girls'' Junior School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Diocesan Girls'' School');
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Daughters of Mary Help of Christians Siu Ming Catholic Secondary School');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+2 where lower(nameeng) = lower('Dr. Catherine F. Woo Memorial School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('The Evangelical Lutheran Church of Hong Kong Wo Che Lutheran School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Fanling Government Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Fanling Kau Yan College');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Fanling Lutheran Secondary School');
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('French International School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Fuk Wing Street Government Primary School');
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Fukien Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Fung Kai Innovative School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Fung Kai Liu Man Shek Tong Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Fung Kai No. 1 Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('G.T. (Ellen Yeung) College') and categoryid=1;
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('German Swiss International School') and categoryid=5;
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Good Counsel Catholic Primary School');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+3 where lower(nameeng) = lower('Good Hope School') and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Heep Yunn School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Hong Kong And Macau Lutheran Church Ming Tao Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('HKBUAS Wong Kam Fai Secondary and Primary School') and categoryid=1;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('HKFYG Lee Shau Kee College');
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+2,speechthird=speechthird+2 where lower(nameeng) = lower('HKMA David Li Kwok Po College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('HKMLC Queen Maud Secondary School');
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('HKTA The Yuen Yuen Institute No. 1 Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Hong Kong Taoist Association The Yuen Yuen Institute No. 2 Secondary Sch.');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('HKUGA Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('HKWMA Chu Shek Lun Secondary School');
update entity set speechfirst=speechfirst+2,speechthird=speechthird+2 where lower(nameeng) = lower('Hoi Ping Chamber of Commerce Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Holy Family Canossian College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Holy Family Canossian School');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+3 where lower(nameeng) = lower('Holy Trinity College');
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Hong Kong Baptist Convention Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Hong Kong Tang King Po College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Hong Kong Taoist Association Wun Tsuen School');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('Hong Kong True Light College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Immaculate Heart of Mary College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Immaculate Heart of Mary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Island School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Jockey Club Government Secondary School');
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Jordan Valley St. Joseph''s Catholic Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Ka Ling School of The Precious Blood');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Kam Tsin Village Ho Tung School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Kiangsu & Chekiang Primary School (W.D.)');
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('King Ling College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('King''s College');
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('King''s College Old Boys'' Association Primary School No. 2');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Kowloon Technical School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Kowloon Tong School (Primary Section)');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Kwai Ming Wu Memorial School of The Precious Blood');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Kwong Ming School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Kwong Ming Ying Loi School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Kwun Tong Maryknoll College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('La Salle College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Laichikok Catholic Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Law Ting Pong Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Lee Chi Tat Memorial School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Lee Kau Yan Memorial School');
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('Leung Kui Kau Lutheran Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Li Cheng Uk Government Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Ling Liang Church Sau Tak Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Lingnan Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Lung Kong WFSL Lau Wong Fat Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Lok Sin Tong Lau Tak Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Lok Sin Tong Leung Chik Wai Memorial School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Lok Sin Tong Leung Kau Kui Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Lok Sin Tong Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Lui Cheung Kwong Lutheran College');
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Ma On Shan Tsung Tsin Secondary School');
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Madam Lau Kam Lung Sec School of Miu Fat Buddhist Monastery');
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Maryknoll Convent School (Secondary Section)');
update entity set speechsecond=speechsecond+3,speechthird=speechthird+1 where lower(nameeng) = lower('Marymount Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Methodist School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Mui Wo School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Munsang College (Hong Kong Island)');
update entity set speechfirst=speechfirst+2,speechthird=speechthird+1 where lower(nameeng) = lower('NT Heung Yee Kuk Yuen Long District Secondary School');
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+2,speechthird=speechthird+2 where lower(nameeng) = lower('Ng Wah Catholic Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Notre Dame College');
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Oblate Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Our Lady of The Rosary College');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('Pentecostal Lam Hon Kwong School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Po Leung Kuk Centenary Li Shiu Chung Memorial College');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Po Leung Kuk Hong Kong Taoist Association Yuen Yuen Pri. Sch.');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Po Leung Kuk Horizon East Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Po Leung Kuk Lee Shing Pik College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Po Kok Primary School');
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('P.L.K. Camões Tan Siu Lin Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Po Leung Kuk Castar Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Po Leung Kuk Chee Jing Yin Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('PLK Laws Foundation College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('P.L.K. Leung Chow Shun Kam Primary School');
update entity set speechsecond=speechsecond+3 where lower(nameeng) = lower('PLK Ngan Po Ling College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Po Leung Kuk Tang Yuk Tien College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Po Leung Kuk Tong Nai Kan Junior Secondary College');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('Po On Commercial Association Wong Siu Ching Secondary School');
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Pok Oi Hospital Tang Pui King Memorial College');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+2 where lower(nameeng) = lower('Pope Paul VI College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Precious Blood Secondary School');
update entity set speechthird=speechthird+2 where lower(nameeng) = lower('Pui Ching Middle School');
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Pui Kiu College') and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('Pui Kiu Middle School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Pui Kiu Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Pui Ying Secondary School');
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Raimondi College');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+2 where lower(nameeng) = lower('SKH Bishop Baker Secondary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. St. Peter''s Primary School (A.M.)');
update entity set speechsecond=speechsecond+1,speechthird=speechthird+4 where lower(nameeng) = lower('Sacred Heart Canossian College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Sacred Heart Canossian School Private Section');
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('Salesians of Don Bosco Ng Siu Mui Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Shak Chung Shan Memorial Catholic Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Shanghai Alumni Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Shatin Methodist Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Shatin Tsung Tsin School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Shek Wu Hui Public School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Shun Lee Catholic Secondary School');
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+5,speechthird=speechthird+5 where lower(nameeng) = lower('Shung Tak Catholic English College');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('Sing Yin Secondary School');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('SINGAPORE INTERNATIONAL SCH (HONG KONG)');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Chai Wan St. Michael''s Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('SKH Chan Young Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Chi Fu Chi Nam Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Chu Oi Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('S.K.H. Chu Oi Primary School (Lei Muk Shue)');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('S.K.H. Kei Fook Primary School');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where lower(nameeng) = lower('S.K.H. Kei Wing Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('SKH Lam Kau Mow Secondary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('SKH Lam Woo Memorial Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Lui Ming Choi Memorial Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. Mung Yan Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. St. Clement''s Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('SKH St. Mary''s Church Mok Hing Yiu College');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. Tak Tin Lee Shiu Keung Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('S.K.H. Tin Wan Chi Nam Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Tsing Yi Chu Yan Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Tsing Yi Estate Ho Chak Wan Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('S.K.H. Yan Laap Memorial Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.K.H. Yan Laap Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Bonaventure College & High School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('St. Francis'' Canossian College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Francis'' Canossian School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('St. Francis of Assisi''s Caritas School');
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('St. Francis of Assisi''s College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Joan of Arc Secondary School');
update entity set speechsecond=speechsecond+2,speechthird=speechthird+2 where lower(nameeng) = lower('St. Joseph''s College');
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('St. Louis School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Margaret''s Co-Educational English Secondary and Primary School') and categoryid=2;
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('St. Mark''s School');
update entity set speechthird=speechthird+3 where lower(nameeng) = lower('St. Mary''s Canossian College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Mary''s Canossian School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Paul''s Co-educational College Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Paul''s College Primary School');
update entity set speechfirst=speechfirst+9,speechsecond=speechsecond+4,speechthird=speechthird+6 where lower(nameeng) = lower('St. Paul''s Convent School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('St. Paul''s Primary Catholic School');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+2 where lower(nameeng) = lower('St. Paul''s School (Lam Tin)');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Rose of Lima''s College');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('St. Rose of Lima''s School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('St. Stephen''s Church College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('St. Stephen''s College');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2,speechthird=speechthird+2 where lower(nameeng) = lower('St. Stephen''s Girls'' College');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Stephen''s Girls'' Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('St. Teresa Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Stewards Pooi Kei College');
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1 where lower(nameeng) = lower('Stewards Pooi Tun Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('S.T.F.A. Ho Yat Tung Primary School');
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('STFA Lee Kam Primary School');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2 where lower(nameeng) = lower('Shun Tak Fraternal Association Lee Shau Kee College');
update entity set speechsecond=speechsecond+1,speechthird=speechthird+2 where lower(nameeng) = lower('Shun Tak Fraternal Association Leung Kau Kui College');
update entity set speechfirst=speechfirst+6,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Shun Tak Fraternal Association Yung Yau College');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('HKKKWA Sun Fong Chung Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Tai Kok Tsui Catholic Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Tai Po Baptist Public School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Tai Po Government Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Tai Po Methodist School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Tak Sun School');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+2,speechthird=speechthird+1 where lower(nameeng) = lower('Tang Shiu Kin Victoria Government Secondary School');
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('Taoist Ching Chung Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('The Chinese Foundation Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('CCC Fung Leung Kit Memorial Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('The H.K.C.W.C. Hioe Tjo Yoeng Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('The Hong Kong Management Association K. S. Lo College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('The Methodist Church HK Wesley College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('The Mission Covenant Church Holm Glad Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Tin Ka Ping Secondary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Tin Shui Wai Catholic Primary School');
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where lower(nameeng) = lower('True Light Girls'' College');
update entity set speechfirst=speechfirst+2 where lower(nameeng) = lower('True Light Middle School of Hong Kong') and categoryid=2;
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('Tsuen Wan Catholic Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Tsuen Wan Government Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Tsz Wan Shan Catholic Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Tuen Mun Catholic Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('TWGHs Wong Fut Nam College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('TWGHs Chang Ming Thien College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('TWGHs Chen Zao Men College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('T.W.G.Hs. H.K. & KLN. E.A.M.A. Ltd. School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('TWGHs Kwok Yat Wai College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('TWGHs Lee Ching Dea Memorial College');
update entity set speechfirst=speechfirst+2,speechthird=speechthird+3 where lower(nameeng) = lower('TWGHs Lui Yun Choy Memorial College');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('T.W.G.Hs Ma Kam Chan Memorial Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('TWGHs Mrs. Fung Wong Fung Ting College');
update entity set speechsecond=speechsecond+2 where lower(nameeng) = lower('T.W.G.Hs Sin Chu Wan Primary School');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('TWGHs Wong Yee Jar Jat Memorial Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Valtorta College');
update entity set speechfirst=speechfirst+1 where lower(nameeng) = lower('W F Joseph Lee Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Wah Yan College Hong Kong');
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Wah Yan College Kowloon');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('Workers'' Children Secondary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Yan Chai Hospital No. 2 Secondary School');
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Yaumati Catholic Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Y.C.H. Chan Iu Seng Primary School');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Ying Wa College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Ying Wa Primary School');
update entity set speechthird=speechthird+1 where lower(nameeng) = lower('YLPMSAA Tang Siu Tong Secondary School');
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where lower(nameeng) = lower('Yu Chun Keung Memorial College');
update entity set speechsecond=speechsecond+1 where lower(nameeng) = lower('Yuen Long Merchants Association Primary School');
update entity set speechsecond=speechsecond+1 where name = '九龍城浸信會禧年(恩平)小學';
update entity set speechthird=speechthird+1 where name = '九龍塘官立小學';
update entity set speechfirst=speechfirst+1 where name = '九龍塘宣道小學';
update entity set speechfirst=speechfirst+1 where name = '九龍塘學校（小學部）';
update entity set speechthird=speechthird+1 where name = '上水宣道小學';
update entity set speechsecond=speechsecond+1 where name = '上水惠州公立學校';
update entity set speechfirst=speechfirst+1 where name = '大角嘴天主教小學（海帆道）';
update entity set speechthird=speechthird+1 where name = '中西區聖安多尼學校';
update entity set speechthird=speechthird+1 where name = '中華基督教會全完中學';
update entity set speechthird=speechthird+1 where name = '中華基督教會何福堂書院';
update entity set speechthird=speechthird+1 where name = '中華基督教會拔臣小學';
update entity set speechthird=speechthird+1 where name = '中華基督教會基法小學（油塘）';
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '中華基督教會基華小學';
update entity set speechsecond=speechsecond+2 where name = '中華基督教會基華小學(九龍塘)';
update entity set speechsecond=speechsecond+1 where name = '中華傳道會安柱中學';
update entity set speechthird=speechthird+1 where name = '五旬節于良發小學';
update entity set speechsecond=speechsecond+1 where name = '五旬節靳茂生小學';
update entity set speechthird=speechthird+1 where name = '五育中學';
update entity set speechthird=speechthird+1 where name = '五邑工商總會學校';
update entity set speechsecond=speechsecond+1 where name = '五邑鄒振猷學校';
update entity set speechthird=speechthird+1 where name = '仁愛堂田家炳小學';
update entity set speechsecond=speechsecond+2,speechthird=speechthird+1 where name = '仁濟醫院王華湘中學';
update entity set speechsecond=speechsecond+1 where name = '仁濟醫院陳耀星小學';
update entity set speechthird=speechthird+1 where name = '仁濟醫院蔡衍濤小學';
update entity set speechthird=speechthird+1 where name = '仁濟醫院靚次伯紀念中學';
update entity set speechsecond=speechsecond+1 where name = '仁濟醫院羅陳楚思小學';
update entity set speechfirst=speechfirst+1 where name = '元朗公立中學校友會英業小學';
update entity set speechsecond=speechsecond+1 where name = '元朗公立中學校友會鄧兆棠中學';
update entity set speechthird=speechthird+1 where name = '元朗官立小學';
update entity set speechthird=speechthird+1 where name = '元朗朗屏邨東莞學校';
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '天水圍天主教小學';
update entity set speechfirst=speechfirst+1 where name = '天水圍官立小學';
update entity set speechfirst=speechfirst+1 where name = '天水圍香島中學';
update entity set speechthird=speechthird+1 where name = '天水圍循道衞理小學';
update entity set speechfirst=speechfirst+2,speechthird=speechthird+1 where name = '天主教伍華中學';
update entity set speechfirst=speechfirst+1,speechthird=speechthird+2 where name = '天主教崇德英文書院';
update entity set speechthird=speechthird+1 where name = '天主教善導小學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '屯門官立小學';
update entity set speechthird=speechthird+1 where name = '方樹福堂基金方樹泉小學';
update entity set speechsecond=speechsecond+1 where name = '王肇枝中學';
update entity set speechthird=speechthird+1 where name = '北角衞理小學(下午)';
update entity set speechfirst=speechfirst+1 where name = '弘立書院' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '石湖墟公立學校';
update entity set speechsecond=speechsecond+2,speechthird=speechthird+1 where name = '石籬天主教小學';
update entity set speechthird=speechthird+1 where name = '伊利沙伯中學舊生會小學';
update entity set speechfirst=speechfirst+1 where name = '伊利沙伯中學舊生會小學分校';
update entity set speechthird=speechthird+2 where name = '伊利沙伯中學舊生會中學';
update entity set speechthird=speechthird+1 where name = '光明英來學校';
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '光明學校';
update entity set speechthird=speechthird+1 where name = '佛教何南金中學';
update entity set speechthird=speechthird+1 where name = '佛教林炳炎紀念學校(香港佛教聯合會主辦)';
update entity set speechthird=speechthird+1 where name = '佛教陳榮根紀念學校';
update entity set speechthird=speechthird+1 where name = '佛教榮茵學校';
update entity set speechfirst=speechfirst+5,speechsecond=speechsecond+6,speechthird=speechthird+3 where name = '妙法寺劉金龍中學';
update entity set speechthird=speechthird+1 where name = '庇理羅士女子中學';
update entity set speechsecond=speechsecond+1 where name = '李求恩紀念中學' and categoryid=5;
update entity set speechfirst=speechfirst+1 where name = '沙田圍胡素貞博士紀念學校';
update entity set speechsecond=speechsecond+1 where name = '沙田循道衞理小學';
update entity set speechthird=speechthird+1 where name = '和富慈善基金李宗德小學';
update entity set speechthird=speechthird+1 where name = '坪石天主教小學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '拔萃男書院附屬小學';
update entity set speechfirst=speechfirst+1 where name = '明愛柴灣馬登基金中學';
update entity set speechthird=speechthird+1 where name = '東涌天主教學校' and categoryid=2;
update entity set speechfirst=speechfirst+1 where name = '東涌天主教學校' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '東莞工商總會劉百樂中學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '東華三院呂潤財紀念中學';
update entity set speechfirst=speechfirst+2 where name = '東華三院李東海小學';
update entity set speechthird=speechthird+1 where name = '東華三院李賜豪小學';
update entity set speechfirst=speechfirst+1 where name = '東華三院冼次雲小學';
update entity set speechfirst=speechfirst+1 where name = '東華三院高可寧紀念小學';
update entity set speechsecond=speechsecond+1 where name = '東華三院郭一葦中學';
update entity set speechthird=speechthird+1 where name = '東華三院陳兆民中學';
update entity set speechsecond=speechsecond+1 where name = '東華三院港九電器商聯會小學';
update entity set speechsecond=speechsecond+1 where name = '東華三院黃笏南中學';
update entity set speechthird=speechthird+1 where name = '東華三院黃鳳翎中學';
update entity set speechfirst=speechfirst+1 where name = '東華三院鄧肇堅小學';
update entity set speechfirst=speechfirst+1 where name = '油蔴地天主教小學（海泓道）';
update entity set speechsecond=speechsecond+1 where name = '玫瑰崗學校';
update entity set speechthird=speechthird+1 where name = '金巴崙長老會耀道小學';
update entity set speechfirst=speechfirst+1,speechthird=speechthird+2 where name = '青松侯寶垣小學';
update entity set speechsecond=speechsecond+1 where name = '青松侯寶垣中學';
update entity set speechfirst=speechfirst+1 where name = '保良局世德小學';
update entity set speechthird=speechthird+1 where name = '保良局田家炳千禧小學';
update entity set speechsecond=speechsecond+1 where name = '保良局田家炳小學';
update entity set speechfirst=speechfirst+1 where name = '保良局西區婦女福利會馮李佩瑤小學';
update entity set speechfirst=speechfirst+1 where name = '保良局李城璧中學';
update entity set speechthird=speechthird+2 where name = '保良局雨川小學';
update entity set speechthird=speechthird+1 where name = '保良局姚連生中學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '保良局香港道教聯合會圓玄小學';
update entity set speechsecond=speechsecond+1 where name = '保良局唐乃勤初中書院';
update entity set speechthird=speechthird+1 where name = '保良局馬錦明夫人章馥仙中學';
update entity set speechfirst=speechfirst+1 where name = '保良局梁周順琴小學';
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '保良局莊啟程小學';
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '保良局馮晴紀念小學';
update entity set speechfirst=speechfirst+1 where name = '保良局蔡繼有學校' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '保良局顏寶鈴書院';
update entity set speechthird=speechthird+2 where name = '保良局羅傑承（一九八三）中學';
update entity set speechfirst=speechfirst+1 where name = '香港九龍塘基督教中華宣道會陳元喜小學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '香港九龍塘基督教中華宣道會陳瑞芝紀念中學';
update entity set speechthird=speechthird+1 where name = '宣道會葉紹蔭紀念小學';
update entity set speechthird=speechthird+1 where name = '柏立基教育學院校友會李一諤紀念學校';
update entity set speechfirst=speechfirst+1 where name = '皇仁舊生會中學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '胡素貞博士紀念學校';
update entity set speechthird=speechthird+1 where name = '英皇書院';
update entity set speechsecond=speechsecond+1 where name = '英皇書院同學會小學';
update entity set speechfirst=speechfirst+1 where name = '英華女學校';
update entity set speechthird=speechthird+2 where name = '英華小學';
update entity set speechfirst=speechfirst+1 where name = '迦密柏雨中學';
update entity set speechsecond=speechsecond+1 where name = '風采中學（教育評議會主辦）';
update entity set speechfirst=speechfirst+2 where name = '香島中學';
update entity set speechthird=speechthird+1 where name = '香海正覺蓮社佛教正慧小學';
update entity set speechsecond=speechsecond+1 where name = '香海正覺蓮社佛教梁植偉中學';
update entity set speechsecond=speechsecond+1 where name = '香港中文大學校友會聯會張煊昌學校';
update entity set speechfirst=speechfirst+3,speechsecond=speechsecond+1,speechthird=speechthird+2 where name = '香港中文大學校友會聯會陳震夏中學';
update entity set speechthird=speechthird+1 where name = '香港仔聖伯多祿天主教小學';
update entity set speechsecond=speechsecond+1 where name = '香港布廠商會朱石麟中學';
update entity set speechthird=speechthird+1 where name = '香港青年協會李兆基小學';
update entity set speechsecond=speechsecond+1,speechthird=speechthird+2 where name = '香港浸信會聯會小學';
update entity set speechsecond=speechsecond+1 where name = '香港浸會大學附屬學校王錦輝中小學' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '香港浸會大學附屬學校王錦輝中小學' and categoryid=2;
update entity set speechthird=speechthird+2 where name = '香港培正小學' and categoryid=1;
update entity set speechsecond=speechsecond+1 where name = '香港普通話研習社科技創意小學';
update entity set speechfirst=speechfirst+1 where name = '聖若瑟英文書院';
update entity set speechthird=speechthird+1 where name = '香港嘉諾撒學校';
update entity set speechsecond=speechsecond+1 where name = '香港潮陽小學';
update entity set speechfirst=speechfirst+1 where name = '香港鄧鏡波書院';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '港九街坊婦女會孫方中小學';
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '海壩街官立小學';
update entity set speechsecond=speechsecond+1 where name = '浸信宣道會呂明才小學';
update entity set speechthird=speechthird+2 where name = '浸信會呂明才小學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '浸信會沙田圍呂明才小學';
update entity set speechsecond=speechsecond+1 where name = '祖堯天主教小學';
update entity set speechsecond=speechsecond+1 where name = '粉嶺救恩書院';
update entity set speechfirst=speechfirst+3,speechthird=speechthird+2 where name = '粉嶺禮賢會中學';
update entity set speechsecond=speechsecond+2 where name = '荃灣天主教小學';
update entity set speechsecond=speechsecond+1 where name = '荃灣官立小學';
update entity set speechfirst=speechfirst+1 where name = '荃灣官立中學';
update entity set speechsecond=speechsecond+1 where name = '荔枝角天主教小學';
update entity set speechsecond=speechsecond+1 where name = '軒尼詩道官立小學（下午）';
update entity set speechfirst=speechfirst+1 where name = '馬鞍山循道衛理小學';
update entity set speechfirst=speechfirst+1 where name = '馬鞍山聖若瑟小學';
update entity set speechfirst=speechfirst+1 where name = '馬鞍山聖若瑟中學';
update entity set speechthird=speechthird+1 where name = '高主教書院小學部';
update entity set speechthird=speechthird+1 where name = '啟基學校';
update entity set speechsecond=speechsecond+1 where name = '培僑小學';
update entity set speechsecond=speechsecond+4,speechthird=speechthird+4 where name = '培僑中學';
update entity set speechfirst=speechfirst+1 where name = '培僑書院' and categoryid=2;
update entity set speechthird=speechthird+1 where name = '基督教女青年會丘佐榮中學';
update entity set speechfirst=speechfirst+2 where name = '基督教宣道會宣基中學';
update entity set speechsecond=speechsecond+1 where name = '基督教宣道會徐澤林紀念小學';
update entity set speechthird=speechthird+2 where name = '基督教香港信義會元朗信義中學';
update entity set speechsecond=speechsecond+1 where name = '基督教香港信義會心誠中學';
update entity set speechsecond=speechsecond+1 where name = '基督教香港信義會葵盛信義學校';
update entity set speechfirst=speechfirst+1 where name = '將軍澳天主教小學';
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '將軍澳官立中學';
update entity set speechthird=speechthird+1 where name = '將軍澳循道衛理小學';
update entity set speechfirst=speechfirst+1 where name = '崇真小學暨幼稚園' and categoryid=1;
update entity set speechthird=speechthird+1 where name = '彩雲聖若瑟小學';
update entity set speechsecond=speechsecond+1 where name = '深井天主教小學';
update entity set speechfirst=speechfirst+1 where name = '陳瑞祺(喇沙)小學';
update entity set speechsecond=speechsecond+1 where name = '博愛醫院歷屆總理聯誼會梁省德中學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '博愛醫院歷屆總理聯誼會鄭任安夫人千禧小學';
update entity set speechthird=speechthird+1 where name = '循理會白普理基金循理小學';
update entity set speechthird=speechthird+1 where name = '循道中學';
update entity set speechthird=speechthird+1 where name = '景嶺書院';
update entity set speechthird=speechthird+1 where name = '曾梅千禧學校';
update entity set speechthird=speechthird+1 where name = '曾璧山中學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '棉紡會中學';
update entity set speechthird=speechthird+1 where name = '港大同學會小學';
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '港青基信書院';
update entity set speechsecond=speechsecond+1 where name = '港澳信義會明道小學';
update entity set speechthird=speechthird+1 where name = '順利天主教中學';
update entity set speechfirst=speechfirst+1 where name = '順德聯誼總會何日東小學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '順德聯誼總會李金小學';
update entity set speechsecond=speechsecond+1 where name = '順德聯誼總會胡少渠紀念小學';
update entity set speechsecond=speechsecond+1 where name = '順德聯誼總會胡兆熾中學';
update entity set speechfirst=speechfirst+1,speechthird=speechthird+3 where name = '順德聯誼總會翁祐中學';
update entity set speechsecond=speechsecond+2 where name = '黃埔宣道小學';
update entity set speechsecond=speechsecond+1 where name = '慈幼葉漢千禧小學';
update entity set speechthird=speechthird+1 where name = '新生命教育協會平安福音中學';
update entity set speechfirst=speechfirst+2,speechsecond=speechsecond+3,speechthird=speechthird+1 where name = '新界鄉議局元朗區中學';
update entity set speechfirst=speechfirst+1 where name = '筲箕灣崇真學校';
update entity set speechsecond=speechsecond+2 where name = '聖士提反女子中學附屬小學';
update entity set speechfirst=speechfirst+2 where name = '聖公會仁立小學';
update entity set speechsecond=speechsecond+1 where name = '聖公會主風小學';
update entity set speechthird=speechthird+1 where name = '聖公會主恩小學';
update entity set speechfirst=speechfirst+1 where name = '聖公會主愛小學';
update entity set speechsecond=speechsecond+1 where name = '聖公會主愛小學（梨木樹）';
update entity set speechsecond=speechsecond+1 where name = '聖公會何澤芸小學';
update entity set speechthird=speechthird+1 where name = '聖公會李兆強小學';
update entity set speechsecond=speechsecond+1 where name = '聖公會李福慶中學';
update entity set speechthird=speechthird+1 where name = '聖公會奉基千禧小學';
update entity set speechsecond=speechsecond+1 where name = '聖公會林裘謀中學';
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '聖公會青衣主恩小學';
update entity set speechfirst=speechfirst+1 where name = '聖公會青衣邨何澤芸小學';
update entity set speechfirst=speechfirst+1 where name = '聖公會馬鞍山主風小學';
update entity set speechthird=speechthird+1 where name = '聖公會基愛小學';
update entity set speechsecond=speechsecond+1 where name = '聖公會基榮小學';
update entity set speechthird=speechthird+1 where name = '聖公會基福小學';
update entity set speechsecond=speechsecond+1 where name = '聖公會基樂小學';
update entity set speechsecond=speechsecond+1 where name = '聖公會基顯小學';
update entity set speechfirst=speechfirst+1 where name = '聖公會陳融中學';
update entity set speechfirst=speechfirst+1 where name = '聖公會聖西門呂明才中學';
update entity set speechthird=speechthird+1 where name = '聖公會聖彼得小學(上午)';
update entity set speechthird=speechthird+1 where name = '聖公會聖馬太小學';
update entity set speechfirst=speechfirst+1 where name = '聖公會聖馬利亞堂莫慶堯中學';
update entity set speechsecond=speechsecond+2 where name = '聖公會嘉福榮真小學';
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '聖公會蒙恩小學';
update entity set speechthird=speechthird+1 where name = '聖公會錦田聖約瑟小學';
update entity set speechthird=speechthird+1 where name = '聖公會靈愛小學';
update entity set speechfirst=speechfirst+1 where name = '聖方濟各英文小學';
update entity set speechthird=speechthird+1 where name = '聖方濟愛德小學';
update entity set speechfirst=speechfirst+1 where name = '聖母玫瑰書院';
update entity set speechfirst=speechfirst+1 where name = '聖母院書院';
update entity set speechfirst=speechfirst+1 where name = '聖安多尼學校';
update entity set speechsecond=speechsecond+1 where name = '聖言中學';
update entity set speechthird=speechthird+1 where name = '聖芳濟書院';
update entity set speechfirst=speechfirst+1,speechthird=speechthird+1 where name = '聖保祿中學';
update entity set speechfirst=speechfirst+2 where name = '聖保祿天主教小學';
update entity set speechsecond=speechsecond+3,speechthird=speechthird+1 where name = '聖保祿學校';
update entity set speechfirst=speechfirst+1 where name = '聖保羅男女中學附屬小學';
update entity set speechsecond=speechsecond+1 where name = '聖保羅書院小學';
update entity set speechsecond=speechsecond+1 where name = '聖博德天主教小學（蒲崗村道）';
update entity set speechthird=speechthird+1 where name = '聖博德學校';
update entity set speechsecond=speechsecond+1 where name = '聖愛德華天主教小學';
update entity set speechthird=speechthird+1 where name = '聖瑪加利男女英文中小學' and categoryid=2;
update entity set speechsecond=speechsecond+1 where name = '聖羅撒書院';
update entity set speechsecond=speechsecond+1 where name = '聖羅撒學校';
update entity set speechsecond=speechsecond+1 where name = '裘錦秋中學（葵涌）';
update entity set speechfirst=speechfirst+2 where name = '路德會呂明才中學';
update entity set speechsecond=speechsecond+1 where name = '路德會呂祥光小學';
update entity set speechfirst=speechfirst+2 where name = '路德會呂祥光中學';
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '路德會協同中學';
update entity set speechfirst=speechfirst+2 where name = '路德會梁鉅鏐小學';
update entity set speechfirst=speechfirst+1 where name = '路德會聖馬太學校（秀茂坪）';
update entity set speechsecond=speechsecond+1 where name = '道教青松小學(湖景邨)';
update entity set speechfirst=speechfirst+1 where name = '僑港伍氏宗親會伍時暢紀念學校';
update entity set speechfirst=speechfirst+1 where name = '嘉諾撒書院';
update entity set speechthird=speechthird+1 where name = '嘉諾撒聖心書院';
update entity set speechfirst=speechfirst+1 where name = '嘉諾撒聖家學校';
update entity set speechfirst=speechfirst+1 where name = '寧波第二中學';
update entity set speechthird=speechthird+1 where name = '漢華中學';
update entity set speechfirst=speechfirst+1 where name = '漢華中學（小學部）';
update entity set speechsecond=speechsecond+1 where name = '瑪利諾修院學校（中學部）';
update entity set speechfirst=speechfirst+1 where name = '福建中學';
update entity set speechsecond=speechsecond+1,speechthird=speechthird+2 where name = '趙聿修紀念中學';
update entity set speechfirst=speechfirst+1 where name = '鳳溪創新小學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '德信學校';
update entity set speechsecond=speechsecond+1 where name = '德望學校' and categoryid=2;
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '樂善堂梁植偉紀念中學';
update entity set speechthird=speechthird+1 where name = '樂善堂楊葛小琳中學';
update entity set speechthird=speechthird+1 where name = '衛理中學';
update entity set speechsecond=speechsecond+1 where name = '錦田公立蒙養學校';
update entity set speechsecond=speechsecond+1,speechthird=speechthird+1 where name = '優才（楊殷有娣）書院' and categoryid=1;
update entity set speechfirst=speechfirst+1 where name = '優才（楊殷有娣）書院' and categoryid=1;
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '勵志會梁李秀娛紀念小學';
update entity set speechfirst=speechfirst+1 where name = '嶺南鍾榮光博士紀念中學';
update entity set speechthird=speechthird+1 where name = '藍田循道衛理小學';
update entity set speechfirst=speechfirst+2 where name = '藍田聖保祿中學';
update entity set speechthird=speechthird+1 where name = '寶安商會王少清中學';
update entity set speechsecond=speechsecond+1 where name = '寶安商會溫浩根小學';
update entity set speechthird=speechthird+1 where name = '寶血女子中學';
update entity set speechfirst=speechfirst+1 where name = '寶血會嘉靈學校';
update entity set speechthird=speechthird+1 where name = '獻主會聖馬善樂小學';
update entity set speechfirst=speechfirst+1 where name = '蘇浙小學（全日）';
update entity set speechfirst=speechfirst+1 where name = '蘇浙公學';
update entity set speechfirst=speechfirst+1,speechsecond=speechsecond+1 where name = '靈糧堂怡文中學';
update entity set speechsecond=speechsecond+1 where name = '觀塘官立中學';

update entityscore es, entity e set es.speechfirst=e.speechfirst,es.speechsecond=e.speechsecond,es.speechthird=e.speechthird where es.entityid=e.id and es.year=2013;


update  entity set debatechi=1 where name = '協恩中學' and categoryid=2;
update  entity set debatechi=2 where name = '九龍塘學校（中學部）' and categoryid=2;
update  entity set debatechi=3 where name = '華英中學' and categoryid=2;
update  entity set debatechi=4 where name = '德愛中學' and categoryid=2;
update entityscore es, entity e set es.debatechi=e.debatechi where es.entityid=e.id and es.year=2013;