update entity set  athleticsposmale=0, athleticsposfemale=0 where categoryid in (1);
update entityscore set   athleticsposmale=0,  athleticsposfemale=0 where categoryid in (1) and year=2013  ;


update entity set athleticsposmale=21,athleticsposfemale=33   where categoryid=1 and name like '%中華傳道會呂明才小學%';
update entity set  athleticsposmale=15,athleticsposfemale=3  where categoryid=1 and name like '%地利亞(閩僑)英文小學%';
update entity set  athleticsposmale=26,athleticsposfemale=16  where categoryid=1 and name like '%郭怡雅神父紀念學校%';
update entity set  athleticsposmale=65,athleticsposfemale=82  where categoryid=1 and name like '%保良局世德小學%';
update entity set  athleticsposmale=39,athleticsposfemale=39  where categoryid=1 and name like '%保良局陳溢小學%';
update entity set  athleticsposmale=66,athleticsposfemale=66  where categoryid=1 and name like '%聖公會何澤芸小學%';
update entity set  athleticsposmale=105,athleticsposfemale=101.5  where categoryid=1 and name like '%聖公會青衣主恩小學%';
update entity set  athleticsposmale=79,athleticsposfemale=53  where categoryid=1 and name like '%聖公會青衣邨何澤芸小學%';
update entity set  athleticsposmale=6,athleticsposfemale=3    where categoryid=1 and name like '%青衣商會小學%';
update entity set  athleticsposmale=34,athleticsposfemale=1  where categoryid=1 and name like '%荃灣商會學校%';
update entity set  athleticsposmale=34,athleticsposfemale=13  where categoryid=1 and name like '%東華三院周演森小學%';
update entity set  athleticsposmale=10,athleticsposfemale=14  where categoryid=1 and name like '%東華三院黃士心小學%';
update entity set  athleticsposmale=11,athleticsposfemale=3  where categoryid=1 and name like '%仁濟醫院趙曾學韞小學%';
update entity set  athleticsposmale=14,athleticsposfemale=30  where categoryid=1 and name like '%上水宣道小學%';
update entity set  athleticsposmale=15,athleticsposfemale=15.5  where categoryid=1 and name like '%基督教粉嶺神召會小學%';
update entity set  athleticsposmale=9,athleticsposfemale=3    where categoryid=1 and name like '%粉嶺官立小學%';
update entity set  athleticsposmale=36.5,athleticsposfemale=44  where categoryid=1 and name like '%粉嶺公立學校%';


update entity set  athleticsposmale=16,athleticsposfemale=5  where categoryid=1 and name like '%方樹福堂基金方樹泉小學%';
update entity set  athleticsposmale=31,athleticsposfemale=25.5  where categoryid=1 and name like '%鳳溪創新小學%';
update entity set  athleticsposmale=13,athleticsposfemale=18  where categoryid=1 and name like '%鳳溪廖潤琛紀念學校%';
update entity set  athleticsposmale=41,athleticsposfemale=53  where categoryid=1 and name like '%鳳溪第一小學%';
update entity set  athleticsposmale=14,athleticsposfemale=6  where categoryid=1 and name like '%香海正覺蓮社佛教陳式宏學校%';
update entity set  athleticsposmale=13,athleticsposfemale=6  where categoryid=1 and name like '%香海正覺蓮社佛教正覺蓮社學校%';
update entity set  athleticsposmale=30,athleticsposfemale=6  where categoryid=1 and name like '%香海正覺蓮社佛教正慧小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%金錢村何東學校%';
update entity set  athleticsposmale=22,athleticsposfemale=5  where categoryid=1 and name like '%李志達紀念學校%';
update entity set  athleticsposmale=53,athleticsposfemale=45  where categoryid=1 and name like '%五旬節靳茂生小學%';
update entity set  athleticsposmale=58,athleticsposfemale=37  where categoryid=1 and name like '%五旬節于良發小學%';
update entity set  athleticsposmale=4,athleticsposfemale=4    where categoryid=1 and name like '%寶血會培靈學校%';
update entity set  athleticsposmale=4,athleticsposfemale=14  where categoryid=1 and name like '%沙頭角中心小學%';
update entity set  athleticsposmale=22,athleticsposfemale=19  where categoryid=1 and name like '%山咀公立學校%';
update entity set  athleticsposmale=13,athleticsposfemale=8  where categoryid=1 and name like '%石湖墟公立學校%';
update entity set  athleticsposmale=23,athleticsposfemale=41  where categoryid=1 and name like '%聖公會嘉福榮真小學%';
update entity set  athleticsposmale=46,athleticsposfemale=44  where categoryid=1 and name like '%聖公會榮真小學%';
update entity set  athleticsposmale=23,athleticsposfemale=10  where categoryid=1 and name like '%打鼓嶺嶺英公立學校%';
update entity set  athleticsposmale=39,athleticsposfemale=29  where categoryid=1 and name like '%曾梅千禧學校%';
update entity set  athleticsposmale=10,athleticsposfemale=3  where categoryid=1 and name like '%上水東莞學校%';
update entity set  athleticsposmale=10,athleticsposfemale=13  where categoryid=1 and name like '%東華三院港九電器商聯會小學%';
update entity set  athleticsposmale=7,athleticsposfemale=43  where categoryid=1 and name like '%東華三院馬錦燦紀念小學%';
update entity set  athleticsposmale=88,athleticsposfemale=58  where categoryid=1 and name like '%上水惠州公立學校%';
update entity set  athleticsposmale=18,athleticsposfemale=36  where categoryid=1 and name like '%育賢學校%';
update entity set  athleticsposmale=22,athleticsposfemale=4  where categoryid=1 and name like '%香港道教聯合會雲泉吳禮和紀念學校%';
-- update entity set  athleticsposmale=1,athleticsposfemale=0    where   categoryid in (1,5) and athleticsposmale=0 and athleticsposfemale=0 and nameeng like '%Hong Loke Yuen International School%';
update entity set  athleticsposmale=9.6,athleticsposfemale=8.6  where categoryid=1 and name like '%林村公立黃福鑾紀念學校%';
update entity set  athleticsposmale=16,athleticsposfemale=17  where categoryid=1 and name like '%新界婦孺福利會梁省德學校%';
update entity set  athleticsposmale=33,athleticsposfemale=44  where categoryid=1 and name like '%保良局田家炳千禧小學%';
update entity set  athleticsposmale=31,athleticsposfemale=18  where categoryid=1 and name like '%保良局田家炳小學%';
update entity set  athleticsposmale=17,athleticsposfemale=7  where categoryid=1 and name like '%天主教聖母聖心小學%';
update entity set  athleticsposmale=14,athleticsposfemale=3  where categoryid=1 and name like '%三水同鄉會禤景榮學校%';
update entity set  athleticsposmale=28.6,athleticsposfemale=8  where categoryid=1 and name like '%聖公會阮鄭夢芹銀禧小學%';
update entity set  athleticsposmale=43,athleticsposfemale=42  where categoryid=1 and name like '%聖公會阮鄭夢芹小學%';
update entity set  athleticsposmale=63,athleticsposfemale=73  where categoryid=1 and name like '%孫方中小學%';
update entity set  athleticsposmale=20,athleticsposfemale=15  where categoryid=1 and name like '%大埔崇德黃建常紀念學校%';
update entity set  athleticsposmale=14,athleticsposfemale=12  where categoryid=1 and name like '%大埔浸信會公立學校%';
update entity set  athleticsposmale=19,athleticsposfemale=7  where categoryid=1 and name like '%大埔官立小學%';
update entity set  athleticsposmale=73,athleticsposfemale=61  where categoryid=1 and name like '%大埔循道衛理小學%';
update entity set  athleticsposmale=66,athleticsposfemale=70.6  where categoryid=1 and name like '%大埔舊墟公立學校%';
update entity set  athleticsposmale=61,athleticsposfemale=46  where categoryid=1 and name like '%大埔舊墟公立學校（寶湖道）%';
update entity set  athleticsposmale=46,athleticsposfemale=58.1  where categoryid=1 and name like '%香港教育學院賽馬會小學%';
update entity set  athleticsposmale=24.6,athleticsposfemale=18  where categoryid=1 and name like '%仁濟醫院蔡衍濤小學%';
update entity set  athleticsposmale=19,athleticsposfemale=9  where categoryid=1 and name like '%浸信會沙田圍呂明才小學%';
update entity set  athleticsposmale=24,athleticsposfemale=9  where categoryid=1 and name like '%浸信會呂明才小學%';
update entity set  athleticsposmale=8,athleticsposfemale=3    where categoryid=1 and name like '%迦密愛禮信小學%';
update entity set  athleticsposmale=1,athleticsposfemale=1    where categoryid=1 and name like '%慈航學校%';
update entity set  athleticsposmale=12,athleticsposfemale=3  where categoryid=1 and name like '%宣道會陳元喜小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%宣道會台山陳元喜小學%';
update entity set  athleticsposmale=9,athleticsposfemale=3    where categoryid=1 and name like '%香港中文大學校友會聯會張煊昌學校%';
update entity set  athleticsposmale=9,athleticsposfemale=15  where categoryid=1 and name like '%胡素貞博士紀念學校%';
update entity set  athleticsposmale=3,athleticsposfemale=3    where categoryid=1 and name like '%禾輋信義學校%';
update entity set  athleticsposmale=2,athleticsposfemale=2    where categoryid=1 and name like '%循理會白普理基金循理小學%';
update entity set  athleticsposmale=3,athleticsposfemale=3    where categoryid=1 and name like '%東莞工商總會張煌偉小學%';
update entity set  athleticsposmale=3,athleticsposfemale=3    where categoryid=1 and name like '%香港道教聯合會純陽小學%';
update entity set  athleticsposmale=34,athleticsposfemale=10  where categoryid=1 and name like '%香港浸會大學附屬學校王錦輝中小學%';
update entity set  athleticsposmale=22,athleticsposfemale=33  where categoryid=1 and name like '%聖母無玷聖心學校%';
update entity set  athleticsposmale=3,athleticsposfemale=3    where categoryid=1 and name like '%九龍城浸信會禧年(恩平)小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%九龍城浸信會禧年小學%';
update entity set  athleticsposmale=4,athleticsposfemale=9    where categoryid=1 and name like '%路德會梁鉅鏐小學%';
update entity set  athleticsposmale=5,athleticsposfemale=3    where categoryid=1 and name like '%世界龍岡學校黃耀南小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%馬鞍山靈糧小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%基督教香港信義會馬鞍山信義學校%';
update entity set  athleticsposmale=15,athleticsposfemale=4  where categoryid=1 and name like '%馬鞍山循道衛理小學%';
update entity set  athleticsposmale=1,athleticsposfemale=1    where categoryid=1 and name like '%馬鞍山聖若瑟小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%吳氏宗親總會泰伯紀念學校%';
update entity set  athleticsposmale=5,athleticsposfemale=11  where categoryid=1 and name like '%保良局朱正賢小學%';
update entity set  athleticsposmale=11,athleticsposfemale=9  where categoryid=1 and name like '%保良局莊啟程小學%';
update entity set  athleticsposmale=4,athleticsposfemale=4    where categoryid=1 and name like '%保良局王賜豪（田心谷）小學%';
update entity set  athleticsposmale=6,athleticsposfemale=3    where categoryid=1 and name like '%保良局雨川小學%';
update entity set  athleticsposmale=5,athleticsposfemale=3    where categoryid=1 and name like '%保良局蕭漢森小學%';
update entity set  athleticsposmale=47,athleticsposfemale=28  where categoryid=1 and name like '%培僑書院%';
-- update entity set  athleticsposmale=12,athleticsposfemale=12  where   categoryid in (1,5) and athleticsposmale=0 and athleticsposfemale=0 and name like '%啟新書院%';
-- update entity set  athleticsposmale=0,athleticsposfemale=0    where   categoryid in (1,5) and athleticsposmale=0 and athleticsposfemale=0 and name like '%沙田小學%';
update entity set  athleticsposmale=19,athleticsposfemale=11  where categoryid=1 and name like '%沙田官立小學%';
update entity set  athleticsposmale=6,athleticsposfemale=9    where categoryid=1 and name like '%沙田循道衛理小學%';
update entity set  athleticsposmale=11,athleticsposfemale=17  where categoryid=1 and name like '%沙田崇真學校%';
update entity set  athleticsposmale=6,athleticsposfemale=16  where categoryid=1 and name like '%沙田圍胡素貞博士紀念學校%';
update entity set  athleticsposmale=6,athleticsposfemale=11  where categoryid=1 and name like '%聖公會主風小學%';
update entity set  athleticsposmale=16,athleticsposfemale=19  where categoryid=1 and name like '%聖公會馬鞍山主風小學%';
update entity set  athleticsposmale=4,athleticsposfemale=4    where categoryid=1 and name like '%培基小學%';
update entity set  athleticsposmale=3,athleticsposfemale=2    where categoryid=1 and name like '%天主教聖華學校%';
update entity set  athleticsposmale=5,athleticsposfemale=3    where categoryid=1 and name like '%救世軍田家炳學校%';
update entity set  athleticsposmale=13,athleticsposfemale=3  where categoryid=1 and name like '%東華三院冼次雲小學%';
update entity set  athleticsposmale=6,athleticsposfemale=4    where categoryid=1 and name like '%基督教神召會梁省德小學%';
update entity set  athleticsposmale=13,athleticsposfemale=7  where categoryid=1 and name like '%佛教志蓮小學%';
update entity set  athleticsposmale=19,athleticsposfemale=26  where categoryid=1 and name like '%基督教宣道會宣基小學%';
-- update entity set  athleticsposmale=1,athleticsposmale=1    where   categoryid in (1,5) and athleticsposmale=0 and athleticsposfemale=0 and nameeng like '%Clearwater Bay School%';
update entity set  athleticsposmale=12,athleticsposfemale=5  where categoryid=1 and name like '%播道書院%';





update entity set  athleticsposmale=79,athleticsposfemale=75  where categoryid=1 and name like '%優才（楊殷有娣）書院%';
update entity set  athleticsposmale=14,athleticsposfemale=5  where categoryid=1 and name like '%香海正覺蓮社佛教黃藻森學校%';
update entity set  athleticsposmale=13,athleticsposfemale=18  where categoryid=1 and name like '%港澳信義會明道小學%';
update entity set  athleticsposmale=34,athleticsposfemale=23  where categoryid=1 and name like '%港澳信義會小學%';
update entity set  athleticsposmale=51,athleticsposfemale=63  where categoryid=1 and name like '%香港華人基督教聯會真道書院%';
update entity set  athleticsposmale=16,athleticsposfemale=23  where categoryid=1 and name like '%景林天主教小學%';
update entity set  athleticsposmale=5,athleticsposfemale=3    where categoryid=1 and name like '%樂善堂劉德學校%';
update entity set  athleticsposmale=48,athleticsposfemale=19  where categoryid=1 and name like '%保良局馮晴紀念小學%';
update entity set  athleticsposmale=42,athleticsposfemale=24  where categoryid=1 and name like '%保良局陸慶濤小學%';
update entity set  athleticsposmale=44,athleticsposfemale=36  where categoryid=1 and name like '%保良局黃永樹小學%';
update entity set  athleticsposmale=14,athleticsposfemale=16  where categoryid=1 and name like '%博愛醫院陳國威小學%';
update entity set  athleticsposmale=3,athleticsposfemale=3    where categoryid=1 and name like '%西貢中心李少欽紀念學校%';
update entity set  athleticsposmale=1,athleticsposfemale=1    where categoryid=1 and name like '%西貢崇真天主教學校（小學部）%';
update entity set  athleticsposmale=12,athleticsposfemale=19  where categoryid=1 and name like '%聖公會將軍澳基德小學%';
update entity set  athleticsposmale=20,athleticsposfemale=16  where categoryid=1 and name like '%天主教聖安德肋小學%';
update entity set  athleticsposmale=71,athleticsposfemale=57  where categoryid=1 and name like '%順德聯誼總會梁潔華小學%';
update entity set  athleticsposmale=67,athleticsposfemale=73  where categoryid=1 and name like '%將軍澳天主教小學%';
update entity set  athleticsposmale=14,athleticsposfemale=14  where categoryid=1 and name like '%將軍澳官立小學%';
update entity set  athleticsposmale=12,athleticsposfemale=27  where categoryid=1 and name like '%將軍澳循道衛理小學%';
update entity set  athleticsposmale=56.5,athleticsposfemale=73  where categoryid=1 and name like '%東華三院王余家潔紀念小學%';
update entity set  athleticsposmale=15,athleticsposfemale=10  where categoryid=1 and name like '%仁濟醫院陳耀星小學%';
update entity set  athleticsposmale=17,athleticsposfemale=8  where categoryid=1 and name like '%仁愛堂田家炳小學%';
update entity set  athleticsposmale=14,athleticsposfemale=18  where categoryid=1 and name like '%博愛醫院歷屆總理聯誼會梁省德學校%';
update entity set  athleticsposmale=13,athleticsposfemale=4  where categoryid=1 and name like '%佛教陳榮根紀念學校%';
update entity set  athleticsposmale=11,athleticsposfemale=15  where categoryid=1 and name like '%佛教榮茵學校%';
update entity set  athleticsposmale=15,athleticsposfemale=18  where categoryid=1 and name like '%基督教宣道會徐澤林紀念小學%';
update entity set  athleticsposmale=11,athleticsposfemale=3  where categoryid=1 and name like '%中華基督教會元朗真光小學%';
update entity set  athleticsposmale=3,athleticsposfemale=2    where categoryid=1 and name like '%中華基督教會方潤華小學%';
update entity set  athleticsposmale=8,athleticsposfemale=6    where categoryid=1 and name like '%中華基督教青年會小學%';
update entity set  athleticsposmale=12,athleticsposfemale=4  where categoryid=1 and name like '%潮陽百欣小學%';
update entity set  athleticsposmale=21,athleticsposfemale=21  where categoryid=1 and name like '%香港潮陽小學%';
update entity set  athleticsposmale=11,athleticsposfemale=4  where categoryid=1 and name like '%宣道會葉紹蔭紀念小學%';
update entity set  athleticsposmale=29,athleticsposfemale=12  where categoryid=1 and name like '%鐘聲學校%';
update entity set  athleticsposmale=3,athleticsposfemale=6    where categoryid=1 and name like '%金巴崙長老會耀道小學%';
update entity set  athleticsposmale=0,athleticsposfemale=0    where categoryid=1 and name like '%基督教香港信義會宏信書院%';
update entity set  athleticsposmale=20,athleticsposfemale=12  where categoryid=1 and name like '%激活英文小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%香港青年協會李兆基小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%港澳信義會黃陳淑英紀念學校%';
update entity set  athleticsposmale=6,athleticsposfemale=3.5  where categoryid=1 and name like '%嗇色園主辦可銘學校%';
update entity set  athleticsposmale=5,athleticsposfemale=2    where categoryid=1 and name like '%香港學生輔助會小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%錦田公立蒙養學校%';
update entity set  athleticsposmale=39,athleticsposfemale=73  where categoryid=1 and name like '%光明學校%';
update entity set  athleticsposmale=66,athleticsposfemale=25  where categoryid=1 and name like '%光明英來學校%';
update entity set  athleticsposmale=6,athleticsposfemale=3    where categoryid=1 and name like '%獅子會何德心小學%';
update entity set  athleticsposmale=24,athleticsposfemale=22  where categoryid=1 and name like '%樂善堂梁銶琚學校%';
update entity set  athleticsposmale=23,athleticsposfemale=11  where categoryid=1 and name like '%樂善堂梁銶琚學校（分校）%';
update entity set  athleticsposmale=10,athleticsposfemale=4  where categoryid=1 and name like '%八鄉中心小學%';
update entity set  athleticsposmale=1,athleticsposfemale=3    where categoryid=1 and name like '%寶覺分校%';
update entity set  athleticsposmale=6,athleticsposfemale=7    where categoryid=1 and name like '%伊利沙伯中學舊生會小學分校%';
update entity set  athleticsposmale=3,athleticsposfemale=31  where categoryid=1 and name like '%伊利沙伯中學舊生會小學%';
update entity set  athleticsposmale=11,athleticsposfemale=8  where categoryid=1 and name like '%十八鄉鄉事委員會公益社小學%';
update entity set  athleticsposmale=6,athleticsposfemale=6    where categoryid=1 and name like '%聖公會錦田聖約瑟小學%';
update entity set  athleticsposmale=11,athleticsposfemale=14  where categoryid=1 and name like '%聖公會靈愛小學%';
update entity set  athleticsposmale=6,athleticsposfemale=4    where categoryid=1 and name like '%聖公會天水圍靈愛小學%';
update entity set  athleticsposmale=34,athleticsposfemale=42  where categoryid=1 and name like '%南元朗官立小學%';
update entity set  athleticsposmale=30,athleticsposfemale=44.5  where categoryid=1 and name like '%順德聯誼總會伍冕端小學%';
update entity set  athleticsposmale=15,athleticsposfemale=23  where categoryid=1 and name like '%天水圍天主教小學%';
update entity set  athleticsposmale=8,athleticsposfemale=12  where categoryid=1 and name like '%天水圍官立小學%';
update entity set  athleticsposmale=7,athleticsposfemale=8.5  where categoryid=1 and name like '%天水圍循道衛理小學%';
update entity set  athleticsposmale=5,athleticsposfemale=11  where categoryid=1 and name like '%惇裕學校%';
update entity set  athleticsposmale=43,athleticsposfemale=10  where categoryid=1 and name like '%通德學校%';
update entity set  athleticsposmale=20,athleticsposfemale=10  where categoryid=1 and name like '%東華三院李東海小學%';
update entity set  athleticsposmale=21,athleticsposfemale=12  where categoryid=1 and name like '%東華三院姚達之紀念小學%';
-- update entity set  athleticsposmale=20,athleticsposfemale=4  where   categoryid in (1,5) and athleticsposmale=0 and athleticsposfemale=0 and nameeng like '%Umah International Primary School%';
update entity set  athleticsposmale=45,athleticsposfemale=60  where categoryid=1 and name like '%和富慈善基金李宗德小學%';
update entity set  athleticsposmale=12,athleticsposfemale=13  where categoryid=1 and name like '%香港普通話研習社科技創意小學%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%元朗朗屏邨東莞學校%';
update entity set  athleticsposmale=5,athleticsposfemale=2    where categoryid=1 and name like '%元朗朗屏邨惠州學校%';
update entity set  athleticsposmale=50,athleticsposfemale=33  where categoryid=1 and name like '%元朗公立中學校友會小學%';
update entity set  athleticsposmale=30,athleticsposfemale=12  where categoryid=1 and name like '%元朗公立中學校友會英業小學%';
update entity set  athleticsposmale=13,athleticsposfemale=14  where categoryid=1 and name like '%元朗官立小學%';
update entity set  athleticsposmale=20,athleticsposfemale=11  where categoryid=1 and name like '%元朗商會小學%';
update entity set  athleticsposmale=35,athleticsposfemale=21  where categoryid=1 and name like '%博愛醫院歷屆總理聯誼會鄭任安夫人千禧小學%';
update entity set  athleticsposmale=34,athleticsposfemale=17  where categoryid=1 and name like '%博愛醫院歷屆總理聯誼會鄭任安夫人學校%';
update entity set  athleticsposmale=14,athleticsposfemale=5  where categoryid=1 and name like '%青山天主教小學%';
update entity set  athleticsposmale=7,athleticsposfemale=6    where categoryid=1 and name like '%中華基督教會拔臣小學%';
update entity set  athleticsposmale=13,athleticsposfemale=14  where categoryid=1 and name like '%中華基督教會何福堂小學%';
update entity set  athleticsposmale=24,athleticsposfemale=18  where categoryid=1 and name like '%中華基督教會蒙黃花沃紀念小學%';
update entity set  athleticsposmale=15,athleticsposfemale=28  where categoryid=1 and name like '%五邑鄒振猷學校%';
update entity set  athleticsposmale=9,athleticsposfemale=4    where categoryid=1 and name like '%興德學校%';
update entity set  athleticsposmale=5,athleticsposfemale=3    where categoryid=1 and name like '%僑港伍氏宗親會伍時暢紀念學校%';
update entity set  athleticsposmale=3,athleticsposfemale=4    where categoryid=1 and name like '%香港紅卍字會屯門卍慈小學%';
update entity set  athleticsposmale=29,athleticsposfemale=0  where categoryid=1 and name like '%伊斯蘭學校%';
update entity set  athleticsposmale=11,athleticsposfemale=5  where categoryid=1 and name like '%世界龍岡學校劉德容紀念小學%';
update entity set  athleticsposmale=8,athleticsposfemale=3    where categoryid=1 and name like '%樂善堂梁黃蕙芳紀念學校%';
update entity set  athleticsposmale=21,athleticsposfemale=5  where categoryid=1 and name like '%路德會呂祥光小學%';
update entity set  athleticsposmale=5,athleticsposfemale=5    where categoryid=1 and name like '%香港路德會增城兆霖學校%';
update entity set  athleticsposmale=29,athleticsposfemale=14  where categoryid=1 and name like '%保良局方王錦全小學%';
update entity set  athleticsposmale=45,athleticsposfemale=66  where categoryid=1 and name like '%保良局香港道教聯合會圓玄小學%';
update entity set  athleticsposmale=52,athleticsposfemale=32  where categoryid=1 and name like '%保良局志豪小學%';
update entity set  athleticsposmale=18,athleticsposfemale=18  where categoryid=1 and name like '%保良局梁周順琴小學%';
update entity set  athleticsposmale=42,athleticsposfemale=53  where categoryid=1 and name like '%保良局莊啟程第二小學%';
update entity set  athleticsposmale=23,athleticsposfemale=25  where categoryid=1 and name like '%保良局西區婦女福利會馮李佩瑤小學%';
update entity set  athleticsposmale=4,athleticsposfemale=1    where categoryid=1 and name like '%鄉師自然學校%';
update entity set  athleticsposmale=9,athleticsposfemale=11  where categoryid=1 and name like '%聖公會蒙恩小學%';
update entity set  athleticsposmale=19,athleticsposfemale=13  where categoryid=1 and name like '%柏立基教育學院校友會何壽基學校%';
update entity set  athleticsposmale=45,athleticsposfemale=45  where categoryid=1 and name like '%順德聯誼總會何日東小學%';
update entity set  athleticsposmale=40,athleticsposfemale=18  where categoryid=1 and name like '%順德聯誼總會李金小學%';
update entity set  athleticsposmale=22,athleticsposfemale=25  where categoryid=1 and name like '%順德聯誼總會胡少渠紀念小學%';
update entity set  athleticsposmale=14,athleticsposfemale=26  where categoryid=1 and name like '%道教青松小學%';
update entity set  athleticsposmale=8,athleticsposfemale=6    where categoryid=1 and name like '%道教青松小學 (湖景邨)%';
update entity set  athleticsposmale=18,athleticsposfemale=9  where categoryid=1 and name like '%台山商會學校%';
update entity set  athleticsposmale=23,athleticsposfemale=13  where categoryid=1 and name like '%屯門官立小學%';
update entity set  athleticsposmale=35,athleticsposfemale=10  where categoryid=1 and name like '%東華三院鄧肇堅小學%';
update entity set  athleticsposmale=5,athleticsposfemale=3    where categoryid=1 and name like '%仁德天主教小學%';
update entity set  athleticsposmale=12.5,athleticsposfemale=6  where categoryid=1 and name like '%仁濟醫院何式南小學%';
update entity set  athleticsposmale=36,athleticsposfemale=20  where categoryid=1 and name like '%仁濟醫院羅陳楚思小學%';
update entity set  athleticsposmale=4,athleticsposfemale=2    where categoryid=1 and name like '%仁愛堂劉皇發夫人小學%';
update entity set  athleticsposmale=25,athleticsposfemale=23  where categoryid=1 and name like '%杯澳公立學校%';
update entity set  athleticsposmale=4,athleticsposfemale=3    where categoryid=1 and name like '%中華基督教會大澳小學%';
update entity set  athleticsposmale=55,athleticsposfemale=71  where categoryid=1 and name like '%青松侯寶垣小學%';
update entity set  athleticsposmale=23,athleticsposfemale=52.5  where categoryid=1 and name like '%香港教育工作者聯會黃楚標學校%';
update entity set  athleticsposmale=23,athleticsposfemale=19  where categoryid=1 and name like '%嗇色園主辦可譽中學暨可譽小學%';
update entity set  athleticsposmale=40,athleticsposfemale=52  where categoryid=1 and name like '%靈糧堂秀德小學%';
update entity set  athleticsposmale=24,athleticsposfemale=23  where categoryid=1 and name like '%梅窩學校%';
update entity set  athleticsposmale=70,athleticsposfemale=54  where categoryid=1 and name like '%寶安商會溫浩根小學%';
update entity set  athleticsposmale=72,athleticsposfemale=72  where categoryid=1 and name like '%聖公會偉倫小學%';
update entity set  athleticsposmale=74,athleticsposfemale=68  where categoryid=1 and name like '%救世軍林拔中紀念學校%';
update entity set  athleticsposmale=52,athleticsposfemale=44  where categoryid=1 and name like '%東涌天主教學校%';
update entity set  athleticsposmale=26,athleticsposfemale=0  where categoryid=1 and name like '%東灣莫羅瑞華學校%';
-- update entity set  athleticsposmale=0,athleticsposfemale=0    where   categoryid in (1,5) and athleticsposmale=0 and athleticsposfemale=0 and nameeng like '%Discovery Bay International School%';
update entity set  athleticsposmale=68,athleticsposfemale=52  where categoryid=1 and name like '%中華基督教會長洲堂錦江小學%';
update entity set  athleticsposmale=73,athleticsposfemale=55  where categoryid=1 and name like '%長洲聖心學校%';
update entity set  athleticsposmale=20,athleticsposfemale=34  where categoryid=1 and name like '%聖家學校%';
update entity set  athleticsposmale=69,athleticsposfemale=63  where categoryid=1 and name like '%國民學校%';
update entity set  athleticsposmale=40,athleticsposfemale=22  where categoryid=1 and name like '%南丫北段公立小學%';
update entity set  athleticsposmale=3,athleticsposfemale=3    where categoryid=1 and name like '%中華基督教會全完第一小學%';
update entity set  athleticsposmale=9,athleticsposfemale=10  where categoryid=1 and name like '%中華基督教會基慧小學%';
update entity set  athleticsposmale=71,athleticsposfemale=52  where categoryid=1 and name like '%中華基督教會基慧小學（馬灣）%';
update entity set  athleticsposmale=30,athleticsposfemale=12  where categoryid=1 and name like '%柴灣角天主教小學%';
update entity set  athleticsposmale=14,athleticsposfemale=5  where categoryid=1 and name like '%靈光小學%';
update entity set  athleticsposmale=68,athleticsposfemale=51  where categoryid=1 and name like '%香港浸信會聯會小學%';
update entity set  athleticsposmale=20,athleticsposfemale=14  where categoryid=1 and name like '%香港道教聯合會圓玄學院石圍角小學%';
update entity set  athleticsposmale=57,athleticsposfemale=15  where categoryid=1 and name like '%嗇色園主辦可信學校%';
update entity set  athleticsposmale=19,athleticsposfemale=38  where categoryid=1 and name like '%海壩街官立小學%';
update entity set  athleticsposmale=6,athleticsposfemale=3    where categoryid=1 and name like '%路德會聖十架學校%';
update entity set  athleticsposmale=50,athleticsposfemale=64  where categoryid=1 and name like '%寶血會伍季明紀念學校%';
update entity set  athleticsposmale=56,athleticsposfemale=26  where categoryid=1 and name like '%梨木樹天主教小學%';
update entity set  athleticsposmale=6,athleticsposfemale=11  where categoryid=1 and name like '%天佑小學%';
-- update entity set  athleticsposmale=5,athleticsposfemale=3    where   categoryid in (1,5) and athleticsposmale=0 and athleticsposfemale=0 and nameeng like '%Rosebud Primary School%';
update entity set  athleticsposmale=49,athleticsposfemale=38  where categoryid=1 and name like '%天主教石鐘山紀念小學%';
update entity set  athleticsposmale=30,athleticsposfemale=22  where categoryid=1 and name like '%深井天主教小學%';
update entity set  athleticsposmale=31,athleticsposfemale=40  where categoryid=1 and name like '%寶血會思源學校%';
update entity set  athleticsposmale=25,athleticsposfemale=19  where categoryid=1 and name like '%聖公會主愛小學(梨木樹)%';
update entity set  athleticsposmale=14,athleticsposfemale=27  where categoryid=1 and name like '%荃灣天主教小學%';
update entity set  athleticsposmale=25,athleticsposfemale=5  where categoryid=1 and name like '%荃灣潮州公學%';
update entity set  athleticsposmale=40,athleticsposfemale=44.5  where categoryid=1 and name like '%荃灣官立小學%';
update entity set  athleticsposmale=19,athleticsposfemale=6  where categoryid=1 and name like '%荃灣公立何傳耀紀念小學%';
update entity set  athleticsposmale=5,athleticsposfemale=3    where categoryid=1 and name like '%亞斯理衞理小學%';
update entity set  athleticsposmale=45,athleticsposfemale=25  where categoryid=1 and name like '%佛教林炳炎紀念學校(香港佛教聯合會主辦)%';
update entity set  athleticsposmale=62,athleticsposfemale=67  where categoryid=1 and name like '%佛教林金殿紀念小學%';
update entity set  athleticsposmale=21,athleticsposfemale=19  where categoryid=1 and name like '%中華基督教會全完第二小學%';
update entity set  athleticsposmale=46,athleticsposfemale=9  where categoryid=1 and name like '%中華基督教會基真小學%';
update entity set  athleticsposmale=37,athleticsposfemale=21  where categoryid=1 and name like '%祖堯天主教小學%';
update entity set  athleticsposmale=24,athleticsposfemale=3  where categoryid=1 and name like '%中華傳道會許大同學校%';
update entity set  athleticsposmale=22,athleticsposfemale=17  where categoryid=1 and name like '%基督教香港信義會葵盛信義學校%';
update entity set  athleticsposmale=55,athleticsposfemale=61  where categoryid=1 and name like '%慈幼葉漢千禧小學%';
update entity set  athleticsposmale=27,athleticsposfemale=45  where categoryid=1 and name like '%慈幼葉漢小學%';
update entity set  athleticsposmale=30,athleticsposfemale=6  where categoryid=1 and name like '%石籬天主教小學%';
update entity set  athleticsposmale=21,athleticsposfemale=20  where categoryid=1 and name like '%石籬聖若望天主教小學%';
update entity set  athleticsposmale=52,athleticsposfemale=65  where categoryid=1 and name like '%聖公會主愛小學%';
update entity set  athleticsposmale=21,athleticsposfemale=6  where categoryid=1 and name like '%聖公會主恩小學%';
update entity set  athleticsposmale=83,athleticsposfemale=63  where categoryid=1 and name like '%聖公會仁立紀念小學%';
update entity set  athleticsposmale=36,athleticsposfemale=53  where categoryid=1 and name like '%聖公會仁立小學%';
update entity set  athleticsposmale=26,athleticsposfemale=25  where categoryid=1 and name like '%柏立基教育學院校友會李一諤紀念學校%';
update entity set  athleticsposmale=7,athleticsposfemale=6    where categoryid=1 and name like '%東華三院高可寧紀念小學%';








update entity set  athleticsposmale=583  where categoryid=1 and name like '%愛秩序灣官立小學%';
-- update entity set  athleticsposmale=154  where   categoryid in (1,5) and athleticsposmale=0 and nameeng like '%Bradbury School%';
update entity set  athleticsposmale=140  where categoryid=1 and name like '%佛教中華康山學校%';
update entity set  athleticsposmale=299  where categoryid=1 and name like '%佛教黃焯菴小學%';
update entity set  athleticsposmale=517  where categoryid=1 and name like '%香港嘉諾撒學校%';
update entity set  athleticsposmale=334  where categoryid=1 and name like '%中華基督教會基灣小學%';
update entity set  athleticsposmale=548  where categoryid=1 and name like '%中華基督教會基灣小學（愛蝶灣）%';
update entity set  athleticsposmale=204  where categoryid=1 and name like '%啟基學校(港島)%';
-- update entity set  athleticsposmale=507  where   categoryid in (1,5) and athleticsposmale=0 and name like '%漢基國際學校%';
update entity set  athleticsposmale=383  where categoryid=1 and name like '%北角循道學校%';
update entity set  athleticsposmale=198  where categoryid=1 and name like '%丹拿山循道學校%';
update entity set  athleticsposmale=78  where categoryid=1 and name like '%基督教香港信義會信愛學校%';
-- update entity set  athleticsposmale=218  where   categoryid in (1,5) and athleticsposmale=0 and name like '%德瑞國際學校%';
update entity set  athleticsposmale=511.5  where categoryid=1 and name like '%港大同學會小學%';
update entity set  athleticsposmale=457  where categoryid=1 and name like '%漢華中學（小學部）%';
-- update entity set  athleticsposmale=168  where   categoryid in (1,5) and athleticsposmale=0 and name like '%香港國際學校%';
update entity set  athleticsposmale=350.5  where categoryid=1 and name like '%蘇浙小學%';
-- update entity set  athleticsposmale=81  where   categoryid in (1,5) and athleticsposmale=0 and name like '%韓國國際學校%';
update entity set  athleticsposmale=256  where categoryid=1 and name like '%李陞大坑學校%';
update entity set  athleticsposmale=132  where categoryid=1 and name like '%嶺南小學%';
update entity set  athleticsposmale=285  where categoryid=1 and name like '%瑪利曼小學%';
update entity set  athleticsposmale=583  where categoryid=1 and name like '%北角官立小學%';
update entity set  athleticsposmale=150  where categoryid=1 and name like '%北角官立小學（雲景道）%';
update entity set  athleticsposmale=717  where categoryid=1 and name like '%北角衛理小學%';
-- update entity set  athleticsposmale=13  where   categoryid in (1,5) and athleticsposmale=0 and nameeng like '%Peak School%';
update entity set  athleticsposmale=125  where categoryid=1 and name like '%保良局金銀業貿易場張凝文學校%';
update entity set  athleticsposmale=240  where categoryid=1 and name like '%寶覺小學%';
update entity set  athleticsposmale=90  where categoryid=1 and name like '%寶血小學%';
update entity set  athleticsposmale=849  where categoryid=1 and name like '%培僑小學%';
update entity set  athleticsposmale=993.5  where categoryid=1 and name like '%番禺會所華仁小學%';
update entity set  athleticsposmale=821  where categoryid=1 and name like '%高主教書院小學部%';
update entity set  athleticsposmale=513  where categoryid=1 and name like '%玫瑰崗學校（小學部）%';
update entity set  athleticsposmale=438  where categoryid=1 and name like '%慈幼學校%';
update entity set  athleticsposmale=707  where categoryid=1 and name like '%滬江小學%';
update entity set  athleticsposmale=174  where categoryid=1 and name like '%筲箕灣官立小學%';
update entity set  athleticsposmale=526  where categoryid=1 and name like '%筲箕灣崇真學校%';
update entity set  athleticsposmale=200  where categoryid=1 and name like '%官立嘉道理爵士小學%';
update entity set  athleticsposmale=829.5  where categoryid=1 and name like '%聖公會柴灣聖米迦勒小學%';
update entity set  athleticsposmale=661  where categoryid=1 and name like '%聖公會聖雅各小學%';
update entity set  athleticsposmale=529  where categoryid=1 and name like '%聖公會聖米迦勒小學%';
update entity set  athleticsposmale=327  where categoryid=1 and name like '%聖馬可小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%聖保祿學校（小學部）%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%聖保祿天主教小學%';




update entity set  athleticsposmale=825  where categoryid=1 and name like '%聖士提反書院附屬小學%';
update entity set  athleticsposmale=522  where categoryid=1 and name like '%太古小學%';
update entity set  athleticsposmale=322  where categoryid=1 and name like '%勵志會梁李秀娛紀念小學%';
update entity set  athleticsposmale=423  where categoryid=1 and name like '%香港中國婦女會丘佐榮學校%';
update entity set  athleticsposmale=388  where categoryid=1 and name like '%救世軍韋理夫人紀念學校%';
update entity set  athleticsposmale=194  where categoryid=1 and name like '%救世軍中原慈善基金學校%';
update entity set  athleticsposmale=248  where categoryid=1 and name like '%香港真光中學（小學部）%';
-- update entity set  athleticsposmale=0  where   categoryid in (1,5) and athleticsposmale=0 and name like '%己連拿小學%';
-- update entity set  athleticsposmale=0  where   categoryid in (1,5) and athleticsposmale=0 and name like '%香港日本人學校%';
update entity set  athleticsposfemale=340  where categoryid=1 and name like '%愛秩序灣官立小學%';
-- update entity set  athleticsposfemale=111  where   categoryid in (1,5) and athleticsposfemale=0 and nameeng like '%Bradbury School%';
update entity set  athleticsposfemale=40  where categoryid=1 and name like '%佛教中華康山學校%';
update entity set  athleticsposfemale=65  where categoryid=1 and name like '%佛教黃焯菴小學%';
update entity set  athleticsposfemale=607  where categoryid=1 and name like '%香港嘉諾撒學校%';
update entity set  athleticsposfemale=406  where categoryid=1 and name like '%中華基督教會基灣小學%';
update entity set  athleticsposfemale=222  where categoryid=1 and name like '%中華基督教會基灣小學（愛蝶灣）%';
update entity set  athleticsposfemale=190  where categoryid=1 and name like '%啟基學校(港島)%';
-- update entity set  athleticsposfemale=269  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%漢基國際學校%';
update entity set  athleticsposfemale=113  where categoryid=1 and name like '%北角循道學校%';
update entity set  athleticsposfemale=212  where categoryid=1 and name like '%丹拿山循道學校%';
update entity set  athleticsposfemale=69  where categoryid=1 and name like '%基督教香港信義會信愛學校%';
-- update entity set  athleticsposfemale=183  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%德瑞國際學校%';
update entity set  athleticsposfemale=445.5  where categoryid=1 and name like '%港大同學會小學%';
update entity set  athleticsposfemale=282  where categoryid=1 and name like '%漢華中學（小學部）%';
-- update entity set  athleticsposfemale=160  where   categoryid in (1,5) and athleticsposfemale=0 and name like '%香港國際學校%';
update entity set  athleticsposfemale=140  where categoryid=1 and name like '%蘇浙小學%';
-- update entity set  athleticsposfemale=0  where   categoryid in (1,5) and athleticsposfemale=0 and name like '%韓國國際學校%';
update entity set  athleticsposfemale=169  where categoryid=1 and name like '%李陞大坑學校%';
update entity set  athleticsposfemale=92  where categoryid=1 and name like '%嶺南小學%';
update entity set  athleticsposfemale=525  where categoryid=1 and name like '%瑪利曼小學%';
update entity set  athleticsposfemale=200  where categoryid=1 and name like '%天主教明德學校%';
update entity set  athleticsposfemale=356  where categoryid=1 and name like '%北角官立小學%';
update entity set  athleticsposfemale=50  where categoryid=1 and name like '%北角官立小學（雲景道）%';
update entity set  athleticsposfemale=364  where categoryid=1 and name like '%北角衛理小學%';
-- update entity set  athleticsposfemale=0  where   categoryid in (1,5) and athleticsposfemale=0 and nameeng like '%Peak School%';
update entity set  athleticsposfemale=15  where categoryid=1 and name like '%保良局金銀業貿易場張凝文學校%';
update entity set  athleticsposfemale=10  where categoryid=1 and name like '%寶覺小學%';
update entity set  athleticsposfemale=111  where categoryid=1 and name like '%寶血小學%';
update entity set  athleticsposfemale=543  where categoryid=1 and name like '%培僑小學%';
update entity set  athleticsposfemale=55  where categoryid=1 and name like '%番禺會所華仁小學%';
update entity set  athleticsposfemale=210  where categoryid=1 and name like '%玫瑰崗學校（小學部）%';
update entity set  athleticsposfemale=329  where categoryid=1 and name like '%慈幼學校%';
update entity set  athleticsposfemale=85  where categoryid=1 and name like '%筲箕灣官立小學%';
update entity set  athleticsposfemale=374  where categoryid=1 and name like '%筲箕灣崇真學校%';
update entity set  athleticsposfemale=174  where categoryid=1 and name like '%官立嘉道理爵士小學%';
update entity set  athleticsposfemale=591.5  where categoryid=1 and name like '%聖公會柴灣聖米迦勒小學%';
update entity set  athleticsposfemale=615  where categoryid=1 and name like '%聖公會聖雅各小學%';
update entity set  athleticsposfemale=364  where categoryid=1 and name like '%聖公會聖米迦勒小學%';
update entity set  athleticsposfemale=169  where categoryid=1 and name like '%聖馬可小學%';
update entity set  athleticsposfemale=796  where categoryid=1 and name like '%聖保祿學校（小學部）%';
update entity set  athleticsposfemale=676  where categoryid=1 and name like '%聖保祿天主教小學%';
update entity set  athleticsposfemale=565  where categoryid=1 and name like '%聖士提反書院附屬小學%';
update entity set  athleticsposfemale=362  where categoryid=1 and name like '%太古小學%';
update entity set  athleticsposfemale=247  where categoryid=1 and name like '%勵志會梁李秀娛紀念小學%';
update entity set  athleticsposfemale=373  where categoryid=1 and name like '%香港中國婦女會丘佐榮學校%';
update entity set  athleticsposfemale=314  where categoryid=1 and name like '%救世軍韋理夫人紀念學校%';
update entity set  athleticsposfemale=153  where categoryid=1 and name like '%救世軍中原慈善基金學校%';
update entity set  athleticsposfemale=698  where categoryid=1 and name like '%香港真光中學（小學部）%';
-- update entity set  athleticsposfemale=0  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%己連拿小學%';
-- update entity set  athleticsposfemale=0  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%香港日本人學校%';
update entity set  athleticsposmale=726  where categoryid=1 and name like '%香港仔聖伯多祿天主教小學%';
update entity set  athleticsposmale=69  where categoryid=1 and name like '%鴨脷洲聖伯多祿天主教小學%';
update entity set  athleticsposmale=176  where categoryid=1 and name like '%鴨脷洲街坊學校%';
update entity set  athleticsposmale=517.5  where categoryid=1 and name like '%般咸道官立小學%';
-- update entity set  athleticsposmale=0  where   categoryid in (1,5) and athleticsposmale=0 and name like '%加拿大國際學校%';
update entity set  athleticsposmale=95  where categoryid=1 and name like '%天主教總堂區學校%';
update entity set  athleticsposmale=591  where categoryid=1 and name like '%中西區聖安多尼學校%';
update entity set  athleticsposmale=387  where categoryid=1 and name like '%香港潮商學校%';
-- update entity set  athleticsposmale=0  where   categoryid in (1,5) and athleticsposmale=0 and name like '%法國國際學校%';
update entity set  athleticsposmale=814  where categoryid=1 and name like '%軒尼詩道官立小學（上午）%';
update entity set  athleticsposmale=526  where categoryid=1 and name like '%軒尼詩道官立小學（下午）%';
update entity set  athleticsposmale=675  where categoryid=1 and name like '%香港南區官立小學%';
update entity set  athleticsposmale=187  where categoryid=1 and name like '%香島道官立小學%';
update entity set  athleticsposmale=582  where categoryid=1 and name like '%救恩學校%';
-- update entity set  athleticsposmale=0  where   categoryid in (1,5) and athleticsposfemale=0 and name like '%啟歷學校%';




update entity set  athleticsposmale=190  where categoryid=1 and name like '%英皇書院同學會小學%';
update entity set  athleticsposmale=599  where categoryid=1 and name like '%英皇書院同學會小學第二校%';
update entity set  athleticsposmale=443  where categoryid=1 and name like '%李陞小學%';
update entity set  athleticsposmale=472  where categoryid=1 and name like '%海怡寶血小學%';
update entity set  athleticsposmale=390  where categoryid=1 and name like '%華富邨寶血小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%嘉諾撒培德學校%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%嘉諾撒聖心學校%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%嘉諾撒聖心學校私立部%';
update entity set  athleticsposmale=10  where categoryid=1 and name like '%新會商會學校%';
-- update entity set  athleticsposmale=293  where   categoryid in (1,5) and athleticsposmale=0  and name like '%新加坡國際學校%';
update entity set  athleticsposmale=436  where categoryid=1 and name like '%聖公會置富始南小學%';
update entity set  athleticsposmale=687  where categoryid=1 and name like '%聖公會基恩小學%';
update entity set  athleticsposmale=395  where categoryid=1 and name like '%聖公會呂明才紀念小學%';
update entity set  athleticsposmale=276  where categoryid=1 and name like '%聖公會聖馬太小學%';
update entity set  athleticsposmale=308  where categoryid=1 and name like '%聖公會聖彼得小學（上午）%';
update entity set  athleticsposmale=266  where categoryid=1 and name like '%聖公會聖彼得小學（下午）%';
update entity set  athleticsposmale=753  where categoryid=1 and name like '%聖公會田灣始南小學%';
update entity set  athleticsposmale=224  where categoryid=1 and name like '%聖安多尼學校%';
update entity set  athleticsposmale=452  where categoryid=1 and name like '%聖嘉祿學校%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%聖嘉勒小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%嘉諾撒聖方濟各學校%';
update entity set  athleticsposmale=1070  where categoryid=1 and name like '聖若瑟小學';
update entity set  athleticsposmale=432  where categoryid=1 and name like '%聖類斯中學(小學部)%';
update entity set  athleticsposmale=693  where categoryid=1 and name like '%聖保羅男女中學附屬小學%';
update entity set  athleticsposmale=798  where categoryid=1 and name like '%聖保羅書院小學%';
update entity set  athleticsposmale=575  where categoryid=1 and name like '%聖伯多祿天主教小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%聖士提反女子中學附屬小學%';
update entity set  athleticsposmale=424  where categoryid=1 and name like '%港灣學校%';
update entity set  athleticsposmale=136  where categoryid=1 and name like '%東華三院鶴山學校%';
update entity set  athleticsposmale=264  where categoryid=1 and name like '%東華三院李賜豪小學%';
-- update entity set  athleticsposmale=451  where categoryid in (1,5) and athleticsposmale=0 and name like '%滬江維多利亞學校%';
-- update entity set  athleticsposmale=0  where   categoryid in (1,5) and athleticsposmale=0 and name like '%香港學堂國際學校%';
update entity set  athleticsposfemale=607  where categoryid=1 and name like '%香港仔聖伯多祿天主教小學%';
update entity set  athleticsposfemale=60  where categoryid=1 and name like '%鴨脷洲聖伯多祿天主教小學%';
update entity set  athleticsposfemale=45  where categoryid=1 and name like '%鴨脷洲街坊學校%';
update entity set  athleticsposfemale=233  where categoryid=1 and name like '%般咸道官立小學%';
-- update entity set  athleticsposfemale=0  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%加拿大國際學校%';
update entity set  athleticsposfemale=76  where categoryid=1 and name like '%天主教總堂區學校%';
update entity set  athleticsposfemale=409  where categoryid=1 and name like '%中西區聖安多尼學校%';
update entity set  athleticsposfemale=369  where categoryid=1 and name like '%香港潮商學校%';
-- update entity set  athleticsposfemale=23  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%法國國際學校%';
update entity set  athleticsposfemale=578  where categoryid=1 and name like '%軒尼詩道官立小學（上午）%';
update entity set  athleticsposfemale=372  where categoryid=1 and name like '%軒尼詩道官立小學（下午）%';
update entity set  athleticsposfemale=443  where categoryid=1 and name like '%香港南區官立小學%';
update entity set  athleticsposfemale=172  where categoryid=1 and name like '%香島道官立小學%';
update entity set  athleticsposfemale=206  where categoryid=1 and name like '%救恩學校%';
-- update entity set  athleticsposfemale=0  where   categoryid in (1,5) and athleticsposfemale=0 and name like '%啟歷學校%';





update entity set  athleticsposfemale=141  where categoryid=1 and name like '%英皇書院同學會小學%';
update entity set  athleticsposfemale=324  where categoryid=1 and name like '%英皇書院同學會小學第二校%';
update entity set  athleticsposfemale=223  where categoryid=1 and name like '%李陞小學%';
update entity set  athleticsposfemale=213  where categoryid=1 and name like '%海怡寶血小學%';
update entity set  athleticsposfemale=236  where categoryid=1 and name like '%華富邨寶血小學%';
update entity set  athleticsposfemale=334  where categoryid=1 and name like '%嘉諾撒培德學校%';
update entity set  athleticsposfemale=804  where categoryid=1 and name like '%嘉諾撒聖心學校%';
update entity set  athleticsposfemale=665  where categoryid=1 and name like '%嘉諾撒聖心學校私立部%';
update entity set  athleticsposfemale=10  where categoryid=1 and name like '%新會商會學校%';
-- update entity set  athleticsposfemale=293  where   categoryid in (1,5) and athleticsposfemale=0 and name like '%新加坡國際學校%';
update entity set  athleticsposfemale=383  where categoryid=1 and name like '%聖公會置富始南小學%';
update entity set  athleticsposfemale=509  where categoryid=1 and name like '%聖公會基恩小學%';
update entity set  athleticsposfemale=271  where categoryid=1 and name like '%聖公會呂明才紀念小學%';
update entity set  athleticsposfemale=179  where categoryid=1 and name like '%聖公會聖馬太小學%';
update entity set  athleticsposfemale=231  where categoryid=1 and name like '%聖公會聖彼得小學（上午）%';
update entity set  athleticsposfemale=109  where categoryid=1 and name like '%聖公會聖彼得小學（下午）%';
update entity set  athleticsposfemale=564  where categoryid=1 and name like '%聖公會田灣始南小學%';
update entity set  athleticsposfemale=160  where categoryid=1 and name like '%聖安多尼學校%';
update entity set  athleticsposfemale=264  where categoryid=1 and name like '%聖嘉祿學校%';
update entity set  athleticsposfemale=227  where categoryid=1 and name like '%聖嘉勒小學%';
update entity set  athleticsposfemale=348  where categoryid=1 and name like '%嘉諾撒聖方濟各學校%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '聖若瑟小學';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%聖類斯中學(小學部)%';
update entity set  athleticsposfemale=688  where categoryid=1 and name like '%聖保羅男女中學附屬小學%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%聖保羅書院小學%';
update entity set  athleticsposfemale=351  where categoryid=1 and name like '%聖伯多祿天主教小學%';
update entity set  athleticsposfemale=678  where categoryid=1 and name like '%聖士提反女子中學附屬小學%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%港灣學校%';
-- update entity set  athleticsposfemale=219  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%弘立書院%';
update entity set  athleticsposfemale=75  where categoryid=1 and name like '%東華三院鶴山學校%';
update entity set  athleticsposfemale=249  where categoryid=1 and name like '%東華三院李賜豪小學%';
-- update entity set  athleticsposfemale=368  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%滬江維多利亞學校%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%香港學堂國際學校%';
update entity set  athleticsposmale=693  where categoryid=1 and name like '%黃埔宣道小學%';
update entity set  athleticsposmale=451  where categoryid=1 and name like '%天主教柏德學校%';
update entity set  athleticsposmale=296  where categoryid=1 and name like '%佛教慈敬學校%';
update entity set  athleticsposmale=314  where categoryid=1 and name like '%迦密梁省德學校%';
update entity set  athleticsposmale=118  where categoryid=1 and name like '%中華基督教會基法小學%';
update entity set  athleticsposmale=810  where categoryid=1 and name like '%中華基督教會基法小學（油塘）%';
update entity set  athleticsposmale=266  where categoryid=1 and name like '%中華基督教會灣仔堂基道小學（九龍城）%';
update entity set  athleticsposmale=841  where categoryid=1 and name like '%陳瑞祺(喇沙)小學%';
update entity set  athleticsposmale=143  where categoryid=1 and name like '%浸信宣道會呂明才小學%';
update entity set  athleticsposmale=1159  where categoryid=1 and name like '%拔萃男書院附屬小學%';
update entity set  athleticsposmale=237  where categoryid=1 and name like '%基督教香港信義會紅磡信義學校%';
update entity set  athleticsposmale=279  where categoryid=1 and name like '%九龍靈光小學%';
update entity set  athleticsposmale=644  where categoryid=1 and name like '%農圃道官立小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%神召第一小學暨幼稚園%';
update entity set  athleticsposmale=622  where categoryid=1 and name like '%福建中學附屬學校%';
update entity set  athleticsposmale=866  where categoryid=1 and name like '%葛量洪校友會黃埔學校%';
update entity set  athleticsposmale=370  where categoryid=1 and name like '%香港道教聯合會圓玄學院陳呂重德紀念學校%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%協恩中學附屬小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%天神嘉諾撒學校%';
update entity set  athleticsposmale=142  where categoryid=1 and name like '%聖匠小學%';
update entity set  athleticsposmale=295  where categoryid=1 and name like '%聖三一堂小學%';
update entity set  athleticsposmale=176  where categoryid=1 and name like '%香港道教聯合會雲泉學校%';
update entity set  athleticsposmale=427  where categoryid=1 and name like '%合一堂學校%';
update entity set  athleticsposmale=487  where categoryid=1 and name like '%佐敦谷聖若瑟天主教小學%';
update entity set  athleticsposmale=517  where categoryid=1 and name like '%九龍灣聖若翰天主教小學%';
-- update entity set  athleticsposmale=0  where   categoryid in (1,5) and athleticsposmale=0 and name like '%九龍小學%';
update entity set  athleticsposmale=256  where categoryid=1 and name like '%觀塘官立小學%';
update entity set  athleticsposmale=198  where categoryid=1 and name like '%觀塘官立小學（秀明道）%';
update entity set  athleticsposmale=510  where categoryid=1 and name like '%藍田循道衛理小學%';
update entity set  athleticsposmale=305  where categoryid=1 and name like '%天主教領島學校%';
update entity set  athleticsposmale=140  where categoryid=1 and name like '%樂善堂楊仲明學校%';
update entity set  athleticsposmale=376.5  where categoryid=1 and name like '%樂華天主教小學%';
update entity set  athleticsposmale=653  where categoryid=1 and name like '%馬頭涌官立小學%';
update entity set  athleticsposmale=1012  where categoryid=1 and name like '%馬頭涌官立小學（紅磡灣）%';
update entity set  athleticsposmale=508  where categoryid=1 and name like '%閩僑小學%';
update entity set  athleticsposmale=262  where categoryid=1 and name like '%獻主會小學%';
update entity set  athleticsposmale=462  where categoryid=1 and name like '%天主教佑華小學%';




update entity set  athleticsposmale=211  where categoryid=1 and name like '%坪石天主教小學%';
update entity set  athleticsposmale=204  where categoryid=1 and name like '%保良局林文燦英文小學%';
update entity set  athleticsposmale=445  where categoryid=1 and name like '%香港培道小學%';
update entity set  athleticsposmale=997  where categoryid=1 and name like '%香港培正小學%';
update entity set  athleticsposmale=588  where categoryid=1 and name like '%秀茂坪天主教小學%';
update entity set  athleticsposmale=397  where categoryid=1 and name like '%秀明小學%';
update entity set  athleticsposmale=973  where categoryid=1 and name like '%聖公會奉基千禧小學%';
update entity set  athleticsposmale=935  where categoryid=1 and name like '%聖公會奉基小學%';
update entity set  athleticsposmale=326  where categoryid=1 and name like '%聖公會牧愛小學%';
update entity set  athleticsposmale=633  where categoryid=1 and name like '%聖公會基顯小學%';
update entity set  athleticsposmale=448  where categoryid=1 and name like '%聖公會基樂小學%';
update entity set  athleticsposmale=689  where categoryid=1 and name like '%聖公會九龍灣基樂小學%';
update entity set  athleticsposmale=722  where categoryid=1 and name like '%聖公會李兆強小學%';
update entity set  athleticsposmale=215  where categoryid=1 and name like '%聖公會聖約翰小學%';
update entity set  athleticsposmale=529  where categoryid=1 and name like '%聖公會聖提摩太小學%';
update entity set  athleticsposmale=941  where categoryid=1 and name like '%聖公會德田李兆強小學%';
update entity set  athleticsposmale=765  where categoryid=1 and name like '%聖公會油塘基顯小學%';
update entity set  athleticsposmale=399  where categoryid=1 and name like '%聖安當小學%';
update entity set  athleticsposmale=920  where categoryid=1 and name like '%聖愛德華天主教小學%';
update entity set  athleticsposmale=228  where categoryid=1 and name like '%獻主會聖馬善樂小學%';
update entity set  athleticsposmale=202  where categoryid=1 and name like '%聖若翰天主教小學%';
update entity set  athleticsposmale=661  where categoryid=1 and name like '%聖若瑟英文小學%';
update entity set  athleticsposmale=297  where categoryid=1 and name like '%路德會聖馬太學校(秀茂坪)%';
update entity set  athleticsposmale=658  where categoryid=1 and name like '%聖羅撒學校%';
update entity set  athleticsposmale=50  where categoryid=1 and name like '%香港扶幼會盛德中心學校%';
update entity set  athleticsposfemale=518  where categoryid=1 and name like '%黃埔宣道小學%';
update entity set  athleticsposfemale=366  where categoryid=1 and name like '%天主教柏德學校%';
update entity set  athleticsposfemale=166  where categoryid=1 and name like '%佛教慈敬學校%';
update entity set  athleticsposfemale=253  where categoryid=1 and name like '%迦密梁省德學校%';
update entity set  athleticsposfemale=109  where categoryid=1 and name like '%中華基督教會基法小學%';
update entity set  athleticsposfemale=544  where categoryid=1 and name like '%中華基督教會基法小學（油塘）%';
update entity set  athleticsposfemale=182  where categoryid=1 and name like '%中華基督教會灣仔堂基道小學（九龍城）%';
update entity set  athleticsposfemale=393  where categoryid=1 and name like '%陳瑞祺(喇沙)小學%';
update entity set  athleticsposfemale=191  where categoryid=1 and name like '%浸信宣道會呂明才小學%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%拔萃男書院附屬小學%';
update entity set  athleticsposfemale=61  where categoryid=1 and name like '%基督教香港信義會紅磡信義學校%';
update entity set  athleticsposfemale=214  where categoryid=1 and name like '%九龍靈光小學%';
update entity set  athleticsposfemale=257  where categoryid=1 and name like '%農圃道官立小學%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%神召第一小學暨幼稚園%';
update entity set  athleticsposfemale=458  where categoryid=1 and name like '%福建中學附屬學校%';
update entity set  athleticsposfemale=556  where categoryid=1 and name like '%葛量洪校友會黃埔學校%';
update entity set  athleticsposfemale=226  where categoryid=1 and name like '%香港道教聯合會圓玄學院陳呂重德紀念學校%';
update entity set  athleticsposfemale=1129  where categoryid=1 and name like '%協恩中學附屬小學%';
update entity set  athleticsposfemale=295  where categoryid=1 and name like '%天神嘉諾撒學校%';
update entity set  athleticsposfemale=69  where categoryid=1 and name like '%聖匠小學%';
update entity set  athleticsposfemale=185  where categoryid=1 and name like '%聖三一堂小學%';
update entity set  athleticsposfemale=126  where categoryid=1 and name like '%香港道教聯合會雲泉學校%';
update entity set  athleticsposfemale=245  where categoryid=1 and name like '%合一堂學校%';
update entity set  athleticsposfemale=318  where categoryid=1 and name like '%佐敦谷聖若瑟天主教小學%';
update entity set  athleticsposfemale=262  where categoryid=1 and name like '%九龍灣聖若翰天主教小學%';
update entity set  athleticsposfemale=268  where categoryid=1 and name like '%觀塘官立小學%';
update entity set  athleticsposfemale=87  where categoryid=1 and name like '%觀塘官立小學（秀明道）%';
update entity set  athleticsposfemale=349  where categoryid=1 and name like '%藍田循道衛理小學%';
update entity set  athleticsposfemale=171  where categoryid=1 and name like '%天主教領島學校%';
update entity set  athleticsposfemale=78  where categoryid=1 and name like '%樂善堂楊仲明學校%';
update entity set  athleticsposfemale=342  where categoryid=1 and name like '%樂華天主教小學%';
update entity set  athleticsposfemale=356  where categoryid=1 and name like '%馬頭涌官立小學%';
update entity set  athleticsposfemale=918  where categoryid=1 and name like '%馬頭涌官立小學（紅磡灣）%';



update entity set  athleticsposfemale=123  where categoryid=1 and name like '%閩僑小學%';
update entity set  athleticsposfemale=70  where categoryid=1 and name like '%獻主會小學%';
update entity set  athleticsposfemale=364  where categoryid=1 and name like '%天主教佑華小學%';
update entity set  athleticsposfemale=124  where categoryid=1 and name like '%坪石天主教小學%';
update entity set  athleticsposfemale=205  where categoryid=1 and name like '%保良局林文燦英文小學%';
update entity set  athleticsposfemale=406  where categoryid=1 and name like '%香港培道小學%';
update entity set  athleticsposfemale=616  where categoryid=1 and name like '%香港培正小學%';
update entity set  athleticsposfemale=245  where categoryid=1 and name like '%秀茂坪天主教小學%';
update entity set  athleticsposfemale=182  where categoryid=1 and name like '%秀明小學%';
update entity set  athleticsposfemale=897  where categoryid=1 and name like '%聖公會奉基千禧小學%';
update entity set  athleticsposfemale=713  where categoryid=1 and name like '%聖公會奉基小學%';
update entity set  athleticsposfemale=362  where categoryid=1 and name like '%聖公會牧愛小學%';
update entity set  athleticsposfemale=475  where categoryid=1 and name like '%聖公會基顯小學%';
update entity set  athleticsposfemale=332  where categoryid=1 and name like '%聖公會基樂小學%';
update entity set  athleticsposfemale=376  where categoryid=1 and name like '%聖公會九龍灣基樂小學%';
update entity set  athleticsposfemale=652  where categoryid=1 and name like '%聖公會李兆強小學%';
update entity set  athleticsposfemale=395  where categoryid=1 and name like '%聖公會聖約翰小學%';
update entity set  athleticsposfemale=276  where categoryid=1 and name like '%聖公會聖提摩太小學%';
update entity set  athleticsposfemale=875  where categoryid=1 and name like '%聖公會德田李兆強小學%';
update entity set  athleticsposfemale=467  where categoryid=1 and name like '%聖公會油塘基顯小學%';
update entity set  athleticsposfemale=512  where categoryid=1 and name like '%聖安當小學%';
update entity set  athleticsposfemale=785  where categoryid=1 and name like '%聖愛德華天主教小學%';
update entity set  athleticsposfemale=205  where categoryid=1 and name like '%獻主會聖馬善樂小學%';
update entity set  athleticsposfemale=139  where categoryid=1 and name like '%聖若翰天主教小學%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%聖若瑟英文小學%';
update entity set  athleticsposfemale=138  where categoryid=1 and name like '%路德會聖馬太學校（秀茂坪）%';
update entity set  athleticsposfemale=851  where categoryid=1 and name like '%聖羅撒學校%';
update entity set  athleticsposfemale=238  where categoryid=1 and name like '%基督教聖約教會堅樂小學%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%香港扶幼會盛德中心學校%';
update entity set  athleticsposmale=748  where categoryid=1 and name like '%大坑東宣道小學%';
update entity set  athleticsposmale=170  where categoryid=1 and name like '%廣東道官立小學%';
update entity set  athleticsposmale=847  where categoryid=1 and name like '%中華基督教會協和小學%';
update entity set  athleticsposmale=770  where categoryid=1 and name like '%中華基督教會協和小學(長沙灣)%';
update entity set  athleticsposmale=166  where categoryid=1 and name like '%中華基督教會基全小學%';
update entity set  athleticsposmale=105  where categoryid=1 and name like '%中華基督教會灣仔堂基道小學%';
update entity set  athleticsposmale=539  where categoryid=1 and name like '%啟基學校%';






update entity set  athleticsposmale=217  where categoryid=1 and name like '%地利亞英文小學暨幼稚園%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%拔萃女小學%';
update entity set  athleticsposmale=180  where categoryid=1 and name like '%五邑工商總會學校%';
update entity set  athleticsposmale=352  where categoryid=1 and name like '%鮮魚行學校%';
update entity set  athleticsposmale=149  where categoryid=1 and name like '%福榮街官立小學%';
update entity set  athleticsposmale=274  where categoryid=1 and name like '%天主教善導小學%';
update entity set  athleticsposmale=731  where categoryid=1 and name like '%旅港開平商會學校%';
update entity set  athleticsposmale=214  where categoryid=1 and name like '%佐敦道官立小學%';
update entity set  athleticsposmale=70  where categoryid=1 and name like '%九龍婦女福利會李炳紀念學校%';
update entity set  athleticsposmale=403  where categoryid=1 and name like '%寶血會嘉靈學校%';
update entity set  athleticsposmale=428  where categoryid=1 and name like '%九龍禮賢學校%';
update entity set  athleticsposmale=605  where categoryid=1 and name like '%荔枝角天主教小學%';
update entity set  athleticsposmale=314  where categoryid=1 and name like '%李鄭屋官立小學%';
update entity set  athleticsposmale=343  where categoryid=1 and name like '%嶺南大學香港同學會直資小學%';
update entity set  athleticsposmale=726  where categoryid=1 and name like '%瑪利諾神父教會學校(小學部)%';
update entity set  athleticsposmale=535  where categoryid=1 and name like '循道學校';
update entity set  athleticsposmale=512  where categoryid=1 and name like '%白田天主教小學%';
update entity set  athleticsposmale=846  where categoryid=1 and name like '%保良局陳守仁小學%';
update entity set  athleticsposmale=503  where categoryid=1 and name like '%保良局蔡繼有學校%';
update entity set  athleticsposmale=167  where categoryid=1 and name like '%保良局陳維周夫人紀念小學%';
update entity set  athleticsposmale=444  where categoryid=1 and name like '%深水埗官立小學%';
update entity set  athleticsposmale=239  where categoryid=1 and name like '%深水埔街坊福利會小學%';
update entity set  athleticsposmale=73  where categoryid=1 and name like '%路德會沙崙學校%';
update entity set  athleticsposmale=225.5  where categoryid=1 and name like '%聖公會基福小學%';
update entity set  athleticsposmale=387  where categoryid=1 and name like '%聖公會基愛小學%';
update entity set  athleticsposmale=218  where categoryid=1 and name like '%聖公會基榮小學%';
update entity set  athleticsposmale=651  where categoryid=1 and name like '%聖公會聖安德烈小學%';
update entity set  athleticsposmale=678  where categoryid=1 and name like '%聖公會聖紀文小學%';
update entity set  athleticsposmale=328  where categoryid=1 and name like '%聖公會聖多馬小學%';
update entity set  athleticsposmale=459  where categoryid=1 and name like '%香港扶幼會則仁中心學校%';
update entity set  athleticsposmale=478  where categoryid=1 and name like '%聖方濟愛德小學%';
update entity set  athleticsposmale=943  where categoryid=1 and name like '%聖方濟各英文小學%';
update entity set  athleticsposmale=374  where categoryid=1 and name like '%聖瑪加利男女英文中小學%';
update entity set  athleticsposmale=122  where categoryid=1 and name like '%嘉諾撒聖瑪利學校%';
update entity set  athleticsposmale=440  where categoryid=1 and name like '%大角嘴天主教小學%';
update entity set  athleticsposmale=727  where categoryid=1 and name like '%大角嘴天主教小學（海帆道）%';
update entity set  athleticsposmale=23  where categoryid=1 and name like '%德雅小學%';
update entity set  athleticsposmale=665  where categoryid=1 and name like '%德信學校%';
update entity set  athleticsposmale=332  where categoryid=1 and name like '%基督教香港信義會深信學校%';
update entity set  athleticsposmale=165  where categoryid=1 and name like '%香港四邑商工總會新會商會學校%';
update entity set  athleticsposmale=134  where categoryid=1 and name like '%東莞同鄉會方樹泉學校%';
update entity set  athleticsposmale=223  where categoryid=1 and name like '%塘尾道官立小學%';
update entity set  athleticsposmale=729  where categoryid=1 and name like '%崇真小學暨幼稚園%';
update entity set  athleticsposmale=484  where categoryid=1 and name like '%東華三院羅裕積小學%';
update entity set  athleticsposmale=564  where categoryid=1 and name like '%油蔴地天主教小學%';
update entity set  athleticsposmale=808.5  where categoryid=1 and name like '%油蔴地天主教小學（海泓道）%';
update entity set  athleticsposmale=283  where categoryid=1 and name like '%油蔴地街坊會學校%';
update entity set  athleticsposmale=1063  where categoryid=1 and name like '%英華小學%';
update entity set  athleticsposfemale=565  where categoryid=1 and name like '%大坑東宣道小學%';
update entity set  athleticsposfemale=124  where categoryid=1 and name like '%廣東道官立小學%';
update entity set  athleticsposfemale=776.5  where categoryid=1 and name like '%中華基督教會協和小學%';
update entity set  athleticsposfemale=660  where categoryid=1 and name like '%中華基督教會協和小學 (長沙灣)%';
update entity set  athleticsposfemale=87  where categoryid=1 and name like '%中華基督教會基全小學%';
update entity set  athleticsposfemale=87  where categoryid=1 and name like '%中華基督教會灣仔堂基道小學%';
update entity set  athleticsposfemale=281  where categoryid=1 and name like '啟基學校';
update entity set  athleticsposfemale=21  where categoryid=1 and name like '%地利亞英文小學暨幼稚園%';
update entity set  athleticsposfemale=933  where categoryid=1 and name like '%拔萃女小學%';



update entity set  athleticsposfemale=141  where categoryid=1 and name like '%五邑工商總會學校%';
update entity set  athleticsposfemale=127  where categoryid=1 and name like '%鮮魚行學校%';
update entity set  athleticsposfemale=33  where categoryid=1 and name like '%福榮街官立小學%';
update entity set  athleticsposfemale=385  where categoryid=1 and name like '%天主教善導小學%';
update entity set  athleticsposfemale=392  where categoryid=1 and name like '%旅港開平商會學校%';
update entity set  athleticsposfemale=96  where categoryid=1 and name like '%佐敦道官立小學%';
update entity set  athleticsposfemale=24  where categoryid=1 and name like '%九龍婦女福利會李炳紀念學校%';
update entity set  athleticsposfemale=251  where categoryid=1 and name like '%寶血會嘉靈學校%';
update entity set  athleticsposfemale=311.5  where categoryid=1 and name like '%九龍禮賢學校%';
update entity set  athleticsposfemale=494  where categoryid=1 and name like '%荔枝角天主教小學%';
update entity set  athleticsposfemale=203  where categoryid=1 and name like '%李鄭屋官立小學%';
update entity set  athleticsposfemale=104  where categoryid=1 and name like '%嶺南大學香港同學會直資小學%';
update entity set  athleticsposfemale=674  where categoryid=1 and name like '%瑪利諾神父教會學校(小學部)%';
update entity set  athleticsposfemale=199.5  where categoryid=1 and name like '循道學校';
update entity set  athleticsposfemale=411  where categoryid=1 and name like '%白田天主教小學%';
update entity set  athleticsposfemale=792  where categoryid=1 and name like '%保良局陳守仁小學%';
update entity set  athleticsposfemale=368  where categoryid=1 and name like '%保良局蔡繼有學校%';
update entity set  athleticsposfemale=15  where categoryid=1 and name like '%保良局陳維周夫人紀念小學%';
update entity set  athleticsposfemale=178  where categoryid=1 and name like '%深水埗官立小學%';
update entity set  athleticsposfemale=185  where categoryid=1 and name like '%深水埔街坊福利會小學%';
update entity set  athleticsposfemale=60  where categoryid=1 and name like '%路德會沙崙學校%';
update entity set  athleticsposfemale=306  where categoryid=1 and name like '%聖公會基福小學%';
update entity set  athleticsposfemale=207  where categoryid=1 and name like '%聖公會基愛小學%';
update entity set  athleticsposfemale=233  where categoryid=1 and name like '%聖公會基榮小學%';
update entity set  athleticsposfemale=725  where categoryid=1 and name like '%聖公會聖安德烈小學%';
update entity set  athleticsposfemale=370  where categoryid=1 and name like '%聖公會聖紀文小學%';
update entity set  athleticsposfemale=150  where categoryid=1 and name like '%聖公會聖多馬小學%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%香港扶幼會則仁中心學校%';
update entity set  athleticsposfemale=249  where categoryid=1 and name like '%聖方濟愛德小學%';
update entity set  athleticsposfemale=625.5  where categoryid=1 and name like '%聖方濟各英文小學%';
update entity set  athleticsposfemale=370.5  where categoryid=1 and name like '%聖瑪加利男女英文中小學%';
update entity set  athleticsposfemale=237  where categoryid=1 and name like '%嘉諾撒聖瑪利學校%';
update entity set  athleticsposfemale=71  where categoryid=1 and name like '%德貞小學%';
update entity set  athleticsposfemale=169  where categoryid=1 and name like '大角嘴天主教小學';
update entity set  athleticsposfemale=706  where categoryid=1 and name like '%大角嘴天主教小學（海帆道）%';
update entity set  athleticsposfemale=76  where categoryid=1 and name like '%德雅小學%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%德信學校%';
update entity set  athleticsposfemale=81  where categoryid=1 and name like '%基督教香港信義會深信學校%';
update entity set  athleticsposfemale=60  where categoryid=1 and name like '%香港四邑商工總會新會商會學校%';
update entity set  athleticsposfemale=139  where categoryid=1 and name like '%東莞同鄉會方樹泉學校%';
update entity set  athleticsposfemale=92  where categoryid=1 and name like '%塘尾道官立小學%';
update entity set  athleticsposfemale=550  where categoryid=1 and name like '%崇真小學暨幼稚園%';
update entity set  athleticsposfemale=283  where categoryid=1 and name like '%東華三院羅裕積小學%';
update entity set  athleticsposfemale=433  where categoryid=1 and name like '油蔴地天主教小學';
update entity set  athleticsposfemale=651  where categoryid=1 and name like '%油蔴地天主教小學（海泓道）%';
update entity set  athleticsposfemale=75  where categoryid=1 and name like '%油蔴地街坊會學校%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%英華小學%';
update entity set  athleticsposmale=977  where categoryid=1 and name like '%九龍塘宣道小學%';
-- update entity set  athleticsposmale=65  where   categoryid in (1,5) and athleticsposmale=0 and name like '%香港澳洲國際學校%';
update entity set  athleticsposmale=62  where categoryid=1 and name like '%浸信會天虹小學%';
-- update entity set  athleticsposmale=0  where   categoryid in (1,5) and athleticsposmale=0 and name like '%畢架山小學%';
update entity set  athleticsposmale=430  where categoryid=1 and name like '%福德學校%';
update entity set  athleticsposmale=649  where categoryid=1 and name like '華德學校';
update entity set  athleticsposmale=574  where categoryid=1 and name like '嘉諾撒小學';
update entity set  athleticsposmale=653  where categoryid=1 and name like '%嘉諾撒小學（新蒲崗）%';
update entity set  athleticsposmale=316  where categoryid=1 and name like '%中華基督教會基慈小學%';
update entity set  athleticsposmale=202  where categoryid=1 and name like '中華基督教會基華小學';
update entity set  athleticsposmale=479  where categoryid=1 and name like '%中華基督教會基華小學(九龍塘)%';
update entity set  athleticsposmale=513  where categoryid=1 and name like '%彩雲聖若瑟小學%';
update entity set  athleticsposmale=570  where categoryid=1 and name like '%真鐸學校%';
update entity set  athleticsposmale=175  where categoryid=1 and name like '%孔教學院大成小學%';
update entity set  athleticsposmale=765  where categoryid=1 and name like '%啟思小學%';
update entity set  athleticsposmale=635  where categoryid=1 and name like '%拔萃小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%德望學校（小學部）%';
update entity set  athleticsposmale=748  where categoryid=1 and name like '%嗇色園主辦可立小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '嘉諾撒聖家學校';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%嘉諾撒聖家學校（九龍塘）%';
update entity set  athleticsposmale=155  where categoryid=1 and name like '%國際基督教優質音樂中學暨小學%';
update entity set  athleticsposmale=202  where categoryid=1 and name like '%伊斯蘭鮑伯濤紀念小學%';
update entity set  athleticsposmale=260  where categoryid=1 and name like '%耀山學校%';
-- update entity set  athleticsposmale=0  where   categoryid in (1,5) and athleticsposmale=0  and name like '京斯頓國際學校';
update entity set  athleticsposmale=580  where categoryid=1 and name like '%九龍塘天主教華德學校%';
update entity set  athleticsposmale=630  where categoryid=1 and name like '%九龍塘官立小學%';
update entity set  athleticsposmale=1106  where categoryid=1 and name like '%九龍塘學校（小學部）%';
update entity set  athleticsposmale=21  where categoryid=1 and name like '%九龍真光中學（小學部）%';
update entity set  athleticsposmale=1082  where categoryid=1 and name like '%喇沙小學%';
update entity set  athleticsposmale=49  where categoryid=1 and name like '%樂善堂小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%瑪利諾修院學校（小學部）%';
update entity set  athleticsposmale=628  where categoryid=1 and name like '%民生書院（小學部）%';
update entity set  athleticsposmale=414  where categoryid=1 and name like '%天主教伍華小學%';
update entity set  athleticsposmale=0  where categoryid=1 and name like '%聖母小學%';
update entity set  athleticsposmale=731  where categoryid=1 and name like '%保良局錦泰小學%';
update entity set  athleticsposmale=69  where categoryid=1 and name like '%保良局陳南昌夫人小學%';
update entity set  athleticsposmale=588  where categoryid=1 and name like '%保良局何壽南小學%';
update entity set  athleticsposmale=390  where categoryid=1 and name like '%獻主會溥仁小學%';
update entity set  athleticsposmale=240  where categoryid=1 and name like '%天主教博智小學%';
update entity set  athleticsposmale=170  where categoryid=1 and name like '%聖公會靜山小學%';
update entity set  athleticsposmale=446  where categoryid=1 and name like '%聖公會基德小學%';
update entity set  athleticsposmale=241  where categoryid=1 and name like '%聖公會日修小學%';
update entity set  athleticsposmale=704  where categoryid=1 and name like '聖文德天主教小學';
update entity set  athleticsposmale=519  where categoryid=1 and name like '%聖博德天主教小學（蒲崗村道）%';
update entity set  athleticsposmale=355  where categoryid=1 and name like '%聖博德學校%';



update entity set  athleticsposmale=478  where categoryid=1 and name like '%慈雲山聖文德天主教小學%';
update entity set  athleticsposmale=412  where categoryid=1 and name like '%慈雲山天主教小學%';
update entity set  athleticsposmale=450  where categoryid=1 and name like '%黃大仙天主教小學%';
update entity set  athleticsposmale=285  where categoryid=1 and name like '%黃大仙官立小學%';
update entity set  athleticsposfemale=721  where categoryid=1 and name like '%九龍塘宣道小學%';
-- update entity set  athleticsposfemale=106  where   categoryid in (1,5) and athleticsposfemale=0 and name like '%香港澳洲國際學校%';
update entity set  athleticsposfemale=59  where categoryid=1 and name like '%浸信會天虹小學%';
-- update entity set  athleticsposfemale=0  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%畢架山小學%';
update entity set  athleticsposfemale=215  where categoryid=1 and name like '%福德學校%';
update entity set  athleticsposfemale=368  where categoryid=1 and name like '%華德學校%';
update entity set  athleticsposfemale=428  where categoryid=1 and name like '%嘉諾撒小學%';
update entity set  athleticsposfemale=696  where categoryid=1 and name like '%嘉諾撒小學（新蒲崗）%';
update entity set  athleticsposfemale=141  where categoryid=1 and name like '%中華基督教會基慈小學%';
update entity set  athleticsposfemale=104  where categoryid=1 and name like '%中華基督教會基華小學%';
update entity set  athleticsposfemale=407  where categoryid=1 and name like '%中華基督教會基華小學(九龍塘)%';
update entity set  athleticsposfemale=412  where categoryid=1 and name like '%彩雲聖若瑟小學%';
update entity set  athleticsposfemale=359  where categoryid=1 and name like '%真鐸學校%';
update entity set  athleticsposfemale=155  where categoryid=1 and name like '%孔教學院大成小學%';
update entity set  athleticsposfemale=482  where categoryid=1 and name like '%啟思小學%';
update entity set  athleticsposfemale=236  where categoryid=1 and name like '%拔萃小學%';
update entity set  athleticsposfemale=967  where categoryid=1 and name like '%德望學校（小學部）%';
update entity set  athleticsposfemale=580  where categoryid=1 and name like '%嗇色園主辦可立小學%';
update entity set  athleticsposfemale=430.5  where categoryid=1 and name like '嘉諾撒聖家學校';
update entity set  athleticsposfemale=409  where categoryid=1 and name like '%嘉諾撒聖家學校（九龍塘）%';
update entity set  athleticsposfemale=22  where categoryid=1 and name like '%國際基督教優質音樂中學暨小學%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%伊斯蘭鮑伯濤紀念小學%';
update entity set  athleticsposfemale=186  where categoryid=1 and name like '%耀山學校%';
-- update entity set  athleticsposfemale=0  where   categoryid in (1,5)  and athleticsposfemale=0 and name like '%京斯頓國際學校%';
update entity set  athleticsposfemale=432  where categoryid=1 and name like '%九龍塘天主教華德學校%';
update entity set  athleticsposfemale=446  where categoryid=1 and name like '%九龍塘官立小學%';
update entity set  athleticsposfemale=830  where categoryid=1 and name like '%九龍塘學校（小學部）%';
update entity set  athleticsposfemale=41  where categoryid=1 and name like '%九龍真光中學（小學部）%';
update entity set  athleticsposfemale=0  where categoryid=1 and name like '%喇沙小學%';
update entity set  athleticsposfemale=10  where categoryid=1 and name like '%樂善堂小學%';
update entity set  athleticsposfemale=538  where categoryid=1 and name like '%瑪利諾修院學校（小學部）%';
update entity set  athleticsposfemale=415  where categoryid=1 and name like '%民生書院（小學部）%';
update entity set  athleticsposfemale=66  where categoryid=1 and name like '%天主教伍華小學%';
update entity set  athleticsposfemale=289  where categoryid=1 and name like '%聖母小學%';
update entity set  athleticsposfemale=551  where categoryid=1 and name like '%保良局錦泰小學%';
update entity set  athleticsposfemale=60  where categoryid=1 and name like '%保良局陳南昌夫人小學%';
update entity set  athleticsposfemale=371  where categoryid=1 and name like '%保良局何壽南小學%';
update entity set  athleticsposfemale=200  where categoryid=1 and name like '%獻主會溥仁小學%';
update entity set  athleticsposfemale=115  where categoryid=1 and name like '%天主教博智小學%';
update entity set  athleticsposfemale=135  where categoryid=1 and name like '%聖公會靜山小學%';
update entity set  athleticsposfemale=371  where categoryid=1 and name like '%聖公會基德小學%';
update entity set  athleticsposfemale=169  where categoryid=1 and name like '%聖公會日修小學%';
update entity set  athleticsposfemale=497  where categoryid=1 and name like '聖文德天主教小學';
update entity set  athleticsposfemale=338  where categoryid=1 and name like '%聖博德天主教小學（蒲崗村道）%';
update entity set  athleticsposfemale=337  where categoryid=1 and name like '%聖博德學校%';
update entity set  athleticsposfemale=274  where categoryid=1 and name like '%慈雲山聖文德天主教小學%';
update entity set  athleticsposfemale=207  where categoryid=1 and name like '%慈雲山天主教小學%';
update entity set  athleticsposfemale=396  where categoryid=1 and name like '%黃大仙天主教小學%';
update entity set  athleticsposfemale=60  where categoryid=1 and name like '%黃大仙官立小學%';




update entityscore es, entity e set es.athleticsposmale=e.athleticsposmale,es.athleticsposfemale=e.athleticsposfemale where es.entityid=e.id and es.year=2013 and e.categoryid in (1) ;




