update entity set athleticsdivmale=0, athleticsposmale =0, athleticsdivfemale =0, athleticsposfemale =0, swimmingdivmale = 0, swimmingdivfemale = 0, swimmingposmale = 0, swimmingposfemale = 0, basketballdivmale = 0, basketballdivfemale = 0, basketballposmale = 0,basketballposfemale = 0, footballdiv = 0, footballpos = 0  where categoryid in (2,5);

update entity set athleticsdivfemale=1, athleticsposfemale=1  where lower(nameeng) = lower('Diocesan Girls'' School') and categoryid=2;
update entity set athleticsdivfemale=1, athleticsposfemale=2  where lower(nameeng) = lower('Good Hope School') and categoryid=2;
update entity set athleticsdivfemale=1, athleticsposfemale=3  where lower(nameeng) = lower('Heep Yunn School') and categoryid=2;
update entity set athleticsdivfemale=1, athleticsposfemale=4  where lower(nameeng) = lower('St. Paul''s Convent School') and categoryid=2;
update entity set athleticsdivfemale=1, athleticsposfemale=5  where lower(nameeng) = lower('Maryknoll Convent School (Secondary Section)') and categoryid=2;
update entity set athleticsdivfemale=1, athleticsposfemale=6  where lower(nameeng) = lower('West Island School') and categoryid=5;
update entity set athleticsdivfemale=1, athleticsposfemale=7  where lower(nameeng) = lower('HKUGA College') and categoryid=2;
update entity set athleticsdivfemale=1, athleticsposfemale=8  where lower(nameeng) = lower('King George V School') and categoryid=5;
update entity set athleticsdivfemale=1, athleticsposfemale=9  where lower(nameeng) = lower('St. Clare''s Girls'' School') and categoryid=2;
update entity set athleticsdivfemale=1, athleticsposfemale=10  where lower(nameeng) = lower('TWGHs Wong Fut Nam College') and categoryid=2;
update entity set athleticsdivfemale=1, athleticsposfemale=11  where lower(nameeng) = lower('Pui Ching Middle School') and categoryid=2;
update entity set athleticsdivfemale=1, athleticsposfemale=12  where lower(nameeng) = lower('St. Margaret''s Co-Educational English Secondary and Primary School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=1  where lower(nameeng) = lower('St. Stephen''s Girls'' College') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=2  where lower(nameeng) = lower('Hoi Ping Chamber of Commerce Secondary School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=3  where lower(nameeng) = lower('True Light Middle School of Hong Kong') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=4  where lower(nameeng) = lower('South Island School') and categoryid=5;
update entity set athleticsdivfemale=2, athleticsposfemale=5  where lower(nameeng) = lower('Marymount Secondary School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=5  where lower(nameeng) = lower('Ying Wa Girls'' School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=7  where lower(nameeng) = lower('Fukien Secondary School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=8  where lower(nameeng) = lower('Island School') and categoryid=5;
update entity set athleticsdivfemale=2, athleticsposfemale=9  where lower(nameeng) = lower('Christian & Missionary Alliance Sun Kei Secondary School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=10  where lower(nameeng) = lower('TWGHs Chang Ming Thien College') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=11  where lower(nameeng) = lower('Hotung Secondary School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=12  where lower(nameeng) = lower('HKCCCU Logos Academy') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=13  where lower(nameeng) = lower('S.K.H. St. Mary''s Church Mok Hing Yiu College') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=14  where lower(nameeng) = lower('Sacred Heart Canossian College') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=15  where lower(nameeng) = lower('St. Stephen''s College') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=16  where lower(nameeng) = lower('St. Mary''s Canossian College') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=17  where lower(nameeng) = lower('Hong Kong True Light College') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=18  where lower(nameeng) = lower('Creative Secondary School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=18  where lower(nameeng) = lower('Pooi To Middle School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=20  where lower(nameeng) = lower('St. Teresa Secondary School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=21  where lower(nameeng) = lower('Holy Trinity College') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=22  where lower(nameeng) = lower('Yan Chai Hospital Law Chan Chor Si College') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=23  where lower(nameeng) = lower('Concordia Lutheran School') and categoryid=2;
update entity set athleticsdivfemale=2, athleticsposfemale=23  where lower(nameeng) = lower('PLK Ngan Po Ling College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=1  where lower(nameeng) = lower('Po Leung Kuk Choi Kai Yau School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=1  where lower(nameeng) = lower('St. Paul''s Co-Educational College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=1  where lower(nameeng) = lower('Leung Shek Chee College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=1  where lower(nameeng) = lower('St. Paul''s School (Lam Tin)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=2  where lower(nameeng) = lower('Holy Family Canossian College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=2  where lower(nameeng) = lower('United Christian College (Kowloon East)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=2  where lower(nameeng) = lower('French International School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=2  where lower(nameeng) = lower('German Swiss International School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=3  where lower(nameeng) = lower('Yan Chai Hospital Wong Wha San Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=3  where lower(nameeng) = lower('Kit Sam Lam Bing Yim Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=3  where lower(nameeng) = lower('St. Paul''s Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=3  where lower(nameeng) = lower('STFA Seaward Woo College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=4  where lower(nameeng) = lower('ELCHK Lutheran Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=4  where lower(nameeng) = lower('Munsang College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=4  where lower(nameeng) = lower('The Chinese Foundation Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=4  where lower(nameeng) = lower('Precious Blood Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=5  where lower(nameeng) = lower('S.K.H. Kei Hau Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=5  where lower(nameeng) = lower('Kowloon True Light School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=5  where lower(nameeng) = lower('Tack Ching Girls'' Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=5  where lower(nameeng) = lower('Hon Wah College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=6  where lower(nameeng) = lower('Po Kok Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=6  where lower(nameeng) = lower('HKSYC & IA Wong Tai Shan Memorial College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=6  where lower(nameeng) = lower('Henrietta Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=6  where lower(nameeng) = lower('Kellett School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=7  where lower(nameeng) = lower('King Ling College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=7  where lower(nameeng) = lower('Queen Elizabeth School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=7  where lower(nameeng) = lower('Our Lady of The Rosary College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=7  where lower(nameeng) = lower('The Independent Schools Foundation Academy') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=8  where lower(nameeng) = lower('Tak Oi Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=8  where lower(nameeng) = lower('Hong Kong Taoist Association The Yuen Yuen Institute No. 3 Secondary Sch.') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=8  where lower(nameeng) = lower('STFA Cheng Yu Tung Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=8  where lower(nameeng) = lower('Buddhist Ho Nam Kam College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=9  where lower(nameeng) = lower('Our Lady''s College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=9  where lower(nameeng) = lower('TWGHs Lui Yun Choy Memorial College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=9  where lower(nameeng) = lower('Cheung Chuk Shan College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=9  where lower(nameeng) = lower('POH 80th Anniversary Tang Ying Hei College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=10  where lower(nameeng) = lower('Ning Po No. 2 College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=10  where lower(nameeng) = lower('Ko Lui Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=10  where lower(nameeng) = lower('G.T. (Ellen Yeung) College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=10  where lower(nameeng) = lower('FDBWA Szeto Ho Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=11  where lower(nameeng) = lower('Stewards Pooi Tun Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=11  where lower(nameeng) = lower('Pui Tak Canossian College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=11  where lower(nameeng) = lower('Po Leung Kuk Celine Ho Yam Tong College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=11  where lower(nameeng) = lower('True Light Girls'' College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=12  where lower(nameeng) = lower('Lung Kong WFSL Lau Wong Fat Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=12  where lower(nameeng) = lower('Delia Memorial School (Hip Wo)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=12  where lower(nameeng) = lower('Canossa College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=12  where lower(nameeng) = lower('St. Catharine''s School For Girls') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=13  where lower(nameeng) = lower('Delia Memorial School (Broadway)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=13  where lower(nameeng) = lower('Ning Po College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=13  where lower(nameeng) = lower('St. Antonius Girls'' College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=13  where lower(nameeng) = lower('Belilios Public School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=14  where lower(nameeng) = lower('Homantin Government Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=14  where lower(nameeng) = lower('Buddhist Wong Fung Ling College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=14  where lower(nameeng) = lower('S.K.H. Tang Shiu Kin Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=14  where lower(nameeng) = lower('Lee Kau Yan Memorial School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=14  where lower(nameeng) = lower('Wa Ying College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=15  where lower(nameeng) = lower('Po Leung Kuk Ho Yuk Ching (1984) College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=15  where lower(nameeng) = lower('St. Mark''s School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=15  where lower(nameeng) = lower('Chinese International School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=16  where lower(nameeng) = lower('S.K.H. Holy Trinity Church Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=16  where lower(nameeng) = lower('Lok Sin Tong Wong Chung Ming Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=16  where lower(nameeng) = lower('Tsung Tsin Christian Academy') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=16  where lower(nameeng) = lower('CCC Kei To Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=17  where lower(nameeng) = lower('SKH Li Fook Hing Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=17  where lower(nameeng) = lower('Evangel College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=17  where lower(nameeng) = lower('S.K.H. Lui Ming Choi Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=17  where lower(nameeng) = lower('Heung To Middle School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=17  where lower(nameeng) = lower('Victoria Shanghai Academy') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=18  where lower(nameeng) = lower('Carmel Divine Grace Foundation Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=18  where lower(nameeng) = lower('St. Francis'' Canossian College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=18  where lower(nameeng) = lower('The Methodist Church HK Wesley College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=19  where lower(nameeng) = lower('PLK Laws Foundation College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=19  where lower(nameeng) = lower('CCC Heep Woh College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=19  where lower(nameeng) = lower('Buddhist Hung Sean Chau Memorial College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=19  where lower(nameeng) = lower('Hong Kong Chinese Women''s Club College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=20  where lower(nameeng) = lower('Mu Kuang English School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=20  where lower(nameeng) = lower('Pui Kiu Middle School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=20  where lower(nameeng) = lower('Raimondi College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=20  where lower(nameeng) = lower('Hong Kong International School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=21  where lower(nameeng) = lower('Lok Sin Tong Yu Kan Hing Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=21  where lower(nameeng) = lower('Maryknoll Fathers'' School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=21  where lower(nameeng) = lower('Nam Wah Catholic Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=21  where lower(nameeng) = lower('Shau Kei Wan East Government Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=21  where lower(nameeng) = lower('China Holiness College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=22  where lower(nameeng) = lower('HKSKH Bishop Hall Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=22  where lower(nameeng) = lower('Kiangsu-Chekiang College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=22  where lower(nameeng) = lower('Yew Chung International School - Hong Kong') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=23  where lower(nameeng) = lower('CCC Ming Kei College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=23  where lower(nameeng) = lower('St. Bonaventure College & High School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=23  where lower(nameeng) = lower('Buddhist Tai Hung College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=23  where lower(nameeng) = lower('TWGHs Lee Ching Dea Memorial College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=24  where lower(nameeng) = lower('Ho Lap College (Sponsored by Sik Sik Yuen)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=24  where lower(nameeng) = lower('Maryknoll Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=24  where lower(nameeng) = lower('Tseung Kwan O Government Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=24  where lower(nameeng) = lower('Qualied College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=25  where lower(nameeng) = lower('ECF Saint Too Canaan College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=25  where lower(nameeng) = lower('Notre Dame College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=25  where lower(nameeng) = lower('Shau Kei Wan Government Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=25  where lower(nameeng) = lower('Tak Nga Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=26  where lower(nameeng) = lower('Clementi Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=26  where lower(nameeng) = lower('CCC Mong Man Wai College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=26  where lower(nameeng) = lower('Rosaryhill School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=26  where lower(nameeng) = lower('Rhenish Church Pang Hok Ko Memorial College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=27  where lower(nameeng) = lower('The Hong Kong Taoist Association Ching Chung Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=27  where lower(nameeng) = lower('Lok Sin Tong Leung Kau Kui College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=27  where lower(nameeng) = lower('Pui Ying Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=27  where lower(nameeng) = lower('Cognitio College (HK)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=27  where lower(nameeng) = lower('MKMCF Ma Chan Duen Hey Memorial College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=28  where lower(nameeng) = lower('Kwun Tong Government Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=28  where lower(nameeng) = lower('CCC Rotary Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=28  where lower(nameeng) = lower('HHCKLA Buddhist Ching Kok Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=29  where lower(nameeng) = lower('New Asia Middle School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=29  where lower(nameeng) = lower('S.K.H. Leung Kwai Yee Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=29  where lower(nameeng) = lower('Bishop Hall Jubilee School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=29  where lower(nameeng) = lower('Carmel Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=29  where lower(nameeng) = lower('Wai Kiu College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=29  where lower(nameeng) = lower('Methodist College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=29  where lower(nameeng) = lower('United Christian College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=30  where lower(nameeng) = lower('WEO Chang Pui Chung Memorial School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=31  where lower(nameeng) = lower('HKMA David Li Kwok Po College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=31  where lower(nameeng) = lower('Po Leung Kuk Tong Nai Kan Junior Secondary College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=31  where lower(nameeng) = lower('Heung To Secondary School (Tseung Kwan O)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=31  where lower(nameeng) = lower('Tang Shiu Kin Victoria Government Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=31  where lower(nameeng) = lower('Chan Shu Kui Memorial School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=32  where lower(nameeng) = lower('The Mission Covenant Church Holm Glad College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=32  where lower(nameeng) = lower('Delia Memorial School (Glee Path)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=32  where lower(nameeng) = lower('Kowloon Tong School (Secondary Section)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=33  where lower(nameeng) = lower('NLSI Lui Kwok Pat Fong College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=33  where lower(nameeng) = lower('Sir Ellis Kadoorie Secondary School (West Kowloon)') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=33  where lower(nameeng) = lower('Yu Chun Keung Memorial College No. 2') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=34  where lower(nameeng) = lower('CCC Kei Heep Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=34  where lower(nameeng) = lower('Po Leung Kuk No.1 W.H. Cheung College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=34  where lower(nameeng) = lower('Workers'' Children Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=34  where lower(nameeng) = lower('Newman Catholic College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=34  where lower(nameeng) = lower('St. Joan of Arc Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=34  where lower(nameeng) = lower('SKH Tsoi Kung Po Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=35  where lower(nameeng) = lower('Caritas Chong Yuet Ming Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=35  where lower(nameeng) = lower('CNEC Lau Wing Sang Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=35  where lower(nameeng) = lower('St. Stephen''s Church College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=36  where lower(nameeng) = lower('Fortress Hill Methodist Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=36  where lower(nameeng) = lower('HKICC Lee Shau Kee School of Creativity') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=36  where lower(nameeng) = lower('Caritas Wu Cheng-chung Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=36  where lower(nameeng) = lower('San Wui Commercial Soc. Chan Pak Sha School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=36  where lower(nameeng) = lower('Islamic Kasim Tuet Memorial College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=37  where lower(nameeng) = lower('Caritas Chai Wan Marden Foundation Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=38  where lower(nameeng) = lower('Jockey Club Government Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=38  where lower(nameeng) = lower('Man Kiu College') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=39  where lower(nameeng) = lower('HKWMA Chu Shek Lun Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=39  where lower(nameeng) = lower('Lingnan Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=39  where lower(nameeng) = lower('SKH Holy Carpenter Secondary School') and categoryid=2;
update entity set athleticsdivfemale=3, athleticsposfemale=42  where lower(nameeng) = lower('Delia Memorial School (Matteo Ricci)') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=1  where lower(nameeng) = lower('Diocesan Boys'' School') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=2  where lower(nameeng) = lower('La Salle College') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=3  where lower(nameeng) = lower('Hoi Ping Chamber of Commerce Secondary School') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=4  where lower(nameeng) = lower('Wah Yan College, Kowloon') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=5  where lower(nameeng) = lower('St. Joseph''s Anglo-Chinese School') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=6  where lower(nameeng) = lower('Cheung Sha Wan Catholic Secondary School') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=7  where lower(nameeng) = lower('Wah Yan College Hong Kong') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=8  where lower(nameeng) = lower('HKUGA College') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=9  where lower(nameeng) = lower('St. Margaret''s Co-Educational English Secondary and Primary School') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=10  where lower(nameeng) = lower('TWGHs Wong Fut Nam College') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=11  where lower(nameeng) = lower('West Island School') and categoryid=5;
update entity set athleticsdivmale=1, athleticsposfemale=12  where lower(nameeng) = lower('STFA Seaward Woo College') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=13  where lower(nameeng) = lower('Yu Chun Keung Memorial College') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=14  where lower(nameeng) = lower('Pui Ching Middle School') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=15  where lower(nameeng) = lower('Chong Gene Hang College') and categoryid=2;
update entity set athleticsdivmale=1, athleticsposfemale=15  where lower(nameeng) = lower('CMA Secondary School') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=1  where lower(nameeng) = lower('St. Stephen''s College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=2  where lower(nameeng) = lower('Choi Hung Estate Catholic Secondary School') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=3  where lower(nameeng) = lower('Delia Memorial School (Broadway)') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=4  where lower(nameeng) = lower('South Island School') and categoryid=5;
update entity set athleticsdivmale=2, athleticsposfemale=5  where lower(nameeng) = lower('Christian & Missionary Alliance Sun Kei Secondary School') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=6  where lower(nameeng) = lower('St. Francis Xavier''s College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=7  where lower(nameeng) = lower('Chan Sui Ki (La Salle) College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=8  where lower(nameeng) = lower('King George V School') and categoryid=5;
update entity set athleticsdivmale=2, athleticsposfemale=9  where lower(nameeng) = lower('Kwun Tong Maryknoll College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=10  where lower(nameeng) = lower('TWGHs Chang Ming Thien College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=11  where lower(nameeng) = lower('Buddhist Ho Nam Kam College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=12  where lower(nameeng) = lower('Lingnan Hang Yee Memorial Secondary School') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=13  where lower(nameeng) = lower('Ying Wa College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=14  where lower(nameeng) = lower('St. Joseph''s College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=15  where lower(nameeng) = lower('Sing Yin Secondary School') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=16  where lower(nameeng) = lower('TWGHs Lui Yun Choy Memorial College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=17  where lower(nameeng) = lower('Evangel College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=18  where lower(nameeng) = lower('St. Paul''s College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=19  where lower(nameeng) = lower('Cheung Chuk Shan College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=20  where lower(nameeng) = lower('STFA Cheng Yu Tung Secondary School') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=21  where lower(nameeng) = lower('Salesian English School') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=22  where lower(nameeng) = lower('HKCCCU Logos Academy') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=23  where lower(nameeng) = lower('Wa Ying College') and categoryid=2;
update entity set athleticsdivmale=2, athleticsposfemale=24  where lower(nameeng) = lower('Mu Kuang English School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=1  where lower(nameeng) = lower('Fukien Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=1  where lower(nameeng) = lower('Munsang College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=1  where lower(nameeng) = lower('Lee Kau Yan Memorial School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=1  where lower(nameeng) = lower('Island School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposfemale=2  where lower(nameeng) = lower('HKSKH Bishop Hall Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=2  where lower(nameeng) = lower('Po Leung Kuk Ho Yuk Ching (1984) College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=2  where lower(nameeng) = lower('Queen''s College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=2  where lower(nameeng) = lower('POH 80th Anniversary Tang Ying Hei College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=3  where lower(nameeng) = lower('PLK Laws Foundation College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=3  where lower(nameeng) = lower('HKSYC & IA Wong Tai Shan Memorial College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=3  where lower(nameeng) = lower('Raimondi College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=3  where lower(nameeng) = lower('CCC Kei To Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=4  where lower(nameeng) = lower('St. Louis School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=4  where lower(nameeng) = lower('Delia Memorial School (Hip Wo)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=4  where lower(nameeng) = lower('PLK Ngan Po Ling College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=4  where lower(nameeng) = lower('TWGHs Lee Ching Dea Memorial College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=5  where lower(nameeng) = lower('Yan Chai Hospital Wong Wha San Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=5  where lower(nameeng) = lower('St. Paul''s Co-Educational College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=5  where lower(nameeng) = lower('St. Joan of Arc Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=5  where lower(nameeng) = lower('S.K.H. St. Mary''s Church Mok Hing Yiu College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=6  where lower(nameeng) = lower('King Ling College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=6  where lower(nameeng) = lower('Maryknoll Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=6  where lower(nameeng) = lower('Henrietta Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=6  where lower(nameeng) = lower('Hon Wah College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=7  where lower(nameeng) = lower('Clementi Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=7  where lower(nameeng) = lower('Concordia Lutheran School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=7  where lower(nameeng) = lower('Nam Wah Catholic Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=7  where lower(nameeng) = lower('Kellett School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposfemale=8  where lower(nameeng) = lower('S.K.H. Holy Trinity Church Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=8  where lower(nameeng) = lower('CCC Heep Woh College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=8  where lower(nameeng) = lower('Rosaryhill School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=8  where lower(nameeng) = lower('Qualied College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=9  where lower(nameeng) = lower('Ho Lap College (Sponsored by Sik Sik Yuen)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=9  where lower(nameeng) = lower('Lok Sin Tong Leung Kau Kui College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=9  where lower(nameeng) = lower('S.K.H. Tang Shiu Kin Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=9  where lower(nameeng) = lower('King''s College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=9  where lower(nameeng) = lower('Hong Kong Tang King Po College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=10  where lower(nameeng) = lower('ELCHK Lutheran Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=10  where lower(nameeng) = lower('The Chinese Foundation Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=10  where lower(nameeng) = lower('Hong Kong Chinese Women''s Club College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=11  where lower(nameeng) = lower('Homantin Government Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=11  where lower(nameeng) = lower('Creative Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=11  where lower(nameeng) = lower('Pui Ying Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=11  where lower(nameeng) = lower('Tsung Tsin Christian Academy') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=11  where lower(nameeng) = lower('Yu Chun Keung Memorial College No. 2') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=12  where lower(nameeng) = lower('S.K.H. Leung Kwai Yee Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=12  where lower(nameeng) = lower('Po Leung Kuk Tong Nai Kan Junior Secondary College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=12  where lower(nameeng) = lower('The Methodist Church HK Wesley College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=13  where lower(nameeng) = lower('Lung Kong WFSL Lau Wong Fat Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=13  where lower(nameeng) = lower('CCC Rotary Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=13  where lower(nameeng) = lower('Buddhist Tai Hung College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=13  where lower(nameeng) = lower('MKMCF Ma Chan Duen Hey Memorial College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=14  where lower(nameeng) = lower('Stewards Pooi Tun Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=14  where lower(nameeng) = lower('Ning Po College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=14  where lower(nameeng) = lower('Buddhist Hung Sean Chau Memorial College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=14  where lower(nameeng) = lower('Kiangsu-Chekiang College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=15  where lower(nameeng) = lower('The Hong Kong Taoist Association Ching Chung Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=15  where lower(nameeng) = lower('Lok Sin Tong Wong Chung Ming Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=15  where lower(nameeng) = lower('CCC Mong Man Wai College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=15  where lower(nameeng) = lower('Rhenish Church Pang Hok Ko Memorial College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=15  where lower(nameeng) = lower('The Independent Schools Foundation Academy') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposfemale=16  where lower(nameeng) = lower('Lok Sin Tong Yu Kan Hing Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=16  where lower(nameeng) = lower('Yan Chai Hospital Law Chan Chor Si College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=16  where lower(nameeng) = lower('German Swiss International School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposfemale=17  where lower(nameeng) = lower('S.K.H. Kei Hau Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=17  where lower(nameeng) = lower('St. Bonaventure College & High School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=17  where lower(nameeng) = lower('S.K.H. Lui Ming Choi Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=17  where lower(nameeng) = lower('Heung To Middle School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=18  where lower(nameeng) = lower('Po Leung Kuk Choi Kai Yau School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=18  where lower(nameeng) = lower('HKSYC & IA Wong Tai Shan Memorial College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=18  where lower(nameeng) = lower('United Christian College (Kowloon East)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=18  where lower(nameeng) = lower('St. Mark''s School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=19  where lower(nameeng) = lower('HK & KLN Chiu Chow Public Assn. Sec. School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=19  where lower(nameeng) = lower('Tang King Po School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=19  where lower(nameeng) = lower('Heung To Secondary School (Tseung Kwan O)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=19  where lower(nameeng) = lower('Cognitio College (HK)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=19  where lower(nameeng) = lower('French International School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposfemale=19  where lower(nameeng) = lower('Hong Kong International School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposfemale=20  where lower(nameeng) = lower('G.T. (Ellen Yeung) College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=20  where lower(nameeng) = lower('Victoria Shanghai Academy') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposfemale=21  where lower(nameeng) = lower('Carmel Divine Grace Foundation Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=21  where lower(nameeng) = lower('S.K.H. St. Benedict''s School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=21  where lower(nameeng) = lower('Ng Wah Catholic Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=21  where lower(nameeng) = lower('CNEC Lau Wing Sang Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=22  where lower(nameeng) = lower('Kwun Tong Government Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=22  where lower(nameeng) = lower('Maryknoll Fathers'' School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=22  where lower(nameeng) = lower('Shau Kei Wan East Government Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=22  where lower(nameeng) = lower('SKH Tsoi Kung Po Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=23  where lower(nameeng) = lower('Po Kok Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=23  where lower(nameeng) = lower('Queen Elizabeth School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=23  where lower(nameeng) = lower('WEO Chang Pui Chung Memorial School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=23  where lower(nameeng) = lower('HKWMA Chu Shek Lun Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=24  where lower(nameeng) = lower('CCC Kei Heep Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=24  where lower(nameeng) = lower('Pui Kiu Middle School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=24  where lower(nameeng) = lower('Shau Kei Wan Government Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=24  where lower(nameeng) = lower('FDBWA Szeto Ho Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=25  where lower(nameeng) = lower('New Asia Middle School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=25  where lower(nameeng) = lower('Ko Lui Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=25  where lower(nameeng) = lower('Tang Shiu Kin Victoria Government Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=25  where lower(nameeng) = lower('Aberdeen Technical School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=26  where lower(nameeng) = lower('HKMA David Li Kwok Po College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=26  where lower(nameeng) = lower('Hong Kong Sea School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=26  where lower(nameeng) = lower('United Christian College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=26  where lower(nameeng) = lower('Yew Chung International School - Hong Kong') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposfemale=27  where lower(nameeng) = lower('The Mission Covenant Church Holm Glad College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=27  where lower(nameeng) = lower('SKH Li Fook Hing Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=27  where lower(nameeng) = lower('Workers'' Children Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=27  where lower(nameeng) = lower('Islamic Kasim Tuet Memorial College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=27  where lower(nameeng) = lower('Wai Kiu College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=27  where lower(nameeng) = lower('Chan Shu Kui Memorial School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=27  where lower(nameeng) = lower('Lingnan Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=28  where lower(nameeng) = lower('Bishop Hall Jubilee School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=29  where lower(nameeng) = lower('Buddhist Wong Fung Ling College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=29  where lower(nameeng) = lower('Delia Memorial School (Glee Path)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=29  where lower(nameeng) = lower('Methodist College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=29  where lower(nameeng) = lower('Chinese International School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposfemale=30  where lower(nameeng) = lower('CCC Kwei Wah Shan College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=30  where lower(nameeng) = lower('NLSI Lui Kwok Pat Fong College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=30  where lower(nameeng) = lower('Sir Ellis Kadoorie Secondary School (West Kowloon)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=30  where lower(nameeng) = lower('San Wui Commercial Soc. Chan Pak Sha School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=30  where lower(nameeng) = lower('St. Stephen''s Church College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=31  where lower(nameeng) = lower('Kowloon Technical School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=31  where lower(nameeng) = lower('Tseung Kwan O Government Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=31  where lower(nameeng) = lower('China Holiness College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=32  where lower(nameeng) = lower('CCC Ming Kei College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=32  where lower(nameeng) = lower('Kwun Tong Kung Lok Government Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=32  where lower(nameeng) = lower('Newman Catholic College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=32  where lower(nameeng) = lower('Kowloon Tong School (Secondary Section)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=33  where lower(nameeng) = lower('ECF Saint Too Canaan College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=33  where lower(nameeng) = lower('Caritas Chong Yuet Ming Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=33  where lower(nameeng) = lower('Munsang College (Hong Kong Island)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=34  where lower(nameeng) = lower('Po Leung Kuk No.1 W.H. Cheung College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=34  where lower(nameeng) = lower('Caritas Wu Cheng-chung Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=34  where lower(nameeng) = lower('Po Leung Kuk Celine Ho Yam Tong College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=34  where lower(nameeng) = lower('Delia Memorial School (Matteo Ricci)') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=35  where lower(nameeng) = lower('Fortress Hill Methodist Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=35  where lower(nameeng) = lower('Pentecostal School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=35  where lower(nameeng) = lower('HHCKLA Buddhist Ching Kok Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=35  where lower(nameeng) = lower('Caritas Chai Wan Marden Foundation Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=36  where lower(nameeng) = lower('Notre Dame College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=36  where lower(nameeng) = lower('Jockey Club Government Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=36  where lower(nameeng) = lower('Man Kiu College') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=37  where lower(nameeng) = lower('Carmel Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=37  where lower(nameeng) = lower('SKH Holy Carpenter Secondary School') and categoryid=2;
update entity set athleticsdivmale=3, athleticsposfemale=38  where lower(nameeng) = lower('HKICC Lee Shau Kee School of Creativity') and categoryid=2;


update entityscore es, entity e set es.athleticsdivname =e.athleticsdivname, es.athleticsdivfemale=e.athleticsdivfemale,
es.athleticsposfemale =e.athleticsposfemale,
es.athleticsdivmale =e.athleticsdivmale,
es.athleticsposmale = e.athleticsposmale,
es.swimmingdivmale = e.swimmingdivmale,
es.swimmingdivfemale = e.swimmingdivfemale,
es.swimmingposmale = e.swimmingposmale,
es.swimmingposfemale = e.swimmingposfemale,
es.basketballdivmale = e.basketballdivmale,
es.basketballdivfemale = e.basketballdivfemale,
es.basketballposmale = e.basketballposmale,
es.basketballposfemale = e.basketballposfemale,
es.footballdiv = e.footballdiv,
es.footballpos = e.footballpos
where es.entityid=e.id and es.year=2017;







