update entity set  athleticsposmale=0, athleticsposfemale=0 where categoryid in (5);
update entityscore set   athleticsposmale=0,  athleticsposfemale=0 where categoryid in (5) and year=2016;

update entity set  athleticsposmale=5  where categoryid=5 and name = '白普理小學';
update entity set  athleticsposfemale=9  where categoryid=5 and name = '白普理小學';
update entity set  athleticsposmale=0  where categoryid=5 and name = '山頂小學';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '山頂小學';
update entity set  athleticsposmale=0  where categoryid=5 and name = '九龍小學';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '九龍小學';
update entity set  athleticsposmale=29  where categoryid=5 and name = '弘立書院';
update entity set  athleticsposfemale=17  where categoryid=5 and name = '弘立書院';
update entity set  athleticsposmale=0  where categoryid=5 and name = '法國國際學校';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '法國國際學校';
update entity set  athleticsposmale=0  where categoryid=5 and name = '宣道會劉平齋紀念國際學校';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '宣道會劉平齋紀念國際學校';
update entity set  athleticsposmale=0  where categoryid=5 and name = '加拿大國際學校';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '加拿大國際學校';
update entity set  athleticsposmale=12  where categoryid=5 and name = '香港國際學校';
update entity set  athleticsposfemale=12  where categoryid=5 and name = '香港國際學校';
update entity set  athleticsposmale=12  where categoryid=5 and name = '香港澳洲國際學校';
update entity set  athleticsposfemale=16  where categoryid=5 and name = '香港澳洲國際學校';
update entity set  athleticsposmale=0  where categoryid=5 and name = '啟歷學校';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '啟歷學校';
update entity set  athleticsposmale=0  where categoryid=5 and name = '畢架山小學';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '畢架山小學';
update entity set  athleticsposmale=30  where categoryid=5 and name = '新加坡國際學校';
update entity set  athleticsposfemale=15  where categoryid=5 and name = '新加坡國際學校';
update entity set  athleticsposmale=17  where categoryid=5 and name = '滬江維多利亞學校';
update entity set  athleticsposfemale=13  where categoryid=5 and name = '滬江維多利亞學校';
update entity set  athleticsposmale=15  where categoryid=5 and name = '漢基國際學校';
update entity set  athleticsposfemale=7  where categoryid=5 and name = '漢基國際學校';
update entity set  athleticsposmale=0  where categoryid=5 and name = '蒙特梭利國際學校';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '蒙特梭利國際學校';
update entity set  athleticsposmale=21  where categoryid=5 and name = '德瑞國際學校（中小學部）';
update entity set  athleticsposfemale=33  where categoryid=5 and name = '德瑞國際學校（中小學部）';
update entity set  athleticsposmale=0  where categoryid=5 and name = '韓國國際學校';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '韓國國際學校';
update entity set  athleticsposmale=6  where categoryid=5 and name = '香港耀中國際學校';
update entity set  athleticsposfemale=3  where categoryid=5 and name = '香港耀中國際學校';
update entity set  athleticsposmale=0  where categoryid=5 and name = '鰂魚涌小學';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '鰂魚涌小學';
update entity set  athleticsposmale=30  where categoryid=5 and name = '日本國際學校';
update entity set  athleticsposfemale=16  where categoryid=5 and name = '日本國際學校';
update entity set  athleticsposmale=0  where categoryid=5 and name = '挪威國際學校';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '挪威國際學校';
update entity set  athleticsposmale=0  where categoryid=5 and name = '基督教國際學校';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '基督教國際學校';
update entity set  athleticsposmale=13  where categoryid=5 and name = '啟新書院';
update entity set  athleticsposfemale=9  where categoryid=5 and name = '啟新書院';
update entity set  athleticsposmale=1  where categoryid=5 and name = '清水灣小學';
update entity set  athleticsposfemale=0  where categoryid=5 and name = '清水灣小學';
update entity set athleticsdivfemale=1, athleticsposfemale=7   where lower(nameeng) = lower('West Island School') and categoryid=5;
update entity set athleticsdivfemale=1, athleticsposfemale=10   where lower(nameeng) = lower('King George V School') and categoryid=5;
update entity set athleticsdivfemale=1, athleticsposfemale=12   where lower(nameeng) = lower('Chinese International School') and categoryid=5;
update entity set athleticsdivfemale=2, athleticsposfemale=1   where lower(nameeng) = lower('Island School') and categoryid=5;
update entity set athleticsdivfemale=2, athleticsposfemale=3   where lower(nameeng) = lower('South Island School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=5   where lower(nameeng) = lower('French International School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=5   where lower(nameeng) = lower('German Swiss International School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=6   where lower(nameeng) = lower('Kellett School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=9   where lower(nameeng) = lower('The Independent Schools Foundation Academy') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=16   where lower(nameeng) = lower('Hong Kong International School') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=18   where lower(nameeng) = lower('Victoria Shanghai Academy') and categoryid=5;
update entity set athleticsdivfemale=3, athleticsposfemale=23   where lower(nameeng) = lower('Yew Chung International School - Hong Kong') and categoryid=5;
update entity set athleticsdivmale=1, athleticsposmale=9   where lower(nameeng) = lower('West Island School') and categoryid=5;
update entity set athleticsdivmale=1, athleticsposmale=15   where lower(nameeng) = lower('King George V School') and categoryid=5;
update entity set athleticsdivmale=2, athleticsposmale=16   where lower(nameeng) = lower('Island School') and categoryid=5;
update entity set athleticsdivmale=2, athleticsposmale=21   where lower(nameeng) = lower('German Swiss International School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposmale=1   where lower(nameeng) = lower('South Island School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposmale=5   where lower(nameeng) = lower('Chinese International School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposmale=9   where lower(nameeng) = lower('The Independent Schools Foundation Academy') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposmale=11   where lower(nameeng) = lower('Kellett School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposmale=22   where lower(nameeng) = lower('Hong Kong International School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposmale=25   where lower(nameeng) = lower('Victoria Shanghai Academy') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposmale=27   where lower(nameeng) = lower('French International School') and categoryid=5;
update entity set athleticsdivmale=3, athleticsposmale=29   where lower(nameeng) = lower('Yew Chung International School - Hong Kong') and categoryid=5;
update  entity set  swimmingdivfemale=2, swimmingposfemale=2 where upper(nameeng) = upper('West Island School') and categoryid=5;
update  entity set  swimmingdivmale=2 , swimmingposmale=2 where upper(nameeng) = upper('Hong Kong International School') and categoryid=5;
update  entity set  swimmingdivfemale=3, swimmingposfemale=3 where upper(nameeng) = upper('The Independent Schools Foundation Academy') and categoryid=5;
update  entity set  swimmingdivmale=3 , swimmingposmale=3 where upper(nameeng) = upper('The Independent Schools Foundation Academy') and categoryid=5;
update  entity set  swimmingdivfemale=3, swimmingposfemale=5 where upper(nameeng) = upper('Island School') and categoryid=5;
update  entity set  swimmingdivmale=2 , swimmingposmale=5 where upper(nameeng) = upper('King George V School') and categoryid=5;
update  entity set  swimmingdivmale=3, swimmingposmale=5 where upper(nameeng) = upper('Singapore International School (Hong Kong)') and categoryid=5;
update  entity set  swimmingdivfemale=1, swimmingposfemale=6 where upper(nameeng) = upper('Hong Kong International School') and categoryid=5;
update  entity set  swimmingdivmale=3, swimmingposmale=6 where upper(nameeng) = upper('Victoria Shanghai Academy') and categoryid=5;
update  entity set  swimmingdivfemale=2, swimmingposfemale=7 where upper(nameeng) = upper('South Island School') and categoryid=5;
update  entity set  swimmingdivmale=3, swimmingposmale=7 where upper(nameeng) = upper('Australian International School Hong Kong') and categoryid=5;
update  entity set  swimmingdivfemale=2, swimmingposfemale=8 where upper(nameeng) = upper('Victoria Shanghai Academy') and categoryid=5;
update  entity set  swimmingdivmale=2 , swimmingposmale=10 where upper(nameeng) = upper('South Island School') and categoryid=5;
update  entity set  swimmingdivmale=1 , swimmingposmale=12 where upper(nameeng) = upper('West Island School') and categoryid=5;
update  entity set  swimmingdivfemale=2, swimmingposfemale=13 where upper(nameeng) = upper('King George V School') and categoryid=5;
update  entity set  swimmingdivfemale=2, swimmingposfemale=14 where upper(nameeng) = upper('Yew Chung International School - Hong Kong') and categoryid=5;
update  entity set  swimmingdivfemale=2, swimmingposfemale=15 where upper(nameeng) = upper('Australian International School Hong Kong') and categoryid=5;
update  entity set  swimmingdivfemale=3, swimmingposfemale=15 where upper(nameeng) = upper('Chinese International School') and categoryid=5;
update  entity set  swimmingdivmale=3, swimmingposmale=15 where upper(nameeng) = upper('Chinese International School') and categoryid=5;
update  entity set  swimmingdivfemale=2, swimmingposfemale=16 where upper(nameeng) = upper('German Swiss International School') and categoryid=5;
update  entity set  swimmingdivfemale=3, swimmingposfemale=16 where upper(nameeng) = upper('French International School') and categoryid=5;
update  entity set  swimmingdivmale=2 , swimmingposmale=16 where upper(nameeng) = upper('German Swiss International School') and categoryid=5;
update  entity set  swimmingdivfemale=3, swimmingposfemale=17 where upper(nameeng) = upper('Singapore International School (Hong Kong)') and categoryid=5;
update  entity set  swimmingdivmale=3, swimmingposmale=17 where upper(nameeng) = upper('Island School') and categoryid=5;
update  entity set  swimmingdivmale=3, swimmingposmale=19 where upper(nameeng) = upper('Yew Chung International School - Hong Kong') and categoryid=5;
update  entity set  swimmingdivmale=3, swimmingposmale=23 where upper(nameeng) = upper('French International School') and categoryid=5;
update  entity set  swimmingdivfemale=3, swimmingposfemale=26 where upper(nameeng) = upper('Delia School of Canada') and categoryid=5;
update  entity set  swimmingdivmale=3, swimmingposmale=32 where upper(nameeng) = upper('Delia School of Canada') and categoryid=5;
update  entity set  basketballdivfemale=1, basketballposfemale=4 where upper(nameeng) = upper('South Island School') and categoryid=5;
update  entity set  basketballdivmale=1, basketballposmale=5 where upper(nameeng) = upper('South Island School') and categoryid=5;
update  entity set  basketballdivfemale=3, basketballposfemale=6 where upper(nameeng) = upper('King George V School') and categoryid=5;
update  entity set  basketballdivmale=3, basketballposmale=6 where upper(nameeng) = upper('Victoria Shanghai Academy') and categoryid=5;
update  entity set  basketballdivfemale=2, basketballposfemale=8 where upper(nameeng) = upper('German Swiss International School') and categoryid=5;
update  entity set  basketballdivmale=3, basketballposmale=8 where upper(nameeng) = upper('Christian Alliance P. C. Lau Memorial International School') and categoryid=5;
update  entity set  basketballdivmale=2, basketballposmale=9 where upper(nameeng) = upper('West Island School') and categoryid=5;
update  entity set  basketballdivmale=1, basketballposmale=10 where upper(nameeng) = upper('Chinese International School') and categoryid=5;
update  entity set  basketballdivfemale=2, basketballposfemale=11 where upper(nameeng) = upper('West Island School') and categoryid=5;
update  entity set  basketballdivmale=2, basketballposmale=12 where upper(nameeng) = upper('King George V School') and categoryid=5;
update  entity set  basketballdivfemale=2, basketballposfemale=14 where upper(nameeng) = upper('Chinese International School') and categoryid=5;
update  entity set  basketballdivmale=3, basketballposmale=16 where upper(nameeng) = upper('Yew Chung International School - Hong Kong') and categoryid=5;
update  entity set  basketballdivfemale=2, basketballposfemale=18 where upper(nameeng) = upper('Victoria Shanghai Academy') and categoryid=5;
update  entity set  basketballdivmale=3, basketballposmale=29 where upper(nameeng) = upper('Island School') and categoryid=5;
update  entity set  basketballdivfemale=3, basketballposfemale=31 where upper(nameeng) = upper('Christian Alliance P. C. Lau Memorial International School') and categoryid=5;
update  entity set  basketballdivmale=3, basketballposmale=39 where upper(nameeng) = upper('Delia School of Canada') and categoryid=5;
update  entity set  footballdiv=1, footballpos=1 where upper(nameeng) = upper('Hong Kong International School') and categoryid=5;
update  entity set  footballdiv=3, footballpos=1 where upper(nameeng) = upper('Canadian International School of Hong Kong') and categoryid=5;
update  entity set  footballdiv=3, footballpos=2 where upper(nameeng) = upper('French International School') and categoryid=5;
update  entity set  footballdiv=3, footballpos=3 where upper(nameeng) = upper('Chinese International School') and categoryid=5;
update  entity set  footballdiv=1, footballpos=4 where upper(nameeng) = upper('West Island School') and categoryid=5;
update  entity set  footballdiv=3, footballpos=4 where upper(nameeng) = upper('Yew Chung International School - Hong Kong') and categoryid=5;
update  entity set  footballdiv=2, footballpos=5 where upper(nameeng) = upper('German Swiss International School') and categoryid=5;
update  entity set  footballdiv=1, footballpos=6 where upper(nameeng) = upper('King George V School') and categoryid=5;
update  entity set  footballdiv=1, footballpos=8 where upper(nameeng) = upper('Island School') and categoryid=5;
update  entity set  footballdiv=3, footballpos=8 where upper(nameeng) = upper('Victoria Shanghai Academy') and categoryid=5;
update  entity set  footballdiv=1, footballpos=9 where upper(nameeng) = upper('South Island School') and categoryid=5;
update  entity set  footballdiv=3, footballpos=25 where upper(nameeng) = upper('Japanese International School') and categoryid=5;
update  entity set  footballdiv=3, footballpos=31 where upper(nameeng) = upper('The Independent Schools Foundation Academy') and categoryid=5;
update  entity set  footballdiv=3, footballpos=40 where upper(nameeng) = upper('Korean International School') and categoryid=5;
update entity set athleticsdivname='大埔及北區', athleticsdivfemale=3, athleticsposfemale=41 where name = '漢基國際學校' and categoryid=5;
update entity set athleticsdivname='屯門區', athleticsdivfemale=3, athleticsposfemale=29 where name = '哈羅香港國際學校' and categoryid=5;
update entity set athleticsdivname='沙田及西貢區', athleticsdivfemale=3, athleticsposfemale=20 where name = '沙田書院' and categoryid=5;
update entity set athleticsdivname='沙田及西貢區', athleticsdivfemale=3, athleticsposfemale=29 where name = '啟新書院' and categoryid=5;
update entity set athleticsdivname='沙田及西貢區', athleticsdivfemale=3, athleticsposfemale=44 where name = '基督教國際學校' and categoryid=5;
update entity set athleticsdivname='沙田及西貢區', athleticsdivfemale=3, athleticsposfemale=45 where name = '香港李寶椿聯合世界書院' and categoryid=5;
update entity set athleticsdivname='荃灣及離島區', athleticsdivfemale=3, athleticsposfemale=23 where name = '智新書院' and categoryid=5;
update entity set athleticsdivname='荃灣及離島區', athleticsdivfemale=3, athleticsposfemale=26 where name = '愉景灣國際學校' and categoryid=5;
update entity set athleticsdivname='大埔及北區', athleticsdivmale=3, athleticsposmale=41 where name = '漢基國際學校' and categoryid=5;
update entity set athleticsdivname='屯門區', athleticsdivmale=3, athleticsposmale=26 where name = '哈羅香港國際學校' and categoryid=5;
update entity set athleticsdivname='沙田及西貢區', athleticsdivmale=3, athleticsposmale=10 where name = '沙田書院' and categoryid=5;
update entity set athleticsdivname='沙田及西貢區', athleticsdivmale=3, athleticsposmale=25 where name = '啟新書院' and categoryid=5;
update entity set athleticsdivname='沙田及西貢區', athleticsdivmale=3, athleticsposmale=46 where name = '基督教國際學校' and categoryid=5;
update entity set athleticsdivname='沙田及西貢區', athleticsdivmale=3, athleticsposmale=47 where name = '香港李寶椿聯合世界書院' and categoryid=5;
update entity set athleticsdivname='荃灣及離島區', athleticsdivmale=3, athleticsposmale=25 where name = '智新書院' and categoryid=5;
update entity set athleticsdivname='荃灣及離島區', athleticsdivmale=3, athleticsposmale=27 where name = '愉景灣國際學校' and categoryid=5;



update entityscore es, entity e set es.athleticsposmale=e.athleticsposmale,es.athleticsposfemale=e.athleticsposfemale where es.entityid=e.id and es.year=2016 and e.categoryid in (5) ;


